### ISSUE TITLE
wrapper option only accepts component with optional children

### ISSUE THREAD

**Issue by karolis-cekaitis** [testing-library/react-testing-library#1002]
- `@testing-library/react` version: `11.2.7`
- Testing Framework and version: jest `26.6.0`
  
- DOM Environment: jsdom `16.7.0`
  

### Relevant code or config:
Wrapper:
```js
function ModalProvider({ children }: { children: ReactNode }) { ... }
```
Test:
```js
render(<App/>, { wrapper: ModalProvider });
```

### What you did:

Trying to test component with wrapper

### What happened:

TypeScript does not allow set component with required children as wrapper option:
```
Type '({ children }: { children: ReactNode; }) => Element' is not assignable to type 'ComponentType<{}> | undefined'.
  Type '({ children }: { children: ReactNode; }) => Element' is not assignable to type 'FunctionComponent<{}>'.
    Types of parameters '__0' and 'props' are incompatible.
      Type '{ children?: ReactNode; }' is not assignable to type '{ children: ReactNode; }'.
        Property 'children' is optional in type '{ children?: ReactNode; }' but required in type '{ children: ReactNode; }'.ts(2322)
```

**Comment by eps1lon** [comment]
What version of `@types/react` do you have installed? Try upgrading to the latest version and check if the issue persists.

**Comment by karolis-cekaitis** [comment]
was `17.0.19`, updated to `17.0.37` error still persists. It's optional in types repo:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f4a7981eb4db40f5f8c8a56ef4f45fd81700c3f0/types/react/index.d.ts#L829

**Comment by eps1lon** [comment]
I can't reproduce this issue with the latest dependencies:

```tsx
import React, { ReactNode } from 'react';
import { render } from '@testing-library/react';

function ModalProvider({ children }: { children: ReactNode }) {
    return null
}

function App() {
    return null;
}

render(<App />, { wrapper: ModalProvider });
```

[Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDejUYByEAJknAL5wBmUEIcA5FATIwNwBQoksucLAHZkolGnQaMAAjCQBnGMEEBzALQAbYACMoKKAE8A9C3RsunagFdBGYBEFwAsqRTqACnQBuwEQAo8aAAWwOokQpQAXPxBIWFIglHIpsRklACUuJxw2QJIMJZQDoKW6uqcFJwW1rb2cACCYGC+GThZOSz5hXDFpVwVnEJ+ADwNYHCGAHzYeADuuo1IUFHOJK4eEN4i6exAA)

@karolis-cekaitis Could you include a minimal, cloneable repository that reproduces this bug?

**Comment by karolis-cekaitis** [comment]
Hey, actually with latest updates this seems to work now correctly. Thanks for the support ;)
