### ISSUE TITLE
Form onSubmit Events Do Not Match Browser Behaviour

### ISSUE THREAD

**Issue by lauchness** [testing-library/react-testing-library#1005]
- `@testing-library/react` version: `12.1.2`
- Testing Framework and version: Jest `27.4.5`
- DOM Environment: @testing-library/jest-dom `5.16.1`

### Relevant code or config:

```js
// Form.tsx
import { FormEvent } from "react";
import "./styles.css";

type MyForm<Elements> = Elements & {
  name: HTMLInputElement;
  email: HTMLInputElement;
};

type FormProps = {
  afterSubmit: (name: string, email: string) => void;
};

export default function Form({ afterSubmit }: FormProps) {
  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const { name, email } = e.currentTarget as MyForm<typeof e.currentTarget>;
    afterSubmit(name.value, email.value);
  };
  return (
    <form onSubmit={handleSubmit}>
      <div>
        <label htmlFor="name">Name</label>
        <input id="name" type="text" />
      </div>
      <div>
        <label htmlFor="email">Email</label>
        <input id="email" type="text" />
      </div>
      <button type="submit">Submit</button>
    </form>
  );
}

// Form.test.tsx
import * as React from "react";
import { render, fireEvent } from "@testing-library/react";
import "@testing-library/jest-dom/extend-expect";
import Form from "./Form";

describe("Form", () => {
  it("should fire afterSubmit on submit", () => {
    const afterSubmit = jest.fn();
    const { getByText } = render(<Form afterSubmit={afterSubmit} />);

    fireEvent.click(getByText(/Submit/i));
    expect(afterSubmit).toHaveBeenCalledTimes(1);
  });
});
```

### What you did:

Writing tests for form submissions.

### What happened:

The test fails, because the form event fired by the `fireEvent` function imported from `@testing-library/react` does not match browser behaviour. In the reproduction below you can see that the browser has access to the `HTMLInputElement` properties (i.e. `email.value`), but when run in jest, these values are not present and the handleSubmit function throws, causing tests to fail.

### Reproduction:

https://codesandbox.io/s/testing-library-reproduce-no-currenttarget-q69xq?file=/src/Form.test.tsx

### Problem description:

I would expect the testing-library functions to mimic how my code behaves in the browser so that I have the most confidence in my tests.

### Suggested solution:

I haven't specifically dug into the code to determine why this is different. My hope is that I'm misunderstanding something in my config, or test, and that this issue can be closed quickly.

Ideally, the fireEvent function will mimic browser behaviour.

### Shoutout

Thanks for everything you do! Appreciate the hard work <3

**Comment by alexkrolick** [comment]
Sounds like a case of https://github.com/jsdom/jsdom/issues/2898. Form submission is not implemented in JSDOM.

**Comment by lauchness** [comment]
@alexkrolick do you have any suggestions on how we can resolve this?

Would we need to fix the issue in JSDOM and then bring in those changes here?

Is that a monumental task?

**Comment by MatanBobi** [comment]
@lauchness No need to bring anything here, since your using jsdom as your testing environment, once a fix for that will be published, you'll need to upgrade your jsdom version and this will work as expected.

About that task being a monumental task, it looks like jsdom don't have the capacity to handle all the issues so I guess they will appreciate any help :)

@alexkrolic can I close this one in favor of https://github.com/jsdom/jsdom/issues/2898? Since it doesn't look like we have anything to do in our scope for this.
