### ISSUE TITLE
bug: getByRole with form and name as option is not able to get form

### ISSUE THREAD

**Issue by PulkitBanta** [testing-library/react-testing-library#1006]
### Dependencies
```
"@testing-library/jest-dom": "4.1.0",
"@testing-library/react": "9.2.0",
"react": "16.9.0",
"react-dom": "16.9.0",
"react-scripts": "3.1.2"
```

### Relevant code or config:

```js
import React from "react";

export const Form = () => (
  <div>
    <form id="form-id" name="formName">
      <input type="text" />
    </form>
  </div>
);
```

```js
test("should get form by label with name", () => {
  render(<Form />);
  expect(screen.getByRole("form", { name: "formName" })).toBeInTheDocument();
});
```

### What you did:

Trying to select the form element by role while providing name as an option.

**Note** This works without the name as an option but it should also work with name as option

### What happened:

```
Unable to find an accessible element with the role "form" and name "formName"

Here are the accessible roles:

  document:

  Name "":
  <body />

  --------------------------------------------------
  form:

  Name "":
  <form
    id="form-id"
    name="formName"
  />

```

### Reproduction:

2 tests are added
- only label
- label with name

[Codesandbox](https://codesandbox.io/s/react-testing-library-demo-forked-qy2be?file=/src/__tests__/hello.js)

### Problem description:

Fails tests that are asserting that an accessible form is in the DOM with name as an option.

### Suggested solution:

Check name while finding the form with role and if it matches return the element

**Comment by MatanBobi** [comment]
Hi @PulkitBanta!
Thanks for taking the time to open this one :)
Unfortunately, the `name` attribute on the form does not imply the **accessible** name. This is quite confusing but the `name` attribute on the form is used mostly for js purposes and not for accessibility purposes.
When we filter by a name in the `ByRole*` queries, it should be the accessible name.

The accessible name of the form is defined by "author" which means we should write `aria-label` or `aria-labelledby` etc.
More on this can be found in [the spec](https://www.w3.org/TR/accname-1.2/#mapping_additional_nd).

Thanks and have a great year!
