### ISSUE TITLE
placeholder-shown pseudo class not working with toBeVisible()

### ISSUE THREAD

**Issue by vaidotasp** [testing-library/react-testing-library#1007]
- `@testing-library/react` version: 12.1.2
-   "@testing-library/jest-dom": 5.16.1,
- DOM Environment:
  

### Relevant code or config:

```js
// Defining styled components
const Clear = styled.button`
  display: block;
`;
const Search = styled.input`
  &::-webkit-search-cancel-button {
    display: none;
  }

  &:placeholder-shown ~ ${Clear} {
    display: none;
  }
`;

// Using them
return (
    <>
      <Search ref={searchInputRef} placeholder="enter name" type="search" />
      <Clear
        type="button"
        aria-label="clear search field"
        label="clear search field"
        onClick={() => {
          searchInputRef.current.value = "";
        }}
      >
        Clear
      </Clear>
    </>
  );

//test.jsx
  it("clear button should clear input value and dissapear", () => {
    const { getByPlaceholderText, queryByLabelText } = render(<SearchInput />);

    const clearButton = queryByLabelText(/clear search field/i);
    expect(clearButton).not.toBeVisible();

    const searchInput = getByPlaceholderText(/enter name/i);
    fireEvent.change(searchInput, { target: { value: "foo" } });

    expect(clearButton).toBeVisible();

    clearButton.click();
    expect(searchInput.value).toEqual("");
    expect(clearButton).not.toBeVisible();
  });

```

### What you did:
I have a search component that is composed from two elements: `input` and `button`. Button clears the input value, essentially resetting its state. Button is displayed only when input has value, this is achieved by using css pseudo class `placeholder-shown`. This works visually but fails testing. I suspect that RTL does not track this pseudo class and its rules but it is highly likely that I am missing something here.

### What happened:

RTL does not seem to track that upon input value change, input's placeholder is gone (replaced by a real value) and pseudo class `placeholder-shown` kicks in with the rule about input's sibling to apply `display:none`. This causes test to fail but visually we can see that the button is gone meaning that `display: none` is applied correctly using pseudo class.
![CleanShot 2021-12-30 at 14 29 00](https://user-images.githubusercontent.com/12076555/147756280-9ebba40a-598f-44b7-bea6-38834dd59c66.png)

### Reproduction:
https://codesandbox.io/s/test-search-vp-4zx8f

### Problem description:
We are unable to test components' visibility if we are using `:placeholder-shown` class and `display: none/block` css values.

**Comment by MatanBobi** [comment]
Hi @vaidotasp!
Thanks for taking the time to open this one :)

Since `jest-dom` is using `[getComputedStyle](https://github.com/testing-library/jest-dom/blob/84fe8e05c0802f0c099f25021072254a49472671/src/to-be-visible.js#L4)` which is implemented by JSDOM, I believe that this is JSDOM not updating the styles correctly.

You can verify it by console logging this in your browser and in your test before typing and after:
`clearButton.ownerDocument.defaultView.getComputedStyle(clearButton).display`

You'll see that in the browser it does change and in the tests it doesn't.
I didn't see any open issue in JSDOM about this one so I'll keep this one open for now to get more feedback, maybe the other maintainers won't agree with my findings.

**Comment by eps1lon** [comment]
Following up on @MatanBobi analysis I would suggest opening an issue on https://github.com/jsdom/jsdom/ showing that `getComputedStyle` does not work correctly with your styles.

Though I doubt this will be implemented considering it likely requires implementing the cascade of CSS. You're probably better off running these tests in a real browser.
