### ISSUE TITLE
How to Test a polyfill in JEST using react-testing-library?

### ISSUE THREAD

**Issue by code-masala** [testing-library/react-testing-library#1011]

**Comment by code-masala** [comment]
import { padStart } from "../es6-polyfill";
describe("Test for polyfills", () => {
	
	it("check for padStart", () => {
               String.prototype.padStart=null;
		expect("abc".padStart(8, "0")).toEqual("00000abc");
	});
	
});

**Comment by eps1lon** [comment]
This doesn't look like an issue with react-testing-library but testing practices in general.

I would advise reading https://testing-library.com/docs/#what-you-should-avoid-with-testing-library first and then ask for further pointers in [our discord](https://testing-library.com/discord).
