### ISSUE TITLE
`Uncaught SyntaxError: import not found: act` when imported in codepen (using skypack.dev)

### ISSUE THREAD

**Issue by julienw** [testing-library/react-testing-library#1017]
See this codepen: https://codepen.io/julienw/pen/gOXKYBj

I wanted to reproduce a problem I had with the library to file an issue, but I couldn't make it work. I get this error in the console:
```
Uncaught SyntaxError: import not found: act
```

It looks like the failing line is this:
```
import {act as act$1} from "/-/react-dom@v17.0.1-oZ1BXZ5opQ1DbTh7nu9r/dist=es2019,mode=imports/unoptimized/test-utils.js";
```
TBH I'm not sure what this does. My understanding is that this loads https://cdn.skypack.dev/-/react-dom@v17.0.1-oZ1BXZ5opQ1DbTh7nu9r/dist=es2019,mode=imports/unoptimized/test-utils.js, which in turns loads https://cdn.skypack.dev/-/react-dom@v17.0.1-oZ1BXZ5opQ1DbTh7nu9r/dist=es2019,mode=imports/unoptimized/cjs/react-dom-test-utils.development.js, and it looks like that one exports `act`. So... it should work?

Thanks for your help on this.

**Comment by eps1lon** [comment]
Really not sure why this is happening. We haven't heard any problems about this import. I would suggest filing this against the skypack repository and referencing the created issue here. Thanks!

**Comment by julienw** [comment]
I filed https://github.com/skypackjs/skypack-cdn/issues/271

**Comment by eps1lon** [comment]
Closing in favor of https://github.com/skypackjs/skypack-cdn/issues/271. We can re-open if there's something actionable for us to do.
