### ISSUE TITLE
Can know if a children was rendered and how

### ISSUE THREAD

**Issue by jefer94** [testing-library/react-testing-library#1024]
### Describe the feature you'd like:

Can find a child react component to avoid duplicate test about the feature are tested by the children, is necessary also can check the props was passed

### Suggested implementation:

```js
screen.findByElement(Component)
screen.findAllByElement(Component)
```

### Describe alternatives you've considered:

That the jest mock should be used inside the test case and not in the global scope

### Teachability, Documentation, Adoption, Migration Strategy:

```js
function Children() {
  return (
    <>
      ...
    </>
  )
}
function Component() {
  return (
    <>
      <Children />
      <Children />
      <Children />
    </>
  )
}

render(<Component />)

expect(screen.findByElement(Children)).toBeCalledWith([{}, {}, {}])
expect(screen.findAllByElement(Children)).toBeCalledWith([{}, {}, {}])
expect(screen.findAllByElement(Children)).toHaveLength(3)
```

**Comment by MatanBobi** [comment]
Hi @jefer94, thanks for taking the time to open this.
Unfortunately, this idea is against the approach testing-library is trying to advocate for which is: ["The more your tests resemble the way your software is used, the more confidence they can give you"](https://twitter.com/kentcdodds/status/977018512689455106) (Kent C. Dodds).

Asserting whether a component was rendered or what `props` it received doesn't give us the confidence that it was rendered properly and mocking a component out is not how our users interact with the app.

For these reasons, I don't see this moving forwards but I'll keep this one open for other maintainers to offer their inputs too :)

Thanks again!

**Comment by eps1lon** [comment]
As @MatanBobi said, this is against our approach.

You may be interested in the [experimental React DOM test selector API](https://gist.github.com/bvaughn/d3c8b8842faf2ac2439bb11773a19cec) which should match what you're looking for.

**Comment by jefer94** [comment]
Then, if a components exists and it is totally tested, and it is use in 6 components, does a way exist to reuse this code in all the parent elements? how you would implement this assertion, I want to implement it using DRY

For now I have the option of use [experimental React DOM test selector API](https://gist.github.com/bvaughn/d3c8b8842faf2ac2439bb11773a19cec) instead of `enzyme`

In my case I would do a integration test using cypress, and the last option to implement the DRY in the test is not possible because our approach, for it I want you opinions

**Comment by jefer94** [comment]
> As @MatanBobi said, this is against our approach.
> 
> You may be interested in the [experimental React DOM test selector API](https://gist.github.com/bvaughn/d3c8b8842faf2ac2439bb11773a19cec) which should match what you're looking for.

I think this solution is incompatible with NextJS

**Comment by MatanBobi** [comment]
@jefer94 if you're using a component in many places, and you've already tested it once, you can export "drivers" or utilities that will reduce the code duplication and just use them, things like `openDropdown` or stuff like that.
But, you should definitely read this one by Kent: [Avoid nesting when you're testing](https://kentcdodds.com/blog/avoid-nesting-when-youre-testing)

**Comment by RLiriaVA** [comment]
openDropdown

Enviado desde mi iPhone
