### ISSUE TITLE
RTL doesn't throw invalid hook call warning

### ISSUE THREAD

**Issue by mrdulin** [testing-library/react-testing-library#1028]
I know the GitHub issue is only for submitting bug issues and feature requests. Since I don't know whether it's a bug or not, so I post this as an issue. 

https://stackoverflow.com/questions/71420220/rtl-doesnt-throw-invalid-hook-call-warning

**Comment by eps1lon** [comment]
Let's keep this discussion on StackOverflow. [I answered there](https://stackoverflow.com/a/71591199/3406963).
