### ISSUE TITLE
How do I use global-jsdom correct for reset window with more options.

### ISSUE THREAD

**Issue by HillLiu** [testing-library/react-testing-library#1032]
Sometime, it need reset window environment such as custom url.

But after reset window, I'll get error `TestingLibraryElementError: Unable to find an accessible element with the role "xxx"`

## sample code

```JS
import { expect } from "chai";
import {  screen, render } from "@testing-library/react";

import jsdom from "global-jsdom";

describe("Test Reshow UNIT", () => {
  let reset;
  beforeEach(()=>{
    reset = jsdom(null, { url: "http://localhost" });
  });

  afterEach(() => {
    reset();
  });

  it("basic test", () => {
    const DIV = () => <div role="dom" />;
    render(<DIV />);
    console.log(screen.getByRole("dom"));
  });
});
```

## Detail error message
```
     TestingLibraryElementError: Unable to find an accessible element with the role "dom"

There are no accessible roles. But there might be some inaccessible roles. If you wish to access them, then set the `hidden` option to `true`. Learn more about this here: https://testing-library.com/docs/dom-testing-library/api-queries#byrole

Ignored nodes: comments, <script />, <style />
```

## Issues...

I try search answers but not luckily. 

Any one could point the way which I missed?

I run the code with mocha command.
```
mocha -r global-jsdom/register  -- 'build/cjs/**/__tests__/*.js'
```

**Comment by HillLiu** [comment]
Not sure it's related, but I'll try this first.
https://github.com/testing-library/testing-library-docs/pull/760

**Comment by HillLiu** [comment]
> Not sure it's related, but I'll try this first. [testing-library/testing-library-docs#760](https://github.com/testing-library/testing-library-docs/pull/760)

After try with global-jsdom and react-testing-library@13(react-18) has same issue.

**Comment by HillLiu** [comment]
After check dom-testing-library, the screen function look like always use same global variable (document).
https://github.com/testing-library/dom-testing-library/blob/main/src/screen.ts#L49-L51

There is a workaround solution but not sure if it's a good practice.
I could change my issue code to use getQueriesForElement and queries.

```js
import { expect } from "chai";
import { render, getQueriesForElement, queries } from "@testing-library/react";
import jsdom from "global-jsdom";

describe("Test Reshow UNIT", () => {
  let reset;
  beforeEach(() => {
    reset = jsdom(null, { url: "http://localhost" });
  });

  afterEach(() => {
    reset();
  });

  it("basic test", () => {
    const screen = getQueriesForElement(document.body, queries);
    const DIV = () => <div role="dom">foo</div>;
    render(<DIV />);
    expect(screen.getByRole("dom").innerHTML).to.equal("foo");
  });
});
```

**Comment by eps1lon** [comment]
https://github.com/testing-library/react-testing-library/issues/1032#issuecomment-1085133714 is the correct solution.
