### ISSUE TITLE
Support SVGR with React 18, Next and Jest

### ISSUE THREAD

**Issue by dkacper** [testing-library/react-testing-library#1034]
- `@testing-library/react` version: 13.0.0
- Testing Framework and version: `Jest` 27.5.1
- `Next` version: 12.1.4
- `React` version: 18.0.0
- `@svgr/webpack` version: 6.2.1
- `Node` version: 16.14.0
  
- DOM Environment:
  

### Jest config:

```js
// jest.config.js
const nextJest = require('next/jest');
const createJestConfig = nextJest({
  dir: './',
});
const customJestConfig = {
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  moduleDirectories: ['node_modules', '<rootDir>/'],
  testEnvironment: 'jest-environment-jsdom',
};
module.exports = createJestConfig(customJestConfig);
```

### What you did:

I want to test a component that has a SVGR icon. Before upgrading to React 18 the test has been passing. I've updated the following packages:

- Next from `12.1.0` to `12.1.4`
- React (and ReactDOM) from `17.0.2` to `18.0.0`
- @testing-library/react from `12.1.4` to `13.0.0`

I use SVGR by simply importing it in the component file `import Icon from 'assets/icon.svg';` and then just render `<Icon/>`.

### What happened:

The error I got is quite big, but it starts with this message 

```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

Then, it tells to 'check the render method` of the component and points the line of code with the Icon.

### Reproduction:

Setup a Next app with SVGR support and testing-library/react with Jest, then use an svg icon and try to `render()` the component with the icon in any test. Use packages versions as described above. 

EDIT: I've created a code sandbox that reproduces the issue https://codesandbox.io/s/issue-reproduced-1034-i3ph43?file=/tests/example.test.tsx Go to the terminal and run `yarn test` or `npm run test`. Test fails despite the icon renders well in the browser window.

**Comment by eps1lon** [comment]
Could you provide a cloneable, minimal repository that reproduces the problem? This would help a lot.

**Comment by dkacper** [comment]
Here is a code sandbox with reproduced issue https://codesandbox.io/s/issue-reproduced-1034-i3ph43?file=/tests/example.test.tsx

Go to the terminal and run `yarn test` or `npm run test`. Notice that the icon renders well in the browser window. However, the test crashes.

**Comment by eps1lon** [comment]
The same error is thrown by just using `react-dom`:
```js
import { act } from "react-dom/test-utils";
import { createRoot } from "react-dom/client";
import IndegPage from "../pages";

describe("View", () => {
  it("Should render icon", async () => {
    act(() => {
      createRoot(document.createElement("div")).render(<IndegPage />);
    });

    const icon = document.querySelector('[data-testid="icon"]');

    expect(icon).toBeInTheDocument();
  });
});
```

There's probably an issue with how the `.svg` file is transpiled. I'm not familiar with this setup so you would need to figure out which library is responsible for transpiling the `.svg` file and file an issue against their repository.
