### ISSUE TITLE
Codesandbox Examples cannot be run.

### ISSUE THREAD

**Issue by leochoo** [testing-library/react-testing-library#1036]
# Issue

The example code provided here is stuck at `Running Test Cases...`.
https://testing-library.com/docs/example-codesandbox/

Is this an expected behavior?

<img width="1202" alt="CleanShot 2022-04-05 at 15 44 31@2x" src="https://user-images.githubusercontent.com/26427048/161694799-99240316-9475-430d-92a5-16c60cf1ab85.png">

**Comment by eps1lon** [comment]
Closing in favor of https://github.com/codesandbox/codesandbox-client/issues/6599.
