### ISSUE TITLE
Cannot find module 'react-dom/client' from 'node_modules/@testing-library/react/dist/pure.js'

### ISSUE THREAD

**Issue by floppey** [testing-library/react-testing-library#1038]
- `@testing-library/react` version: 13.0.0
- Testing Framework and version:
  - jest: 27.5.1
  - ts-jest: 27.1.3
- DOM Environment: jsdom

### Relevant code or config:

```js
import { render, screen } from '@testing-library/react';
import React from 'react';

describe('bug demo', () => {
  it('should not crash', () => {
    render(<div>test</div>);
    expect(screen.findByText('test')).toBeInTheDocument();
  });
});
```

### What you did:

I ran `yarn test`

### What happened:

$ yarn test simple
yarn run v1.22.15
$ jest -u --runInBand simple
 FAIL  src/__tests__/simpletest.test.tsx
  ● Test suite failed to run

    Cannot find module 'react-dom/client' from '../../node_modules/@testing-library/react/dist/pure.js'

    Require stack:
      C:/path-to-repo/node_modules/@testing-library/react/dist/pure.js
      C:/path-to-repo/node_modules/@testing-library/react/dist/index.js
      src/__tests__/simpletest.test.tsx

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (../../node_modules/@testing-library/react/dist/pure.js:33:46)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        6.295 s
Ran all test suites matching /simple/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Problem description:

I am unable to run any tests using @testing-library/react after updating to the latest version

**Comment by floppey** [comment]
I was not using React 18, so I'll downgrade to 12.1.4 for now

**Comment by xusanduo08** [comment]
I have the same issue, is there any problem with 13.0.0?

**Comment by MatanBobi** [comment]
@xusanduo08, version 13 only supports React 18 [which introduced `react-dom/client`](https://github.com/facebook/react/blob/main/CHANGELOG.md#react-dom-client). 
If you need support for lower version (React<18), you'll need to use 12.x.

**Comment by aVileBroker** [comment]
For me, I had updated to `react` 18+, `react-testing-library` 13+, but was still getting the error.

Once I updated `react-dom` to 18+ I stopped getting this error. Pretty obvious, but I spun my wheels on it for a good hour so wanted to leave a note for anyone else encountering this problem!
