### ISSUE TITLE
Add ability to check for classNames and css from the pseudo classes ::before ::after states

### ISSUE THREAD

**Issue by jamesguan** [testing-library/react-testing-library#1050]
### Describe the feature you'd like:
Currently, I am trying to test for specific styling added to a component via pseudo classes. There are styles and classes applied on the ::before and ::after which I would like to confirm exists via a unit test but there does not seem to be a good way to check for this currently with react-testing-library.

### Suggested implementation:
Add the ability to validate an element's pseudo classes and styling.

### Describe alternatives you've considered:
Enzyme can find the prop that is applied to the element that causes those pseudo classes to be applied but I don't we want to do that.

**Comment by eps1lon** [comment]
This is out of scope for this package. It's probably better suited for `@testing-library/jest-dom`. Though pseudo styles aren't supported very well in JSDOM so visual regression tests are probably the better canidate.
