### ISSUE TITLE
Invariant Violation: Unable to find node on an unmounted component.

### ISSUE THREAD

**Issue by Abhi2019** [testing-library/react-testing-library#1052]
Facing this issue when trying to submit the form of popup, which is on a side menu. The button type of submit is: submit.
could anyone help with this.

fireEvent.mouseOver(await screen.findByText('Add'));
fireEvent.click(await screen.findByText('Regular Expression'));
await(screen.findByText('Regular Expression Rule'));
fireEvent.change(document.querySelector('input[id="regexText"]'),{ target: { value: "test" } });
fireEvent.click(document.querySelector('button[id="regex_overlay_ok"]'));

**Comment by eps1lon** [comment]
Closing since no reproduction was provided.
