### ISSUE TITLE
mock fn is called but not counted

### ISSUE THREAD

**Issue by vishalthakur3666** [testing-library/react-testing-library#1056]
- `@testing-library/react` version:
- Testing Framework and version:
  
- DOM Environment:
  

### Relevant code or config:

```
jest.mock('@app/hooks/useLiveperson/useLiveperson');
const initializeSdkMock = jest.fn();
(initializeSdkMock as jest.Mock).mockImplementation(() => {
  console.log('initializeSdkMock called');
});
const startConversationWithEngagementMock = jest.fn();
(useLiveperson as jest.Mock).mockImplementation(() => {
  return {
    initializeSdk: initializeSdkMock,
    startConversationWithEngagement: startConversationWithEngagementMock,
  };
});

..tl/dr...

expect(initializeSdkMock).toHaveBeenCalled();
```

### What you did:
I mocked "initializeSdk". It is called by the test not counted in expected number of calls. I also tried initializeSdkMock.mock.calls it returned empty [ ].

### What happened:
Console
 console.log
      initializeSdkMock called
 expect(jest.fn()).toHaveBeenCalled()

    Expected number of calls: >= 1
    Received number of calls:    0

      91 |     //Assert
      92 |     expect(resumeChatBtn).toBeTruthy();
    > 93 |     expect(initializeSdkMock).toHaveBeenCalled();
         |                               ^
      94 |   });
      95 | });
      96 | 

### Problem description:
Ideally,
1.  the test should have passed.
2. expect(initializeSdkMock).toHaveBeenCalled() = true
3. initializeSdkMock.mock.calls.length = 1

Observed : 
1. test failed
2. expect(initializeSdkMock).toHaveBeenCalled() = false
3. initializeSdkMock.mock.calls.length = 0

### Suggested solution:
can anyone please suggest what might be the issue ?

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by vishalthakur3666** [comment]
Never mind got it. I was using await initializeSdkMock. So the test finished before the mock fn could execute.
