### ISSUE TITLE
Padding on parent container affecting tests 

### ISSUE THREAD

**Issue by lukesims12** [testing-library/react-testing-library#1058]
- `@testing-library/react` version: "^12.1.3"
- Testing Framework and version: "ts-jest": "^27.1.3"
  
- DOM Environment: "@testing-library/jest-dom": "^5.16.2"
  

### Relevant code or config:

```js
<Container sx={{ height: '100%', padding: '.75em', display: 'flex', flexDirection: 'column', gap: '0.5em' }}>
    // ### FUNCTIONALITY TO TEST ###
</Container>
```

### What you did:

I was attempting to add some styling to my component post-completion, and added a padding of **.75em** to the parent container, which contains all of the functionality that I wanted to test. The Container element shown is that of [MUI](https://mui.com/material-ui/react-container/#main-content), although, this is not the cause of the issue, as this happens with a standard div also.

### What happened:

Upon doing so, 10 of my 19 unit tests failed. After looking at the unit tests and the code for a few days, I eventually decided to rollback and add in parts of the new styling bit by bit to see what affected the tests. After more investigation, simply changing the padding from .**75em** to **1em** made the tests pass again. I then tried with 0.75em, .5em, 16px, 10% and all unit types. **Only em unites below 1 failed the tests**. This was the **only** change.

### Reproduction:

Add a parent container that encapsulates the code you want to test. 
Add a padding property of < 1em.
All tests that follow a happy path will return failures. All tests that rely on an element or component conditionally rendering will return timeout errors.

### Problem description:

The current behavior is an issue as it was a very hard problem to spot and find. Padding in the CSS is not something a developer would look for when going to fix a failed unit test. I lost a huge amount of time to this issue, and I do not want people to do the same.

### Suggested solution:

I'm not sure what is causing this in the first place, and so I'm not sure what I can suggest to fix it. I recommend putting out a warning for now so that devs can check if the tests they are running are in a parent container with padding of less than 1em.

**Comment by eps1lon** [comment]
Closing since this is most likely an issue with CSS not being fully implemented in the testing environment.
