### ISSUE TITLE
actImplementation is not a function

### ISSUE THREAD

**Issue by michalstrzelecki** [testing-library/react-testing-library#1064]
- `@testing-library/react` version: 13.2.0
- Testing Framework and version: "react": "^18.1.0"
  
- "jest": "^28.0.0"
- DOM Environment: "jest-environment-jsdom": "^28.0.2"
  

### Relevant code or config:

```js
it("can display first 5 tags", async () => {
    render(<TagsList />)

    const links = await screen.findAllByRole("link")
    expect(links).toHaveLength(5)
  })
```

### What you did:

I have upgraded project to react 18, jest to 28, and rtl to 13.2.
### What happened:

```actImplementation is not a function
TypeError: actImplementation is not a function
    at /var/www/node_modules/@testing-library/react/dist/act-compat.js:57:25
    at renderRoot (/var/www/node_modules/@testing-library/react/dist/pure.js:159:26)
    at Object.render (/var/www/node_modules/@testing-library/react/dist/pure.js:246:10)
    at Object.render (/var/www/src/testUtils/test-utils.tsx:79:7)
    at Object.<anonymous> (/var/www/src/components/features/ResponsiveDrawer/TagsList/TagsList.test.tsx:7:25)
    at Promise.then.completed (/var/www/node_modules/jest-circus/build/utils.js:391:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/var/www/node_modules/jest-circus/build/utils.js:316:10)
    at _callCircusTest (/var/www/node_modules/jest-circus/build/run.js:218:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections 
```

### Problem description:

Every test fails.

### Suggested solution:

Please, provide the way to add actImplementation function.

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), or a link to a repository on GitHub.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by michalstrzelecki** [comment]
I can not get codesandbox to run my testsuite - https://codesandbox.io/s/frosty-diffie-5fb0z3?file=/src/App.spec.jsx

**Comment by eps1lon** [comment]
> Here is the repo [michalstrzelecki/rtl13](https://github.com/michalstrzelecki/rtl13). Any help would be appreciated.

@michalstrzelecki How do I use the repro? `npm test` did not reproduce the reported error:

```bash
$ npm ci
$ npm test

> ccfound-frontend@0.1.0 test /home/eps1lon/Development/throwaway/rtl13
> jest --config=jest.config.ts

Error: Jest: Failed to parse the TypeScript config file /home/eps1lon/Development/throwaway/rtl13/jest.config.ts
  Error: > Couldn't find a `pages` directory. Please create one under the project root
    at readConfigFileAndSetRootDir (/home/eps1lon/Development/throwaway/rtl13/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:136:13)
    at async readConfig (/home/eps1lon/Development/throwaway/rtl13/node_modules/jest-config/build/index.js:208:18)
    at async readConfigs (/home/eps1lon/Development/throwaway/rtl13/node_modules/jest-config/build/index.js:404:26)
    at async runCLI (/home/eps1lon/Development/throwaway/rtl13/node_modules/@jest/core/build/cli/index.js:140:59)
    at async Object.run (/home/eps1lon/Development/throwaway/rtl13/node_modules/jest-cli/build/cli/index.js:155:37)
npm ERR! Test failed.  See above for more details.
```

**Comment by MatanBobi** [comment]
@eps1lon I was able to reproduce it by just adding a folder named `pages` under `src`.

It looks quite similar to another issue we had with [swc](https://github.com/testing-library/react-testing-library/issues/996).

From a first look, it seems like when [we run the import from `react-dom/test-utils`](https://github.com/testing-library/react-testing-library/blob/main/src/act-compat.js#L1), jest is wrongfully using `test-utils.ts` file in the repo. (It's a first look, still didn't get a chance to look into the details too much).

**Comment by michalstrzelecki** [comment]
@eps1lon I have just add `.gitkeep` to the pages folder. Please, pull the changes.
@MatanBobi I have put the `pages` folder inside the root folder.

**Comment by iuridias-imtf** [comment]
I am facing the same issue, using react-18 and following the provided example in the documentation.

` TypeError: actImplementation is not a function

      at node_modules/@testing-library/react/dist/act-compat.js:57:25
      at node_modules/@testing-library/react/dist/pure.js:261:28
          at Array.forEach (<anonymous>)
      at cleanup (node_modules/@testing-library/react/dist/pure.js:257:22)
      at Object.<anonymous> (node_modules/@testing-library/react/dist/index.js:35:25)`

**Comment by eps1lon** [comment]
The issue was caused by `moduleNameMapper`: You're saying that any `test-utils` maps to your test-utils. So `'test-utils'` as well as `react-dom/test-utils` maps. The following patch fixes this issue:

```patch
diff --git a/jest.config.ts b/jest.config.ts
index 0c0e703..cd1004b 100644
--- a/jest.config.ts
+++ b/jest.config.ts
@@ -6,7 +6,7 @@ const createJestConfig = nextJest({ dir: "./" })
 const config: Config.InitialOptions = {
   moduleDirectories: ["node_modules"],
   moduleNameMapper: {
-    "test-utils": "<rootDir>/src/testUtils/test-utils.tsx",
+    "^test-utils$": "<rootDir>/src/testUtils/test-utils.tsx",
   },
   setupFilesAfterEnv: ["./jest.setup.ts"],
   testEnvironment: "jsdom",
```

**Comment by MatanBobi** [comment]
Good catch @eps1lon, I totally forgot to check the jest config :)

**Comment by michalstrzelecki** [comment]
@eps1lon thanks a lot! :)

**Comment by Deeksha123** [comment]
Hi @michalstrzelecki, I am getting the same issue in my test file. I tried to see how you setup your jest config file. Can you share the configuration. This issue is kind of blocker for me to proceed. 
Thanks!

**Comment by michalstrzelecki** [comment]
@Deeksha123 
```ts
const config: Config.InitialOptions = {
  // bail: true, // stop run test after one error
  // collectCoverage: true, // show test statistics
  errorOnDeprecated: true,
  coverageDirectory: "coverage",
  moduleDirectories: ["node_modules"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
    "^test-utils$": "<rootDir>/src/testUtils/test-utils.tsx",
  },
  setupFiles: ["./jest.setup.tsx"],
  setupFilesAfterEnv: ["./jest.setupAfterEnv.ts"],
  testEnvironment: "jest-environment-jsdom",
  verbose: true,
  roots: ["./src"],
}

```

**Comment by Deeksha123** [comment]
Thanks @michalstrzelecki.
