### ISSUE TITLE
getByLabelText returns 2 elements, instead of 1

### ISSUE THREAD

**Issue by nemonemi** [testing-library/react-testing-library#1065]
- `@testing-library/react` version: 12.1.5
- Testing Framework and version:
  
- DOM Environment: jest: 27.2.3
  

### Relevant code or config:

```js
    expect(screen.getByLabelText('Some field')).toBeInTheDocument();
```
Produces the following report:
```ts
TestingLibraryElementError: Found multiple elements with the text of: Some field

Here are the matching elements:

Ignored nodes: comments, <script />, <style />
<input
  aria-describedby="some-field-helper-text"
  aria-invalid="false"
  class="MuiInputBase-input-hieRCO MuiFilledInput-input-gnEWXF gVXmpM gqxwhg MuiFilledInput-input MuiInputBase-input MuiInputBase-inputSizeSmall MuiInputBase-inputAdornedEnd"
  id="some-field"
  type="text"
  value=""
/>

Ignored nodes: comments, <script />, <style />
<span
  aria-label="Some field"
  class=""
  data-mui-internal-clone-element="true"
>
  Some field
</span>
```

### What you did:

I am asserting that the TextField is in the document.

### What happened:

Instead of returning one component, two are returned, instead.

### Problem description:

I have a project that used Material-ui v4.x.x. After updating it to v5.6.x I've noticed all of my tests that were targeting input fields were failing because instead of 1 element, they were returning 2.

The same behavior exists with the `@testing-library/react:12.1.5` as well as with `@testing-library/cypress:8.0.2`
https://github.com/testing-library/cypress-testing-library/issues/214

**Comment by joaoVCNN** [comment]
I have same problem

**Comment by samtsai** [comment]
@nemonemi can you share a snippet of your code under test?

**Comment by eps1lon** [comment]
This is intended behavior since you have both a `textbox` with the given name and a `generic` element with the given name.

`getByRole('textbox', { name: 'Some field' })` would return a single element.

**Comment by nemonemi** [comment]
@eps1lon,
`screen.getByLabelText('Some field')` has always returned one element if only one element with the label "Some field" exists.

> This will search for the label that matches the given [TextMatch](https://testing-library.com/docs/queries/about#textmatch), then find the element associated with that label.
https://testing-library.com/docs/queries/bylabeltext/

**Comment by eps1lon** [comment]
> screen.getByLabelText('Some field') has always returned one element if only one element with the label "Some field" exists.

That's right. But it's not relevant here since there are two elements with that label. `getBy*` always threw when there is more than one element available.

**Comment by nemonemi** [comment]
I have ended up with the same issue again, but this time with the testing-library for Cypress version, and while using the `cy.findByRole( 'textfield', { name: 'Name' })` works, it shouldn't be necessary. 
The command `cy.findByLabelText` should return only one element, because there is only one `Name` input element on the screen.
