### ISSUE TITLE
`-- bail` does not work as expected

### ISSUE THREAD

**Issue by riteshf** [testing-library/react-testing-library#1066]
### Describe the bug

npm run test (`react-scripts test --watchAll=false --bail`) does not stop executing the tests after the first test failure.
Even specifying numbers as `--bail=1` does not help.

### Did you try recovering your dependencies?

Yes, I tried deleting and re-installing everything.

### Which terms did you search for in User Guide?

- I searched jest document.
- I went through the react-testing-library document.
- I also went through create-react-app.

### Environment

Github: [Link](https://github.com/riteshf/bail-failure)
Sanbox: [Link](https://codesandbox.io/s/confident-haslett-gbbnpx?file=/package.json)

### Steps to reproduce

(Write your steps here:)

1. git clone https://github.com/riteshf/bail-failure.git
2. npm install
3. npm run test

### Expected behavior

The Test Execution Should stop after first test case failure.

### Actual behavior

All tests ran even post failures.

### Reproducible demo

Github: [Link](https://github.com/riteshf/bail-failure)
Sanbox: [Link](https://codesandbox.io/s/confident-haslett-gbbnpx?file=/package.json)

**Comment by eps1lon** [comment]
Closing in favor of https://github.com/facebook/create-react-app/issues/12390. It's unlikely that there is an action required on our part. 

If it is, then we can always reopen.

**Comment by riteshf** [comment]
I only raised it on Facebook, But seems like it's an action required on your side as it's also in `Open` status on CRA.
