### ISSUE TITLE
renderHook assumes a document is available

### ISSUE THREAD

**Issue by BackEndTea** [testing-library/react-testing-library#1080]
- `@testing-library/react` 13.3.0:
- Testing Framework and version: jest 28
  
- DOM Environment: N/A
  

### Relevant code or config:
N/A

### What you did:

One of our tests verifies that the the `useHasAnalytics` hook has specific behaviour in an SSR environment. 
This means it is loaded without JSDom, and as such, has no window or document.

### What happened:

```
useHasAnalytics SSR › defaults to false when there is no window

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: document is not defined

       7 |      */
       8 |     it('defaults to false when there is no window', () => {
    >  9 |         const { result } = renderHook(useHasAnalytics);
         |                            ^
      10 |         expect(result.current).toBe(false);
      11 |     });
      12 | });

```

### Reproduction:

Run renderHook without a DOM environment.

### Problem description:

Hooks can be executed in an SSR environment, and we need to verify their behavior is correct.

**Comment by eps1lon** [comment]
`@testing-library/react` is currently not supported without a DOM available.

See https://github.com/testing-library/react-testing-library/issues/561#issuecomment-594032426 for the latest context. TL;DR: We're looking for someone to build a library for server-side rendering that should be used for these cases.
