### ISSUE TITLE
Redirection test using useNavigate does not change the location

### ISSUE THREAD

**Issue by slim-hmidi** [testing-library/react-testing-library#1082]
- `@testing-library/react` version: 13.3.0
- Testing Framework and version: Jest 
  
- DOM Environment: 8.13.0
  

### Relevant code or config:

```ts
import { render, RenderType } from "./customRender";
import HomePage from "./HomePage";
import "@testing-library/jest-dom/extend-expect";

describe("HomePage", () => {
  let wrapper: RenderType;
  beforeEach(() => {
    wrapper = render(<HomePage />, { route: "/" });
  });

  test.only("Should redirects to other page", async () => {
    const { getByText, user } = wrapper;

    expect(getByText(/homepage/i)).toBeInTheDocument();

    const button = getByText(/redirect/i);
    expect(button).toBeInTheDocument();
    user.click(button);
    expect(getByText(/other/i)).toBeInTheDocument();
  });
});

```

### What you did:

I try to test the redirection to another page when I click the button `Redirect`, but it does not change neither the path nor the page content.

### What happened:

```
Unable to find an element with the text: /other/i. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

Ignored nodes: comments, <script />, <style />
<body>
  <div>
    <h3>
      HomePage
    </h3>
    <button>
      Redirect
    </button>
  </div>
</body>
```

### Reproduction:

here: https://codesandbox.io/s/test-redirection-ltxudv?file=/src/HomePage.test.tsx:0-604
-->

### Problem description:

The redirection was not triggered when the button clicked.

### Suggested solution:

Display the change of the path location or the content of the page if it can be re-rendered using jsdom.

**Comment by eps1lon** [comment]
Support requests filed as GitHub issues often go unanswered. We want you to find the answer you're looking for, so we suggest asking in [our discord](https://testing-library.com/discord).
