### ISSUE TITLE
Feature request: Allow `render` function to accept a function

### ISSUE THREAD

**Issue by garbles** [testing-library/react-testing-library#1083]
The current `render` function requires that you pass it a `React.ReactElement<any>` as the first argument. Sometimes when I'm testing components, it is convenient to wrap them in a stateful HOC for the sake of brevity of the test. That is, I don't want to have to imperatively call `rerender` or `render` again to feed it new state. I end up doing something like:

```tsx
const App = () => {
  const [selected, setSelected] = React.useState<string | null>(null);
  return <SelectMenu options={...} selected={selected} onSelect={setSelected} />
};

render(<App />);

// ... do test things
```

It would be awesome if, instead, I could just pass the `App` component as a function to `render` where RTL would internally create a `ReactElement` from the function:

```tsx
render(() => {
  const [selected, setSelected] = React.useState<string | null>(null);
  return <SelectMenu options={...} selected={selected} onSelect={setSelected} />
});

// ... do test things
```

It's a small thing, but thought I'd suggest it because this seems to happen to me (and my colleagues) quite a bit. Maybe I'm  missing an API that already enables this.

Thoughts? If you like, I can also implement this feature.

```tsx
ui = (typeof ui === 'function' ? React.createElement(ui) : ui);
```

**Comment by eps1lon** [comment]
This would tie us to a specific JSX runtime. Right now `createElement` is considered legacy and most usage today uses an automatic runtime (e.g. `react/jsx-dev`).

So this is already problematic while not really solving anything other than very minor convenience. Instead of 
```tsx
render(() => {
  const [selected, setSelected] = React.useState<string | null>(null);
  return <SelectMenu options={...} selected={selected} onSelect={setSelected} />
});
```
you can just as well write

```tsx
const TestComponent = () => {
  const [selected, setSelected] = React.useState<string | null>(null);
  return <SelectMenu options={...} selected={selected} onSelect={setSelected} />
}
render(<TestComponent />);
```

This convenience seem not worth the added API surface and problems described when choosing a JSX runtime.

**Comment by garbles** [comment]
Thinking about this further, I'm also not sure the suggestion is a good idea because it can accidentally lead to something like the following where the developer accidentally passes the component instead of a zero-argument function. An error would throw from not being able to access keys on props instead of at the actual render call. E.g.

```tsx
render(SelectMenu)
```

**Comment by eps1lon** [comment]
It doesn't really unlock any big new features and just saves 1 or 2 lines while also tying us to a specific JSX runtime.
