### ISSUE TITLE
background-* properties never have the expected values

### ISSUE THREAD

**Issue by jbaccarelli-equinix** [testing-library/react-testing-library#1084]
- `@testing-library/react` version: latest
- Testing Framework and version: jest
- DOM Environment: jsdom

### Relevant code or config:

```js
// this test should fail but it passes
it('should add background-image property with value', () => {
    const Comp = () => (
      <div
        data-testid="myDiv"
        style={{
          backgroundImage: 'linear-gradient(to right, #f00, #0f0)',
          backgroundColor: 'red',
        }}
      >
        myDiv
      </div>
    )
    render(<Comp />)

    expect(screen.getByTestId('myDiv')).toHaveStyle({
      backgroundImage: 'linear-gradient(whatever)',
      backgroundColor: 'notRed',
    })
  })
```

### What you did:

Trying to test background related styles on a component

### What happened:

Values for background, backoground-color and background-image are always treated as "empty string" and pass any test

### Reproduction:

[Sandbox](https://codesandbox.io/s/react-testing-library-demo-forked-dh51si?file=/src/__tests__/hello.js)

### Problem description:

Can't reliably test different properties affecting a component's looks and behavior related to these css properties

### Suggested solution:

Seems like it might be related to css functions like linear-gradient or rgb/a but i can't really tell when this works or not, i see when i print the element with all the fiber info that the proper values are somewhere nested deep into fiber nodes, but when i try to retrieve the style or properties no matter how, i always get an empty string

**Comment by MatanBobi** [comment]
Hi @jbaccarelli-equinix, thanks for taking the time to open this :)
Unfortunately, Testing-Library isn't responsible for the actual rendering to the DOM, for that you use JSDOM which has an [open issue about `linear-gradient`](https://github.com/jsdom/jsdom/issues/2166).

Thanks again and sorry we can't help more :)
