### ISSUE TITLE
'render' function unexpectedly removes vendor prefixed css properties

### ISSUE THREAD

**Issue by markusenglund** [testing-library/react-testing-library#1085]
- `@testing-library/dom` version: 13.3.0
- Testing Framework and version: Jest 28.1.1
  
- DOM Environment: Jsdom 16.7.0
  

### Relevant code or config:

```js
const ComponentWithPrefixedStyles = () => (
  <div
    style={{
      background: "red",
      WebkitTapHighlightColor: "rgba(0, 0, 0, 0)",
      WebkitUserSelect: "none",
      MozUserSelect: "none",
      msUserSelect: "none",
      userSelect: "none"
    }}
  >
    Hello
  </div>
);

```

### What you did:

```js
  const { debug } = render(<ComponentWithPrefixedStyles />);
  debug();
```

### What happened:

```
console.log
    <body>
      <div>
        <div
          style="background: red; user-select: none;"
        >
          Hello
        </div>
      </div>
    </body>
```

### Reproduction:
https://github.com/markusenglund/dom-testing-library-template

### Problem description:

As mentioned in the title the prefixed styles are removed for some reason. It's a problem because I want to create tests to make sure that a component gets the correct styles.

**Comment by eps1lon** [comment]
This is how user-agents usually work. They strip unsupported CSS properties.

See how Chrome only keeps webkit properties: https://codesandbox.io/s/style-attribute-unsupported-css-properties-rhghzs
See how JSDOM only keeps unprefixed properties: https://runkit.com/eps1lon/62c49737538428000775ce8b
