### ISSUE TITLE
onChange does not get called when changing input.

### ISSUE THREAD

**Issue by georgesunnyt** [testing-library/react-testing-library#1090]
I am testing out a component that uses jsonforms to render forms. Changing the input for it does not trigger the onChange handler. OnChangeHandler gets called in codeosandbox but not during testing on a local machine. link to codesandbox : https://codesandbox.io/s/wizardly-panka-u9z3ff?file=/src/App.test.js

```
@testing-library/react` version: 12.1.2
@testing-library/jest-dom": 5.16.1
@testing-library/user-event": "^13.5.0",

  `import { person } from "@jsonforms/examples";
import {
  materialRenderers,
  materialCells
} from "@jsonforms/material-renderers";
import React, { useState } from "react";
import { JsonForms } from "@jsonforms/react";

export default function Example() {
  const schema = person.schema;
  const uischema = person.uischema;
  const initialData = person.data;
  const [data, setData] = useState(initialData);
  const [disabled, setDisabled] = useState(true);

  return (
    <div className="App">
      <JsonForms
        schema={schema}
        uischema={uischema}
        data={data}
        renderers={materialRenderers}
        cells={materialCells}
        onChange={({ data, _errors }) => {
          setDisabled(false);
          console.log("onchange is called");
          setData(data);
        }}
      />
      <button disabled={disabled}>Submit</button>
    </div>
  );
}

import mediaQuery from "css-mediaquery";
import { render, screen } from "@testing-library/react";
import userEvent from '@testing-library/user-event'
import Example from "../Example";
import { debug } from "jest-preview";

function createMatchMedia(width) {
    return (query) => ({
      matches: mediaQuery.match(query, {
        width,
      }),
      addListener: () => {},
      removeListener: () => {},
    });
  }

describe("test change chandler", () => {
  beforeAll(() => {
    window.matchMedia = createMatchMedia(window.innerWidth);
  });

  test("checks if button is enabled on first render", () => {
    render(<Example></Example>);
    screen.debug(undefined, Infinity);
    expect(
      screen.getByRole("button", {
        name: /submit/i
      })
    ).toHaveProperty("disabled", false);
  });

  test("checks if onchange is triggered on updating field", async () => {
    render(<Example></Example>);
    screen.debug(undefined, Infinity);
    let nameInput = screen.getByLabelText(/Name/i)
    await userEvent.type(nameInput,'George')
    debug()
    expect(
      screen.getByRole("button", {
        name: /submit/i
      })
    ).toHaveProperty("disabled", false);
  });

});
```

according to above code, the input field gets updated but it does not trigger an onchange event to enable the submit button. 
<img width="1438" alt="Screenshot 2022-07-07 at 4 46 45 PM" src="https://user-images.githubusercontent.com/66377779/177764030-d4117271-38bf-4d2f-83ef-f11431e807e7.png">
<img width="1440" alt="Screenshot 2022-07-07 at 4 46 10 PM" src="https://user-images.githubusercontent.com/66377779/177764053-27f67e1d-d520-49b1-8f5e-ede9f1913089.png">

**Comment by MatanBobi** [comment]
Hi @georgesunnyt, thanks for opening this one.
When using `user-event` version 14, you need to call [`setup`](https://testing-library.com/docs/user-event/setup) before running the operation.

I'm closing this one as this doesn't seem to be an issue with testing-library.
If you believe there's still an issue, please comment here and I'll re-open.

**Comment by georgesunnyt** [comment]
The code on my local machine runs user-event version 13.5.0. I have updated the version on code sandbox to 13.5.0 as well now. The user-event is able to change the input but it does not trigger the onchange handler. I also tried changing input  using firevent.change and the onchange handler still doesnt get called. The issue occurs only on local development and not on codesandbox. The onchange handler for jsonforms is supposed to be triggered on first render also. This also doesnt happen while testing with react testing library on local machine, but works in codesandbox.

**Comment by MatanBobi** [comment]
If this works in codesandbox but doesn't work on your local machine it means that there's probably some issue with your setup.

Do you mind sharing a code reproduction using github repo or something so we'll be able to investigate?
Anyways, this doesn't seem like an issue with the library as long as it works in a different environment.

**Comment by georgesunnyt** [comment]
Unable to reproduce issue inside a fresh react project indicating something was wrong in the local configuration of the previous project I was working on. If I ever find out what was wrong in the previous configuration, I'll post it here. Thanks for your time @MatanBobi

**Comment by georgesunnyt** [comment]
So it turned out to be an issue where the UI was taking more time in the test environment. I fixed it by waiting for it.
await waitFor(() => {
    screen.getByRole("button", {
        name: /submit/i
      })
    ).toHaveProperty("disabled", false);
})
Hope this helps someone else :-)
