### ISSUE TITLE
renderHook do not return latest state after call setState

### ISSUE THREAD

**Issue by Darmody** [testing-library/react-testing-library#1092]
- `@testing-library/react` version: 13.3.0
- Testing Framework and version: jest@28.1.2
  
- DOM Environment: jsdom@19.0.0
  

### Relevant code or config:

```ts
// test
  const { result } = renderHook(() => useBlockActionHandlers(onVisibleChange))

      result.current.onMenuVisibleChange(visible)

      expect(result.current.menuVisible).toBe(visible)
      expect(onVisibleChange).toBeCalledWith(visible)
```
```ts
// useBlockActionHandlers
export function useBlockActionHandlers(onMenuVisibleChange: BlockActionButtonProps['onMenuVisibleChange']): {
  menuVisible: boolean
  onMenuVisibleChange: (visible: boolean) => void
} {
  const [menuVisible, setMenuVisible] = useState(false)
  const handleMenuVisibleChange = useCallback(
    (visible: boolean) => {
      setMenuVisible(visible)
      onMenuVisibleChange?.(visible)
    },
    [onMenuVisibleChange]
  )

  return {
    menuVisible,
    onMenuVisibleChange: handleMenuVisibleChange,
  }
}
```

### What you did:

Testing a react hook with state updation.

### What happened:

Except the `menuVisible` state to be true after calling the `onMenuVisibleChange(true)`, but not.

### Reproduction:

Run the code above.

### Problem description:
Except the `menuVisible` state to be true after calling the `onMenuVisibleChange(true)`, but not.

**Comment by eps1lon** [comment]
Try
```tsx
act(() => {
   result.current.onMenuVisibleChange(visible)
})
```

All state updates should be wrapped in `act()` in React 18.

**Comment by Darmody** [comment]
@eps1lon Thanks, it works.

**Comment by MatanBobi** [comment]
@eps1lon should this be documented in the docs?

**Comment by MatanBobi** [comment]
@eps1lon I agree about the general use of `act`, but since the old react-hooks-testing-library did show an [example with act](https://react-hooks-testing-library.com/usage/basic-hooks#updates) and we moved most of it's capabilities here, I believe our guide should also show that.. Wdyt?
