### ISSUE TITLE
act() await ts warning

### ISSUE THREAD

**Issue by glend1** [testing-library/react-testing-library#1096]
here is my test (which passes);

````
it("Should fail if the platofrm doesn't support midi", async () => {
			const { result } = renderHook(() => {
				return MidiConnection();
			});
			await act(() => {
				result.current.enable();
			});
			// await waitForNextUpdate();
			expect(result.current.error).toBe(
				"navigator.requestMIDIAccess is not a function"
			);
		});
````

but when i remove the `await` it fails. but typescript tells me `'await' has no effect on the type of this expression.`

clearly its doing something, or the test wouldn't pass. whats happening here?

I've noticed there are other act issues in the posts so maybe there is some tightening up done around that.

**Comment by eps1lon** [comment]
> but when i remove the await it fails. but typescript tells me 'await' has no effect on the type of this expression.

Because it's not async. If you want to await it, try

```diff
-await act(() => {
+await act(async () => {
   result.current.enable();
 });
```
