### ISSUE TITLE
screen.debug() not displaying the value that userEvent.type() typed into a textbox

### ISSUE THREAD

**Issue by AnthonyMadia** [testing-library/react-testing-library#1098]
- `@testing-library/react` version: 12.1.2
- Testing Framework and version: Jest ^28.1.3
  
- DOM Environment: jsdom 28.1.2
  

### Relevant code or config:

```js
test('LoginPage should handle events properly', async () => {
    render(<LoginPage />)
    screen.debug()
    const privateKeyInput = screen.getByPlaceholderText(/enter your private key here/i)
    await userEvent.type(privateKeyInput, 'asdf4saf45saf45sdaf542545')
    expect(privateKeyInput).toHaveValue('asdf4saf45saf45sdaf542545')
    screen.debug(privateKeyInput)
})
```

### What you did:

Wrote a test to see if the value of the textbox was updated with the value that `userEvent.type()` would write in. I asserted that the value of the textbox was updated using the `.toHaveValue() `method and used `screen.debug()` before and after the typing assertion to see that the value field would show after the typing assertion was made.

### What happened:
The assertion that uses the `.toHaveValue()` method passed! The _**strange**_ part was that the `value=` field was _not_ populated when I used `screen.debug()` the second time.

No error message, but here are the` screen.debug()` outputs before and after the typing assertion to demonstrate that the value is not populated after the `.type() `assertion:

```js
    <body>
      <div>
        <div
          class="login-page"
        >
          <div
            class="left-column"
          >
            <img
              src="test-file-stub"
            />
          </div>
          <div
            class="right-column"
          >
            <div
              class="close"
            >
              <img
                id="unirep-icon"
                src="test-file-stub"
              />
              <img
                id="close-icon"
                src="test-file-stub"
              />
            </div>
            <div
              class="info"
            >
              <div
                class="title"
              >
                Welcome back
              </div>
              <p>
                To enter the app, please use the private key you got when you signed up.
              </p>
              <textarea
                placeholder="enter your private key here."
              />
              <div />
              <div
                class="sign-in-btn"
              >
                <div
                  class="loading-btn"
                >
                  Sign in
                </div>
              </div>
              <div
                class="notification"
              >
                Lost your private key? Hummm... we can't help you to recover it, that's a lesson learned for you. Want to restart to earn rep points?
                 
                <a
                  href="https://about.unirep.social/alpha-invitation"
                  target="_blank"
                >
                  Request an invitation code here.
                </a>
              </div>
              <div
                class="go-to-signup"
              >
                Got an invitation code? 
                <a
                  href="/signup"
                >
                  Join here
                </a>
              </div>
            </div>
          </div>
          <div />
        </div>
      </div>
    </body>
```
Debug statement _after_ typing assertion was made.. this is where I assumed the value field would populate.
```js
 <textarea
      placeholder="enter your private key here."
    />
```

### Problem description:
`screen.debug() `not showing the value field populated with the correct value.

### Suggested solution:
Really not sure about a solution to this and just wondering if this is a bug. I'd like to be sure that the value is actually populated so I can have confidence in this test.

**Comment by AnthonyMadia** [comment]
Made a stackoverflow [here](https://stackoverflow.com/questions/73128118/userevent-type-not-showing-value-in-screen-debug-but-passes-assertion-for-va).

**Comment by AnthonyMadia** [comment]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) the `textarea` element doesn't use/support the value attribute. I imagine the testing library is internally dealing with this, which is why the test passes. I tried changing the tested value and it fails as expected.

"Default content entered between the opening and closing tags. <textarea> does not support the value attribute."

**Comment by zeeshanjan82** [comment]
I was able to get the issue fixed
https://stackoverflow.com/questions/65182439/userevent-type-not-updating-value-of-input-in-test
