### ISSUE TITLE
How I can get testing component using mocking data by Intersection Observer API

### ISSUE THREAD

**Issue by JUDONGHYEOK** [testing-library/react-testing-library#1099]
My Application calls Get API by Infinite Scroll using Intersection Observer API
I tried to testing this Component But occurred error like below
```
  console.error
    Warning: The current testing environment is not configured to support act(...)
```

I wrapped this render by act like below
```javascript
 beforeEach(async () => {
    await act(async () => {
      const queryClient = new QueryClient();

      render(
        <QueryClientProvider client={queryClient}>
          <MemoryRouter initialEntries={['/']}>
            <ThemeProvider theme={theme}>
              <App />
            </ThemeProvider>
          </MemoryRouter>
        </QueryClientProvider>,
      );
    });

    console.log(prettyDOM(re.container.firstChild));
  });
```
But I can't get mocking data by MSW
Other Tests run well
data fetching is no problem.
I think the App Component can't re-render after data fetching(updating state).
How can I fix it?
Please Tell me What is wrong.

**Comment by eps1lon** [comment]
Support requests filed as GitHub issues often go unanswered. We want you to find the answer you're looking for, so we suggest the following alternatives:

Talk to other React developers
There are many online forums which are a great place for discussion about best practices and application architecture as well as the future of React.

https://testing-library.com/discord
