### ISSUE TITLE
HTML Dialog element not supported

### ISSUE THREAD

**Issue by ryan0122** [testing-library/react-testing-library#1106]
I'm using the native HTML Dialog element (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) with React for a modal component. The Dialog element contains methods to interact with. In order to gain access to the native element and call the methods of the Dialog the `useRef` hook must be used in React. 

- `@testing-library/react` version: 12.1.4
- Testing Framework and version: "jest": ^27.0.6
- DOM Environment: "@testing-library/jest-dom": 5.16.3
- React Version: 16.13.1
- Typescript Version: 4.2.4
- Node Version: 14.18.1

### Relevant code or config:

```
const dialogRef: any = useRef<HTMLDialogElement>(null);

dialogRef.current?.show();
```

In my Dialog.tsx file, this is working as expected with no errors/warnings from Typescript. However when running unit tests via testing library, I get the following error: 

```
Dialog › should fire callbackfunctions

    TypeError: _a.show is not a function

      79 |     if (isOpen) {
      80 |      
    > 81 |       dialogRef.current?.show();
         |                          ^
      82 |     }
      83 |   }, [isOpen]);
```

### What you did:

In my Dialog.tsx file, this is working as expected with no errors/warnings from Typescript. However when running unit tests via testing library, I get the error about the native method `show` not being a function. 

### Problem description:

The testing library should support all native HTML elements and their internal methods.

**Comment by eps1lon** [comment]
This is an issue with the testing environment not this library. You're most likely using Jest which uses `jsdom` which has not added support for `HTMLDialogElement`. Closing in favor of https://github.com/jsdom/jsdom/issues/3294
