### ISSUE TITLE
Does not work with React 17 - Readme implies works for 16+

### ISSUE THREAD

**Issue by oehm-smith** [testing-library/react-testing-library#1111]
I have a react17 project.  Installation results in peerDependency error.  The latest version (v13.3.0)'s `package.json` contains

```"peerDependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
```

You need to update the doco to help those not on 18.

v12.1.5 specifies:

```"peerDependencies": {
    "react": "*",
    "react-dom": "*"
  }
```

Which seems to be what I need.  But if not (or if so) you need to make this clear.

Good work otherwise! :)

**Comment by eps1lon** [comment]
13.x does work with the versions specified in `peerDependencies`. The warning is correct. You need to switch to 12.x.

> Readme implies works for 16+

Could you point to the part of the documentation that implies that to you?

**Comment by oehm-smith** [comment]
https://github.com/testing-library/react-testing-library#suppressing-unnecessary-warnings-on-react-dom-168 says:

> Suppressing unnecessary warnings on React DOM 16.8

>    There is a known compatibility issue with React DOM 16.8 where you will see the following warning:

**Comment by MatanBobi** [comment]
PR's are welcome for this if anyone wants to fix it in the README and state that version >=13 requires React >=18.
