### ISSUE TITLE
This version is not compatible with react 17.02 

### ISSUE THREAD

**Issue by Subhanshu007** [testing-library/react-testing-library#1121]
### Teachability, Documentation, Adoption, Migration Strategy:

npm ERR!npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.0.0" from @testing-library/react@13.4.0
npm ERR! node_modules/@testing-library/react
npm ERR!   @testing-library/react@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution. 
npm ERR!

**Comment by pascalvos** [comment]
use 
    "@testing-library/react": "12.1.5",
    "@testing-library/react-hooks": "^8.0.1",

**Comment by eps1lon** [comment]
This is intended. For Reach 17, use `@testing-library-react@^12.x`. For React 18, use `@testing-library-react@^13.x`
