### ISSUE TITLE
Problem with CookieJar

### ISSUE THREAD

**Issue by alessio-de-padova** [testing-library/react-testing-library#1123]
What I want to do it to test a component that uses formik and is connected to the store. 
I am trying to fill the form fields and check if the ajax request will have the requested body. 

The problem is that whenever I try to run this test I incur in the following problem:

"Error: Cookie has domain set to the public suffix "localhost" which is a special use domain. To allow this, configure your CookieJar with {allowSpecialUseDomain:true, rejectPublicSuffixes: false}."

I have not got the slightest idea of how that could happen since I don't use CookieJar in my application. 
The only thing I could think about is that the application is not running on localhost but domain.local (reconfigured in /etc/hosts)

Below is the test:

`
import React from 'react'
import {render,  waitFor} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import PatientContent from './index.js'
import GeneralData from "./GeneralData";
import configureStore from 'redux-mock-store'
import {SET_NEW_PATIENT, SET_SELECTED_PATIENT} from "../../../redux/tabs";
import Provider from "react-redux/lib/components/Provider";
import {SnackbarProvider} from "notistack";
const mockStore = configureStore()
test('rendering and submitting a basic Formik form', async () => {
    const handleSubmit = jest.fn()
    const getPatients = () => ({ type: 'SET_SELECTED_PATIENT' })
    const setSelectedPatient = () => ({ type: 'SET_NEW_PATIENT' })
    const store = mockStore();
    const patientContent = render(
        <Provider  store={store}>
            <SnackbarProvider>
                <PatientContent
                    getPatients={getPatients}
                    setSelectedPatient={setSelectedPatient}
                    onSubmit={handleSubmit}
                />
            </SnackbarProvider>
        </Provider>
    )
    const generalData = render(<GeneralData/>)
    const user = userEvent.setup()
    await user.type(generalData.container.querySelector('#name'), 'John')
    await user.type(generalData.container.querySelector('#surname'), 'Wick')
    await user.type(generalData.container.querySelector('#fiscalCode'), 'john.dee@someemail.com')
    await user.click(patientContent.container.querySelector('#submit'))
    await waitFor(() =>
        expect(handleSubmit).toHaveBeenCalledWith({
            name: 'John',
            surname: 'Wick',
            fiscalCode: 'john.dee@someemail.com',
        }),
    )
})
`

These are the testing libraries in my package.json:
   "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^14.0.0",

**Comment by eps1lon** [comment]
Sorry to hear you're having trouble. This doesn't sound like an issue with `@testing-library/react` per-se.

I recommend you check out our [community discord](https://testing-library.com/discord) and see if someone is able to help you.
