### ISSUE TITLE
introducing timeouts to code breaks test.

### ISSUE THREAD

**Issue by janusqa** [testing-library/react-testing-library#1124]
- `@testing-library/react` version: "@testing-library/react": "^13.3.0",
- Testing Framework and version:
  
- DOM Environment:     "@testing-library/jest-dom": "^5.16.5",
  

### Relevant code or config:

```js

// This sets state  in a component
const handleOnClick = (e, p) => {
       setTimeout(() => dispatch(getResource(payload)), 1500);
};


// in another component state change from above detected and makes an api requet
useEffect(
    function () {
      setTimeout(() => dispatch(getAnotherResource()), 2000);
    }
);

// response recevied
export const getAnotherResource = createAsyncThunk('resource/getAnotherResource', async (_, thunkApi) => {
   setTimeout(() => thunkApi.dispatch(makeMove(apiResponse)), 1500);
}


// TESTING CODE
// mock api request
rest.post(
    `/api/getResource`,
    async (req, res, ctx) => {
        return res(
            ctx.status(200),
            ctx.json({ resource })
        );
    }
)
    
    
beforeEach(() => {
    jest.useFakeTimers();
});

afterEach(() => {
    jest.runOnlyPendingTimers();
    jest.useRealTimers();
});
    
...
userEvent.click(pitElements[10]);
jest.advanceTimersByTime(1500);
...
    
```

### What happened:

// if i have below line I can see that state is change for the first settimeout
// if i comment it out no state change occurs, i think i expect this.
// HOWEVER, the full state changes do not occur for the other two settime outs
jest.advanceTimersByTime(1500);

I expect that at least to be able to run all the setimeouts to get to the end stage.
Or is there a way to short-circuit the timeouts and call thier callbacks directly.
Something like mock timeouts and call their callbacks immediately. Is there a setting 
for this in the before each block.

```
console.error
    Warning: An update to Resource inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
```

### Problem description:

Only the first timeout seems cause no issues if advancing for that time out is used.
But the other timeouts are left in limbo. And any state set by them i am depending 
on to check is not set in time to be checked.

### Suggested solution:

It would be nice to be able to in the before each block/ or per test
to indicate that i just want to call the callback of the timeout and not test the timeout itself

**Comment by eps1lon** [comment]
Sorry to hear you're having trouble. This doesn't sound like an issue with `@testing-library/react` per-se but rather with your mocks (or lack of network request mocking). 

I recommend you check out our [community discord](https://testing-library.com/discord) and see if someone is able to help you.
