### ISSUE TITLE
post-upgrade, unexpected `act` warning with `fireEvent` (includes repro)

### ISSUE THREAD

**Issue by trv-wcaneira** [testing-library/react-testing-library#1126]
- `@testing-library/react` version: 13.4.0
- Testing Framework and version:  jest@27.5.1
- DOM Environment: jsdom@16.7.0
- node: 16.14.2
- react: 18.2.0

### Relevant code or config:

```js
  render(<App />);
  
  //generates an act warning unexpectedly
  fireEvent.click(screen.getByText('Click Me'))
 
  await waitFor(() => {
    expect(global.fetch).toHaveBeenCalled()
  })
```

### What you did:

Upgraded existing application to react 18+ and RTL 13+.

### What happened:

A number of tests starting producing `act` warnings after the upgrade.  

In this case, the component is rendered , the test `fireEvent`s a click, and then awaits that a `fetch` function was called.  The `fireEvent` now produces an `act` warning.

### Reproduction:

I was able to reproduce the issue with a simple CRA repo, here: https://github.com/trv-wcaneira/act-warning-fireevent-mcve

### Problem description:

In this case, I can't figure out how to get rid of the `act` warning without "hacking" something I can't explain around the `fireEvent` call.  I was under the impression that the RTL functions like `fireEvent` already internally used `act`, and even eslint warns me when I play around and wrap the `fireEvent` call with it.

### Suggested solution:

None ATM, sorry.

**Comment by eps1lon** [comment]
Your test is just waiting for the `fetch` call and ends. But after that you have state updates that are therefore no longer wrapped in `act`.

Either implement aborting the effect handler or test the effect until it finished.

**Comment by trv-wcaneira** [comment]
> Either implement aborting the effect handler or test the effect until it finished.

Thank you, you are right.  I apologize for missing this.
