### ISSUE TITLE
RenderHook with Wrapper that has async useEffect

### ISSUE THREAD

**Issue by tuul-wq** [testing-library/react-testing-library#1134]
Today I've faced an interesting test that should use a `wrapper` that is a `Context.Provider` with `useEffect` inside.
`useEffect` has side effect - makes a fetch request.
Running the test I see an error ` When testing, code that causes React state updates should be wrapped into act(...).`
The side effect doesn't affect my `connections`, however I would like to eliminate this error and do it the right way.

```
  useEffect(() => {
    (async () => {
      await setupConnections();
      setConnectionReady(true);
    })();
  }, []);
```
In other tests where `useEffect` contains a side effect I use this approach, but in hook test seems that I'm missing something.
```
  await act(async () => {
     render(<NetworkProvider>children</NetworkProvider>);
  });
```
```
  test('should have defined connection', async () => {
    const wrapper = ({ children }: any) => <NetworkProvider>{children}</NetworkProvider>;

    const { result } = renderHook(() => useNetworkContext(), { wrapper });
    const { connections } = result.current;
    expect(connections).toBeDefined();
  });
```
Would be nice to somehow wait for `NetworkProvider` to render and use it as a wrapper 🤔

**Comment by eps1lon** [comment]
You need wrap the state update in `act`. To make this agnostic to the internal timing (unclear how long `setupConnections` takes) your should probably use `waitFor`:

```tsx
waitFor(() => {
  expect(connections).toBeDefined();
})
```

For further questions please reach out in our [community discord](https://testing-library.com/discord).
