### ISSUE TITLE
Can't seem to test a custom hook

### ISSUE THREAD

**Issue by louis-young** [testing-library/react-testing-library#1140]
- `@testing-library/react` version: 13.4.0
- Testing Framework and version: Jest version 27.5.1
- DOM Environment: Jest DOM version 5.16.5 with JSDOM version 27.5.1

### Relevant code or config:

```js
export const useValue = (getValue) => {
  const [value, setValue] = useState();

  useEffect(() => {
    (async () => {
      const newValue = await getValue();

      setValue(newValue);
    })();
  }, [getValue]);

  return value;
};

...

describe("useValue", () => {
  it("works", async () => {
    const { result } = renderHook(() =>
      useValue(jest.fn().mockResolvedValue("__VALUE__"))
    );

    await waitFor(() => result.current === "__VALUE__");

    expect(result.current).toBe("__VALUE__");
  });
});
```

### What you did:

Tried to test a custom hook.

### What happened:

It failed with the following error:

```
expect(received).toBe(expected) // Object.is equality

Expected: "__VALUE__"
Received: undefined
```

### Reproduction:

https://codesandbox.io/s/github/louis-young/react-testing-library-issue

### Problem description:

I can't test my hook.

### Suggested solution:

I'm not sure if this is a bug or if I'm doing something wrong so I'm not sure what the solution would be. Thanks.

**Comment by bpinto** [comment]
I believe the problem here is that recently - couldn't find the release notes for it - `waitFor` has changed and instead of it supporting a boolean value you now need to return a promise.

```
-    await waitFor(() => result.current === "__VALUE__");
+    await waitFor(() => expect(result.current).toEqual("__VALUE__"));
```

fixes your test.

**Comment by louis-young** [comment]
Using an `expect` inside `waitFor` appears to do the trick! I had a look for the release notes and couldn't find them either. It makes sense though as this isn't an issue with the previous major version of Testing Library. Thanks for your help!

**Comment by MatanBobi** [comment]
@bpinto the code for [`checkCallback`](https://github.com/testing-library/dom-testing-library/blame/edffb7c5ec2e4afd7f6bedf842c669ddbfb73297/src/wait-for.js#L143) hasn't changed for two years now, when do you think this behavior broke?

**Comment by bpinto** [comment]
@MatanBobi maybe it's a difference between the react-hooks-testing-library `renderHook` and the one on this library?

**Comment by MatanBobi** [comment]
Yep, that's it.. Looking at the custom `waitFor` in [RHTL](https://github.com/testing-library/react-hooks-testing-library/blob/main/src/core/asyncUtils.ts#L45), it looks different.
Thanks for clarifying that :)

**Comment by bpinto** [comment]
Thanks for verifying that, I'll update my previous comment above to remove the wrong information.

**Comment by louis-young** [comment]
Speaking of differences between RHTL and RTL, the `wrapper` option function of `renderHook` no longer appears to be called with the `initialProps` that the hook under test is being called with. 

We often used this to (for example) create an authentication service in each test with different initial states and then make assertions on it (such as functions being called) using the `authenticationService` that's in scope in the test.

```ts
const wrapper = ({
  children,
  authenticationService,
}) => {
  return (
    <AuthenticationContextProvider
      authenticationService={authenticationService}
    >
      {children}
    </AuthenticationContextProvider>
  );
};

...

{
  wrapper,
  initialProps: {
    authenticationService
  },
}
```

I can roll a curried creator function to be able to provide dependencies to the wrapper from the test but is there an idiomatic way to do this with RTL?

As an aside, is there anywhere that documents all of the changes between RHTL and RTL? We're attempting to upgrade to RTL 13 and drop RHTL and are running into a few issues. Thanks.

**Comment by MatanBobi** [comment]
@louis-young I think that opening an issue about this will be best so we'll be able to verify it's indeed an issue :)
Re a changelog, I'm pretty sure there's no place that documents the changes because we aimed for RTL's `renderHook` to be a drop-in replacement with no regression or different design decisions.

**Comment by louis-young** [comment]
Sure thing, I'll raise an issue. Thanks 🙂
