### ISSUE TITLE
Can't put render() with update in act()

### ISSUE THREAD

**Issue by david-morris** [testing-library/react-testing-library#1142]
- `react` version: 18.2.0
- `@testing-library/react` version: 13.4.0
- Testing Framework and version: jest 14.3.2
  
- DOM Environment: jsdom 29.1.2
  

### Relevant code or config:

```js
    await act(async () => {
      render(<QuoteError />)
      await screen.findByRole("alert", {}, { timeout: 5000 })
    })
```

### What you did:

I bundled a `render()` in an `act()` because my webapp (a client for a Django GraphQL API) fetches immediately after loading.

### What happened:

The DOM did not update, so the findByRole found the following:
```html
    <body>
      <div />
    </body>
```

![image](https://user-images.githubusercontent.com/5530960/195596474-4584f879-3fc7-4d8a-82b5-cb181e0a667d.png)

### Reproduction:

https://codesandbox.io/s/jest-test-forked-puz6ow?file=/index.test.js
### Problem description:

There's no way I've found to wrap a render and immediate update in an `act()`.  I'll have to skip tests that flood the console with warnings.

### Suggested solution:

Either render should be possible to put in an `act()` or should accept an optional async callback to tell it it's not done rendering till the callback resolves.

**Comment by david-morris** [comment]
Update: a workaround: if you put just your query in the `act()`, you'll probably get only one error:

```jsx
    render(<QuoteError />)
    await act(async () => {
      await screen.findByRole("alert", {}, { timeout: 5000 })
    })
```
![image](https://user-images.githubusercontent.com/5530960/195611838-01df368e-da04-413b-b007-4a1e8a1dd6f5.png)

**Comment by david-morris** [comment]
I've been noticing this happening with `userEvent` too, so this isn't limited to making trouble with pages that need to fetch after loading.

**Comment by eps1lon** [comment]
Whatever updates are caused by `render` will not be flushed until the outermost `act` is exited.

So `act( () => {render(...); findByRole(...)})` is probably not doing what you want it to do.

What you want instead is 

```js
render(...);
findByRole(...);
```
