### ISSUE TITLE
waitForNextUpdate() Missing in react testing library RenderHookResult

### ISSUE THREAD

**Issue by naajil-aamir** [testing-library/react-testing-library#1145]
`@testing-library/react` version: "^13.4.0"
- Testing Framework and version:
   "@testing-library/jest-dom": "^5.16.4",
   "@types/jest": "^26.0.24",
   "@types/react": "^18.0.0",   
   "@types/react-dom": "^18.0.0",
   "@types/react-router-dom": "^5.3.3",

### Relevant code or config:

```js
if (tokens) {
    options = {
        wrapper: ({children}) => (
           //gets wrapped token here        
        )
    };
}

const returnedComponent = renderHook(callback, options);
await returnedComponent.waitForNextUpdate();

```

### What I did and what happened
I changed the library from the React hooks testing library to the react testing library because I updated to React 18 and I needed the renderHook. However, in this library, it gives me the following error on the result. 

`Property 'waitForNextUpdate' does not exist on type 'RenderHookResult '.`

(In my understanding, and from the description here, https://github.com/testing-library/react-hooks-testing-library#a-note-about-react-18-support, the change is supposed to be only an import from a different library. Please let me know if i am also missing something else.

**Comment by eps1lon** [comment]
This method is not available in `@testing-library/react`. We currently have no plans implementing this method since we believe `waitFor` is a more robust helper that doesn't couple your test with the specific scheduling implementation of React.

**Comment by daveschinkel** [comment]
then why don't you update your documentation to REMOVE `waitForNextUpdate`
