### ISSUE TITLE
Clearing `innerText` does not correct update DOM

### ISSUE THREAD

**Issue by Nokel81** [testing-library/react-testing-library#1146]
- `@testing-library/react` version: 12.1.5
- Testing Framework and version: jest@28.1.3
  
- DOM Environment: jsdom@20.0.1
  

### Relevant code or config:

```js
const result = render(<div id="my-div" />);
const myDiv = result.baseElement.querySelector("#my-div") as HTMLDivElement;
const newEntry = document.createElement("span");

newEntry.append("I am some text");

myDiv.appendChild(newEntry);
myDiv.innerText = "";
logDOM(myDiv);
```

This outputs:

```
<div
  id="my-div"
>
  <span>
    I am some text
  </span>
</div>
```

instead of what it should

```
<div
  id="my-div"
/>
```

### What you did:

I am trying to test `xterm` and found that if I set `innerHTML` instead then this library produces the expected results.

### What happened:

The child elements were not being cleared correctly.

### Reproduction:

See above

### Problem description:

It is incorrect behaviour according to the spec

### Suggested solution:

Maybe this is required to be fixed in jsdom instead? (I found https://github.com/jsdom/jsdom/issues/1245).

---

I am creating this issue because https://github.com/xtermjs/xterm.js/pull/4214 was closed due to security concerns.

**Comment by eps1lon** [comment]
> Maybe this is required to be fixed in jsdom instead? (I found https://github.com/jsdom/jsdom/issues/1245).

Indeed. Closing in favor of https://github.com/jsdom/jsdom/issues/1245
