### ISSUE TITLE
Suddenly, I wondered whether the act testing library could be a good server-side rendering engine?

### ISSUE THREAD

**Issue by aweiu** [testing-library/react-testing-library#1147]
Compared with ReactDOMServer's [renderToString](https://reactjs.org/docs/react-dom-server.html#rendertostring), RTL's render function is more powerful. It can execute effects and trigger events.
It is simply a lighter headless browser! 😄

**Comment by eps1lon** [comment]
For server rendering, use the corresponding APIs  from `react-dom/server`. Testing Library is not intended as an replacement for server-side rendering.
