### ISSUE TITLE
Timed out in waitFor.

### ISSUE THREAD

**Issue by Hr-new** [testing-library/react-testing-library#1149]
**Problem**
I want to test validation message when user give empty value so i use waitFor and inside that i try to find that alert using findByRole() but it throw error like Timed out in waitFor. I also use { timeout: 250000}

`import React from "react";
import { screen, waitFor, fireEvent } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { customRender } from '../../utils/test-utils'
import Accountmanagerinfo from "./Accountmanagerinfo";

test('initial rendering', async () => {
    customRender(<Accountmanagerinfo />)

    const profileImage = screen.getByAltText('Mail Icon')
    expect(profileImage).toBeInTheDocument()

    const firstNameInput = screen.getByRole('textbox', { name: "First Name" })
    expect(firstNameInput).toBeInTheDocument()

    userEvent.clear(firstNameInput)
    userEvent.type(firstNameInput, '')

    await waitFor(async () => {
        const alert = await screen.findByRole('alert')
        expect(alert).toBeInTheDocument()
    })

    const headerText = screen.getByRole('heading', { name: /Contact Info/i })
    expect(headerText).toBeInTheDocument()
})`

**Comment by cjsilva-umich** [comment]
@Hr-new  Did you ever get this figured out? I'm running into the same issue and am pretty confused.

**Comment by mstangret** [comment]
The newest version of user-event library requires all actions to be awaited. Have you tried that?

**Comment by deshiknaves** [comment]
I'm seeing this issue too. `jest.useFakeTimers` causes `getByX` and `waitFor` not to work. Take the fake timers and everything works.

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), or a link to a repository on GitHub.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by eps1lon** [comment]
Closing since no repro was provided.

**Comment by skulden13** [comment]
After removing the following line from `jest.config` the same issue was fixed for me.

```global.setImmediate = jest.useRealTimers;```

Thanks, @deshiknaves!
