### ISSUE TITLE
unabled to find role "img"

### ISSUE THREAD

**Issue by luckymore** [testing-library/react-testing-library#1151]
- `@testing-library/react` version: 13.3.0
- Testing Framework and version:  ts-jest@28.0.8 node: v16.16.0
  
- DOM Environment: jest@28.1.3
  

### Relevant code or config:

```js
test('`ImageViewer.show/ImageViewer.clear` should be work', async () => {
    render(
      <button
        onClick={() => {
          ImageViewer.show({ image: demoImages[0] })
        }}
      >
        show
      </button>
    )
    fireEvent.click(screen.getByText('show'))
    const img = await screen.findByRole('img')
    expect(img).toBeVisible()

    act(() => {
      ImageViewer.clear()
    })
    await waitFor(() => expect(img).not.toBeVisible())
  })
```

### What happened:
Should `img` have default role values? why findByRole can't find it ?
![image](https://user-images.githubusercontent.com/5390013/200832405-3009d227-3961-4125-98b5-f926fc6356f9.png)

**Comment by eps1lon** [comment]
It has `display: none` and is thus not part of the a11y tree. I'd usually recommend `const img = await screen.findByRole('img', {hidden: true})` but the very next assertion expects it to be visible so either your assertions need refinement or your implementation is broken.

**Comment by luckymore** [comment]
@eps1lon  thx, I have a doubt, why check visible in `findByRole` rather than in `toBevisible`
