### ISSUE TITLE
Unable to find an element by: data-testid 

### ISSUE THREAD

**Issue by ApooBG** [testing-library/react-testing-library#1154]
I am trying to create a new Jest test (after successfully creating a few simple ones) but for some reason I get this error.
![image](https://user-images.githubusercontent.com/47273549/203308822-f5af3b92-849e-4a6a-b906-09c71f6034fa.png)
code:
![image](https://user-images.githubusercontent.com/47273549/203309608-0127f534-f47b-46b7-957d-807d85b49ad2.png)

and inside Home.js I have another render which is called Rules.js and returns this
![image](https://user-images.githubusercontent.com/47273549/203309664-58c895a1-d3e1-48fb-8f54-db253feda0ea.png)

What I want is to get the input and change it to another word ("For") and then userText should be the same as that input. However, for some reason it cannot find the input, when I successfully tested it in another test and also the userText is null, when in the program there is a onChange method in the input which makes the userText equal to that input.

**Comment by eps1lon** [comment]
Sorry to hear you're having trouble.

I recommend you check out our [community discord](https://testing-library.com/discord) and see if someone is able to help you.
