### ISSUE TITLE
Doesn't work well with NextJs v13 next/image

### ISSUE THREAD

**Issue by soulbeing** [testing-library/react-testing-library#1158]
Image can be used without width and height like what I did in the following code.

### Relevant code or config:
with 
```
<Image src={`https:${url}`} fill placeholder="empty" priority alt={title} />
```

and 
```
 "@testing-library/react": "13.4.0",
"next": "13.0.5",
```

because nextjs 13 deprecated layout property
https://nextjs.org/docs/api-reference/next/image

### What you did and what happened:

I get 

```
    Image with src "https://images.ctfassets.net/xxxx....." must use "width" and "height" properties or "layout='fill'" property.
```

### Problem description:

change the code to 
```
 <Image src={`https:${url}`} fill layout="fill" placeholder="empty" priority={isPrimaryHero} alt={title} />
```
 fixes the problem, but layout="fill" is totally doing nothing at all but to pass the test.

**Comment by eps1lon** [comment]
This sounds like a problem with either Next.js or possibly JSDOM. I would suggest opening this against https://github.com/vercel/next.js/ first to identify where the issue originates.
