### ISSUE TITLE
Different DOM upon rendering same component in 2 or more tests

### ISSUE THREAD

**Issue by Rasikh-DMio** [testing-library/react-testing-library#1159]
- `@testing-library/react` version: ^12.1.5
- Testing Framework and version: Jest ^29.3.1
  
- DOM Environment: jest-dom ^5.16.5 (@testing-library/jest-dom)
  
- Node: v18.11.0
- React: 17.0.2
### Relevant code or config:

```js
describe('The problem', () => {
  it('displays initial DOM', async () => {
    render(<WrappedApp />);
    screen.debug();
  });

  it('should display the same DOM as above', async () => {
    render(<WrappedApp />);
    screen.debug();
  });

  it('should also match the last two DOMs', async () => {
    render(<WrappedApp />);
    screen.debug();
  });
});
```

### What you did:

Writing integration test to test the flow of our entire app and simulate a few actions

### What happened:

Following is the screen.deug() for all three tests in order, for the same component being render(...)'d, the outputs are progressing as if the component never gets resets and if it was all a single test

![image](https://user-images.githubusercontent.com/113328290/204702240-7a7ad3a5-ba92-4150-b0df-9f6c6a6bdc30.png)
![image](https://user-images.githubusercontent.com/113328290/204702272-3da58763-a35d-40c3-b370-ad922d9f7e06.png)
![image](https://user-images.githubusercontent.com/113328290/204702299-f325b41e-d119-4193-9e20-9e0f3500bc6f.png)
(The DOM is too big at this point to capture in a single screenshot but hopefully I've conveyed the issue I'm having)

### Problem description:

Each test should be separate and isolated from others as far as I understand, if that is the case, all three tests rendering the same component should all display the same dom elements for test 2 and 3 but they're not

### Suggested solution:

I thought this might be due to us using redux and the store not getting reset. Searching brought me to [this stackoverflow question](https://stackoverflow.com/questions/69687249/reset-redux-store-after-each-test-with-jest) which I implemented into my tests but still nothing changed.

Any help/guidance would be appreciated. The WrappedApp component is pretty much the entirety of our app, with many many nested components, hooks and what-not, perhaps that is an issue and we shouldn't be approaching our tests like this? Thank you in advance

**Comment by fcotabar** [comment]
Hi @Rasikh-DMio 
I'm not quite sure the reason of that behavior. But what I can tell is that there is a lot of async happening in your component when is rendered and you are not waiting for it until it stops rendering.
Have you tried to wrap the render in the 'waitFor' method?
`await waitFor(() => render(<WrappedApp />));`

Sometimes its better to wait for the element you're expecting to be rendered so you wait for the first assertion instead of waiting in the render.
Example:
First render the component: `render(<WrappedApp />)`
Then wait (with waitFor) for the component you want to test if its render:
`await waitFor(() => expect(screen.getByText(/loading/i).toBeInTheDocument());`

I don't know if I made me understand. But the main problem is that you are not waiting for the async process to be resolved.

**Comment by Rasikh-DMio** [comment]
Hmm alright, I wrapped it into waitFor however is it normal that the first test goes through all the loading process however the second test seems to not have the loading at all?

What I'm trying to say is, if the first test was awaited, everything gets cleaned up, the 2nd test starts and renders _WrappedApp_ with new redux store and mocks, wouldn't it also go through the loading phase of the app, instead it instantly starts from where the last _WrappedApp_ render left off, even with _await waitFor(() => \<WrappedApp />);_for now I'll just go with the component render starting without loading phase after the first test and move on from there, Thanks.

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it. Especially it's not clear how you cleanup between tests.

Please provide a CodeSandbox (https://react.new), or a link to a repository on GitHub.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by Rasikh-DMio** [comment]
Alright no worries, I've already solved the issue with the help of fcotabar's comment, and what I'm worried about isn't really an issue, in-fact it only makes the subsequent tests run faster. I'm not cleaning anything up manually because my setup allows RTL to cleanup automatically in-between tests.

Thank you all for your help, closing now
