### ISSUE TITLE
Supplying wrapper component doesn't allow testing hooks that use mobx observables

### ISSUE THREAD

**Issue by sethreidnz** [testing-library/react-testing-library#1164]
Node = v16.15.0
"dependencies": {
  "mobx": "^6.7.0",
  "mobx-react": "^7.6.0",
  "react": "^18.2.0",
  "react-dom": "^18.2.0"
},
"devDependencies": {
  "@testing-library/jest-dom": "^5.16.5",
  "@testing-library/react": "^13.4.0",
  "@testing-library/react-hooks": "^8.0.1",
  "@testing-library/user-event": "^14.4.3",
  "@types/react": "^18.0.26",
  "@types/react-dom": "^18.0.9",
  "@vitejs/plugin-react": "^3.0.0",
  "jsdom": "^20.0.3",
  "typescript": "^4.9.3",
  "vite": "^4.0.0",
  "vitest": "^0.26.0"
}

### Summary

I'm not 100% sure this is a bug more of a limitation of the way that renderHook ends up using the wrapper component. I'm using mobx which will [automatically re-render any components wrapped in `observer`](https://mobx.js.org/react-integration.html). However since the wrapper component for `renderHook` is then wrapping a `TestComponent` in the test harness helper I believe this means that the actual wrapping component (`TestComponent`) is not an observer and therefore renderHook cannot work as expected with mobx.

### Problem description

I have setup a reproduction here with a simplified version of what I'm doing in a project. 

https://github.com/sethreidnz/mobx-renderHook-example

You'll see [there are two tests:](https://github.com/sethreidnz/mobx-renderHook-example/blob/main/src/useRepositoryQuery.test.tsx)

1. Where I use renderHook with a wrapper component that is an `observer`
2. Where I render the hook inside of a wrapper component using react testing libraries render. 

The second one passes and the first does not. The only explanation I can have is that since the hook is being called in `TestComponent` (which is not an observer) and not in the the wrapper provided, then mobx doesn't even register there is a listener to the result of the hook, and therefore does not make the component tree re-render.

### Reproduction

https://github.com/sethreidnz/mobx-renderHook-example

### Proposal

I'm happy to make a PR to solve this issue as I imagine it's true for any library like mobx where you need the wrapper component to be the direct caller of the hook in order for things to work correctly. 

I am not 100% sure of the approach as I've played around a little, but haven't come up with something yet and thought I'd raise the issue first and get feedback before sinking too much time into this issue.

**Comment by sethreidnz** [comment]
> As you are using react 18, you should rather use `renderHook` from `@testing-library/react` ([half finished migration guide if you need it](https://github.com/testing-library/react-hooks-testing-library/blob/chore/migration-guide/MIGRATION_GUIDE.md)). We won't be making any significant change to this version of `renderHook`, but I'll transfer this issue over for the @testing-library/react team to consider.

Thanks that's great! I have upgraded my repro to use the `renderHook` from `@testing-library/react` also just to make sure it didn't make a difference. Thanks for that. More than happy to make a contrib if there is some way that we could make it possible to get this working. 

The simplest approach I can see from looking at the new code would be to allow for the passing of optional function that would be called on the `TestComponent` if it exists and would allow people to decorate the direct component that is rendering the hook.

**Comment by eps1lon** [comment]
I would suggest having a custom component that uses your hook as it is supposed to. `renderHook` is supposed to be a minimal utility. I would suggest forking its implementation if you want to keep using such an API.

**Comment by sethreidnz** [comment]
Thanks for your response I know I can do that but then that is the entire point of a hook to isolate the state part from the UI and allow for independent testin of state logic without having to render things into the DOM and then query it. Makes for way more complex tests that are not as complete or easy to understand. That's why I like using testing libraries renderHook utility in the first place.

It's less of I want to but the project is using it (along with many many many other projects) and it would be a simple change with no affect to any other users. But I understand you position.

Thanks!

**Comment by c01nd01r** [comment]
Workaround: 
```typescript
import { ReactNode, isValidElement, FunctionComponent } from 'react'

const MobxWrapper = ({ children }: { children: ReactNode }) => {
  if (isValidElement(children)) {
    return { ...children, type: observer(children.type as FunctionComponent) };
  }

  throw new Error('Invalid children. Check MobxWrapper');
};

const useCouter = () => {...}

test('My test', () => {
  const { result } = renderHook(() => useCounter(), { wrapper: MobxWrapper });
})

```
