### ISSUE TITLE
fireEvent does not trigger onLoad event of form component

### ISSUE THREAD

**Issue by komarovalexander** [testing-library/react-testing-library#1171]
- `@testing-library/react` version: 13.0.0
- Testing Framework and version: 
  
- DOM Environment:
  

### Relevant code or config:

```js
        const CustomForm = () => (
		<form
			onLoad={() => {
				console.log('onLoad'); // this is not triggered
			}}
			data-testid="formmy"
		></form>
	);
	test('SendToCheckButton is disabled if form has unsaved changes', async () => {
		await act(async () => {
			await render(<CustomForm />);
		});
		const form = await screen.findByTestId('formmy');
		act(() => fireEvent.load(form));
	});
```

### What you did:
Hi I'm trying to fire onLoad event on the form but it does not work

it only works inside the addEventListener funtion: form.addEventListener('load', () => console.log('load'));

is there a way to make onLoad work on the form component when calling fireEvent.load?

**Comment by eps1lon** [comment]
Does this work in a browser?

**Comment by komarovalexander** [comment]
My bad, I use antd form and this form has onLoad event. Probably I was fired this in a wrong way
