### ISSUE TITLE
window env  variables are not not accessible while running component test

### ISSUE THREAD

**Issue by Rk1131** [testing-library/react-testing-library#1175]
While running component test it is giving me an error of undefined for _window.env.VAR_NAME_, i have all the api endpoints in a single file with env variable.

- `@testing-library/react` version: "^13.4.0"
- "react" : "18.0.0"
- DOM Environment:

**Comment by eps1lon** [comment]
Sorry to hear you're having trouble. This doesn't sound like an issue with `@testing-library/react` per-se but rather with your mocks (or lack of network request mocking). 

I recommend you check out our [community discord](https://testing-library.com/discord) and see if someone is able to help you.
