### ISSUE TITLE
Event data undefined when using fireEvent.change

### ISSUE THREAD

**Issue by Mic1e** [testing-library/react-testing-library#1181]
- `@testing-library/react` version: ^14.0.0
- Testing Framework and version: `jest`: ^29.4.3
- DOM Environment: `jest-environemnt-jsdom`: ^29.4.3

#### ExampleComponent.tsx
```tsx
import React, { useState } from "react";
import { OptionProps } from "./OptionProps";

export default function ExampleComponent() {
    const [optionList, setOptionList] = useState([])

    const onOptionChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
        throw Error('TEST: ' + console.log(e))
    }

    return (
        <select
            onChange={(e) => onOptionChange(e)}
            value=''
            data-testid='select-test'
        >
            {optionList && 
                optionList?.map((option: OptionProps) => {
                    return (
                        <option key={option.key} value={option.value}>
                            {option.text}
                        </option>
                    )
                })
            }
        </select>
    )
}
```

#### ExampleComponent.test.tsx
```tsx
import { fireEvent, render } from "@testing-library/react";
import React from "react";
import ExampleComponent from "./ExampleComponent";
import { OptionProps } from "./OptionProps";


const optionList: OptionProps[] = [
    { text: 'Default Option', value: 'Default Option', key: '' },
    { text: 'Option 1', value: 'Option 1', key: '1' },
]

beforeEach(() => {
    const setStateMock = jest.fn()
    const optionListStateMock = jest.fn().mockReturnValue([optionList, setStateMock])

    jest.spyOn(React, 'useState').mockImplementationOnce(optionListStateMock)
})


test('testing onChange event', async () => {
    const result = render(<ExampleComponent />)
    const selectElement = result.getByTestId('select-test')

    fireEvent.change(selectElement, {target: {value: '1'}})

    expect(selectElement).toHaveValue('Option 1')
})
```

### What you did:

I was trying to test code inside the onChange event listener of a drop down select element. I want to fire the onChange event and then grab the newly selected value inside the onChange function.

I have looked through many examples and docs and at this point I'm lost as to why this is happening, nobody else seems to have this problem.
I have also tried using ReactTestUtils.Simulate, userEvent.selectOptions etc. They all manage to fire the on change function but none of them pass any data into it.

### What happened:

Using `fireEvent.change` I got the onChange function to run for my selected element. However, the data passed to the function is undefined. I am throwing an error inside the function to see what I get there and it shows undefined. The actual value of the select element also doesn't change.

### Reproduction:

Render a component which has a select element with an on change function.
Fire an on change event on the select element.
Notice that there is no event data in the on change function and select element's value doesn't change.

### Problem description:

I would like to test code that is inside an on change function which uses data from the event. I would also like to test whether the select element value actually changes. Currently neither are possible.

**Comment by Mic1e** [comment]
Figured it out, you need to pass in a `HTMLOptionElement` object instead of `{ target: { value: '1' } }`. The option element needs to also exist in the rendered component.
I also went with `userEvent` and using `await`, works fine now.
Also ensure the option element has your desired value before passing it to `userEvent`.

**Comment by MatanBobi** [comment]
@Mic1e Feel free to create a PR if you believe there's something worth mentioning in the docs :)
