### ISSUE TITLE
test fails in interaction simulation

### ISSUE THREAD

**Issue by devmanbr** [testing-library/react-testing-library#1186]
- `@testing-library/react` version: 13.4.0
- Testing Framework and version: jest 29.4.2
- DOM Environment: @happy-dom/jest-environment 8.7.1

### Relevant code or config:

```tsx
test("should render button", async () => {
    const { getByTestId } = render(<Button data-testid="button">Submit</Button>);
    const button = getByTestId("button");

    expect(button).toBeInTheDocument();
    expect(getComputedStyle(button).backgroundColor).toBe("#253FCC"); // works

    userEvent.hover(button);
    expect(getComputedStyle(button).backgroundColor).toBe("#263DB6"); // not work (hover)
    userEvent.unhover(button);
});
```

### Problem description:

I'm using @testing-library/react, @happy-dom/jest-environment (since with jsdom not even part of the tests works), and tailwind (whose css I inject before each test).

the test works on default state check but on hover it fails.

I already checked if this was due to the absence of the css, and everything that could be related. from what I understand, either the failure is happening because happy-dom does not simulate the event (hover), or the failure is in the @testing-library.

with jsdom not even the default state works. background color remains as transparent all the time

### Suggested solution:
I don't know exactly how to proceed

**Comment by MatanBobi** [comment]
Hi @devmanbr, thanks for opening this one.
Can you please create a minimal code reproduction for us to investigate if the issue is on our end or in happy-dom? Debugging this without the correct reproduction will take us a lot of time.
Thank you.

**Comment by devmanbr** [comment]
I created a simple minimal example that can be easily reproduced.

install `@happy-dom/jest-environment`, `jest`, `ts-jest` and all other usual required dependencies.

the `jest.config.js` file:
```js
const { resolve } = require("path");
const root = resolve(__dirname);
module.exports = {
    rootDir: root,
    testMatch: [
        "<rootDir>/**/*.test.{ts,tsx}"
    ],
    testEnvironment: "@happy-dom/jest-environment",
    preset: "ts-jest",
    clearMocks: true,
    coverageDirectory: "coverage",
    coverageProvider: "v8"
};
```

the `render` function is customized to inject styles into all tests (`custom-render.ts`). I haven't found a different way that works.
```ts
import { render as renderRTL } from "@testing-library/react";
export function render(ui, option) {
    const view = renderRTL(ui, option);
    const style = document.createElement("style");
    style.type = "text/css";
    style.innerHTML = `
    button {
        background-color:#253FCC;
    }
    button:hover {
        background-color:#263DB6;
    }
    `;
    document.body.appendChild(style);
    document.body.appendChild(view.container);
    return view;
};
```

the test file:
```tsx
import "@testing-library/jest-dom";
import { render } from "./custom-render";
import userEvent from "@testing-library/user-event";

test("should render button", async () => {
    const { getByTestId } = render(<button data-testid="button">Teste</button>);

    const button = getByTestId("button");

    expect(button).toBeInTheDocument();
    expect(getComputedStyle(button).backgroundColor).toBe("#253FCC"); // works

    userEvent.hover(button);
    expect(getComputedStyle(button).backgroundColor).toBe("#263DB6"); // not work
    userEvent.unhover(button);
});
```

it is not mandatory for me to use the `@happy-dom/jest-environment` library. I installed it because with `jsdom` the failure was total.
I just need it to work, so I can reliably test everything, including the interactions.

**Comment by eps1lon** [comment]
Computed styles is a responsibility of whoever implements the DOM in your environment. For Jest, that's JSDOM. However, due to the complexity and performance impact, they don't implement all of CSS.

If you want to assert on visuals I'd recommend running tests in a real browser.
