### ISSUE TITLE
render a react component for testing does not work with React 18

### ISSUE THREAD

**Issue by reinertisa** [testing-library/react-testing-library#1189]
- `@testing-library/react` version:14.0.0
- Testing Framework and version: 
  
- DOM Environment: 18.2.0
  

### Relevant code or config:

```js

import * as React from 'react'
import {createRoot} from 'react-dom/client';
import {FavoriteNumber} from '../favorite-number';

test('renders a number input with a label "Favorite Number"', () => {
  const div = document.createElement('div');
  createRoot(div).render(<FavoriteNumber />);
  expect(div.querySelector('input').type).toBe('number')
})
```

**Comment by MatanBobi** [comment]
Hi @reinertisa.
It looks like this test isn't using react-testing-library at all, it just renders a component as part of the test.
I'm closing this one as it doesn't seem related to RTL. 
Having said that, feel free to reach out in our [discord channel](https://discord.gg/testing-library), people in the community would love to help :)
