### ISSUE TITLE
Accesing a key that does not exist on a object from a scss module import returns a string of undefined instead of undefined.

### ISSUE THREAD

**Issue by kainn9** [testing-library/react-testing-library#1190]
- `@testing-library/react` version:
"@testing-library/jest-dom": "^5.16.5",
"@testing-library/react": "^14.0.0",
- Testing Framework and version:
Jest(I think), not sure how to check the version
- DOM Environment:
"@testing-library/jest-dom": "^5.16.5",

### What you did:
Imported a scss module and attempted to access a key that does not exist from the object.

### What happened:
It returned a string "undefined" instead of undefined. This seemed to only occur in the test.

### Reproduction:
Here is a video showing the potential issue:

https://user-images.githubusercontent.com/85503587/224442203-25435642-d586-4eec-8415-6a055f845371.mp4

One thing I did not show in the video is that the string is "undefined"(in the video, I only show the logs of `typeof foo` instead of the values themselves. But if I were to log the values, they would be "undefined" and undefined. I also falsely thought spreading the module import into a new object could resolve the issue, but it turns out that this results in an empty object(only in the test context though).

Something also worth noting is that in the video I'm importing the scss module from a ts file that looks something like:
```ts
import scssColors from "./colors.module.scss"
import { type colorName } from "./types"
export {
  scssColors ,
  type colorName
}
```
But the result is the same even if I import the scss module directly into the component file /w the logs.

To reproduce, you must import a scss module and console.log the value of attempting to access a key that does not exist on the object from the import(inside the context of a test).

### Problem description:
If you are writing a test for a react component that expects an undefined/nullish/falsey value(for example, the component uses the `null coalescing operator - ??`), this behavior can mess up the test.

**Comment by eps1lon** [comment]
Sorry to hear you're having trouble. This doesn't sound like an issue with `@testing-library/react` per-se.

I recommend you check out our [community discord](https://testing-library.com/discord) and see if someone is able to help you.
