### ISSUE TITLE
Cleanup freezes for react-native tests

### ISSUE THREAD

**Issue by brunovollmer** [testing-library/react-testing-library#1193]
- `@testing-library/react-native` version: 12.0.0-rc.2
- Testing Framework and version: jest -> 29.4.1
- DOM Environment: jsdom -> 29.3.1

### Relevant code or config:

```js
export function renderWithProviders(
  ui: React.ReactElement,
  {
    preloadedState = {},
    // Automatically create a store instance if no store was passed in
    store = configureStore({ reducer: reducers, preloadedState }),
    ...renderOptions
  }: ExtendedRenderOptions = {},
) {
  function Wrapper({ children }: PropsWithChildren<{}>): JSX.Element {
    return <Provider store={store}>{children}</Provider>
  }

  // Return an object with the store and all of RTL's query functions
  return { store, ...render(ui, { wrapper: Wrapper, ...renderOptions }) }
}

```

```js
describe('XXX', () => {

  beforeEach(async () => {
    store = createTestStore({})
  })

  it('XXX', async () => {
    renderWithProviders(<Screen />, { store })

    await waitFor(() => {
      expect(
        screen.getByRole('button', { name: /test/i }),
      ).toBeTruthy()
    })

    fireEvent(
      screen.getByRole('button', { name: /test/i }),
      'click',
    )
  })
})

```

### What you did:

Use the render function to render a screen.

### What happened:

Screen is rendered correctly but the cleanup function freezes.

```
thrown: "Exceeded timeout of 5000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      1 | import React, { PropsWithChildren } from 'react'
    > 2 | import { render } from '@testing-library/react-native'
```

### Problem description:

I need to run the tests that use the render function from  `'@testing-library/react-native'` with `RNTL_SKIP_AUTO_CLEANUP=True yarn test` as otherwise they would fail because the cleanup freezes.

### Suggested solution:

I could not find out why the cleanup freezes.

**Comment by MatanBobi** [comment]
Hi @brunovollmer, the `@testing-library/react-native` repo doesn't belong to the testing-library organization, you can file an issue on their repo:
https://github.com/callstack/react-native-testing-library

**Comment by brunovollmer** [comment]
@MatanBobi Thanks for pointing that out. I created an issue there.
