### ISSUE TITLE
🐛 debug does not render HTML style elements

### ISSUE THREAD

**Issue by ling1726** [testing-library/react-testing-library#1194]
- `@testing-library/react` version: 13.4.0
- Testing Framework and version: jest@27.5.2 from react-scripts@5.0.1

- DOM Environment: from react-scripts@5.0.1

Relevant code or config

Repro repo 

https://github.com/ling1726/repro-testing-library-debug-style

clone and run `npm test`

https://github.com/ling1726/repro-testing-library-debug-style/blob/ec8c5cc1010a9ea85b225b3e341827168982bfbd/src/App.test.tsx#L3-L31

What you did:

Rendered a `<style>` element and called `debug()`

What happened:

`style` elements are not visible in the console output

```
    <body>
      <div>
        <div>
          Foo 
           
        </div>
      </div>
    </body>
```

Actual snapshot

```
<div>
  <div>
    Foo 
    <style
      id="style-children"
    >
      .foo { color: red; }
    </style>
     
    <style
      id="style-dangerous"
    >
      .foo { color: red; }
    </style>
  </div>
</div>
```

Reproduction repository: https://github.com/ling1726/repro-testing-library-debug-style

Problem description:

HTML style elements are not visible when debugging

Suggested solution: Don't have enough knowledge of the codebase to propose one sorry 😅

**Comment by MatanBobi** [comment]
Hi @ling1726!
As you can see in the [`prettyDom` section in our docs](https://testing-library.com/docs/dom-testing-library/api-debugging#prettydom), `style` and `script` tags are ignored by default. You can change that behavior by passing a custom `filterNode` function.
