### ISSUE TITLE
Peer dependency is too strict and prevents install with React 18.1 or 18.2

### ISSUE THREAD

**Issue by wylieconlon** [testing-library/react-testing-library#1210]
`@testing-library/react` version: 14.0.0

The current peerDependencies for this library are too restrictive and prevent installation of the library. The error is:

```
npm ERR! Conflicting peer dependency: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^18.0.0" from @testing-library/react@14.0.0
npm ERR!   node_modules/@testing-library/react
npm ERR!     dev @testing-library/react@"14.0.0" from the root project
```

The root cause is that `@testing-library/react` specifies

```
  "peerDependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
```

The suggest fix is to update peerDependencies to:

```
  "peerDependencies": {
    "react": "^18",
    "react-dom": "^18"
  },
```

That would allow any 18.x version.

**Comment by eps1lon** [comment]
`^18.0.0` allows `18.2.0`. This looks like a bug with your package manager. Please open an issue against their repository and link it to this issue so that we can track it.
