### ISSUE TITLE
React test suits fail with SyntaxError: Illegal break statement

### ISSUE THREAD

**Issue by rimpu** [testing-library/react-testing-library#1221]
![image](https://github.com/testing-library/react-testing-library/assets/25206744/3ad072a6-25e7-48e1-8b81-3c99affeb36c)

![image](https://github.com/testing-library/react-testing-library/assets/25206744/a1489178-0d37-47f3-a894-84ea30229477)

I have started to get this error. These are the set of packages I am using.

![image](https://github.com/testing-library/react-testing-library/assets/25206744/3a861f88-72ae-4c4e-8088-60d7a17a6d4a)

Please advise how to solve the same.

**Comment by mbaric1** [comment]
As a workaround, override the latest version of `nwsapi` which seems to be causing this issue.

If using `npm`, add following to the package.json.

```json
"overrides": {
    "nwsapi": "2.2.5"
}
```

**Comment by MatanBobi** [comment]
Thanks @mbaric1.
I'm closing this one as it's not related to us directly, here's a bug for future reference: https://github.com/dperini/nwsapi/issues/90.
