### ISSUE TITLE
Upgrade to react-scripts v5 breaking my test cases

### ISSUE THREAD

**Issue by nikgun1984** [testing-library/react-testing-library#1223]
Hi,

I recently upgraded react-scripts to v5, which added bunch of breaking changes, including to jest. My useFakeTimers no longer work. When I run my tests it stops running it throws the error "Exceeded timeout of 10000". If add timeout to longer time, my test just hangs. I tried to upgrade jest to 29 but now I am getting "ReferenceError: TextEncoder is not defined". Does anyone have similar issues? Seems breaking happens for jest27 just like documentation mentions? I tried to downgrade to previous jest version but my fakeTimers still not working. Can anyone help to figure it out?

**Comment by MatanBobi** [comment]
Hi @nikgun1984, can you please create a reproduction repo for us to look into? It will be quite hard to help without having a clear definition of the problem.

**Comment by nikgun1984** [comment]
Hi,
It is going to be hard to reproduce this repo, since my team uses AEM and repo is in bitbucket under the company. Will sharing package.json, setupTest.js and test file help at all? But yeah it would be probably quite hard to reproduce this.

**Comment by MatanBobi** [comment]
Without a proper reproduction, it will be hard for us to pin down what's causing it and whether there's a bug in testing-library or not. package.json and setupTests probably won't be enough because react-scripts 5 is available for almost two years if I'm not mistaken and we haven't got issues related to this.
