### ISSUE TITLE
 TypeError: expect(...).toBeInTheDocument is not a function  

### ISSUE THREAD

**Issue by rakhmonovbekzod** [testing-library/react-testing-library#1226]
TypeError: expect(...).toBeInTheDocument is not a function  and  TypeError: expect(...).toHaveBeenSubmitted is not a function

**Comment by MatanBobi** [comment]
Hi @rakhmonovbekzod.
This issue doesn't contain enough data for us to understand what's wrong.
Did you import `@testing-library/jest-dom`?

**Comment by dgesteves** [comment]
I am having the same issue.

**Comment by MatanBobi** [comment]
@dgesteves withiug more information we won't be able to help. Did you import the correct packages? Please attach a cloneable reproduction.

**Comment by GurovDmitriy** [comment]
![image](https://github.com/testing-library/react-testing-library/assets/26795848/53747629-ab06-49ea-959c-1ebf2d76c683)

**Comment by Andrew-Staines-ZS** [comment]
@GurovDmitriy If your issue is still not resolved you can check this out for more details,
https://github.com/nrwl/nx/issues/9140
