### ISSUE TITLE
react-testing-examples.com (linked in README) redirects to parked ad site

### ISSUE THREAD

**Issue by rbracco** [testing-library/react-testing-library#1228]
[react-testing-examples.com](https://react-testing-examples.com/jest-rtl/) which is recommended in the README redirects to this page:
http://iyfbodn.com/?dn=react-testing-examples.com (tracking data removed from url) 

![image](https://github.com/testing-library/react-testing-library/assets/47190785/f2b12468-0795-4e14-b102-8723d4fea194)

**Comment by MatanBobi** [comment]
Thanks @rbracco!
I've created a PR to resolve this one.
