### ISSUE TITLE
I cannot use my component in .test.jsx file 

### ISSUE THREAD

**Issue by coderbahrom** [testing-library/react-testing-library#1246]
it returns  below error

> SyntaxError: /src/components/templates/AuthComponent/SignInSection/SignSection.test.jsx: Support for the experimental syntax 'jsx' isn't currently enabled (7:52):

       5 | describe("SignSection Component", () => {
       6 |     it("should render the component", () => {
    >  7 |       const { getByText, getByLabelText } = render(<SignSection />);
         |                                                    ^
       8 |   
       9 |       // Use queries to assert that specific elements are rendered
      10 |       expect(getByText("sign_in")).toBeInTheDocument();

```
import { render, fireEvent } from "@testing-library/react";
import SignSection from "./SignSection"

describe("SignSection Component", () => {
    it("should render the component", () => {
      const { getByText, getByLabelText } = render(<SignSection />);
  
      // Use queries to assert that specific elements are rendered
      expect(getByText("sign_in")).toBeInTheDocument(); // Change to your actual text content
      expect(getByLabelText("phone_number")).toBeInTheDocument();
      expect(getByLabelText("password")).toBeInTheDocument();
    });
  
    it("should handle form submission", () => {
      // You may need to mock the login function and other dependencies that are used in the component.
  
      const { getByLabelText, getByText } = render(<SignSection />);
  
      // Provide valid values for phone_number and password
      const phoneInput = getByLabelText("phone_number");
      const passwordInput = getByLabelText("password");
      const submitButton = getByText("sign_in");
  
      fireEvent.change(phoneInput, { target: { value: "valid_phone_number" } });
      fireEvent.change(passwordInput, { target: { value: "valid_password" } });
  
      // Trigger form submission
      fireEvent.click(submitButton);
  
      // You can use assertions to check if the component behaves as expected after submission.
      // For example, you can expect that loading state changes.
    });
  });
```

**Comment by maksimovicdanijel** [comment]
Could you please provide more information on how you are bundling (Webpack, Vite), how you are configuring your test runner (I assume you are using `jest`), etc? 

Looking at the error it sounds like the problem isn't with the library itself but it's more a configuration problem that the runtime can't understand `jsx` files.

Thanks!

**Comment by coderbahrom** [comment]
@maksimovicdanijel thanks for the reply 
I am using Vite for testing just now I have a problem with
 The test suite failed to run import.meta.env.VITE_*
