### ISSUE TITLE
Provide a better experience with lifecycle hooks

### ISSUE THREAD

**Issue by timdeschryver** [testing-library/react-testing-library#1249]
@MatanBobi (and @timdeschryver, if you're still interested in Angular's implementation), it seems like this change could potentially run the risk of cluttering the logs for developers who intentionally _aren't_ using the automatic cleanup functions. (For example, I'm using `vitest`, which by default doesn't have globals enabled. But I'm sticking with Vitest's defaults intentionally.) Particularly, this warning will be logged for every single test file that tests React components.

Is it possible to only display this warning once per call to `jest`/`vitest`/etc.? For instance, is there a way that an ENV var (e.g., `*TL_GLOBAL_WARNING_LOGGED`) could be set (which only lasts the lifetime of `npx jest`, `npx vitest`, etc.)? Or maybe something else would be possible?

_Originally posted by @ITenthusiasm in https://github.com/testing-library/react-testing-library/issues/1244#issuecomment-1802111077_

**Comment by MatanBobi** [comment]
I'll try to get to this one tomorrow evening :) If anyone wants to take it before, feel free.

**Comment by MatanBobi** [comment]
@timdeschryver Do we want to re-open this to think of a better way to do it?
