### ISSUE TITLE
@testing-library/react TypeError: defineProperties is not a function

### ISSUE THREAD

**Issue by Nikodem98** [testing-library/react-testing-library#1261]
Hi, I get this error whenever I import @testing-library/react
<img width="497" alt="image" src="https://github.com/testing-library/react-testing-library/assets/67469274/ddac2e70-dfa0-4ffc-bb76-a4b40af33b91">

"@testing-library/jest-dom": "^6.0.0",
 "@testing-library/react": "^14.1.2",
"@testing-library/user-event": "^14.0.0",

**Comment by meeowngit** [comment]
Can you try to upgrade your react version to v18+?

**Comment by Nikodem98** [comment]
we use "react": "^18.2.0",

**Comment by meeowngit** [comment]
Oops, sorry 😃  I guess issue is totally different

**Comment by MatanBobi** [comment]
@Nikodem98, can you please provide a reproduction of this one? At the moment this issue doesn't have a lot of us to investigate.
You can use https://testing-library.com/new-rtl to create the reproduction.

**Comment by MatanBobi** [comment]
I'm resolving this as no reproduction was added. If someone's experiencing this and can provide a reproduction, please comment here and I'll re-open.
