### ISSUE TITLE
calling rerender causes remounting

### ISSUE THREAD

**Issue by kasir-barati** [testing-library/react-testing-library#1264]
- `@testing-library/react` version: 14.1.2
- Testing Framework and version: jest, 29.7.0
  
- DOM Environment: `"jest-environment-jsdom": "^29.7.0"`
  

#### custom hook:
https://github.com/kasir-barati/my-nextjs-journey/blob/main/libs/hooks/use-update-effect.hook.ts

#### Test case:
https://github.com/kasir-barati/my-nextjs-journey/blob/main/libs/hooks/use-update-effect.hook.spec.tsx

### What you did:

I was just making sure that my hook reset the `useRef` on component unmount and not rerender (like when your states changes and react rerenders it), So I wrote the mentioned unit test to check that out.

### What happened:
https://github.com/kasir-barati/my-nextjs-journey/blob/main/README.md#bug

### Reproduction:

https://github.com/kasir-barati/my-nextjs-journey/

### Problem description:

AFAIK rerender should not cause useEffect to call cleanup callback since it should be invoked only when the component is unmounted. But here it is not the case. I thought something is wrong with the testing library. But I am not 100% sure and also not does not have the confident to do that. So please feel free to enlighten me on what IDK. 🙏 

### Suggested solution:

Do not have any

**Comment by kasir-barati** [comment]
Found some clues here: https://github.com/testing-library/react-hooks-testing-library/issues/9

**Comment by MatanBobi** [comment]
Correct me if I'm wrong or I didn't understand the issue correctly, but React calls the cleanup function on every re-render, that's React's behavior:
<img width="869" alt="Explanation of useEffect setup and cleanup calls from react.dev" src="https://github.com/testing-library/react-testing-library/assets/12711091/c76f62a1-1314-4cf6-97be-bb7f8f39c5b0">
https://react.dev/reference/react/useEffect

So it looks like what you're experiencing is the default behavior, isn't it?

**Comment by kasir-barati** [comment]
hmm, my bad. then I think I cannot test this scenario using react testing lib: 
> I was just making sure that my hook reset the useRef on component unmount and not rerender (like when your states changes and react rerenders it), So I wrote the mentioned unit test to check that out.

Or it is possible still?

**Comment by MatanBobi** [comment]
AFAIU, there's no way to test this because it's not what happens. React will call your cleanup function but then call your setup again, so you might be able to count the times this happens.
Having said that, this is an extreme implementation detail, if react will change it's behavior in the future, this test will likely fail. I wouldn't go down that path and try to find a way to test this hook by ignoring it's implementation details.
