### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module when using render or .tsx files

### ISSUE THREAD

**Issue by Shishouille** [testing-library/react-testing-library#1283]
First of all, hello and thanks if you have time to help me!

### Version summary

```
        "@testing-library/jest-dom": "6.4.2", <--- dom environment
        "@testing-library/react": "^14.2.1" <--- version of testing library
        <---- testing framework: vitest ---->
        "@vitejs/plugin-react-swc": "^3.6.0",
        "vitest": "^1.3.1",
        "vite-tsconfig-paths": "4.3.1",
       <---- front-end framework: nextjs ---->
         "next": "^14.0.4",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        <---------------------------------->
        "node": "20.10.0" <--- node version
        "pnpm": "8.14.0" <--- packager (using workspaces)
```

#### Error
```
SyntaxError: Cannot use import statement outside a module
 ❯ Object.<anonymous> ../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/test-utils.js:6:20

Module node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-test-utils.development.js:12 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "react-dom" asking them to ship the file in .mjs extension or add "type": "module" in their package.json.
```

### Config
```
// tsconfig.json
{
    "$schema": "https://json.schemastore.org/tsconfig",
    "compilerOptions": {
        "jsx": "react-jsx",
        "target": "ES6",
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "incremental": true,
        "noErrorTruncation": true
        "baseUrl": ".",
        "types": ["node", "@testing-library/jest-dom"],
        "noEmit": true
        "paths": {
            "@/*": ["./src/*"],
            "@legacy/*": ["./legacy/*"],
            "@tests/*": ["./tests/*"],
            "@locales/*": ["./locales/*"]
        },
        "types": ["vitest/globals", "@testing-library/jest-dom"]
    },
    "include": [
        "next-env.d.ts",
        "**/*.ts",
        "**/*.tsx",
        "**/*.js",
        "**/*.cjs",
        "**/*.mjs",
        "**/*.gql",
        ".next/types/**/*.ts"
    ],
    "exclude": ["node_modules"]
}
```

```
// vitest.config.mts
import react from "@vitejs/plugin-react-swc"
import tsconfigPaths from "vite-tsconfig-paths"
import { defineConfig } from "vitest/config"

export default defineConfig({
    plugins: [react(), tsconfigPaths()],
    test: {
        environment: "jsdom",
        setupFiles: ["./vitest.setup.ts"],
        exclude: ["**/node_modules/**", "**/dist/**", "**/tests/**"],
    },
    resolve: {
        alias: {
            "@/": new URL("./src/", import.meta.url).pathname,
            "@legacy": new URL("./legacy/", import.meta.url).pathname,
            "@locales": new URL("./locales/", import.meta.url).pathname,
            "@tests": new URL("./tests/", import.meta.url).pathname,
        },
    },
})
```

```
// vitest.setup.ts
import "@testing-library/jest-dom/vitest"
```

### What you did:

- type: module on package.json
-  Change the module targets and resolutions in tsconfig
- try the server deps list of vitest
- Tried with and without ts config paths
- tried with jsx: preserve
- tried with removing testing library from types
- tried without the aliases
- tweak the configs in 1001 ways I don't remember (sorry)

### Problem description:

I'm facing an issue while switching from `jest` to `vitest`. When testing on tsx files or when using `render` from `testing-library`, I have an issue with imports of modules from `react-dom` (see the error above)

### To reproduce:

Take the same config, and use `npx vitest` command

### Suggested solution:

I guess I have to tweak the config, but I don't see what is wrong.
I tried to change the vitest setup from jest-dom/vitest to jest-dom, but then the library can not find the expected import.

**Comment by eps1lon** [comment]
I suggest you file this against Vitest first. I'm not familiar with the inner workings of this test runner so I can't tell where the issue is.

Especially 
> Module node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-test-utils.development.js:12 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "react-dom" asking them to ship the file in .mjs extension or add "type": "module" in their package.json.

seems odd since that file is definitely a CommonJS package.

There a re probably also existing examples on how to use Vitest and React Testing Library so you should take a look at those and then slowly reduce differences until you can no longer reproduce the issue.

**Comment by Shishouille** [comment]
Hi @eps1lon, thanks for answering!

In the end it was because pnpm didn't clean the packages well... Just had to remove all the `node_modules` for it to work. 
So if people encounter that issue, this should help! 

Have a nice day 🌞
