### ISSUE TITLE
Regression: Options not available in `renderHook`

### ISSUE THREAD

**Issue by icatalina** [testing-library/react-testing-library#1307]
- `@testing-library/react` version: 15.0.3
- Testing Framework and version: jest@29
- DOM Environment: jsdom

### Relevant code or config:

```tsx
import { renderHook } from '@testing-library/react';

renderHook(() => null, { wrapper: () => null });
```

### What you did:

Trying to use a wrapper on `renderHook`.

### What happened:

<img width="1510" alt="image" src="https://github.com/testing-library/react-testing-library/assets/4542735/d140143f-8ea8-4151-8982-60affd5ec66a">

### Reproduction:

https://stackblitz.com/edit/rtl-template-emaqfx?file=src%2FApp.test.tsx

### Problem description:

Only `initialProps` is available when using `renderHook`

### Suggested solution:

🤷

**Comment by eps1lon** [comment]
Thank you for the report. Should be fixed with `@testing-library/react@15.0.4`
