### ISSUE TITLE
unable to Find Element by data-testid After Component Re-render in React Testing Library

### ISSUE THREAD

**Issue by EhsanKey** [testing-library/react-testing-library#1358]
I am encountering an issue where a test is unable to find an element using `data-testid` after re-rendering a component in React Testing Library. The specific error message is:

```
TestingLibraryElementError: Unable to find an element by: [data-testid="file-uploader-remove"]
```

### Steps to Reproduce:
1. Render the `FileUploader` component with a file input.
2. Trigger a file change event to upload a file.
3. Re-render the `FileUploader` component.
4. Attempt to find the remove button using `data-testid="file-uploader-remove"`.

### Example Code:
**Test Code:**
```javascript
import { expect, test, describe, afterEach, vi } from "vitest";
import { cleanup, render, screen, fireEvent } from "@testing-library/react";
import Component from ".";

test("removes the selected file", async () => { 
    global.URL.createObjectURL = vi.fn();
    const onFileSelect = vi.fn();
    
    render(
      <Component
        buttonText="Upload a file"
        placeholder="Upload a file"
        onFileSelect={onFileSelect}
      />
    );

    const input = screen.getByTestId("file-uploader-input");
    const file = new File(["hello"], "hello.png", { type: "image/png" });
    fireEvent.change(input, { target: { files: [file] } });
    
    render(
      <Component
        buttonText="Upload a file"
        placeholder="Upload a file"
        onFileSelect={onFileSelect}
      />
    );

    const removeButton = screen.getByTestId("file-uploader-remove");
});
```

**Component Code:**
```javascript
"use client";
import React, { useState, useRef, useCallback, forwardRef } from "react";
import { CloseCircleIcon, DocumentUploadIcon } from "@/lib/icons";
import Image from "next/image";

interface FileUploaderProps {
  onFileSelect: (file: File | null) => void;
  placeholder: string;
  accept?: string;
}

const FileUploader = forwardRef<HTMLInputElement, FileUploaderProps>(
  ({ onFileSelect, placeholder, accept }, ref) => {
    const internalRef = useRef<HTMLInputElement | null>(null);
    const inputRef = ref
      ? (ref as React.MutableRefObject<HTMLInputElement | null>)
      : internalRef;
    const [image, setImage] = useState<string | null>(null);

    const handleChange = useCallback(
      (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
          onFileSelect(e.target.files[0]);
          setImage(URL.createObjectURL(e.target.files[0]));
        }
      },
      [onFileSelect]
    );

    const handelRemoveImage = () => {
      setImage(null);
      onFileSelect(null);
    };

    return (
      <div>
        <input
          ref={inputRef}
          type="file"
          className="hidden"
          onChange={handleChange}
          accept={accept}
          data-testid="file-uploader-input"
        />

        {image ? (
          <>
            <Image
              src={image}
              alt="uploaded"
              className="w-full h-full object-cover rounded-2xl"
              width={184}
              height={184}
              data-testid="file-uploader-image"
            />
            <button
              type="button"
              className="absolute top-4 left-4 bg-CoolGray-10 p-3 rounded-full"
              data-testid="file-uploader-remove"
              onClick={handelRemoveImage}
            >
              <CloseCircleIcon />
            </button>
          </>
        ) : (
          <div
            className="flex flex-col items-center justify-center p-4 text-center space-y-2"
            data-testid="file-uploader-placeholder"
          >
            <DocumentUploadIcon />
            <span>{placeholder}</span>
          </div>
        )}
      </div>
    );
  }
);

FileUploader.displayName = "FileUploader";

export default FileUploader;
```

### Expected Behavior:
The test should successfully find the element with `data-testid="file-uploader-remove"` after re-rendering the component.

### Actual Behavior:
The element with `data-testid="file-uploader-remove"` is not found, resulting in an error.

### Additional Information:
- The `data-testid` for the remove button is correctly set in the component.
- Re-rendering the component seems to affect the ability to find this element.

### Possible Causes:
- The re-render might not be updating the component state or props as expected.
- There could be an issue with how the `file-uploader-remove` button is rendered or updated in the DOM.

If anyone has insights or solutions for this issue, your help would be greatly appreciated. Thank you!

```
  "dependencies": {
    "next": "14.2.7",
    "react": "^18",
    "react-dom": "^18",
  },
    "devDependencies": {
    "@testing-library/dom": "^10.4.0",
    "@testing-library/react": "^16.0.1",
    "jsdom": "^25.0.0",
    "vitest": "^2.0.5"
  }
```

**Comment by nimaa77** [comment]
to trigger a re-render you don't have to call the `render` function again 
it happens automatically

just render the component
trigger the event
assert

**Comment by nimaa77** [comment]
you just need to wait for the react to render the tree and commits the changes to the dom
testing-library has utilities for this https://testing-library.com/docs/dom-testing-library/api-async/

what you need to do is to remove the second render function call

and replace this line:
```js
const removeButton = screen.getByTestId("file-uploader-remove");
```

with:
```js
const removeButton =  await screen.findByTestid('Clicked once')
```

**Comment by EhsanKey** [comment]
> you just need to wait for the react to render the tree and commits the changes to the dom testing-library has utilities for this https://testing-library.com/docs/dom-testing-library/api-async/
> 
> what you need to do is to remove the second render function call
> 
> and replace this line:
> 
> ```js
> const removeButton = screen.getByTestId("file-uploader-remove");
> ```
> 
> with:
> 
> ```js
> const removeButton =  await screen.findByTestId('Clicked once')
> ```

thanks, I tried this way before but it didn't work

**Comment by EhsanKey** [comment]
### Issue Resolution:
I was able to resolve the issue by mocking the `URL.createObjectURL` function using the following code snippet:

```javascript
global.URL.createObjectURL = vi.fn(
  () =>
    "https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png"
);
```

### Explanation:
The issue occurred because `URL.createObjectURL` was being used to generate a temporary URL for the uploaded file, but it was not returning a valid URL in the test environment. By mocking this method with a predefined URL, I was able to simulate the behavior of uploading a file in the test. 

The function now returns a static image URL, allowing the test to proceed without errors and find the `data-testid="file-uploader-remove"` element as expected.
