### ISSUE TITLE
*ByRole "status" for <output/> element doesn't handle name attribute correctly

### ISSUE THREAD

**Issue by Yimiprod** [testing-library/react-testing-library#1359]
- `@testing-library/react` version: ^15.0.4
- Testing Framework and version: Jest ^29.7.0
- DOM Environment: JSDom ^29.7.0

### Relevant code or config:

```jsx
const Test = () => {
  return (
    <>
      <output name="not-found">NOT FOUND</output>
      <output aria-label="found">IS FOUND</output>
    </>
  );
};

describe('not founding status role with standard name attribute', () => {
  it('should have found both status', () => {
    const { getByRole } = render(<Test />);

    const statusOne = getByRole('status', { name: 'not-found' }); // this one will fail
    const statusTwo = getByRole('status', { name: 'found' });

    expect(statusOne).toHaveValue('NOT FOUND');
    expect(statusTwo).toHaveValue('IS FOUND');
  });
});
```

### What you did:

Tried to find by role a `"status"` with `<output/>` element, with the attribute `name` on it.

### What happened:

It is flagged as an empty name:
<img width="446" alt="image" src="https://github.com/user-attachments/assets/2142f451-5595-4349-b057-46fc9dfe1389">

### Reproduction:

Run example code in jest environnement. The one named with `aria-label` is correctly named, the one with `name` attribute isn't.

### Problem description:

The `name` attribute is a standard for `input` and `output` naming, the fact that we have to use `aria-label` mean that the name is lost in the process.

### Suggested solution:

`*ByRole()` for `<output/>` should find by name for `aria-label` and `name` both.

**Comment by MatanBobi** [comment]
Hi @Yimiprod.
The `name` attribute is not an accessible name which is what the `name` property means, it's only a name for development use cases and is not reflected to our users. More on this is available in our [docs](https://testing-library.com/docs/queries/byrole#api).
