### ISSUE TITLE
the "@testing-library/react" not integrate with react @19.0.0

### ISSUE THREAD

**Issue by Abdokhalil11** [testing-library/react-testing-library#1368]
- `@testing-library/react` version: @16.1.0 
- Testing Framework and version: jest version:@29.7.0
  
- DOM Environment:@10.4.0
  

### Relevant code or config:

```js
var your => (code) => here;
```

### What happened:  that throw an error

![issue](https://github.com/user-attachments/assets/0dfb589e-eaee-4410-ace9-ca2a6e28b070)

**Comment by eps1lon** [comment]
You're using `19.0.0-rc-*`. If you want to use that version, you need to use `--force`. Otherwise change the installed version of React to `19.0.0`
