### ISSUE TITLE
Change props on same component instance, reprise

### ISSUE THREAD

**Issue by eschiebel** [testing-library/react-testing-library#273]
- `react-testing-library` version:5.4.4
- `react` version:16.7.0
- `node` version: v8.10.0
- `npm` (or `yarn`) version: yarn 10.1.1

### Relevant code or config:
in a previously closed ticket https://github.com/kentcdodds/react-testing-library/issues/65#issuecomment-385529996 you suggest calling 
```js
render(<C {...newProps}/>, container)
```
to rerender with new props, but when I do this, the existing instance is not updated, but I get a new instance of the component. 

### What you did:

1. set a breakpoint in my component's constructor, render, and componentDidUpdate functions
1. call {{const {container} = render(<C value="17"/>)}}
1. The constructor and render breakpoints are hit. In render, I set `window.xxx=this`
1. call `render(<C value="177"/>, container)`
1. I see the constructor and render called. componentDidUpdate is not called and `window.xxx!==this`

### Reproduction:
https://codesandbox.io/s/jj56q52rqw

You can see that the test output renders 2 instances of the Hello component, and that componentDidUpdate is never called

### Problem description:

I don't know how to test property change behavior on my components

**Comment by puemos** [comment]
```js
render(<Hello name="Jack" />, container);
```
probably needs to be:
```js
render(<Hello name="Jack" />, {container});
```
