### ISSUE TITLE
How to trigger pointer events using fireEvent?

### ISSUE THREAD

**Issue by mohsinulhaq** [testing-library/react-testing-library#317]
Hi!
I have a tooltip library where I have recently switched to pointer events instead of clicks and touchend.
I found that `fireEvent.pointerUp` and other pointer events don't exist. How should I trigger this event?

**Comment by weyert** [comment]
Have a look in `dom-testing-library'`s `events.js`-file which defines all the events: https://github.com/kentcdodds/dom-testing-library/blob/master/src/events.js

Don't hesitate to make a PR for it :D

**Comment by mohsinulhaq** [comment]
I tried it adding the event. It turns out `jsdom` doesn't support Pointer Events yet. So dom-testing-library falls back to `Event` constructor.

https://github.com/jsdom/jsdom/issues/2527

Have raised an issue regarding this.

**Comment by kentcdodds** [comment]
Thanks for doing the research @mohamedmagdy17593. We'll close this in favor of the issue you opened on jsdom.
