### ISSUE TITLE
undefined History object when testing with and react-testing-library

### ISSUE THREAD

**Issue by LaraMo** [testing-library/react-testing-library#364]
I have a button that is supposed to do:   `this.props.history.push(PageA)` when clicked.
However, I get this error:     `TypeError: Cannot read property 'push' of undefined` - meaning that history is undefined.

Here is my set up that runs before each test for the Tax comonent

```
const initialState = {
	tax: {
		amount: 0.35
	}
};
```
```

function renderWithRedux(
	component,
	history = createMemoryHistory({ initialEntries: ['/app/dashboard'] }),
	store = createStore(***createReducer(history), initialState, applyMiddleware(thunk))
) {
	return {
		...render(
			<Provider store={store}>
				<HelmetProvider>
					<Router history={history}>
						<Switch>{component}</Switch>
					</Router>
				</HelmetProvider>
			</Provider>
		),
		store,
		history
	};
}

```
*** this is imported from another file :
```
export default history =>
	combineReducers({
		tax: taxReducer,
		router: connectRouter(history)
	});

```
Is there another way to pass the history? Am I missing a point?
Thank you very much for those who will try to help.
Any links with examples or important information will be appreciated :) 

- `react-testing-library`:  6.1.2
- `react` version: 16.8.6
- `npm`: 6.9.0

**Comment by kentcdodds** [comment]
Could you make a reproduction repository and/or codesandbox to show this issue and then ask on [the spectrum community](https://spectrum.chat/react-testing-library)?

Thanks!
