### ISSUE TITLE
How do you mock react class functions?

### ISSUE THREAD

**Issue by RichMatthews** [testing-library/react-testing-library#367]
I'm doing this:

`await wait(() => fireEvent.click(getByText('Next')))` when I click this it invokes a function and I'm getting the error: `Actions must be plain objects. Use custom middleware for async actions.`

I'm hoping to have full control over this function that gets called (`handleSubmit`) and then get it to return nothing or undefined or what ever

I've tried `jest.mock()` and `spyOn` but I was wondering if there was a conventional way in this library where you do things like this? must be a common use case with all the fireEvents that happen

**Comment by alexkrolick** [comment]
It sounds like this is due to an incorrectly fired Redux action within the component
