### ISSUE TITLE
The add-contributor command is gone?

### ISSUE THREAD

**Issue by FredyC** [testing-library/react-testing-library#369]
Sorry for a bit meta. The command has been removed from scripts https://github.com/testing-library/react-testing-library/commit/5a88da27a87de869e40fc8abdf5a9483066e5ec2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L12 and yet it's still referred in CONTRIBUTING.md. 

I am merely curious as I wanted to use the implementation for another OSS project. Is there some other fancy way of managing contributors these days? Even the latest `kcd-scripts` seems not to have `contributors` script anymore.

**Comment by alexkrolick** [comment]
Use @all-contributors bot/cli

**Comment by FredyC** [comment]
Yea, I know about the bot and even found [the CLI](https://allcontributors.org/docs/en/cli/installation), just got a bit surprised that command has been removed and yet it's still mentioned as to be used. Nevermind then. Thanks.

**Comment by kentcdodds** [comment]
Thanks for bringing this up @FredyC! We should remove it from the `CONTRIBUTING.md`. Would you be willing to do that?

**Comment by FredyC** [comment]
Well, you mean to remove a whole section? It should probably be a whole template to be used across other *-testing-library projects (and others?). I am not feeling like creating it when I don't know specifics.

**Comment by kentcdodds** [comment]
Yeah, I need to go through all my projects and remove that section honestly. People don't add themselves anymore because we're using the bot so it's just confusing.

You're welcome to do it if you're bored sometime :)
