### ISSUE TITLE
useEffect causing test failures (but not with Enzyme)

### ISSUE THREAD

**Issue by jamescrowley** [testing-library/react-testing-library#372]
- `react-testing-library` version: 7.0.0
- `react` version: 16.8.6
- `node` version: code sandbox
- `npm` (or `yarn`) version: code sandbox

### Relevant code or config:

I've created a code sandbox here: https://codesandbox.io/s/dazzling-keldysh-80o9d (note for me on MacOS I needed to run code sandbox from Chrome rather than Safari to get the same test failure messages I have locally)

### What you did:

I'm testing React form that uses a custom hook which has a useEffect hook. The useEffect hook is used to 'reset' the form when the initial form state changes.

* I'm migrating from Enzyme, where this worked as expected (with a full mount) - I've included this example too.
* If I comment out the hook, everything works as expected. 

### What happened:

I get strange timing issues with form field states - the useEffect() hook appears to being triggered in ways I do not understand - but works perfectly outside of the test harness.

The first test to be executed always fails (see the code sandbox).

### Reproduction:

https://codesandbox.io/s/dazzling-keldysh-80o9d

### Problem description:

The form state is not as I'd expect when asserting on tests.

### Suggested solution:

Not sure - I've read https://github.com/testing-library/react-testing-library/issues/215 and not sure if that's related or not - tried playing around the act() and async waits but with no luck. I'm fairly new to React so not sure I fully understand all the interactions going on here.

*Edit* updated sandbox to show the Enzyme tests that work

**Comment by kentcdodds** [comment]
Hi @jamescrowley,

Your event handler was causing the problems: https://codesandbox.io/s/holy-water-jvp97?fontsize=14&module=%2Fsrc%2FSimpleForm.test.js

In the future, if you could ask these kinds of questions on [the spectrum community](https://spectrum.chat/testing-library) that would be great. Thanks!

**Comment by jamescrowley** [comment]
@kentcdodds Many thanks and my apologies - had convinced myself it was a library issue as it worked in Enzyme - I'll head to spectrum in future!! :)

**Comment by kentcdodds** [comment]
No worries!
