### ISSUE TITLE
createEvent is not being exported

### ISSUE THREAD

**Issue by alexreardon** [testing-library/react-testing-library#373]
- `react-testing-library` version: 7.0.0
- `react` version: 16.8.6

### Relevant code or config:

```js
import { createEvent } from "react-testing-library";
it("should have the createEvent export", () => {
  // this fails as createEvent is undefined
  expect(createEvent).toBeTruthy();
});
```
https://codesandbox.io/s/reacttestinglibrary-createevent-gr9ms (click on the tests tab)

### Problem description:

[`createEvent`](https://testing-library.com/docs/dom-testing-library/api-events#createevent-eventname) is not being exported

**Comment by alexreardon** [comment]
I would have expected this line to export it:

https://github.com/testing-library/dom-testing-library/blob/master/src/index.js#L12

**Comment by alexkrolick** [comment]
Did you update the dom testing dependency with `yarn upgrade react-testing-library`?

**Comment by bcarroll22** [comment]
Ah, we’ll have to bump the version of DTL used and minor bump this library also. The line you referenced should cover it then since this re-exports everything. Wanna make a PR here as well?

**Comment by alexreardon** [comment]
The example I posted is a fresh install from npm

**Comment by tommarien** [comment]
Any update on this ?

**Comment by bcarroll22** [comment]
I can’t reproduce this on a fresh install of RTL. Maybe try deleting package-lock or yarn.lock and node_modules and try a fresh install? The lockfile should say DTL is version 4.1.0 after an install of RTL ^7.0.0.

**Comment by tommarien** [comment]
That is why the patch is needed I tried last friday installing the newer query lib did not work maybe I did something wrong

**Comment by tommarien** [comment]
@kentcdodds Thanks ;)
