### ISSUE TITLE
The `data-testid` won't work if `div` isn't wrapped

### ISSUE THREAD

**Issue by hyochan** [testing-library/react-testing-library#377]
Hi there. Thanks for awesome library. I've been a real lover of `react-testing-library` these days.

I have an issue using this when I try to grab the `data-testid` inside my custom component (example below).

```
<Button
  data-testid='my-test'
  onClick={() => changeTheme()}
/>
```

When I try to grab above component like below
```
const btn = renderResult.getByTestId('my-test');
```

`react-testing-library` won't grab this.

The workaround of solving above problem is by wrapping my component with `div` tag.
Workaround:
```
<div data-testid='my-test'>
  <Button
    onClick={() => changeTheme()}
  />
</div>
```

I've not experienced above in `react-native-testing-library` which was inspired by `react-testing-library`. I hope this could work without the `workaround`.

**Comment by bcarroll22** [comment]
Hey @hyochan, generally speaking this is the opposite of what you should try to do with this library (and [native-testing-library](https://github.com/testing-library/native-testing-library) as well). 

You shouldn't be querying for your custom components (they're [implementation details](https://kentcdodds.com/blog/testing-implementation-details)) and usually when you need to use a test id, I find it tends to be a symptom of some undesirable test behavior.

I think the better place for this type of question in the future would be the [spectrum chat](https://spectrum.chat/testing-library), could you please follow up on this question there to get some suggestions on what you should do?

**Comment by kentcdodds** [comment]
My guess is the Button component doesn't forward the props it receives to the underlying button that is rendered which is why you're having this problem

**Comment by fandingdevs** [comment]
So sad that it's been closed. @kentcdodds Maybe you are right but it comes worse when you use `styled-component`. Below is what I am doing.

```
const Container = styled.div`
  flex: 1;
  background-color: transparent;
  flex-direction: row;
  align-items: center;
  justify-content: center;
`;

interface IProps {
  history?: any;
}

function Page(props: IProps) {
  return (
    <Container>
      <div
        data-testid='myText'
      >dooboolab</div>
    </Container>
  );
}

export default Page;
```

I can't use `data-testid` directly inside `Container`.

**Comment by bcarroll22** [comment]
I believe that’s still a question for spectrum, but I don’t believe you need to select the container. The container is an implementation detail. You should be selecting the DOM nodes your users interact with, not your components or styled wrappers.

**Comment by hyochan** [comment]
@bcarroll22  Well `@testing-library/react-native` works well with the `styled-component`. Why should they have the different behavior?

**Comment by bcarroll22** [comment]
`@testing-library/react-native` won't allow you to query custom components either assuming you're using the latest version and the Jest preset. You can only query for the built-in native components.

I've never used styled-components with React Native, but if it works it's likely because styled components renders a `View` or `Text` with the React Native styles, or it passes the test id down to the child native component that it renders. The thing to keep in mind is that many React Native components, especially built-in and library ones, pass through `{...props}`.

**Comment by Juanjo4U** [comment]
I just get the element by first rendering the component:
`import { render, cleanup, fireEvent } from "@testing-library/react";
  it('event click fires correctly', () => {
        const handleClick = jest.fn()
        const { getByTestId } = render(<Button text={translationKey} onClick={handleClick} />);
        fireEvent.click(getByTestId('button'));
        expect(handleClick).toHaveBeenCalledTimes(1)
    })`

**Comment by dschinkel** [comment]
There's nothing wrong with using data-testId as an approach to writing tests.  I don't agree.

**Comment by dschinkel** [comment]
You are coupling your tests to the DOM instead of domain concepts 

Furthermore byText you are coupling tests to static text if it's a label

Write your tests via data-testid named based on the domain behavior they provide to the user, not the DOM

So this using Role and byText going to result in not just fragility but also tests that don't read back a story of domain concepts when reading the test's implementation

**Comment by janehorton** [comment]
I'm also seeing this issue still.

**Comment by Ruoye36** [comment]
> Hey @hyochan, generally speaking this is the opposite of what you should try to do with this library (and [native-testing-library](https://github.com/testing-library/native-testing-library) as well).
> 
> You shouldn't be querying for your custom components (they're [implementation details](https://kentcdodds.com/blog/testing-implementation-details)) and usually when you need to use a test id, I find it tends to be a symptom of some undesirable test behavior.
> 
> I think the better place for this type of question in the future would be the [spectrum chat](https://spectrum.chat/testing-library), could you please follow up on this question there to get some suggestions on what you should do?

May I ask what IS the good practice to test custom components? Thank you!
