### ISSUE TITLE
waitForElementToBeRemoved null?

### ISSUE THREAD

**Issue by thetif** [testing-library/react-testing-library#381]
- `react-testing-library` version: 5.4.4
- `react` version: 16.0.0
- `node` version: 8.15.0
- `npm` (or `yarn`) version: 6.4.1

### Relevant code or config:
waitForElementToBeRemoved

```js
import { waitForElementToBeRemoved } from 'react-testing-library';
...
console.log('waitForElementToBeRemoved', waitForElementToBeRemoved);
```

### What you did:
I am trying to import and use waitForElementToBeRemoved and it is undefined.

### What happened:
console.log waitForElementToBeRemoved undefined

**Comment by bcarroll22** [comment]
Your version of React Testing Library uses a version of DOM Testing Library that doesn't have `waitForElementToBeRemoved` [see here](https://github.com/testing-library/dom-testing-library/tree/v3.13.1/src). Can you update to a newer version?

**Comment by thetif** [comment]
yes, thanks!

**Comment by bcarroll22** [comment]
awesome, thanks!
