### ISSUE TITLE
Clean side effect dom nodes in cleanup method

### ISSUE THREAD

**Issue by mohamedmagdy17593** [testing-library/react-testing-library#384]
hi kent
the problem is that `cleanup()` unmount and remove ReactDom container but not any side effect dom nodes, so we have some code that adds dom nodes imperatively under `<body>` i need to remove it after each test case  

### Describe the feature you'd like:

so I think we can add code to `cleanup` method that removes any dom side effect
we could do it by default or add options to `cleanup` method
example:
```js
cleanup({sideEffect: true}) // default to false
```

### Suggested 

add this to the end of `cleanup` method:
```js
[...document.body.children].forEach(c => c.remove())
```

**Comment by kentcdodds** [comment]
I would argue that your components should be cleaning up after themselves on unmount. if they're not doing that, then that's a bug and should be fixed in your source code.

**Comment by mohamedmagdy17593** [comment]
Yes you are right but we use ant design and it do that by default i think because it uses it in the future :(

**Comment by mohamedmagdy17593** [comment]
I know that your library try to encourage good code and accessibility but that is not the case with most of libraries out there

**Comment by alexkrolick** [comment]
You can probably do `document.body.innerHTML = ''` if you just want to remove all the nodes

**Comment by kentcdodds** [comment]
Whether or not most of the libraries out there are inaccessible it's kind of irrelevant. Those are bugs in those bugs should be fixed. We're not going to add things into this library which enable people to continue to build buggy software.

There's a simple work around as Alex suggested. So if you want to use that then feel free. Good luck.

**Comment by mohamedmagdy17593** [comment]
> You can probably do `document.body.innerHTML = ''` if you just want to remove all the nodes

thanks, Alex it's more simple, I will consider using this snippet as a workaround

**Comment by mohamedmagdy17593** [comment]
> Whether or not most of the libraries out there are inaccessible it's kind of irrelevant. Those are bugs in those bugs should be fixed. We're not going to add things into this library which enable people to continue to build buggy software.
> 
> There's a simple work around as Alex suggested. So if you want to use that then feel free. Good luck.

thanks for helping Kent you are right, the library should not support anything that will encourage bad code
