### ISSUE TITLE
Issue with Material-UI React (@material-ui/core components)

### ISSUE THREAD

**Issue by noamraby-ssky** [testing-library/react-testing-library#391]
- `react-testing-library` version: 8.0.1
- `react` version: 16.8.6

### Relevant code or config:

Imports from @material-ui/core
Please see CodeSandbox below

### What you did:

I'm trying to test components that use Material-UI-React (https://material-ui.com/) 
Getting strange results with Dialog and TextFields

### What happened:

Dialogs are not rendered to the DOM. TextFields are rendered, but value isn't found by `toHaveTextContent()`

### Reproduction:

Repro on CodeSandbox:
https://codesandbox.io/s/material-ui-react-issue-with-react-testing-library-9f4vb
two test in the __tests__ directory

### Problem description:

I'm expecting dialog and text content to be on the DOM 

### Suggested solution:

I have no suggested solution. 😔

**Comment by alexkrolick** [comment]
In the text input example, the testid is not being forwared to the input tag, it's being set on a wrapper div.

> Error: Unable to find an element by: [data-testid="textfield-testid"]

```html
<body>
  <div>
    <div
      class="MuiFormControl-root-1"
      data-testid="textField-testid"
    >
      <div
        class="MuiInputBase-root-18 MuiInput-root-5 MuiInput-underline-9 MuiInputBase-formControl-19 MuiInput-formControl-6"
      >
        <input
          aria-invalid="false"
          class="MuiInputBase-input-28 MuiInput-input-13"
          type="text"
          value="text field value"
        />
      </div>
    </div>
  </div>
</body>
```
Also, `.toHaveValue` is the matcher for input values, not `.toHaveTextContent`.

--- 

In the dialog example, the `container` is the root node of the app, but Dialogs render in portals with a different root. You can use `within(document.body).getByTestId()` to scope the queries to the body instead.

--- 

Workarounds:

https://codesandbox.io/s/material-ui-react-issue-with-react-testing-library-33k1q

**Comment by alexkrolick** [comment]
If you have further questions, https://spectrum.chat/testing-library?tab=posts would be a good place to ask

**Comment by noamraby-ssky** [comment]
Thanks for the quick response. 🙏
Didn't know about `within(document.body)`. Hopefully the next person will find it useful.

**Comment by alexkrolick** [comment]
Sorry, the `within` wasn't actually necessary (see amended comment and  https://github.com/testing-library/react-testing-library/issues/392)
