### ISSUE TITLE
Should "container" returned from render reference the document body?

### ISSUE THREAD

**Issue by alexkrolick** [testing-library/react-testing-library#392]
The current `render` behavior returns the root div that the ReactDOM.render() call uses (unless certain options are passed). This makes it hard to test dialogs, modals, tooltips, etc. - you have to use `within` or use imported DTL queries with a custom node argument to grab the elements. I wonder if this behavior is creating more indirection than is warranted - everyone should be cleaning up the DOM between tests so returning isolated nodes doesn't really prevent any problems.

**Comment by kentcdodds** [comment]
🤔 all the returned queries are bound to document.body by default. So as long as the modal appears in the body people shouldn't have to do anything special to select things within it.

**Comment by alexkrolick** [comment]
👍 actually the issue is using `container.firstChild()` - the appended elements are siblings. Documentation should fix this.
