### ISSUE TITLE
Provide mechanism for accessing the page title

### ISSUE THREAD

**Issue by jedmao** [testing-library/react-testing-library#402]
### Describe the feature you'd like:

Similar to [this guy](https://spectrum.chat/testing-library/help/how-to-test-dynamic-page-titles~a982d183-9c1b-4bac-9f2e-694d822cbdd8) who has yet to receive an answer, I'm looking to do the exact same thing (i.e., test dynamic changes to the page title).

### Suggested implementation:

```ts
const { getPageTitle } = render(...);
```

### Describe alternatives you've considered:

I tried just testing `expect(document.title).toEqual('something')` or even `requestAnimationFrame` before testing the title, which is what [Helmet does for their tests](https://github.com/nfl/react-helmet/blob/420810c644f94c3743f7b088321dbd62a8037b7b/test/HelmetTest.js#L31-L42), but no 🎲 .

### Teachability, Documentation, Adoption, Migration Strategy:

1. I'm not sure if this somehow goes against the `@testing-library` paradigms.
1. I think it's a pretty self-explanatory method name, so I wouldn't want to add any more noise to it.

**Comment by Gpx** [comment]
This works for me:

```jsx
test("test", async () => {
  const Foo = () => (
    <>
      <Helmet>
        <title>foo</title>
      </Helmet>
      <div>Hello</div>
    </>
  );
  render(<Foo />);
  await wait(() => expect(document.title).toEqual("foo"));
 });
```

**Comment by mbrowne** [comment]
This also works:

```js
    await waitForDomChange()
    expect(document.title).toEqual("foo")
```

And actually if you're not checking for `document.title` directly, then `wait()` will NOT work. For example I needed to use `waitForDomChange()` to get this to work (`MetaDataOpenGraph` is our custom component, which uses `Helmet` internally):

```js
    it('should add title and meta tags to <head>', async () => {
        render(<MetaDataOpenGraph {...metadata} routeChanged={false} />)
        await waitForDomChange()
        expect(document.querySelector('head')).toMatchSnapshot()
    })
```

**Comment by ctsstc** [comment]
A note from the future, this seems to be the updated API:

```javascript
it('renders the login page title', async () => {
    await waitFor(() => expect(document.title).toBe('Company Name - Login'));
  });
```

A note for Next JS users, this doesn't seem to work with the `<Head>` component unfortunately.
Here's an interesting thread on it: https://github.com/vercel/next.js/discussions/11060
