### ISSUE TITLE
`wait()` function never completes in a production build

### ISSUE THREAD

**Issue by RoystonS** [testing-library/react-testing-library#403]
- `react-testing-library` version: 8.0.4
- `react` version: 16.8.6
- `node` version: 10.16.0
- `npm` (or `yarn`) version: yarn 1.16.0

### Relevant code or config:

```js
await wait(fn);
```
in a production (minified) build never completes.

### What you did:

We're attempting to upgrade from `react-testing-library` 6.0.1 to `@testing-library/react` 8.0.4 but have hit an issue:

We run our tests in a production (minified) build, in order to be certain that our minified code is actually behaving correctly. (We've had issues where the generated code doesn't work in some browsers, so we make sure we test the actual code we're going to ship, which means building our tests in production mode.)

Unfortunately, our test suite hangs when we upgrade `testing-library`: the calls to `wait()` now never complete.
 
### What happened:

We attempted to upgrade `react-testing-library` and now many of our tests lock up and never complete.

### Reproduction:

```js
import * as rtl from '@testing-library/react';

/**
 * An asynchronous function that just runs @testing-library/react#wait()
 * and checks to see if that completes.
 */
async function runIt() {
  const timeoutHandle = setTimeout(() => {
    console.error("Five seconds on, and wait still hasn't completed");
  }, 5000);

  await rtl.wait(() => {
    console.log("This is the function we are waiting for, now complete");
  });

  clearTimeout(timeoutHandle);
  console.log("The wait function returned; it's all working fine!");
}

runIt();
```

This code sets up a timer that complains after 5 seconds, then runs a simple `wait` call, and waits for it to complete. After it completes, it cancels the timer and indicates that everything is working fine.

In a development build it reports that everything is working fine.  In a production build, the timer goes off, indicating that `wait` didn't complete.

To make it easy to run this, I've added the above code to a [Github repo](https://github.com/RoystonS/react-testing-library-wait-never-finishes). This is an out-of-the-box `create-react-app` application (commit 1) with the above code pasted into the `index.js` file ([commit 2](https://github.com/RoystonS/react-testing-library-wait-never-finishes/commit/30b97ac9ca92b0d142c7031d259daf141e2a7dfd))

To reproduce:

1. check out that repo
1. `yarn`
1. `yarn build`
1. (assuming you have `serve` installed):  `serve -s build`
1. View the page in a browser, and look in the console

Here's what it _should_ say:
![image](https://user-images.githubusercontent.com/19773/60913847-2f9f6680-a280-11e9-8290-94a50255e69f.png)

but it'll actually say something like:
![image](https://user-images.githubusercontent.com/19773/60913591-a9832000-a27f-11e9-91aa-b4a21c4c2925.png)

### Problem description:

It means that the code that `@testing-library/react` is generating is not working properly when incorporated into a production build using the default `create-react-app` settings. (Actually, the codebase where we found this _isn't_ using `create-react-app`: we've just managed to boil it down to this trivial example.)

### Suggested solution:

I'm really not sure. I've traced through the minified code and it seems to be getting stuck inside the regenerator code in the new `asyncWrapper`.  I don't know whether it's a bug in `terser` or something in the `react-testing-library` code that isn't quite right but which happens to work in a non-production build but fails in a production build.

**Comment by RoystonS** [comment]
I've just done a little more digging, and it looks like `act-compat` decides that `asyncActSupported` is `true` in a production build, but `false` in a dev build.

**Comment by RoystonS** [comment]
Gotcha. It's expecting `act` to throw because it doesn't support async act, but in a production build, `act` doesn't throw: https://github.com/facebook/react/blob/16.8.6/packages/react-dom/src/test-utils/ReactTestUtils.js#L413

**Comment by kentcdodds** [comment]
Ah, that makes sense. Hmm... This is a temporary problem. I'm hoping this will be fixed within the next few weeks.

**Comment by RoystonS** [comment]
You mean when React 16.9.0 comes out?

I'm actually finding myself wondering _why_ `act` doesn't throw in a production build. It's designed for _test_ usage, so it's not as if they need to make it fast or silent for a prod build...?

**Comment by alexkrolick** [comment]
That's a @threepointone question

**Comment by kentcdodds** [comment]
Could you explain why you need this to work? I'm thinking that there's not a practical reason to run tests using the production version of the library and we should just close this.

**Comment by RoystonS** [comment]
Sure. We build our unit tests in production mode so that we can be sure that the minified code we plan to ship will actually work. (We've had a number of issues over the years where a minifier will generate code that's broken for a particular browser, for instance.)

**Comment by kentcdodds** [comment]
Interesting. Well I'm not sure there's much we can do on our end I'm afraid. You may have to do some fancy webpack-foo to make this work the way you want it to work 🤔 Because you really need the development version of react for act to work correctly I think.

**Comment by threepointone** [comment]
act() should work fine in prod mode, you only won’t get the warnings. 

I haven’t dug into this issue yet, but can say 16.9 is close. Trying to get an alpha out within the next few days.

**Comment by RoystonS** [comment]
We've temporarily put something in to patch the `act-compat` file so it doesn't think that we have async act. It does then work fine, with the production build of react.

**Comment by kentcdodds** [comment]
Cool. A PR would be welcome :)

**Comment by RoystonS** [comment]
I'm not sure it would. :-)

Our patch _literally_ hacks `act-compat` to change the line that says `asyncActSupported = true` to `asyncActSupported = false` because _we_ know _we_ don't have a React that has async `act`.  I can't see a way to do the detection _properly_ without just resorting to checking the React version number.

**Comment by kentcdodds** [comment]
Aaaah, I see. Haha. In that case, I'm glad you've found a workaround and hopefully we can move beyond this once 16.9 is released 👍

Thanks!

**Comment by shayantabrizi** [comment]
@threepointone 
Could you please explain more about your sentence:

> act() should work fine in prod mode, you only won’t get the warnings.

I'm facing something that I guess may be relevant to this. I'm getting warnings like the following when in the development mode but do not get in the production mode:
```
 Warning: It looks like you're using the wrong act() around your test interactions.
      Be sure to use the matching version of act() corresponding to your renderer:
      
      // for react-dom:
      import {act} from 'react-dom/test-utils';
      // ...
      act(() => ...);
      
      // for react-test-renderer:
      import TestRenderer from 'react-test-renderer';
      const {act} = TestRenderer;
      // ...
      act(() => ...);

```
