### ISSUE TITLE
False Positive for HOC with useEffect hooks

### ISSUE THREAD

**Issue by jasonlimantoro** [testing-library/react-testing-library#406]
- `react-testing-library` version: 8
- `react` version: 16.8
- `node` version: 16.8
- `npm` (or `yarn`) version: 6.9

### Relevant code or config:

```js
//routes/index.js

import React, { Fragment } from "react";
import { Link, Router } from "@reach/router";
import Home from "./Home";
import Dashboard from "./Dashboard";
import NotFound from "./404";
import Protect from "../HOC/ProtectedRoutes";

const ProtectedDashboard = Protect(Dashboard);

const Routes = () => (
  <Fragment>
    <Link to="/">Home</Link> <Link to="/dashboard">dashboard</Link>
    <Router>
      <Home path="/" />
      <ProtectedDashboard path="/dashboard" />
      <NotFound default />
    </Router>
  </Fragment>
);

export default Routes;
```

```js
// HOC/ProtectedRoutes.jsx

import React, { useEffect } from "react";
import { navigate } from "@reach/router";

const ProtectedRoutes = Component => props => {
  useEffect(() => {
    navigate("/", {
      state: { message: "not authenticated" },
      replace: true
    });
  }, []);
  return <Component {...props} />;
};

export default ProtectedRoutes;

```
```js
// tests/router.test.js

  /**
   * @test
   */
  it("should not show protected routes", async () => {
    const { queryByText, debug } = renderWithRouter(App, {
      route: "/dashboard"
    });
    await waitForElement(() => queryByText(/protected/i));
    // fails from this line onwards
    await waitForElementToBeRemoved(() => queryByText(/protected/i));
    await waitForElement(() => queryByText(/not authenticated/i));
    debug();
  });

```

### What you did:

I am testing protected routes.
Here, `/dashboard` should immediately redirect to `/`, with a message "Not Authenticated" displayed in the `/` page.
I use HOC implementation to protect the routes (with useEffect hooks) and `@reach/router` library.

### What happened:

The component works fine.
The test fails.
**False Positive!**
Specifically, the 2nd test case timeouts as it cannot find the 'Not Authenticated' message.
```js
await waitForElement(() => queryByText(/protected/i));
// fails from this line onwards
await waitForElementToBeRemoved(() => queryByText(/protected/i));
await waitForElement(() => queryByText(/not authenticated/i));
```

### Reproduction:

[![Edit react-testing-protected-routes](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-testing-protected-routes-3tdut?fontsize=14)
### Problem description:

False-positive.

### Suggested solution:
I haven't thought of any.

## Side notes
If I didn't use HOC (therefore, redirect happens in the `Dashboard` component, using hooks), the test works wonderfully. Once I use HOC, it breaks.
So, hooks is not the problem here.

**Comment by aleksey-shmatov** [comment]
I think problem here is with `navigate` you are using in `ProtectedRoutes `. You are creating your own history object but using global `navigate` which will come from the global history object. This works in browser because `window` is being used as history object.

**Comment by kentcdodds** [comment]
Hi @jasonlimantoro,

Thanks for the issue. I'm guessing @aleksey-shmatov is correct. If you need further support, please open a new thread on https://spectrum.chat/testing-library

Thanks!
