### ISSUE TITLE
Firing touch events throws **TypeError: Illegal constructor** error

### ISSUE THREAD

**Issue by saravanan10393** [testing-library/react-testing-library#413]
- `react-testing-library` version: ^8.0.5
- `react` version: 16.8
- `node` version: 10.15
- `npm` (or `yarn`) version: 6.4.1

### Relevant code or config:

```js
import {
  render,
  fireEvent,
  cleanup
} from '@testing-library/react';

let { container, getByText } = render(
      <Slider minValue={10} maxValue={30} />
 );

fireEvent.touchStart(container.firstChild);
```

### Description:

I am trying to test my slider widget. I used touchStart and touchMove events. When i try to fire touch events on any elements, i am getting mentioned error.

**Comment by kentcdodds** [comment]
Could you make a reproduction of this issue?

**Comment by kentcdodds** [comment]
Hi @saravanan10393!

I'm afraid I cannot reproduce this issue. My guess is that there's a bug in your Slider component: https://codesandbox.io/s/react-codesandbox-uxbxz

Feel free to post more information on https://spectrum.chat/testing-library

**Comment by jottaxwds** [comment]
Sorry but I can not consider this topic as closed simply because you are only firing an event and that's all... @kentcdodds I think people wanting to do side effects with that touchStart event rather than only put a fireEvent on the test... this is not a test from my point of view.
