### ISSUE TITLE
byTag Query

### ISSUE THREAD

**Issue by FabianoLothor** [testing-library/react-testing-library#417]
It is very exhaustive do this:

`getByText((content, element) => element.tagName.toLowerCase() === 'header'))`

I could create something like a parent function that uses

`(tag, content, element) => element.tagName.toLowerCase() === tag)`

But... Maybe a default `byTag` could be interesting for the library.

**Comment by kentcdodds** [comment]
Hi @FabianoLothor.

Thanks for the suggestion. However it doesn't follow [the guiding principles](https://testing-library.com/docs/guiding-principles) considering that `tagName` is not something that end users know about.

That said, there are two solutions to this that I can suggest:

```javascript
const {container} = render(<YourThing />)
container.querySelector('header')
```

Or, even better:

```javascript
const {getByText} = render(<YourThing />)
getByText(/text that is in the header/i)
```

Good luck!

**Comment by FabianoLothor** [comment]
OK, I see...

But, i don't know... Please, tell me...

What are the cases where the user see the `role`?

![image](https://user-images.githubusercontent.com/2192995/62062135-cc5d8000-b1fe-11e9-80bd-15eb1d836afd.png)

**Comment by FabianoLothor** [comment]
I understand your principles, and i like them.

But I don't understand why some basic features can't be implemented...

`role` is not a something that the user can see, but is been there.

**Comment by FabianoLothor** [comment]
Think a little...

I can write my code like this:

```
...
<header role="header">
...
</header>
...
```

But this dosen't make any sense. I should not change my code because the principles of a library.

**Comment by kentcdodds** [comment]
You'll notice that `role` is low on the "Which query should I use?" list: https://testing-library.com/docs/guide-which-query

Role has semantic meaning for assistive technologies. This is what makes it better than querying based on the tag name.

**Comment by kentcdodds** [comment]
Again, I strongly recommend querying by text...

**Comment by FabianoLothor** [comment]
> meaning

Technically `role` doesn't make part of `html`. It is a `custom` attribute.

**Comment by FabianoLothor** [comment]
Plus: The same way that the `role attribute` it is been forced to be accepted by the principles, `tags` could been too.

If I am seeing a `button` in my screen, I am know that the element it is a button. This works to an image too, and others `tags`.

I agree that tags like `div`, `span` are not user-friendly, but others, can be.

**Comment by FabianoLothor** [comment]
Anyway... I will make a HelperFunction for it.

Something like this or close:

`(tag, content, element) => element.tagName.toLowerCase() === tag)`

I understand that the most of the components can be tested using querying by text, but some guarantees that my component have some at least a tag for example, are essential.

**Comment by FabianoLothor** [comment]
> You'll notice that `role` is low on the "Which query should I use?" list: https://testing-library.com/docs/guide-which-query
> 
> Role has semantic meaning for assistive technologies. This is what makes it better than querying based on the tag name.

Plus 2: A good html page, following the html semantics has a important role for the assistive technologies. Even more than the `role` tag.

**Comment by kentcdodds** [comment]
Please note that DOM Testing Library's `getByRole` query supports implicit roles. So as long as you're using semantic HTML, you can use `getByRole` to get elements without having to specify a `role` attribute.

If you wanted to write a helper function for that, then I don't recommend passing it to `getByText` because `getByText(byTag('header'))` doesn't make any sense...

Is there any reason you wont just use `container.querySelector`?

**Comment by FabianoLothor** [comment]
> Please note that DOM Testing Library's `getByRole` query supports implicit roles. So as long as you're using semantic HTML, you can use `getByRole` to get elements without having to specify a `role` attribute.
> 
> If you wanted to write a helper function for that, then I don't recommend passing it to `getByText` because `getByText(byTag('header'))` doesn't make any sense...
> 
> Is there any reason you wont just use `container.querySelector`?

I will try do something about tomorrow.

Thanks.

**Comment by BBlackwo** [comment]
For good screen reader accessibility, having a `h1` is very important. I'd like to be able to query by HTML type for checking the `h1` of the page.

**Comment by eps1lon** [comment]
@BBlackwo You can build your own queries if you find that you repeat yourself often:

```js
const [queryHeading, queryAllHeadings, getHeading, getAllHeadings, findHeading, findAllHeadings] = buildQueries(
  function queryAllHeadings(container, level) {
    return container.querySelectorAll(`h${level}`);
  },
  function getMultipleError() {
    return `Insert helpfull error message`;
  },
  function getMissingError() {
    return `Insert helpfull error message`;
  },
);
...
getHeading(1)
```

You can implement `ByTag` in a similar fashion though we don't recommend it. `ByRole` is a better `ByTag`.

**Comment by BBlackwo** [comment]
Ok thanks @eps1lon

**Comment by sami616** [comment]
Would this not be useful for when a component can conditionally render different html elements depending on props?

**Comment by i-mighty** [comment]
> Please note that DOM Testing Library's `getByRole` query supports implicit roles. So as long as you're using semantic HTML, you can use `getByRole` to get elements without having to specify a `role` attribute.
> 
> If you wanted to write a helper function for that, then I don't recommend passing it to `getByText` because `getByText(byTag('header'))` doesn't make any sense...
> 
> Is there any reason you wont just use `container.querySelector`?

 `container.querySelector` fails terribly with Typescript though. 
Would be nice to just query by tag name
