### ISSUE TITLE
`act` not support well with async function update state

### ISSUE THREAD

**Issue by demozhang1029** [testing-library/react-testing-library#419]
```javascript
const Upload = () => {
  const handleUploadFile =  (e) => {
    uploadFileApi(e.target.files[0]).then(() => {
      setPopup({message: "show popup"});   //update state
    )
  }
  return <input type="file" onChange={handleUploadFile}/>
}
```

we want to test this behavior "uploadFileApi" be called

```javascript
const {container} = render(<Upload/>);
const uploadInput = container.querySelector("input[type=file]");

act(() => {
  fireEvent.change(uploadInput, {target: {
    files: ["file-test"],
  }});
});
```
it will always show "When testing, code that causes React state updates should be wrapped into act" as we update state after api call successfully.

**Comment by alexkrolick** [comment]
Please see discussion in #291 😀

**Comment by demozhang1029** [comment]
> Please see discussion in #291 😀

Sorry didn't find any relationship.
My problem happened because `setPopup` triggered after API success but at that moment it out of act function.

**Comment by demozhang1029** [comment]
I fixed this with upgrade `react` and `react-dom` version to `16.9.0-alpha.0`. so it will support 
`async/await act()` method.
