### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by lawler61** [testing-library/react-testing-library#422]
hello, when i run `yarn test`, it comes out `ReferenceError: document is not defined` and node_modules are all lasted version.
anyone can help? thanks a lot.

```js
ReferenceError: document is not defined

       7 | describe('基础 react 单元测试', () => {
       8 |   it('home 组件测试', () => {
    >  9 |     const { getByTestId } = render(<TestExample />);
         |                             ^
      10 |     expect(getByTestId('home-ul').children.length).toBe(3);

      at Object.render (node_modules/@testing-library/react/dist/index.js:68:5)
      at Object.it (tests/unit/example.spec.tsx:9:29)
```

package.json

```js
"scripts": { "test": "jest" }
```

jest.config.js

```js
module.exports = {
  setupFilesAfterEnv: [
    '@testing-library/react/cleanup-after-each',
    '@testing-library/jest-dom/extend-expect'
  ],
  testMatch: [
    '**/?(*.)spec.ts?(x)'
  ],
  globals: {
    'ts-jest': {
      tsConfig: 'tsconfig.json',
      diagnostics: false,
    },
  },
  testEnvironment: 'node',
  preset: 'ts-jest',
}
```

component and unit test
```js
import React from 'react';
const TestExample = () => {
  return (
      <ul data-testid="home-ul">
        <li>a item</li>
        <li>b item</li>
        <li>c item</li>
      </ul>
  );
};
export default TestExample;

// example.spec.tsx
import React from 'react';
import { render, cleanup } from '@testing-library/react';
import TestExample from '../../src/web/components/test-example';

afterEach(cleanup);

describe('基础 react 单元测试', () => {
  it('home 组件测试', () => {
    const { getByTestId } = render(<TestExample />);
    expect(getByTestId('home-ul').children.length).toBe(3);
  });
});
```

**Comment by kentcdodds** [comment]
Hi @lawler61,

React Testing Library needs a DOM to operate. Change your jest config `testEnvironment` to `jsdom` and you'll be set.

**Comment by CarlosHdez** [comment]
Is there a step I might be missing? I have `testEnvironment: jsdom` configured but I still get `window is not defined` or `document is not defined`.
To be clear I'm not using document or window on my test file but the source code I'm trying to test uses it.

Thanks

**Comment by nickmccurdy** [comment]
Are you sure it's a runtime error and not an error with a tool like ESLint or TypeScript? If so, please send a reproduction of the error.

**Comment by CarlosHdez** [comment]
I was indeed getting a runtime error, but I was not sure if I was missing a confiugration since we are upgrading our babel to version 7 and this error came after that. Finally I fixed this by also increasing our node version from 10.13 to 10.22
Thanks and sorry for the noice

**Comment by drydenwilliams** [comment]
If you checkout the Jest docs for [test environment](https://jestjs.io/docs/en/configuration#testenvironment-string) you can add a docblock in the specific test file to change the envrironment e.g. changing the `.ts` file to `node` would be: 

**Docblock**:

```
/**
 * @jest-environment node || jsdom
 */
```

**My test file.ts**:

```ts
/**
 * @jest-environment node 
 */

describe('api-client', () => {
  it('should intercept a 401 status code', (done) => {
    const statusCode = 401
    const testError = [
      { code: 'AUTHENTICATION_FAILURE', message: 'Authentication Failure' },
    ]
    const scope = nock(apiUrl!).get('/products').reply(statusCode, testError)

    fetchProducts()
      .then()
      .catch((error) => {
        expect(error.response.status).toBe(statusCode)
        expect(sessionStorage.removeItem).toHaveBeenCalledTimes(1)
        scope.done()
        done()
      })
  })
});
```

**Comment by joeldbirch** [comment]
How should we test a component that should not run in a Node environment, eg. during a Gatsby build? 

If we want the component to render nothing in this case, the first line of a component is:
```if (typeof document === `undefined`) return null```

…and we eliminate `window` in our test, either by using the `@jest-environment node` docblock or something like:
```
  const {window} = global
  beforeAll(() => {
    // @ts-ignore
    delete global.window
  })
  afterAll(() => {
    global.window = window
  })
 ```
 
 ...in our `describe` block, then React Testing Library's `render` function doesn't seem to work. In the Node jest-environment, the error shown is: 
 ```
 The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/en/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: document is not defined
 ```
 
 …and when deleting `global.window` the error is the same but refers to `window` not being defined.

So how do we test this case with React Testing Library? Any hints would be most appreciated, thank you 😃

**Comment by MatanBobi** [comment]
Hi @joeldbirch, thanks for your question :)
My suggestion might be a hack but I'd think of separating the "server" component and the "client" component to two different components since they have two different functionalities.
That way, your server component actually renders the client component only if the window is defined.
So in your tests you can test your "server" component by removing the `global.window` as you did, and you'll test your "client" component regularly :)

**Comment by BSlaven** [comment]
Just in case someone runs into this issue. I am learning testing in react and I just ran into this issue. I resolved it by going to node_modules folder, jest folder, package.json file. I just added one property.

"testEnvironment": "jsdom"`

It works perfectly. I know editing node_modules folder is a no no, but just for the sake of learning it works.

**Comment by nickmccurdy** [comment]
If you rely on an edit to `node_modules`, other developers and machines (including CI services like GitHub Actions) will not work properly. Additionally newer packages like Yarn Berry do not support editing `node_modules` by default, as it's not used in installation anymore.

Instead, if you're running Jest directly, you should add `"testEnvironment": "jsdom"` to your own Jest config.

**Comment by thepuzzlemaster** [comment]
I'm not sure if this has changed since the suggested solution, or if was implied by @kentcdodds when they suggested setting the `testEnvironment` to `jsdom`, but for anyone coming to this, to set the `testEnvironment`, you use the following line in your `jest.config.js`

`testEnvironment: 'jest-environment-jsdom',`

**Comment by ralyodio** [comment]
I'm getting this error in svelte test as well. No idea how to fix.

**Comment by Alisson9423** [comment]
primero: **yarn add -D @testing-library/react** depois crie um arquivo de configuração **"jest.setup.ts"**
segundo: no seu arquivo **jest.config.js** adicione isso **"dentro de module.export"**  -> testEnvironment: 'jsdom',
terceito: no seu arquivo **jest.config.js** adicione **"dentro de module.export"** -> **setupFilesAfterEnv**
quarto: **parâmetro** do **"setupFilesAfterEnv"** é esté **['caminho do jest.setup.ts']**

depois disso tudo -> yarn jest --clearCache
só roda o jest agora

**Comment by IbrahimO123** [comment]
> I'm not sure if this has changed since the suggested solution, or if was implied by @kentcdodds when they suggested setting the `testEnvironment` to `jsdom`, but for anyone coming to this, to set the `testEnvironment`, you use the following line in your `jest.config.js`
> 
> `testEnvironment: 'jest-environment-jsdom',`

the jest.config.js file, Are we creating this file ourself....?

**Comment by IbrahimO123** [comment]
### ReferenceError: document is not defined

Just in case someone have simliar issue, I solved mine by put a docblock at the top of my test file

**Comment by zirlman** [comment]
Had the same issue. This code block
```ts
/**
* @jest-environment jsdom
*/
```
**MUST BE ON TOP OF FILE**. If you put it below the `import` statement it won't work 😄

**Comment by ashu9972ya** [comment]
still i am getting error ReferenceError: document is not defined

**Comment by 1mehdifaraji** [comment]
I had the same issue and resolved it by providing jest , an environment with installing ```jest-environment-jsdom``` and providing the test environment in ```jest.config.js```
```
{ "testEnvironment": "jsdom" }
```

**Comment by mltsy** [comment]
In case anybody else is confused: `jsdom` was previously the default for `testEnvironment`, and that was changed to `node` in jest v27... which is coincidentally *right* before the authors started publishing upgrade guides 😜  So this is a likely thing to encounter when upgrading from jest 26.x or earlier to jest 27.x or later.

**Comment by sehrish30** [comment]
1) install "npm i jest-environment-jsdom"

2) (testEnvironment: "jsdom") in jest.config.js

**Comment by hafeeeii** [comment]
if still not working then remove the 'coverage' folder and reload vs code then run test again.
