### ISSUE TITLE
Have render call cleanup

### ISSUE THREAD

**Issue by Gpx** [testing-library/react-testing-library#428]
### Describe the feature you'd like:

Right now we have to call `cleanup` before each test. This tends to be confusing for beginners especially if they come from other libraries (Enzyme) that do not need this step. It would be good if `render` could call `cleanup` automatically.

### Suggested implementation:

I didn't dig into the code too much but it should be as easy as having `render` call `cleanup` as the first thing it does.

### Describe alternatives you've considered:

I'm trying to think about a use-case where you might want to run two `render`s in the same test or where you might want to manually run `cleanup`—which would invalidate this idea—but can't come up with anything.

### Teachability, Documentation, Adoption, Migration Strategy:

We would have to remove the documentation about `cleanup`. Potentially we would have to introduce a breaking change.

**Comment by threepointone** [comment]
If `render` called `cleanup` automatically, what would you make assertions on? :) The application would unmount and the dom element would be removed.

**Comment by kentcdodds** [comment]
I think the suggestion is to call `cleanup` _before_ rendering. I'm considering this... I'm leaning toward "no" because it violates the principle of least surprise. But I want to hear what other people have to say.

**Comment by Gpx** [comment]
Yes, I meant calling `cleanup` before doing any rendering

**Comment by weyert** [comment]
I was wondering how this would affect the rerendering of components?

**Comment by kentcdodds** [comment]
I guess we'd need to make sure that calling `rerender` would not call `cleanup`.

**Comment by alexkrolick** [comment]
🤔 I like the idea of reducing the amount of setup required...

- It would have to check the `container` and `baseElement` identities before cleaning up
- `rerender` would have to not do this

This might make sense at a higher level of abstraction like the `const page = visit('/route')` thing @mxstbr demoed

**Comment by threepointone** [comment]
Let’s say a component has a bug where unmounting throws an error (the effect cleanup is bad, eg). Then this feature would make the *next* test fail, and debugging would be a pain. 

Not sure if this is worth the short term gain, tbh. The ‘fix’ should be figuring out how to automate cleanup. 

(As an example, why not “import ‘cleanup-after-each’” by default on importing rtl?)

**Comment by kentcdodds** [comment]
> (As an example, why not “import ‘cleanup-after-each’” by default on importing rtl?)

I've considered that. If we made `cleanup-after-each` work in non-jest environments then I'd be 👍 for that I think.

**Comment by alexkrolick** [comment]
> non-jest environments

👆

**Comment by kentcdodds** [comment]
The more I think about it, the more I think this makes sense. I'm totally open to seeing a PR for this.

**Comment by alexkrolick** [comment]
> Let’s say a component has a bug where unmounting throws an error (the effect cleanup is bad, eg). Then this feature would make the next test fail, and debugging would be a pain.

This seems like a big deal though.

**Comment by kentcdodds** [comment]
It is a big deal. What Sunil suggested and what I want is for `import 'cleanup-after-each'` to happen automatically when you import `@testing-library/react` (and to do some `typeof afterEach` checks so it doesn't break in other environments).

**Comment by alexkrolick** [comment]
👍 misread what "this" meant in "this makes sense"

**Comment by alexkrolick** [comment]
> import 'cleanup-after-each' to happen automatically when you import @testing-library/react (and to do some typeof afterEach checks so it doesn't break in other environments)

One thing to confirm is that this works if you have a custom test utils file that imports and re-exports from RTL.

**Comment by kentcdodds** [comment]
Yes, definitely would work with that

**Comment by kentcdodds** [comment]
Alright, I feel really great about this. Made #430.

**Comment by kentcdodds** [comment]
I'm thinking this'll happen soon. Will require a major version bump though 😬
