### ISSUE TITLE
[bug] act-compat assume console.error is called with a string

### ISSUE THREAD

**Issue by SBoudrias** [testing-library/react-testing-library#442]
- `react-testing-library` version: 
- `react` version:
- `node` version:
- `npm` (or `yarn`) version:

### Relevant code or config:

Code is situated here: https://github.com/testing-library/react-testing-library/blob/master/src/act-compat.js#L32

```js
args[0].indexOf(
              'Warning: Do not await the result of calling ReactTestUtils.act',
            ) === 0
```

This assumes the first arg passed to `console.error` is a string; but the type could be different. For example, it can be an object `console.error({ error })`

### Suggested solution:

We could either:

1. Stringify the args before calling `indexOf`
2. Type check the arg first

**Comment by alexkrolick** [comment]
> Type check the arg first

This seems fine, since we can only check for the substring when the input is a string itself

**Comment by kentcdodds** [comment]
Agreed. Would you like to [make a pull request](http://makeapullrequest.com/) for this @SBoudrias?

**Comment by ely-alamillo** [comment]
@kentcdodds I can go ahead and stringify the args for this.

**Comment by rvdkooy** [comment]
@ely-alamillo you still taking this? I can also do this one?

**Comment by ely-alamillo** [comment]
Why does this case exist if it's not doing anything ? https://github.com/testing-library/react-testing-library/blob/master/src/act-compat.js#L38

@kentcdodds

**Comment by kentcdodds** [comment]
Because otherwise this would run:

https://github.com/testing-library/react-testing-library/blob/8881803ea50f773cf909764299e68f35e22478d1/src/act-compat.js#L45
