### ISSUE TITLE
Cleanup not running in v9

### ISSUE THREAD

**Issue by alexandernanberg** [testing-library/react-testing-library#443]
- `react-testing-library` version: 9.1.1
- `react` version: 16.9.0
- `node` version: 10.16.0
- `npm` (or `yarn`) version: N/A

### Relevant code or config:

```js
// jest.setup.js
import { configure as configureRTL } from '@testing-library/react';
configureRTL({ testIdAttribute: 'data-test-id' });
```

```js
// some-component.test.js
it('test 1', () => {
  const { getByText } = render(<>Hello</>);

  expect(getByText('Hello')).not.toBeNull();
});

it('test 2', () => {
  const { getByText } = render(<>Hello</>);

  expect(getByText('Hello')).not.toBeNull();
});
```

### What you did:

Upgraded to v9

### What happened:

Automatic cleanup isn't run which causes tests to break. Seems to be linked caused by the `configure` fn, when removing it from our setup file cleanup works as expected 🤔 

When adding 

```js
import {render, cleanup} from '@testing-library/react'

afterEach(cleanup)
```

it works as expected

### Reproduction:

I wasn't able to get Codesandbox to honor the jest config, so no repro unfortunately.

### Problem description:

Cleanup doesn't run

### Suggested solution:

Cleanup should run

**Comment by kentcdodds** [comment]
Could you make a reproduction here? https://github.com/testing-library/dom-testing-library-template

**Comment by alexandernanberg** [comment]
Ah found the issue while creating the repro, the issue is that we used `setupFiles` instead of `setupFilesAfterEnv` for setting the RTL config. 

Not sure if this should be considered a bug or not. It's a simple fix once you know whats wrong

**Comment by kentcdodds** [comment]
Thanks for digging in. It's not a bug. Working as documented 😀 glad you worked it out!

**Comment by schreyerpeter** [comment]
@alexandernanberg I'm running into the same issue after upgrading to version 9.1.1
Would you mind sharing your RTL config?

**Comment by alexandernanberg** [comment]
@schreyerpeter The RTL config is in my first comment, do you mean the jest config?

**Comment by schreyerpeter** [comment]
@alexandernanberg Yes, Jest config. Thanks!

**Comment by artem-galas** [comment]
I've create a sandbox with the issue, seems it's still remaining

https://codesandbox.io/s/green-platform-5fhd1

**Comment by eps1lon** [comment]
> I've create a sandbox with the issue, seems it's still remaining
> 
> [codesandbox.io/s/green-platform-5fhd1](https://codesandbox.io/s/green-platform-5fhd1)

@artem-galas 

```diff
-fireEvent.click(getByText(/Submit/i)[0]);
+fireEvent.click(getByText(/Submit/i));
```

`getByText` already returns a single element. The error message included that you didn't pass a valid element. Why did you think this relates to `cleanup`?

**Comment by artem-galas** [comment]
Yes, you are right about that error, thanks.

But just try to run all tests once again, and you will get an error.

`Found multiple elements with the text: /Submit/i`

And you will see that component were render several times
![Screenshot 2020-03-06 at 14 02 57](https://user-images.githubusercontent.com/6387897/76082067-33bc8900-5fb3-11ea-959c-2a6364429d8e.png)

**Comment by kentcdodds** [comment]
I think that's a bug in codesandbox. Are you seeing this locally?

**Comment by artem-galas** [comment]
Just tried that locally, seems everything is fine with the example above.... 🤔 

But something went wrong with my real-world project... Will try to find out what's wrong. 

Thanks for your time. Sorry for the buzz.
