### ISSUE TITLE
how to test ant design `Select`

### ISSUE THREAD

**Issue by NyanShen** [testing-library/react-testing-library#453]
- `react-testing-library` version:   9.1.0
- `react` version:  16.9.0
- `node` version:  9.11.1
- `npm` (or `yarn`) version:  6.10.3

Relevant code or config

``` javascript
const [selectValue, setSelectValue] = useState<string>("");
const handleChange = (value: string) => {
     setSelectValue(value);
}
<Select 
   value={selectValue}
   onChange={(value: string) => handleChange(value)}
>
.....some option
</Select>
```

What you did:
I have no idea hoe to test the antd Select use testing-library/react.
What happened:

Reproduction repository:

Problem description:

Suggested solution:

**Comment by weyert** [comment]
If you can give us codesandbox with the problem at hand we can have a look.

**Comment by afontcu** [comment]
Hi!

For questions related to using the library, please visit [Spectrum](https://spectrum.chat/testing-library/) instead of filing an issue on GitHub.


I'm gonna close this, feel free to reopen it if you were actually reporting a bug or a missing feature 😃
