### ISSUE TITLE
Documentation out of sync with all FindBy signatures?

### ISSUE THREAD

**Issue by Beej126** [testing-library/react-testing-library#456]
i'm seeing all the samples in the docs use matcher as the first arg but the FindBy signatures are expecting container as the first arg and matcher second... when was that change?  that seems like a pretty huge breaking change but it doesn't seem to be called out in any of the releases so i assume i'm missing something?

**Comment by afontcu** [comment]
Hi @Beej126!

I'm wild guessing here, but is it possible that you are reading DOM Testing Library queries signatures, which actually expect a container as a first argument?
React's queries are returned with their first argument bound ([source](https://testing-library.com/docs/react-testing-library/api#queries-1)), so you only need to provide one argument.

**Comment by Beej126** [comment]
thanks a ton for responding... that's how all our code is structured so i know that was true when we pulled v 8.0.1 originally just a couple months ago, but something has shifted and i can't understand where... i'm seeing that just yesterday the types were moved to [definitely typed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/testing-library__react/index.d.ts)... and you can see that they simply export all these functions directly from '@testing-library/dom... and when i go back in history, it seems like it's been that way for a long time

export * from '@testing-library/dom';

**Comment by alexkrolick** [comment]
If you import the methods, you need to provide an element as the first arg:

```jsx
import { findByText, render } from '@testing-library/react'

test('should work', async () => {
  const {container} = render(<div>Hello</div>
  expect(await findByText(container, 'Hello')).toBeInTheDocument()
})
```

If you use the methods returned by render, you do not (it is bound to the document):

```jsx
import { render } from '@testing-library/react'

test('should work', async () => {
  const {findByText} = render(<div>Hello</div>
  expect(await findByText('Hello')).toBeInTheDocument()
})
```

**Comment by Beej126** [comment]
ok thanks... this is starting to come into focus...
i guess the bummer is that we don't get typescript signatures for the
methods returned by render
the only FindByText typescript declaration has container as the first arg...
so we can't properly declare findByText in typescript like your second
example which is most similar to the docs

but fortunately, tweaking your first example a smidge looks good for
us to shift to:

test('should work', async () => {
  const {container} = render(<div>Hello</div>
  expect(await container.findByText('Hello')).toBeInTheDocument()
})

**Comment by alexkrolick** [comment]
There should be TS definitions for the render result...

**Comment by Beej126** [comment]
yes thank you, my last code sample follows that lead
