### ISSUE TITLE
Running `npm run setup -s` fails

### ISSUE THREAD

**Issue by ely-alamillo** [testing-library/react-testing-library#464]
- `react-testing-library` version: 9.1.3
- `react` version:
- `node` version: 12.6.0
- `npm` (or `yarn`) version: npm 6.9.0

### What you did:
Tried to set up project following the CONTRIBUTING.md file.

### What happened:
Setup failed with `npm run setup -s` fails with ` Tests should not contain if statements  jest/no-if` for the file `react-testing-library/src/__tests__/rerender.js`

### Reproduction:
Run through setup instructions found in CONTRIBUTING.md.

### Problem description:

Running `npm run setup -s` fails with ` Tests should not contain if statements  jest/no-if` for the file `react-testing-library/src/__tests__/rerender.js`

### Suggested solution:
1. Fix the test so it doesn't use `if` statements.
2. Suppress the rule for this test case.

**Comment by afontcu** [comment]
Hi @ely-alamillo, nice catch! Would you like to submit a PR to fix it? 🙌

**Comment by ely-alamillo** [comment]
Issue now fixed thanks to @rvdkooy.
