### ISSUE TITLE
Cannot find module '@testing-library/react'.ts(2307)

### ISSUE THREAD

**Issue by wolverineks** [testing-library/react-testing-library#472]
- `react-testing-library` version: >= 9.1.2-alpha.0
- `react` version: 16.8.4
- `node` version: unknown
- `npm` (or `yarn`) version: unknown

### Relevant code or config:
```js
import { render } from "@testing-library/react";
```

### What you did:
Import library

### What happened:
Typescript error: `Cannot find module '@testing-library/react'.ts(2307)`

### Reproduction:
https://codesandbox.io/s/mystifying-lamport-wytox

### Problem description:
Tests run just fine, but no types, and typescript error

**Comment by kentcdodds** [comment]
Sorry, that codesandbox link takes me to a 404 page. A lot of people are using this library and it's working fine, so I'm guessing your issues are something specific to your project. If you're still having trouble please start a thread on http://spectrum.chat/testing-library/help-react

**Comment by Dom-Mc** [comment]
Ran into a similar issue on a project, solved with a force reinstall `yarn install --force`

**Comment by miguelangeltorresfp** [comment]
I solved this issue with this option in the tsconfig.json file: 
` "moduleResolution": "node", `

**Comment by hsnmrd** [comment]
I have the same problem, none of these answers works for me, any help please?

**Comment by MatanBobi** [comment]
@hsnmrd can you please share a cloneable repo of that so we'll be able to investigate how we can help?

**Comment by ktoqaloglu** [comment]
Solution: npm install --save-dev @testing-library/react

**Comment by yaserkya** [comment]
Upgrading to "@types/react": "^16.8.18" with npm i @types/react@latest fixed it.

**Comment by yaserkya** [comment]
change from "moduleResolution": "node", to "moduleResolution": "NodeNext",
Wich available in tsconfig.json

**Comment by soiswis** [comment]
Sometimes after running `npm install` VSCode for some reason doesn't pick the changes! So in my case it was the "old" reastart trick that did it.. I just restarted VSCode and it disappeared 😉

**Comment by jthomas-rsi** [comment]
@soiswis the good old restart worked for me. Thanks.

**Comment by jiangxiaoqiang** [comment]
restart work for me.

**Comment by teodora-zhelyazkova** [comment]
Check if the name of your file is with .tsx extension or you have missed the x

**Comment by paulsimongb** [comment]
Tried all of the above. None of it works. I manually copied in @type\jest and @testing-library\react from another working project and it then compiled. However, as soon as I did an npm install the folders disappaeared. Clearly npm is deciding for whatever reason that these are not needed, and it is deleting them.

**Comment by MatanBobi** [comment]
@paulsimongb without a reproduction link we won't be able to help you figure out what's causing that, please attach a codesandbox reproduction so we'll try to investigate.

**Comment by paulsimongb** [comment]
Hi Ronny

Many thanks for your reply.

I already had @types/jest installed

However, I have since worked out that it also needs to be added to setupTests.ts, below the @testing-library/jest-dom

import ***@***.***/jest-dom';
import ***@***.***/jest'

With that in place the error I had before went away.

It also cured the toBeInTheDocument  error

  const linkElement = screen.getByText(/learn react/i);
  expect(linkElement).toBeInTheDocument();

Regards

Paul Simon

**Comment by foloinfo** [comment]
In my case, the problem was using yarn 3.x with PnP feature. I'm currently using ALE(nvim).
I edited `.yarnrc.yml` to include `nodeLinker: node-modules`, which resolved the error. So, I guess the problem was caused by the tsc server running from a different dependency.

**Comment by ClydeDz** [comment]
Restarting VS Code works for me

**Comment by behnam-maqsudi** [comment]
> change from "moduleResolution": "node", to "moduleResolution": "NodeNext", Wich available in tsconfig.json

 "moduleResolution": "NodeNext" work for me
