### ISSUE TITLE
Why rerender called setTimeout?

### ISSUE THREAD

**Issue by LeeHao92** [testing-library/react-testing-library#473]
Why rerender called setTimeout?

- `@testing-library/react` version: `^9.1.3`
- `react` version: `^16.9.0`
- `node` version: `10.15.1`
- `yarn` version: `1.13.0`

### Relevant code or config:

```js
import React from 'react'
import renderer from 'react-test-renderer'
import { render } from '@testing-library/react'

jest.useFakeTimers()

const Comp = ({ active = false }) => <div>{active ? 'active' : 'inactive'}</div>

describe('setTimeout rerender test', () => {
  it('test', () => {
    const { rerender } = render(<Comp active />)
    rerender(<Comp active />)
    expect(setTimeout).toHaveBeenCalledTimes(1) // PASS
  })
})

```

**Comment by rvdkooy** [comment]
`sherlock mode ON`

react-dom is doing this

if I do this and check the stack trace

```
import React from 'react'
import { render } from '../index'

const Comp = ({ active = false }) => <div>{active ? 'active' : 'inactive'}</div>

describe('setTimeout rerender test', () => {
  it('test', () => {
    /* eslint-disable */
    global.setTimeout = function (fn, t) {
        throw new Error('argh');
    }
    
    const { rerender } = render(<Comp active />)
    rerender(<Comp active />)
    expect(setTimeout).toHaveBeenCalledTimes(1) // PASS
  })
})
```

you can see:
![image](https://user-images.githubusercontent.com/4119960/64199863-8f367e80-ce8b-11e9-8e1e-69a9bfe6da50.png)

they are using scheduler (https://www.npmjs.com/package/scheduler)

from here:

https://github.com/facebook/react/blob/3ed289b3b1286007e3f594b0b767b3b64bf3f86c/packages/react-reconciler/src/SchedulerWithReactIntegration.js#L143

which is doing the actual setTimeout

`sherlock mode OFF`

**Comment by kentcdodds** [comment]
🕵 Thank you Sherlock!

**Comment by alexkrolick** [comment]
You probably want to assert something more specific than that a global like `setTimeout` is called. It's used all the time in library code, and, in general, doesn't describe an observable behavior.
