### ISSUE TITLE
Getting error while testing @rmwc/tabs using react-testing-library

### ISSUE THREAD

**Issue by Sravan501** [testing-library/react-testing-library#481]
Im using latest react-testing-library version.
while testing @rmwc/tabs, occur following error.

![image](https://user-images.githubusercontent.com/48708141/64848815-b0d3fa80-d62f-11e9-9bf8-bede3fa82adf.png)

**Comment by eps1lon** [comment]
It looks like you're mocking the DOM with `jsdom`? If so then this should be handled once https://github.com/jsdom/jsdom/pull/2626 is released.

If you are using `jsdom` I would recommend subscribing to the linked PR and watching for a release.
