### ISSUE TITLE
Tab navigation bug

### ISSUE THREAD

**Issue by xMokAx** [testing-library/react-testing-library#483]
- `react-testing-library` version: 9.1.1
- `react` version: 16.9.0
- `node` version: 10.14.1
- `npm` (or `yarn`) version: 1.17.3

### Relevant code or config:

```js
import React, { useState } from "react";
import styled from "styled-components";
import { render, fireEvent } from "@testing-library/react";
import Modal, { ModalProvider } from "../src";

function StatefulModal(props) {
  const { isOpen: propsIsOpen, ...rest } = props;
  const [isOpen, setIsOpen] = useState(propsIsOpen);
  const toggleModal = () => {
    setIsOpen(!isOpen);
  };
  return (
    <div>
      <button data-testid="button" onClick={toggleModal}>
        Open Modal
      </button>
      <button>Useless</button>
      <Modal isOpen={isOpen} closeModal={toggleModal} {...rest}>
        <div>
          <span data-testid="content">Hello world</span>
          <button>first</button>
          <button onClick={toggleModal}>close</button>
          <button>last</button>
        </div>
      </Modal>
    </div>
  );
}

function renderWithProvider(modalProps = {}, providerProps = {}) {
  const finalModalProps = {
    isOpen: false,
    ...modalProps
  };

  return render(
    <ModalProvider data-testid="provider" {...providerProps}>
      <StatefulModal {...finalModalProps} />
    </ModalProvider>
  );
}

describe("<Modal />", () => {
// this passes for sure
  it("should focus first tabbable element after open", () => {
    const { getByText } = renderWithProvider({ isOpen: true });
    expect(getByText("first")).toHaveFocus();
  });
  // this passes
  it("should focus first tabbable element when Tab key is pressed while the last tabbable element is focused", () => {
    const { getByText } = renderWithProvider({
      isOpen: true
    });
    console.log(document.activeElement.textContent); // first
    getByText("last").focus();
    console.log(document.activeElement.textContent); // last
    fireEvent.keyDown(document, { keyCode: 9 });
    console.log(document.activeElement.textContent); // first
    expect(getByText("first")).toHaveFocus();
  });
  // this passes
  it("should focus last tabbable element when Shift + Tab keys are pressed while the first tabbable element is focused", () => {
    const { getByText } = renderWithProvider({
      isOpen: true
    });
    console.log(document.activeElement.textContent); // first
    fireEvent.keyDown(document, { keyCode: 9, shiftKey: true });
    console.log(document.activeElement.textContent); // last
    expect(getByText("last")).toHaveFocus();
  });
  // this passes but actually the focus never changed (check the logs)
  it("should focus first tabbable element when Tab key is pressed while the last tabbable element is focused", () => {
    const { getByText } = renderWithProvider({
      isOpen: true
    });
    console.log(document.activeElement.textContent); // first
    fireEvent.keyDown(document, { keyCode: 9 });
    console.log(document.activeElement.textContent); // first
    fireEvent.keyDown(document, { keyCode: 9 });
    console.log(document.activeElement.textContent); // first
    fireEvent.keyDown(document, { keyCode: 9 });
    console.log(document.activeElement.textContent); // first
    expect(getByText("first")).toHaveFocus();
  });
  // this fails!!! the focus never changes
  it("should focus the next element when Tab is pressed", () => {
    const { getByText } = renderWithProvider({
      isOpen: true
    });
    console.log(document.activeElement.textContent); // first
    fireEvent.keyDown(document, { keyCode: 9 });
    console.log(document.activeElement.textContent); // first
    expect(getByText("close")).toHaveFocus();
  });
});
```

### What you did:
Trying to test tab navigation in a modal (trapped focus) I know `JSDOM` doesn't support that from this https://github.com/testing-library/react-testing-library/issues/336 but I see strange behavior.

### What happened:
Some tests passed while they shouldn't !!!

### Reproduction:
Clone this repo https://github.com/xMokAx/styled-react-modal and replace the code inside `modal.test.jsx` with the code I posted here and run `yarn test`.

### Problem description:
`fireEvent.keyDown()` works as expected sometimes and sometimes it doesn't.

### Suggested solution:
IDK

**Comment by eps1lon** [comment]
Is this strange behavior gone if you use `fireEvent.keyDown(document.activeElement)`?

Why would you expect the focus to change if you know that jsdom does not implement tabbing?

**Comment by xMokAx** [comment]
> Is this strange behavior gone if you use `fireEvent.keyDown(document.activeElement)`?
> 
> Why would you expect the focus to change if you know that jsdom does not implement tabbing?

I don't expect it to change but it changed in the second and the third tests. Check the logs.

**Comment by eps1lon** [comment]
This might very well be your component. Could you create a minimal example without any outside dependencies? Modals are very difficult with regards to focus behavior. I see a lot of logic with regards to focus managment and it might very well be that the Modal traps it when it receives tab keyboard events which might seem like it works inconsistent.

A single test case with component source which fails the expected behavior would help a lot. Both maintainers to review and issuers to understand what's going on.

**Comment by xMokAx** [comment]
@eps1lon 
In the second test when `fireEvent.keyDown(document, { keyCode: 9 });` is called the focus changes from the last button to the first button which is the right behavior in the browser but it shouldn't happen in `jsdom` if I understand correctly.
In the third test when when `fireEvent.keyDown(document, { keyCode: 9, shiftKey: true });` is called the focus changes from the first button to the last button which is the right behavior in the browser but it shouldn't happen in `jsdom` if I understand correctly.
In the fourth and fifth tests when `fireEvent.keyDown(document, { keyCode: 9 });` is called focus doesn't change which is the expected behavior from `jsdom`.
