### ISSUE TITLE
/pure build throws in browsers not supporting async-await

### ISSUE THREAD

**Issue by eps1lon** [testing-library/react-testing-library#486]
More of a problem with `kcd-scripts` but I'm filing it here since the use case is more obvious. Feel free to transfer the issue.

- `react-testing-library` version: 9.1.4
- `react` version: N/A
- `node` version: N/A
- `npm` (or `yarn`) version: N/A

### Relevant code or config:

```js
import '@testing-library/react/pure'
```

### What you did:

Used `@testing-library/react` in IE11

### What happened:

Threw with `unexpected identifier` (due to async-await)

### Reproduction:

https://github.com/mui-org/material-ui/pull/17165/commits/1e54d497d94b68d3ea594ac83fa3d2e62ab8026c 

failing build: https://circleci.com/gh/mui-org/material-ui/113431

### Problem description:

`kcd-scripts build` will use babel but ignore any `browserslists` assuming the target is `node: 8`. [Only rollup and webpack bundles will load browserslist](https://github.com/kentcdodds/kcd-scripts/blob/bd3c762c0202ac3564bb6a329e3e9e972795b5e7/src/config/babelrc.js#L40)

### Suggested solution:

Add a browserslist targetting ie 11, node 8 and the last 3 versions of the evergreen browsers as well as:

No special case for babel `targets`. It should always use `.browserslistrc` since that supports a `node` entry as well. I think it didn't use to support a node version since I occasionally encounter a repository using browserslist but throwing with a node entry.

**Comment by kentcdodds** [comment]
I got a fix for you. Let me know what you think: #489
