### ISSUE TITLE
Inconsistency of input behaviour on keypress

### ISSUE THREAD

**Issue by Copainbig** [testing-library/react-testing-library#488]
- `react-testing-library` version: 4.0.0
- `react` version: 16.8.6
- `node` version: 12.1.0
- `npm` (or `yarn`) version: 6.10.2

I try to create a component, that includes an input and will have a callBack function passed as props, that will be called when you unfocus the input, or press ENTER in it. Here is a simplified version of the code : 

```javascript
const Input = ({onSelectValue, displayedValue, placeholder}) => {

return (
    <div>
        <input onSelectValue
             value={displayedValue}
             placeholder={placeholder}
             onBlur={event => onSelectValue(event)}
        />
    </div>
)
}

```

Common implementation for pressing the "ENTER" key on a focused input field, is trigger the "Blur" event, and make the input loose its focus (tested on Chrome, Safari, Firefox).
In this example, the _onSelectFunction_ props function, it attached to the input onBlur event in the component. So this test works : 

```javascript
  it("should trigger onSelectValue function when input loose the focus", () => {
    const TEST_VALUE = "test";
    const onSelectFunction = jest.fn();
    const { getByDisplayValue } = render(
      <Input
        onSelectValue={elt => onSelectFunction(elt)}
        displayedValue={TEST_VALUE}
        placeholder="Enter a value"
      />
    );
    const input = getByDisplayValue(TEST_VALUE);
    input.focus();
    input.blur();
    expect(onSelectFunction.mock.calls.length).toBe(1);
    expect(onSelectFunction.mock.calls[0][0]).toBe(TEST_VALUE);
  });
```
But, even if it works when I try my component, this test does not work, because pressing ENTER, does not make the component loose its focus : 

```javascript
  it("should trigger onSelectValue function when input is on focus and user push ENTER", () => {
    const TEST_VALUE = "test";
    const onSelectFunction = jest.fn();
    const { getByDisplayValue } = render(
      <Input
        onSelectValue={elt => onSelectFunction(elt)}
        displayedValue={TEST_VALUE}
        placeholder="Enter a value"
      />
    );
    const input = getByDisplayValue(TEST_VALUE);
    input.focus();
    fireEvent.keyPress(input, { key: "Enter", code: 13, charCode: 13 });
    expect(onSelectFunction.mock.calls.length).toBe(1);
    expect(onSelectFunction.mock.calls[0][0]).toBe(TEST_VALUE);
  });
```

And indeed, the component still has the focus, because this test succeed :

```javascript
  it("example test : does not loose focus when ENTER is pressed", () => {
    const TEST_VALUE = "test";
    const onSelectFunction = jest.fn();
    const { getByDisplayValue } = render(
      <ValueWithHintsInput
        onSelectValue={elt => onSelectFunction(elt)}
        displayedValue={TEST_VALUE}
        placeholder="Enter a value"
      />
    );
    const input = getByDisplayValue(TEST_VALUE);
    input.focus();
    fireEvent.keyPress(input, { key: "Enter", code: 13, charCode: 13 });
    expect(document.activeElement).toEqual(input);
  });
```

Am I missing something here, or is there an issue with the underlying event implementation?

Thanks for your work and help.

**Comment by kandros** [comment]
@Copainbig it looks like it's working as intended, you should add an event-handler  to handle keyPress that can if Enter was press and trigger blur (of the callback direcly) 

as you can see in the examples here
https://codesandbox.io/s/frosty-butterfly-u9o27
and here 
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onblur
pressing enter should not trigger blur event by default

**Comment by kentcdodds** [comment]
Thanks @kandros!
