### ISSUE TITLE
TypeScript and ESLint state RTL should be a dependency, not devDependency

### ISSUE THREAD

**Issue by skube** [testing-library/react-testing-library#491]
- `react-testing-library` version: 9.1.4
- `react` version: 16.8.6
- `node` version: 10.15.3
- `npm` (or `yarn`) version: 6.9.0

### Relevant code or config:

```ts
import { render } from '@testing-library/react';

// Error: '@testing-library/react' should be listed in the project's dependencies,
// not devDependencies.eslint(import/no-extraneous-dependencies)

```

### What you did:

Added RTL as [per instructions](https://testing-library.com/docs/react-testing-library/intro): 

```sh
npm install --save-dev @testing-library/react
```

### What happened:

Received an error inside VSCode informing the package should be listed projects dependencies, not devDependencies.

### Problem description:

Seems to be a disconnect when using TypeScript and the installation instructions shown on RTL site.

**Comment by alexkrolick** [comment]
That is an issue with an ESLint rule you have in your project. I'm guessing you are using the AirBnB lint config?

**Comment by skube** [comment]
Yes I'm using AirBnB lint config.

**Comment by alexkrolick** [comment]
You should configure the rule to ignore test files per the docs: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md#options

```
"import/no-extraneous-dependencies": ["error", {"devDependencies": ["**/*.test.js", "**/*.spec.js"]}]
```
