### ISSUE TITLE
Cannot read property 'location' of undefined react-router hooks (official)

### ISSUE THREAD

**Issue by yuritoledo** [testing-library/react-testing-library#493]
- `react-testing-library` version:    `"@testing-library/react": "^9.1.3"`
- `react` version: `"react": "^16.9.0"`
- `node` version: `v8.16.1`
- `npm` (or `yarn`) version: `yarn 1.17.3`

### Relevant code or config:

```js
const EtapaFormulario = () => {
  const location = useLocation()
  const params = useParams<{ id?: string }>()
  const history = useHistory()
// { ... }
}
```

### Problem description:
When using the `react-router` hoooks (`useLocation`, `useParams`, `useHistory`), throws the following error:

```
TypeError: Cannot read property 'location' of undefined

      51 | 
      52 | const EtapaFormulario = () => {
    > 53 |   const location = useLocation()
         |                    ^
      54 |   const params = useParams<{ id?: string }>()
      55 |   const history = useHistory()
      56 | 

      at useLocation (node_modules/react-router/modules/hooks.js:28:10)
      at EtapaFormulario (src/Modules/CalendarioEscolar/Etapa/Formulario/Formulario.tsx:53:20)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:15108:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17342:13)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:18486:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:347:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:397:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:454:31)
      at beginWork$$1 (node_modules/react-dom/cjs/react-dom.development.js:23217:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22211:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22185:22)
      at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:21878:11)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21419:22)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:24319:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:24347:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24436:10)
      at node_modules/react-dom/cjs/react-dom.development.js:24963:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21687:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24962:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:25042:12)
      at node_modules/@testing-library/react/dist/pure.js:86:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21643:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1002:14)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1418:12)
      at render (node_modules/@testing-library/react/dist/pure.js:82:26)
    {...}
```

**Comment by alexkrolick** [comment]
Are you following the guide to add the context provider?

https://testing-library.com/docs/example-react-router

**Comment by yuritoledo** [comment]
nop, gonna check with it.

I thinked that was an error with hooks.

Thanks.

**Comment by Ralphkay** [comment]
I am having the same issue, 

TypeError: Cannot read property 'location' of undefined
useLocation
node_modules/react-router/esm/react-router.js:712

any help please?

**Comment by Ralphkay** [comment]
> nop, gonna check with it.
> 
> I thinked that was an error with hooks.
> 
> where you able to get it resolved?.

**Comment by yuritoledo** [comment]
@Ralphkay can you share your code?

what version of `router` and `react-testing-lib`  are you using?

**Comment by michaeljblum** [comment]
Same issue over here. I am getting my error in a full application with latest versions of react-router-dom and React, but here's the same thing reproduced: https://codesandbox.io/s/awesome-swartz-kzdwv

For useLocation, or basically whenever I'm doing `const location = useLocation()` -> "TypeError
Cannot read property 'location' of undefined."

**Comment by alexkrolick** [comment]
Are you all following the instructions here? https://testing-library.com/docs/example-react-router

You need to have a context provider in the tree.

**Comment by michaeljblum** [comment]
Where is the context provider in the example code you're pointing to? Sorry, I'm not seeing any context or providers...

**Comment by alexkrolick** [comment]
The context provider for React Router is the Router/MemoryRouter/BrowserRouter component:

```diff
  const history = createMemoryHistory()
  const { container, getByText } = render(
+    <Router history={history}>
      <App />
    </Router>
  )
```

**Comment by michaeljblum** [comment]
In my full app I have `
<Router>
          <Header />
          <Switch>
            <Route exact path="/" component={Home} />
            <Route exact path="/about" component={About} />

            <Route exact path="/visit" component={Visit} />
            <Route exact path="/events/:slug" component={Exhibition} />

            <Route component={NotFound} />
          </Switch>
          <Footer />
      </Router>`

In the return statement of the function in which I also have `const location = useLocation();`

Is that not sufficient for context?

**Comment by alexkrolick** [comment]
You need to render the <Router> in the test too

**Comment by michaeljblum** [comment]
So you're saying I need a `ReactDOM.render(...)` in the same file in order for useLocation to not throw a type error?

**Comment by michaeljblum** [comment]
Ah, nevermind - got it working!

**Comment by yuritoledo** [comment]
@michaeljblum I use this HoC

```js
import React from 'react'

import { Router, Route } from 'react-router'
import { createMemoryHistory } from 'history'
import { render } from '@testing-library/react'
const history = createMemoryHistory()

export const renderWithRouter = Component => render(
  <Router history={history}>
    <Route component={Component} />
  </Router>
)
```

and this, on my test:

`  const render = () => renderWithRouter(EventForm)`

**Comment by Ralphkay** [comment]
i think it had got to do with the packages installed. they seemed to mix up. npm audit seemed a good fix, but i uninstalled and reinstalled and it worked

**Comment by lewislbr** [comment]
How did you fixed it @michaeljblum? I just stumbled upon this, and deleting/reinstalling packages doesn't work.

**Comment by brendonco** [comment]
> @michaeljblum I use this HoC
> 
> ```js
> import React from 'react'
> 
> import { Router, Route } from 'react-router'
> import { createMemoryHistory } from 'history'
> import { render } from '@testing-library/react'
> const history = createMemoryHistory()
> 
> export const renderWithRouter = Component => render(
>   <Router history={history}>
>     <Route component={Component} />
>   </Router>
> )
> ```
> 
> and this, on my test:
> 
> ` const render = () => renderWithRouter(EventForm)`

This works for me

**Comment by darryl-snow** [comment]
> @michaeljblum I use this HoC
> 
> ```js
> import React from 'react'
> 
> import { Router, Route } from 'react-router'
> import { createMemoryHistory } from 'history'
> import { render } from '@testing-library/react'
> const history = createMemoryHistory()
> 
> export const renderWithRouter = Component => render(
>   <Router history={history}>
>     <Route component={Component} />
>   </Router>
> )
> ```
> 
> and this, on my test:
> 
> ` const render = () => renderWithRouter(EventForm)`

This helps me resolve the error but unfortunately the test fails because the component isn't getting rendered... `screen.debug()` just outputs:

```
<body>
    <div />
</body>
```

**Comment by nickmccurdy** [comment]
Make sure your test navigates to the proper route.

**Comment by allisonjulioo** [comment]
`
import { Router } from 'react-router-dom';
import { createMemoryHistory } from 'history';

const MyComponentRender = mount(
  <Router history={history}>
    <MyComponent />,
  </Router>,
).children();
`

**Comment by cs11wcq** [comment]
> > @michaeljblum I use this HoC
> > ```js
> > import React from 'react'
> > 
> > import { Router, Route } from 'react-router'
> > import { createMemoryHistory } from 'history'
> > import { render } from '@testing-library/react'
> > const history = createMemoryHistory()
> > 
> > export const renderWithRouter = Component => render(
> >   <Router history={history}>
> >     <Route component={Component} />
> >   </Router>
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and this, on my test:
> > ` const render = () => renderWithRouter(EventForm)`
> 
> This helps me resolve the error but unfortunately the test fails because the component isn't getting rendered... `screen.debug()` just outputs:
> 
> ```
> <body>
>     <div />
> </body>
> ```

Hi I am getting the same problem. After clicking a button and going to a new route, the screen.debug() shows that exactly. Do you remember how you got around this?

**Comment by francmarin98** [comment]
```
jest.mock("react-router-dom", () => ({
  ...jest.requireActual("react-router-dom"),
  useLocation: () => ({
    pathname: "localhost:3000/example/path"
  })
}));
```
