### ISSUE TITLE
Mocking Fat Arrow Component Methods

### ISSUE THREAD

**Issue by chubaka** [testing-library/react-testing-library#494]
- `react-testing-library` version: ^7.0.0
- `react` version: ^16.8.6
- `node` version: 10.15.3
- `npm` (or `yarn`) version: 1.17.3

### Relevant code or config:

```js
    onRemove = (event) => {};
```

### What you did:

I'm trying to create a unit test for testing a React component with fat arrow methods. I'm trying to mock these methods in the unit test, but with no success

### What happened:

It was not able to do the mocking as the jest.spyOn throws an error saying that the method is not a function

### Problem description:

I dont want to switch to Enzyme as my testing library or to re-write my components just because the testing library does not have this functionality!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!.

### Suggested solution:

Provide a working solution how to do mocking on fat arrow component methods!!!!!!!!!!!!!!!!!.

**Comment by eps1lon** [comment]
Part of the reason this library was created is to move away from having to mock or test class methods.

You should try to write your tests without having to know what methods your class component implements. If you still think you need to mock instance methods feel free to join [our spectrum.chat](https://spectrum.chat/testing-library). Somebody may be willing to help you out. 

But I'm fairly certain we do not want to provide a first-class API for those practices.

**Comment by kentcdodds** [comment]
Perhaps we should add a page of documentation about this so when people search for it they land on a page that explains that it's the wrong way to think about testing components...

**Comment by JacobMGEvans** [comment]
Basically, I think one way could be to distill one of your articles that covered the philosophy of testing that react-testing-library was based on.

**Comment by kentcdodds** [comment]
Someone already added this to the docs here: https://testing-library.com/docs/dom-testing-library/faq

If you have suggestions on ways to improve that, more PRs would be welcome :)

**Comment by Singtah** [comment]
In the [TDD ](https://www.youtube.com/watch?v=kCR3JAR7CHE&t=48s) video, @kentcdodds you are asserting that onSubmit() function was called. 
The only difference with this topic is that the function is passed down as a prop. The implementation details are just a few steps higher in the components hierarchy, aren't they ?

**Comment by kentcdodds** [comment]
The `onSubmit` handler is part of the API of the component. Consider the "guiding philosophy" of the library:

> The more your tests resemble the way your software is used, the more confidence they can give you. - [17 Feb 2018](https://twitter.com/kentcdodds/status/977018512689455106)

Our React components have 2 users, the end user who interacts with our component, and the developer user who renders our component. Asserting the `onSubmit` handler is called is testing for the developer user.

For more on this: https://kentcdodds.com/blog/avoid-the-test-user
