### ISSUE TITLE
Not able to find input element by getByLabelText and getByTestId

### ISSUE THREAD

**Issue by kushalmahajan** [testing-library/react-testing-library#497]
- @testing-library/react = "^9.2.0",
-  node - 12.10.0
- yarn - 1.17.3

### Relevant code or config:

```
const StyledInput = styled.input<
	Pick<Styles.InputProps, "error" | "disabled"> &
		Omit<Styles.InputProps, "onChange">
>`
export const Input: React.FC<
	Styles.InputProps &
		Omit<React.InputHTMLAttributes<HTMLInputElement>, "onChange">
> = ({
	type = "text",
	placeholder,
	label,
	error,
	helpText,
	block = false,
	disabled = false,
	onChange,
	onBlur,
	value,
	className,
	...rest
}: Styles.InputProps & React.InputHTMLAttributes<HTMLInputElement>) => {
	const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		if (onChange) {
			onChange(e.target.value);
		}
	};
	return (
		<StyledWrapper block={block}>
			<StyledLabel error={error}>
				<label>{label}</label>
			</StyledLabel>
			<StyledInput
				type={type}
				placeholder={placeholder}
				error={error}
				disabled={disabled}
				onBlur={onBlur}
				onChange={handleChange}
				value={value}
				className={className}
				aria-labelledby="tm-input"
				{...rest}
			/>
			{error ? (
				<StyledError>
					<label>{error}</label>
				</StyledError>
			) : null}
			{helpText ? <StyledHelpText>{helpText}</StyledHelpText> : null}
		</StyledWrapper>
	);
};
```

 **input.stories.tsx** file

```
export const TestInput = () => {
	const [value, setValue] = React.useState("");
	const handleChange = (val: string) => {
		setValue(val);
	};
	return (
		<Input
			type="text"
			placeholder="Test input"
			value={value}
			onChange={handleChange}
		/>
	);
};
```
 **input.spec.js** file 

```
import React from "react";
import { fireEvent, render } from "@testing-library/react";
import { TestInput } from "./input.stories";

// afterEach(cleanUp);

describe("Input tests", () => {
	const { asFragment, getByLabelText } = render(<TestInput />);

	test("renders correcty", () => {
		expect(asFragment()).toMatchSnapshot();
	});

	test("Handles text change", () => {
		const input = getByLabelText("tm-input");
		fireEvent.change(input, { target: { value: "New value" } });
		expect(input.value).toBe("New value");
	});
});

```
```

### What you did:

yarn unit -u i.e.  "unit": "jest",

### What happened:

>  Input tests › Handles text change

    Unable to find a label with the text of: tm-input

    <body />

      13 | 
      14 |      test("Handles text change", () => {
    > 15 |              const input = getByLabelText("tm-input");
         |                            ^
      16 |              fireEvent.change(input, { target: { value: "New value" } });
      17 |              expect(input.value).toBe("New value");
      18 |      });

      at getElementError (node_modules/@testing-library/dom/dist/query-helpers.js:22:10)
      at getAllByLabelText (node_modules/@testing-library/dom/dist/queries/label-text.js:112:43)
      at node_modules/@testing-library/dom/dist/query-helpers.js:59:17
      at Object.getByLabelText (packages/web/src/components/input/input.spec.js:15:17)

**Comment by kentcdodds** [comment]
This is happening because react-testing-library automatically cleans up the DOM between every test. You can either swap the import from `@testing-library/react` to `@testing-library/react/pure` (not recommended), or change the way you structure your tests so that `render` appears *within* the test itself.

Learn more about why this is important here: https://kentcdodds.com/blog/avoid-nesting-when-youre-testing

and this may help as well: https://kentcdodds.com/blog/write-fewer-longer-tests

Good luck!

**Comment by kushalmahajan** [comment]
Yay! moving render inside test blocks and switching back to aria-label worked. Thanks~

**Comment by kentcdodds** [comment]
Great!

You shouldn't have to use aria-label. And especially for form elements you shouldn't use aria-label and should instead have a label that's both visible and connected to the component. Maybe this will help: https://kentcdodds.com/blog/please-stop-building-inaccessible-forms-and-how-to-fix-them

Good luck!

**Comment by kushalmahajan** [comment]
Surprisingly, for my earlier checkbox outside render worked. Confusing!

```

describe("Checkbox", () => {
	const { getByLabelText, asFragment } = render(<CheckboxState />);
	test("changes checkbox state", () => {
		const checkbox = getByLabelText("tm-checkbox");
		fireEvent.click(checkbox, { checked: true });
		expect(checkbox.checked).toBeTruthy();
	});
	test("renders checkbox", () => {
		expect(asFragment()).toMatchSnapshot();
	});
});
```

**Comment by kushalmahajan** [comment]
Umm..interesting post. Thanks!

**Comment by kentcdodds** [comment]
That's because the cleanup doesn't happen until _after_ the test completes. So the first test passes because it hasn't been cleaned up yet :)

**Comment by kushalmahajan** [comment]
> Umm..interesting post. Thanks!



> Great!
> 
> You shouldn't have to use aria-label. And especially for form elements you shouldn't use aria-label and should instead have a label that's both visible and connected to the component. Maybe this will help: https://kentcdodds.com/blog/please-stop-building-inaccessible-forms-and-how-to-fix-them
> 
> Good luck!

Umm..interesting post. Thanks!

**Comment by kushalmahajan** [comment]
> That's because the cleanup doesn't happen until _after_ the test completes. So the first test passes because it hasn't been cleaned up yet :)

Oh! By running the test I was assuming `test` block. What you mean is `describe` block or a test suite. After a `describe` block, the cleanup runs. Correct?

**Comment by kentcdodds** [comment]
No, it cleans up after every `test` or `it`. It's using `afterEach`.

**Comment by kushalmahajan** [comment]
Then I'm confused. How is Checkbox first ( test suite with outside render and two `test` blocks ) passing and `input` in the same way fails and requires `render` inside of `test` blocks?

**Comment by kentcdodds** [comment]
Because the cleanup happens *after* each `test` function. So if you do some setup before the first test function then it hasn't been cleaned up yet so it just happens to work. If you switch the order of the tests, you'll notice that the first one is the one that passes.

Just put `render` inside the test and you'll be good :)
