### ISSUE TITLE
Incorrect input type does not trigger onChange

### ISSUE THREAD

**Issue by Githiora** [testing-library/react-testing-library#500]
- `react-testing-library` version: latest
- `react` version: ^16.8.3

Tried testing logging in using Firebase when I came across some unusual behavior. Not sure if it's an error with Jest or react-testing-library. When I set the input type to something wrong like type="input" and fire an event to change the email address, Jest returns that the input value has changed but when I debug the value field is empty. 

When I change the input type to something correct like type="email" the problem goes away.

Here is the link to a codesandbox to reproduce the error: https://codesandbox.io/embed/still-darkness-2z63s

Thanks!

**Comment by kentcdodds** [comment]
I tried this directly in a browser and it works fine, so I'm guessing that it's a JSDOM issue in which case we can't do anything about it in this library and you'll need to file an issue in JSDOM. Sorry.
