### ISSUE TITLE
RTL not cleanup when using connected-react-router

### ISSUE THREAD

**Issue by ApolloTang** [testing-library/react-testing-library#501]
- `react-testing-library` version: ^9.3.0
- `react` version: ^16.10.2
- `node` version: 10
- `npm` (or `yarn`) version: 1.16.0

### Relevant code or config:

```js
describe('[Connected Router]', () => {
  beforeEach(()=>{ cleanup() }) // <------ cleanup not working ?
  afterEach(()=>{ cleanup() }) // <------- cleanup not working ?

  describe('Navigate to page a', () => {

    it('Connected Router Redux show navigate to page a', () => {
      const history = createBrowserHistory()
      const RootReducer = combineReducers( { router: connectRouter(history), })
      const store = createStore( RootReducer, {}, applyMiddleware(routerMiddleware(history), thunk))
      const rendered:RenderResult = render(
        <Provider store={store}>
          <ConnectedRouter history={history}>
            <App />
          </ConnectedRouter>
        </Provider>
      )

      const {
        getByText, unmount
      } = rendered

      const storeBeforeNavigate = store.getState()
      expect(storeBeforeNavigate.router.location.pathname).toBe('/')

      const link = getByText('Link to: /page a')
      fireEvent.click(link)

      const storeAfterNavigate = store.getState()
      expect(storeAfterNavigate.router.location.pathname).toBe('/a')

      unmount() // <-- unmount() not working ????
    })

    it('This test should fail', () => {
      const history = createBrowserHistory()
      const RootReducer = combineReducers( { router: connectRouter(history), })
      const store = createStore( RootReducer, {}, applyMiddleware(routerMiddleware(history), thunk))

      const rendered:RenderResult = render(
        <Provider store={store}>
          <ConnectedRouter history={history}>
            <App />
          </ConnectedRouter>
        </Provider>
      )

      const {
        queryByText,
        debug, container
      } = rendered

      debug(container)                  //<--- show that jsDom was not clear: showing 'Page content a'
      const pageContentA = queryByText('Page content a')
      expect(pageContentA).toBeNull()  // <-------- Fail !!!

      const storeBeforeNavigate = store.getState()
      expect(storeBeforeNavigate.router.location.pathname).toBe('/')  //<------- Fail!!!

    })
  })

})
```

### What you did:

jsDom is not cleared after an 'it' test block, it still show the state of previous navigation

### What happened:

first  test, navigate to a route, it works, test passed. 
second test, jsdom is not cleanup, it still show the state of previous test

### Reproduction:

link to repo:
https://github.com/ApolloTang/issue-rtl-not-cleanup-using-react-connected-router

**Comment by connormeredith** [comment]
I can see that the `cleanup` function is working as intended by adding `console.log(document.body.innerHTML)` at the end of the first test and the beginning of the second:
```js
describe('[Connected Router]', () => {
  beforeEach(()=>{ cleanup() }) // <------ cleanup not working ?
  afterEach(()=>{ cleanup() }) // <------- cleanup not working ?

  describe('Navigate to page a', () => {

    it('Connected Router Redux show navigate to page a', () => {
      ...

      // print the contents of the body - shows rendered output
      console.log('end of first test:', document.body.innerHTML)
    })

    it('This test should fail', () => {
      // print the contents of the body - shows no output
      console.log('start of second test:', document.body.innerHTML)

      ...
    })
  })

})
```

![image](https://user-images.githubusercontent.com/4907463/66550712-e17b5700-eb3d-11e9-9312-1808a7541bce.png)

I presume this is likely an issue with the way you're setting up your redux store, router or history?

**Comment by connormeredith** [comment]
You probably need to switch `createBrowserHistory` for `createMemoryHistory` in your tests: https://github.com/ReactTraining/history/blob/3f69f9e07b0a739419704cffc3b3563133281548/docs/GettingStarted.md

**Comment by ApolloTang** [comment]
@connormeredith, yes it works with `createMemoryHistory`, changes are here:

https://github.com/ApolloTang/issue-rtl-not-cleanup-using-react-connected-router/commit/7ff5712562b00bdf28331aa2fe2024be7fdeca81

**Comment by ApolloTang** [comment]
@connormeredith, A quick question on my confusion:

Should I createMemoryHistory on production code as well ? or just during testing.

**Comment by connormeredith** [comment]
You'll want to use `createBrowserHistory` in your production code and `createMemoryHistory` in your tests.

`createBrowserHistory` uses the browser's history and location APIs and `createMemoryHistory` stores all of its state internally. If you use `createMemoryHistory` in your production code you'll lose the integration with the address bar and browser history. If you use `createBrowserHistory` in your tests I believe it'll update JSDOM's history and location but not reset it between tests. Hopefully that helps 😄

**Comment by ApolloTang** [comment]
@connormeredith, That was super helpful, Thank you very much for your answer, and your quick response! 

closing this issue now!
