### ISSUE TITLE
The debug command is not printing the entire component.

### ISSUE THREAD

**Issue by felipediogo** [testing-library/react-testing-library#503]
- `react-testing-library` version: 9.2.0
- `react` version: 16.8.1
- `node` version: 11.6.0
- `npm` (or `yarn`) version: 6.9.0

### Relevant code or config:

```js
it("should render the component", async () => {
    const { debug, getByTestId } = render(
      <Component
        navigate={() => {}}
        location={{ search: "" }}
        setError={() => {}}
        setException={() => {}}
      />
    );
    await wait();
    debug();
});
```

### What you did:
I'm just testing a component and doing a debug of the component

### What happened:
The debug that was printed was just half of what I was expecting.

![image](https://user-images.githubusercontent.com/26486135/66768071-1eba4e80-ee88-11e9-8b5c-919d77e1738d.png)

### Problem description:
The Debug is not printing the entire component, I think it is probably something related to the terminal.

**Comment by alexkrolick** [comment]
Output is truncated

https://testing-library.com/docs/dom-testing-library/api-helpers#debugging

Set ,DEBUG_PRINT_LIMIT=1000 to increase the limit

**Comment by felipediogo** [comment]
Thanks mate!

**Comment by dnorth** [comment]
Wow it took me so long to realize that my output was getting truncated... I was very confused as to why my component wasn't rendering properly. and now that i've realized it I agree with @eric-burel that this should be an option of `debug()`.

**Comment by danawoodman** [comment]
I would argue that the default should be extremely high (or set to infinity) as setting an env var to increase this is strange and not intuitive. At least an optional param as @eric-burel mentions would be a big step forward.

**Comment by dnorth** [comment]
So as I was looking over this again, I realized that `debug()` is built on top of `prettyDom` and DOES have optional parameters including one for `maxLength`.

So if you do `screen.debug(null, 20000)` then it will print as expected.

**Comment by maciejmyslinski** [comment]
a neat trick is to use `screen.debug(null, Infinity)`.

**Comment by larsenwork** [comment]
FWIW it's `screen.debug(undefined, Infinity)` if you want to use correct types 😄

**Comment by evanjmg** [comment]
still doesn't work in some cases

**Comment by bell-matthew** [comment]
> This work for me:
> 
> `screen.debug(undefined, Infinity, { highlight: false });`
> 
> Note: if I do not put the "highlight: false" it does not print everything and it is cut off
> 
> I took it from this page: https://blog.logrocket.com/using-react-testing-library-debug-method/

Even using this command or the one above it my output is still cutoff. I think it's due to the async nature of my test and the fact that the next line is errorring for not being able to find the element, and the test is failing before the entire output is written? Not sure but I'm getting a ... at the end out my debug output before the error so it must be truncating the output still right?

**Comment by rlassi** [comment]
`--silent` flag on my test script was truncating output as well. Removing it showed complete output.
