### ISSUE TITLE
render: ref callback called twice

### ISSUE THREAD

**Issue by anton6** [testing-library/react-testing-library#504]
- `react-testing-library` version:  9.3.0 (originally noticed this with 5.9.0)

- `react` version: 15.6.2

- `node` version: 8.16.2

- `npm` version: 6.4.1

 

### Relevant code or config:

 

```js

 

// Component

import React from "react";

 

export default class TestComponent extends React.PureComponent {

    callRef = () => {

        console.log("CALL REF")

    }

    render() {

        console.log("RENDER");

        return <div ref={this.callRef} />;

    }

}

 

// Test

import React from 'react';

import { render } from '@testing-library/react';

 

import TestComponent from '../TestComponent';

 

describe('TestComponent', () => {

    test('calls ref twice', () => {

        render(<TestComponent />)

    });

});

 

// Output

console.log src/TestComponent.jsx:8

    RENDER

 

console.log src/TestComponent.jsx:5

    CALL REF

 

console.log src/TestComponent.jsx:5

    CALL REF

 

```

 

### Problem description:

 

I was expecting for RENDER and CALL REF to be printed once. Not sure if it's my setup or issue with react-testing-library? Can some please check if you get the same result?

**Comment by eps1lon** [comment]
This is expected behavior for callback refs. One call is with the actual instance, the next one with `null` to signal cleanup.

> React will call the ref callback with the DOM element when the component mounts, and call it with null when it unmounts.

-- https://reactjs.org/docs/refs-and-the-dom.html#callback-refs
