### ISSUE TITLE
Flexible Prop initialisation function

### ISSUE THREAD

**Issue by hloughrey** [testing-library/react-testing-library#506]
### Describe the feature you'd like:
A while back i read a blog post by Kent (sorry can't put my hands on the exact blog post) but essentially the post talked about having a simple test setup which made it easy to identify the difference between 2 tests without having to repeat the setup. 

I therefore wrote a function which i've been using through out my project which i thought would be useful to share via a module / ecosystem within the `testing-library` namespace, but was unsure where might be the best place for it to live.

### Suggested implementation:
-- Setup Function

```javascript
function setup<T>(props: T): Function {
    let partialProps = {
        ...props
    };
    return (testProps = {}) => ({
        ...partialProps,
        ...testProps
    });
}
```
-- Usage
```javascript
describe('MyComponent', () => {
    const mockAdd = jest.fn();
    const mockRemove = jest.fn();

    const partialProps = setup<IProps>({
        prop1: 'Foobar',
        prop2: false
        add: mockAdd,
        remove: mockRemove,
    });

    it('should do something when prop2 is false', () => {
        const props = partialProps();
        const { container } = render(<MyComponent {...props} />);
        ...
    });

    it('should do something when prop2 is true', () => {
        const props = partialProps({prop2: true});
        const { container } = render(<MyComponent {...props} />);
        ...
    });
```

### Teachability, Documentation, Adoption, Migration Strategy:

Essentially within your top most `describe` block you setup some props which are going to be your default position. then within each test `it` block you can amend the default position for the scenario under test.

I appreciate that this is just a closure function, but i end up writing this same function in every project & thought it would be useful for the wider community.

**Comment by alexkrolick** [comment]
There are a lot of approaches to this. I tend to do this:

```jsx
render(<MyComponent {...defaults} prop1="something" />);
```

I'd prefer to have people work this out for themselves rather than providing a black box that seems more mysterious than it really is.

**Comment by kentcdodds** [comment]
Thank you for your issue @hloughrey.

I tend to agree with @alexkrolick. If we add an API to this I think we just make more things for people to learn and the problem it solves has simpler solutions. If you feel like having an abstraction for this would be worthwhile for you, then I suggest you include it in your own utility file (eg https://testing-library.com/docs/react-testing-library/setup#custom-render).

Good luck!
