### ISSUE TITLE
@testing-library/react has deps to @types/react: *

### ISSUE THREAD

**Issue by jackyef** [testing-library/react-testing-library#508]
- `react-testing-library` version: 9.3.0

### What you did:

We have a react library written in typescript that has exact devDependency to `@types/react: "16.9.9". `@testing-library/react` is also one of the library devDependencies.

### What happened:

When installing all devDependencies (including bundler and babel stuffs) so we can build our library, we ended up with 2 different `@types/react`, because @testing-library/react has deps to `@types/react: *`, which resolves to a newer version of `@types/react`. 

Because there are 2 different `@types/react`, `tsc` will fail when trying to build our package.

### Suggested solution:

Set `@types/*` packages as `devDependencies` of `@testing-library/react`

**Comment by kentcdodds** [comment]
Hi @jackyef,

Thanks for the issue. React Testing Library does not include `@types/react` in the `package.json` at all. I don't think that this package is the culprit to your problems. Good luck!

**Comment by jackyef** [comment]
@kentcdodds Hi, you're right, I was incorrect in saying it was one of `@testing-library/react` deps, it was actually one of the transitive dependencies!

It goes like this:
1. `@testing-library/react` has deps to `@types/testing-library__react`
2. `@types/testing-library__react` has deps to `@types/react-dom`,
3. `@types/react-dom` has deps to `@types/react`

Would there be a problem if we make `@types/testing-library__react` as a `devDependencies` instead of `dependencies` of `@testing-library/react`?

**Comment by kentcdodds** [comment]
Including them as dependencies is an intentional choice (read more: https://github.com/testing-library/react-testing-library/pull/437).

Is there a reason you're not using the latest version of the react types? I think you probably should...

**Comment by jackyef** [comment]
Ah, I see! For my specific case, yes, it would be totally fine to just use the latest version of `@types/react`. 

For what it's worth, some people might be using an older version of `react` and therefore use old version `@types/react` to match. The amount of that specific case is probably really small though.

**Comment by eps1lon** [comment]
@jackyef That is a long standing issue with how types are published from DefinitelyTyped. TL;DR: `@types/react: "*"` is a hack for optional peer dependencies. 

Most package managers do support these now so we can revisit this over at DefinitelyTyped. In the meantime I suggest you get familiar with manually editing your lockfile. For `yarn.lock` you can post every entry for `@types/react` here and I can patch it so that you have a single, older version of `@types/react`. For npm I can't help you unfortunately.

**Comment by jackyef** [comment]
We have fixed this issue on our end. My reason for continuing the discussion here is mostly just to satisfy my curiosity 😃

I'll be looking forward to hear the updates over at DefinitelyTyped then, thanks!
