### ISSUE TITLE
"cleanup" relies on module state

### ISSUE THREAD

**Issue by alexkrolick** [testing-library/react-testing-library#511]
Because the cleanup relies on a closure around a variable set inside the module, it doesn't work if you reset the module state between tests.

Encountered this when looking at https://github.com/reach/reach-ui/pull/331#issuecomment-546487439

Can anyone think of a workaround?

**Comment by alexkrolick** [comment]
I guess it's not really a bug, more of an enhancement if there was a way to support it statelessly.

Here's the workaround:

```
  beforeEach(() => {
    ({ default: Whatever, } = require('.')); // thing to test
    ({ cleanup, render, fireEvent, act } = require("@testing-library/react"));
  });

  afterEach(() => {
    cleanup();
  })
```

**Comment by eps1lon** [comment]
Why do you need to reset the module state and why cant this be done after cleanup()?

**Comment by alexkrolick** [comment]
If:
1. you have a module that depends on a module with module state (eg a counter, see linked PR),
2. And that module uses hooks,
3. And you want to reset the stateful module between test,

Then:
1. You need to call jest.resetModules() or use the resetModules config option
2. You also have to re-require RTL at the same time to get the React/ReactDOM instances to match the other module

**Comment by eps1lon** [comment]
> You also have to re-require RTL at the same time to get the React/ReactDOM instances to match the other module

That was my question. Why reset RTL specificially. 

Leaves why you can't call cleanup before that?

**Comment by alexkrolick** [comment]
cleanup only cleans up nodes it thinks it created, so beforeEach doesn't work, and afterEaxh

**Comment by eps1lon** [comment]
Yeah I don't think I understand what the issue is. Did you expect it to magically keep cleaning up if the module is reset? That would defeat the purpose of resetting the module. If you want to reset modules then you need to call their respective cleanup/teardown logic.

I would agree that we're missing documentation for this describing that if you import/require it in a test hook (e.g. beforeEach) then you need to call cleanup manually (since nested hooks wont't work). Otherwise 

```jsx
let cleanup, render, App, React;
beforeEach(() => {
  React = require("react");
  ({ default: App } = require("./App"));
  ({ cleanup, render } = require("@testing-library/react"));
});

afterEach(() => {
  cleanup();
});
```
seems to work fine.

**Comment by alexkrolick** [comment]
> If you want to reset modules then you need to call their respective cleanup/teardown logic.

True, let's just document this. It's not always obvious that a module has teardown logic particularly when it happens automatically.
