### ISSUE TITLE
fireEvent.click doesn't work with checkbox in default jest jsdom environment

### ISSUE THREAD

**Issue by trurl-master** [testing-library/react-testing-library#517]
- `react-testing-library` version: 9.3.0
- `react` version: tried 16.8.6 to 16.11.0 
- `node` version: tried 10 to 11
- `npm` version: 6.10.3

### Relevant code or config:

Component:
```js
import React, { useState } from "react";

export default () => {
  const [isChecked, setIsChecked] = useState(false);

  const toggleIsChecked = () => setIsChecked(!isChecked);

  return (
    <label data-testid="checkbox">
      <input type="checkbox" checked={isChecked} onChange={toggleIsChecked} />
      <div>label text</div>
    </label>
  );
};
```

Test:
```js
import React from "react";
import { render, fireEvent } from "@testing-library/react";
import CheckboxWithLabel from "./CheckboxWithLabel";

const CHECKBOX = "checkbox";
const LABEL = "label text";

it("works when clicked on the text", () => {
  const { getByText, getByTestId } = render(<CheckboxWithLabel />);

  fireEvent.click(getByText(LABEL));

  // fails
  expect(getByTestId(CHECKBOX).querySelector("input").checked).toBe(true);
});

```

### What you did:
I used `fireEvent.click` on a div inside a label, it should have checked the checkbox

### What happened:
It didn't (in tests)

### Reproduction:
It's not possible to use the template repo nor codesandbox as they both use non-default jest jsdom environment.

Here's the repo with a minimal example:
https://github.com/trurl-master/rtl-onchange-test

### Problem description:
Trying to test a controlled checkbox I found out that it doesn't change it's state when is being tested inside the default jest jsdom environment (and `fireEvent.click` is applied to a div inside a label). Both template repo and codesandbox use `react-scripts` which use `jest-environment-jsdom-fourteen` instead of the default and it works fine there. The issue also was mentioned here: https://github.com/testing-library/react-testing-library/issues/359#issuecomment-486974422

It also works fine when `fireEvent.click` is applied to the label itself.

### Suggested solution:
If it's not a bug, I think it would be very helpful to other users to mention in the readme that `jest-environment-jsdom-fourteen` is a requirement.

**Comment by kentcdodds** [comment]
I'm sure we'd be happy to have a PR to the docs to recommend using `jest-environment-jsdom-fifteen` so people get the latest version of jsdom which fixes bugs like this.

Really can't wait until Jest upgrades jsdom. That will be a glorious day. Should happen in a month or two.

**Comment by trurl-master** [comment]
@kentcdodds good enough?

**Comment by kentcdodds** [comment]
Yep. Thanks!
