### ISSUE TITLE
Cleanup doesn't seem to be working (cra + jest + react-router-dom + use-react-router)

### ISSUE THREAD

**Issue by cardea-fletcher** [testing-library/react-testing-library#518]
- `react-testing-library` version: 9.3.1
- `react` version: 16.8.6
- `node` version: not sure (whaever comes with CodeSandbox & CRA)
- `npm` (or `yarn`) version: not sure (whaever comes with CodeSandbox & CRA)

### Relevant code or config:

CodeSandbox:
https://codesandbox.io/s/focused-worker-wc3j2?fontsize=14

```js
import "@testing-library/jest-dom/extend-expect";
import React from "react";
import { render, fireEvent, cleanup } from "@testing-library/react";
import { App } from "../app.jsx";

beforeEach(() => {
  // jest.resetModules();
  // cleanup();
});

// this first test passes
it("loads home page", async () => {
  const { getByText } = render(<App />);

  expect(getByText("page 1")).toBeInTheDocument();

  const expectedPath = "/";
  const path = global.window.location.pathname;
  expect(path).toEqual(expectedPath);
});

// comment this test out to have the 3rd test pass
it("clicking on 'page 1' button sends user to /page1", async () => {
  const { getByText } = render(<App />);

  const clickedElement = getByText("page 1");
  fireEvent.click(clickedElement);

  const expectedPath = "/page1";
  const path = global.window.location.pathname;
  expect(path).toEqual(expectedPath);
});

// duplicate of first test
// fails if 2nd test is left in
// passes if 2nd test is commented out
it("loads home page again", async () => {
  const { getByText } = render(<App />);

  expect(getByText("page 1")).toBeInTheDocument();

  const expectedPath = "/";
  const path = global.window.location.pathname;
  expect(path).toEqual(expectedPath);
});

```

### What you did:

Trying to test the broad functionality of a starting page in an app. Two independent tests to test 2 different buttons.

- In one test the user clicks on one button (on the home page), and I check that the URL has changed, and that the correct new component has loaded.

- In the next test the user clicks on a different button (on the home page), and I check that the URL has changed, and that the correct new component has loaded.

### What happened:

In the 2nd test, the rendered component is still the one that rendered after clicking on the button from the 1st test. However I would expect that if the entire app has re-rendered, it would start from the same initial starting point. Please check out the CodeSandbox for a very minimal reproduction of the behavior.

EDIT: Also, a note:
I am getting the following error when trying to call:
```
const { getByText } = render(<App />);
```
More than once. I am not sure whether this is a CodeSandbox issue or whether this is a clue to the overall problem.

The error:
`Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.`

### Reproduction:

CodeSandbox:
https://codesandbox.io/s/focused-worker-wc3j2?fontsize=14

### Problem description:

I would expect that if the entire app has re-rendered, it would start from the same initial starting point. Cleanup does not seem to be working. I read in the docs that it happens automatically if we're using Jest, but even if I call it using `beforeEach` it does nothing.

### Suggested solution:

I tried:

```
beforeEach(() => {
  jest.resetModules();
  cleanup();
});
```

To no avail.

I suspect that it has to do with one of the following:
- async issue with not enough time for the new app to render?
- `cleanup()` or `jest.resetModules()` has no effect on:
  -  the `use-react-router` hook
  -  or the `react-router-dom`??
- EDIT: it could have something to do with the error (see above): `Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.`

I suspect this behavior may be working-as-intended, without me realizing the proper implementation of this library. And that the problem actually lies outside of RTL. I hope to learn whether this is the case with this post.

Thanks in advance, and apologies if this is in the wrong spot.

EDIT: I discovered this recipe for using [`RTL` with `react-router`](https://testing-library.com/docs/example-react-router), and I now believe the problem lies with the setting and resetting of the history object of react-router.

UPDATE:
After following the information in the [react-router testing docs](https://reacttraining.com/react-router/web/guides/testing) I now realize how to test with a router, at least a little better than before.

Hidden in the docs is the following:

`You can also use BrowserRouter if your test environment has the browser globals window.location and window.history (which is the default in Jest through JSDOM, **but you cannot reset the history between tests**).`

**Comment by alexkrolick** [comment]
I believe this is similar to #511 and the linked PR in Reach UI. `resetModules` depends on module state that tracks the created nodes. See the workaround in the Reach UI PR. Also, if your app doesn't need modules to be reset you can avoid this by not using resetModules at all.

**Comment by eps1lon** [comment]
Closing this since it is a documented limitation of BrowserRouter

> You can also use BrowserRouter if your test environment has the browser globals window.location and window.history (which is the default in Jest through JSDOM, **but you cannot reset the history between tests**).

-- https://reacttraining.com/react-router/web/guides/testing

**Comment by DercilioFontes** [comment]
> Closing this since it is a documented limitation of BrowserRouter
> 
> > You can also use BrowserRouter if your test environment has the browser globals window.location and window.history (which is the default in Jest through JSDOM, **but you cannot reset the history between tests**).
> 
> -- https://reacttraining.com/react-router/web/guides/testing

Link Not Found anymore. Do you guys know any other references?

**Comment by MatanBobi** [comment]
> > -- https://reacttraining.com/react-router/web/guides/testing
> 
> Link Not Found anymore. Do you guys know any other references?

@DercilioFontes You're looking for this one:
https://v5.reactrouter.com/web/guides/testing

Keep in mind that this is a react-router v5 page :)

**Comment by DercilioFontes** [comment]
Thanks, @MatanBobi

**Comment by DercilioFontes** [comment]
It solved the History reset with what follows in the `setuTests.ts` file.

```typescript
beforeEach(() => {
  window.history.pushState({}, '', '/');
});
```

**Comment by Lauro235** [comment]
@DercilioFontes brilliant. Thank you!
