### ISSUE TITLE
FireEvent not working locally

### ISSUE THREAD

**Issue by Ex4l** [testing-library/react-testing-library#524]
Hello everybody ! Thank you for your amazing work on that library.

I'm having a few problems with the fireEvent feature locally.

I got a simple component displaying conditionally from a prop and the onChange event is not triggering locally.

i made a sandbox that you can find here : https://codesandbox.io/s/competent-moore-61pul

It's working perfectly in the sandbox but not locally (handleOnChange is not called) on my mac in vscode.

It seems to be related to #487 but i'm not sure.

I've got another test not working with an input file and a onChange on it that is not triggered locally either but i don't have a sandbox about it.

**Comment by kentcdodds** [comment]
Hi @Ex4l,

The data-testid you are passing is being applied to a span, and you're firing a click event on the span, but you want to fire the click event on the `input`. So I suggest you use `getByLabelText` instead: https://codesandbox.io/s/ecstatic-fog-0rr34

If you have further questions, please ask on https://spectrum.chat/testing-library/help-react. Good luck!

**Comment by Ex4l** [comment]
Thank you very much for your answer Kent.
