### ISSUE TITLE
TypeError container.queryselectorall is not a function

### ISSUE THREAD

**Issue by kushalmahajan** [testing-library/react-testing-library#526]
```
 "react": "^16.9.0",
 "@testing-library/jest-dom": "^4.1.2",
 "@testing-library/react": "^9.2.0",
```

### Relevant code or config:

```js
 test("toggles", () => {
        const { getByTestId } = render(
            <Collapse data-testid="collapse" activeKey={2}>
                <Panel panelKey={1} header="Panel Header 1">
                    Some content
                </Panel>
                <Panel panelKey={2} header="Panel Header 2">
                    Some content
                </Panel>
                <Panel panelKey={3} header="Panel Header 3" disabled>
                    Some content
                </Panel>
            </Collapse>
        );
    });
```

### What I did

```
const node = getByTestId("collapse");
console.log(node);
```
### Problem description:

Ok, `data-testid` is not working here as expected.  It throws error below 

> collapse › encountered a declaration exception
TypeError: container.querySelectorAll is not a function

Here is my collapse implementation

```
export const Collapse = ({
	activeKey = 1,
	accordion,
	onChange,
	expandIconPosition,
	children,
	...rest
}: CollapseProps) => {
	const [key, setKey] = React.useState(activeKey);

	const closeOtherPanels = (key: string | number) => {
		setKey(key);
	};

	return (
		<CollapseContext.Provider
			value={{
				key,
				accordion,
				closeOtherPanels,
				onChange,
				expandIconPosition
			}}
		>
			<CollapseWrap {...rest}>{children}</CollapseWrap>
		</CollapseContext.Provider>
	);
};
```

**Comment by alexkrolick** [comment]
Are you running this with a JSDOM environment, like the one from Jest?

**Comment by kushalmahajan** [comment]
I didn't quite follow your comment

**Comment by kentcdodds** [comment]
Hi @kushalmahajan,

What is the implementation of `CollapseWrap`? If you could create a reproduction on codesandbox and post it to https://spectrum.chat/testing-library/help-react that would be helpful.

This is unlikely an issue with the library, so I'll close this here and ask you to take it over there. Thanks!

**Comment by kushalmahajan** [comment]
Hi @kentcdodds ,

Collapse Wrap is just a styled component - `div`.

> This is unlikely an issue with the library, so I'll close this here and ask you to take it over there

Can we close this here when we at least find a reason? Do you should post such a lengthy question would fetch an answer on spectrum chat. 

Plus, I feel there is a gap somewhere to achieve what I'm trying to do. It sure works for my other components.

Let me know if you still need sandbox link. Or you may copy-paste my code in an existing sandbox of yours. I just have to create everything from scratch otherwise.

**Comment by intelligentspark** [comment]
I can confirm this using your testing-javascript course code. As soon as you get to branch cypress-04, this error appears with Chrome 79 and Electron 78. @kentcdodds ... Help!

**Comment by kentcdodds** [comment]
Hi Fred, could you open a new issue on [Cypress Testing Library](https://github.com/testing-library/cypress-testing-library/issues/new) please? And if you could screenshot the error you're seeing that would also be helpful. Thank you.

**Comment by intelligentspark** [comment]
Thanks @kentcdodds! here: [https://github.com/testing-library/cypress-testing-library/issues/109] (https://github.com/testing-library/cypress-testing-library/issues/109)

**Comment by kentcdodds** [comment]
Thank you!

**Comment by kushalmahajan** [comment]
@kentcdodds I did edit for a Collapse implementation earlier. Any thoughts?

**Comment by kentcdodds** [comment]
Sorry @kushalmahajan, that still doesn't give me enough information to diagnose the issue. Please follow the instructions in https://kcd.im/rtl-help to solve this issue.

**Comment by goepi** [comment]
[Here](https://codesandbox.io/s/serene-browser-iqcfe) is a codesandbox with this error.

**Comment by kentcdodds** [comment]
Your `getQueriesForElement` call should be `getQueriesForElement(root)` not `getQueriesForElememt("root")`.

Is there a reason you're not using `@testing-library/react` exports of `render` and `screen`? I think you'd have better success with those.
