### ISSUE TITLE
Having Trouble Getting Testing-Library to Pass CI Build (SyntaxError: Unexpected identifier)

### ISSUE THREAD

**Issue by mcastre** [testing-library/react-testing-library#528]
Hello! I could really use some help in figuring out a build error when trying to run npm test in a ci/cd environment (Bamboo) with my create-react-app. Locally, all my tests pass with no issue, yet when i push a build to the CI, it fails all the tests with the same js error (See Relevant code or config snippet).

I was wondering if anyone has encountered this particular error before and has a solution. I don't believe its specific to our CI build but probably a configuration issue on my end. It seems like babel isnt transpiling the setupTests.js file, which is causing the unexpected identifier error. I verified that the NODE_ENV is 'test' when the CI build runs. Im at a loss so any help would be greatly appreciated!! Thank you!

- `react-testing-library` version: 8.0.4
- `react` version: 16.8.6
- `node` version: 10.14.2
- `npm` (or `yarn`) version: 6.4.1

### Relevant code or config:

```js
Test suite failed to run

    /u01/bamboo_home/xml-data/build-dir/ROCO-OF3310-BFE/node_modules/@testing-library/react/dist/index.js:48
      asyncWrapper: async cb => {
                          ^^
    SyntaxError: Unexpected identifier

       5 |  *
       6 |  */
    >  7 | import { cleanup, configure as configureTestingLibrary } from '@testing-library/react';
         | ^
       8 | import 'custom-event-polyfill';
       9 | import '@babel/polyfill';
      10 |

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (src/setupTests.js:7:1)

```

### What you did:
Running basic npm test in a CI build environment fails all tests with a js compilation error, but passes normally in a local environment.

### What happened:

Error is happening in my setupTests.js file...
(just ignore the references to enzyme)
```
/* eslint-disable import/no-extraneous-dependencies */
/**
 *
 * The utility script for setting up Jest
 *
 */
import 'custom-event-polyfill';
import '@babel/polyfill';

/* enzyme */
import { configure, shallow, mount, render } from 'enzyme';
import { toMatchSnapshot } from 'jest-snapshot';
import { cleanup, configure as configureTestingLibrary } from '@testing-library/react';

/* enzyme-to-json */
import { createSerializer } from 'enzyme-to-json';

import Adapter from 'enzyme-adapter-react-16';

/* emotion */
import * as emotion from 'emotion';

/* jest-emotion */
import { createMatchers } from 'jest-emotion';
import 'jest-dom/extend-expect';

configureTestingLibrary({ testIdAttribute: 'data-test-id' });

/* configure enzyme to grab the adaptor for react */
configure({ adapter: new Adapter() });

/* expose enzyme methods globally */
global.shallow = shallow;
global.mount = mount;
global.render = render;

/* substitute the assertion with additional serializers and matchers */
expect.addSnapshotSerializer(createSerializer({ mode: 'deep' }));
expect.extend(createMatchers(emotion));

/* Our custom serializer that strips out the unique portion of the component ID */
expect.extend({
  toMatchIdTrimmedSnapshot(received) {
    const numeralRegex = /_\d{8}/g;
    return toMatchSnapshot.call(
      this,
      String(received.html().replace(numeralRegex, '')),
      'toMatchIdTrimmedSnapshot'
    );
  }
});

/* Not sure if this is really needed, but it dismissed an error associated to window.scrollTo */
window.scrollTo = () => {};

// this is just a little hack to silence a warning that we'll get until react
// fixes this: https://github.com/facebook/react/pull/14853
const originalError = console.error;
beforeAll(() => {
  console.error = (...args) => {
    if (/Warning.*not wrapped in act/.test(args[0])) {
      return;
    }
    originalError.call(console, ...args);
  };
});

afterAll(() => {
  console.error = originalError;
});

// Cleanup mounted components after each test
afterEach(cleanup);

```

### Reproduction:

Im not sure i can get a repro since it works locally no matter what i do.

**Comment by eps1lon** [comment]
This is best asked on our [spectrum.chat](https://spectrum.chat/testing-library). Seems like you're not transpiling your test which is not caused nor solvable by this library.

**Comment by mcastre** [comment]
Thanks @eps1lon! Ill try on there. I knew it wasnt an issue in the library, i was just hoping someone has encountered it before

**Comment by nvh95** [comment]
@mcastre I just wonder if you resolved this problem in the past. I encountered exactly this problem. My project is bootstrapped by CRA v 1.x and ejected for 3 years ago.
