### ISSUE TITLE
Use GitHub actions instead of Travis CI

### ISSUE THREAD

**Issue by MichaelDeBoey** [testing-library/react-testing-library#530]
GitHub made their Actions (CI) public, so I think it would be nice to use it in the repos instead of Travis CI.

https://github.com/features/actions

**Comment by eps1lon** [comment]
What issues would this solve for us?

**Comment by MichaelDeBoey** [comment]
It's just a more integrated way of doing CI, where you can just stay on GitHub to watch what happened instead of needing to go to Travis.

**Comment by eps1lon** [comment]
I think I'd rather click one more time occasionally than migrate CI. That's usually not a trivial task. So feel free to work on this.  But unless someone can demonstrate some issues with the current CI I don't see the necessity to put time into this.

It's a bit confusing to me that all the argument you can make is about having to navigate. I've seen several opened issues from you on various repositories I work on so I would've expected more arguments if you're so enthusiastic about github actions or codesandbox ci or github sponsors.

**Comment by MichaelDeBoey** [comment]
Doh! 😓
I forgot to update my previous comment with the following:

> Numbers from the [GitHub Universe 2019 keynote](https://www.youtube.com/watch?v=9EoNqyxtSRM) also see a massive time improvement ([Pinterest had their pipeline down from 80mins to 10mins](https://youtu.be/9EoNqyxtSRM?t=640)) when using GitHub Actions instead.

**Comment by eps1lon** [comment]
I'm sorry this is the kind of situation I shouldn't argue but I will not platform these statements unquestioned:

>Numbers from the GitHub Universe 2019 keynote also see a massive time improvement (Pinterest had their pipeline down from 80 to 10 mins) when using GitHub Actions instead.

Pinterest moved from a single pipeline in BuildKite to 8 pipelines on github actions (https://github.com/TextureGroup/Texture/pull/1623) which incidentally accounts exactly for 7/8 time reduction. This is advertisement for parallel pipelines not github actions.

**Comment by alexkrolick** [comment]
I'd prefer not to go all-in on GitHub infrastructure at this time.

**Comment by kentcdodds** [comment]
I agree. It's too early. Let's hold off.
