### ISSUE TITLE
Jest timeout error when using `wait` or `waitForElement` in RTL along with `fast-check`

### ISSUE THREAD

**Issue by kai-ming-91** [testing-library/react-testing-library#534]
- `react-testing-library` version: 9.3.2
- `react` version: 16.11.0
- `fast-check` version: 1.18.1
- `ts-loader` version: 6.2.1
- `typescript` version: 3.7.2
- `ts-jest` version: 24.1.0
- `node` version: 10.16.0
- `npm` (or `yarn`) version: 1.16.0

### Relevant code or config:

```js
import * as React from "react";
import * as fc from "fast-check";
import {render, wait, cleanup} from "@testing-library/react";

const Title = (props: { titles: string[] }) => {
    return <>
        {props.titles.map((t, i) => (<div key={i}>{t}</div>))}
    </>
}

describe("RTL", () => {

    it("should run test without timeout (but it timeout)", async () => {
        await fc.assert(
            fc.asyncProperty(fc.array(fc.lorem(), 0, 10), async (titles) => {
                const {findByText} = render(<Title titles={titles}/>)

                for (const t in titles) {
                    const el = await findByText(t)
                    await expect(el).resolves.toBeDefined()
                }
            }).afterEach(async () => cleanup())
        )
    })

})
```

### What you did:

I'm doing property base testing (via fast-check) along with RTL and Jest. `fast-check` by default will run the test 100 times with different variation of data. And the timeout will happen, especially when there's a call to `wait` or `waitForElement`. 

### What happened:

Jest will timeout waiting for promise to be resolved/rejected.

![image](https://user-images.githubusercontent.com/2922397/69043317-cf8aaf00-0a2d-11ea-952d-713ea182b056.png)

### Reproduction:

I've created the repo to replicate the problem: https://github.com/kai-ming-91/fast-check-with-rtl

### Problem description:

The timeout problem cause a flaky test, and timeout error doesn't provide meaningful insight on why the test is failing. Doesn't help in debugging. 

### Suggested solution:

Currently I don't have any. I can try to help up, if someone can guide me to debug to the library level. I've read the code, but not too familiar in how is to debug node library (I'm jvm based developer).

**Comment by kentcdodds** [comment]
I'm afraid there's not much we can do here. Those tests just take a long time to run by their nature. But you can use `jest.setTimeout` to increase the test timeout limit: https://jestjs.io/docs/en/jest-object#jestsettimeouttimeout

Good luck!

**Comment by husni1992** [comment]
> I'm afraid there's not much we can do here. Those tests just take a long time to run by their nature. But you can use `jest.setTimeout` to increase the test timeout limit: https://jestjs.io/docs/en/jest-object#jestsettimeouttimeout
> 
> Good luck!

I faced the same scenario. I had increased `jest.setTimeout` to 30000. It works fine when only that file runs. But when the entire tests run in the app, it throws `Async callback was not invoked within the 30000ms timeout`. Any specific solution for this, maybe remove timout only for the specific test?

**Comment by kai-ming-91** [comment]
Hi @husni1992,

>  maybe remove timout only for the specific test?

Timeout is needed, to avoid a test to hang and not running at all.

> But when the entire tests run in the app

For my case, it's really because of the test take quite some time to run, especially on `fast-check` generating test data. 

Sometimes when you run entire tests, it took up CPU/RAM resources, which indirectly causes some test to take longer time to run. 

So you will need to drill down which part of your test is slow. Maybe you can try do a manual benchmark, eg (collect and log the time taken to reach certain section of test code), and see which section of your test code is taking too long.
