### ISSUE TITLE
Export `flushMicroTasks` function

### ISSUE THREAD

**Issue by aleclarson** [testing-library/react-testing-library#542]
### Describe the feature you'd like:

The `flushMicroTasks` function should be exported by RTL.

### Describe alternatives you've considered:

The workaround I'm using currently (but no TypeScript support 😢):
```ts
import flushMicroTasks from '@testing-library/react/dist/flush-microtasks'
```

**Comment by kentcdodds** [comment]
Hi @aleclarson,

I'm curious what your use case for this is? Our implementation is basically copy/pasted from React. If you have a use case for it, maybe we should ask if React itself could export theirs and we can use theirs as well.

**Comment by kentcdodds** [comment]
cc @threepointone

**Comment by threepointone** [comment]
Use act()?

**Comment by aleclarson** [comment]
> I'm curious what your use case for this is?

For testing code that (often indirectly) uses the microtask queue as an update queue.

> Use act()?

`act` flushes the microtask queue? It doesn't let me `await` its return value.

Anyway, I'm gonna copy `flushMicroTasks` into my own helper library, since I'm not always testing components when I use it.

**Comment by threepointone** [comment]
You sure can await the return value, if you pass an async function. 

await act(async ()=> {...})
