### ISSUE TITLE
onChange do not trigger by fireEvent.change in Mocha environment

### ISSUE THREAD

**Issue by whodoeshua** [testing-library/react-testing-library#544]
As title, the change event in the component will not trigger by the fireevent. I look at some similar question, mostly is testing by jest. But my company build our test environment by mocha. This is a question.

It also not the type problem, I try to set the type to 'text' explicit, it still not work.

Could you please hlep to fix the problem? Thank very much.

- `react-testing-library` version: `9.3.2`
- `react` version:  `16.3.2`
- `node` version: `12.13.0`
- `yarn` version: `1.17.3`
- `mocha` version: `5.2.0`
- `jsdom` version: `15.2.1`
- `jsdom-global` version: `3.0.2`

### Relevant code or config:

```js
  it('test', () => {
      const onChange = spy();
      const { container } = render(<input type='text' onChange={onChange}></input>);
      const input = container.querySelector('input') as HTMLInputElement;
      const changeObj = { target: { value: 'new value' } };
      fireEvent.change(input, changeObj);
      // tslint:disable-next-line: no-console
      console.log('input: ', onChange.callCount); // 0
    });
```

### What happened:

The spy function never be called. 
![image](https://user-images.githubusercontent.com/8555485/70313573-d77d8800-1850-11ea-884f-6eb600140c58.png)

**Comment by kentcdodds** [comment]
Hi @whodoeshua,

Could you please make a reproduction repository so we can investigate this further? Thanks!

**Comment by whodoeshua** [comment]
Hi @kentcdodds ,

I try to make a reproduction repository in [codesanbox](https://codesandbox.io/s/affectionate-dubinsky-4f898?fontsize=14&hidenavigation=1&theme=dark), but it work.

The result that running for the same code is not same between sandbox and local, I'm not sure where the problem is.

Test result in the local as below:
```
Testing for Input Component                              
  1. Testing for Input component                         
    test:                                                
                                                         
 AssertionError: expected 0 to equal 1                   
 + expected - actual                                     
                                                         
 -0                                                      
 +1                                                      
                                                         
 at Context.<anonymous> (test/unit/test-input.tsx:139:40)
 at processImmediate (internal/timers.js:439:21)         
```

The console result in the local is 
```
change called count:  0 ; input value: new value
      2) test
```

By the way, I use `jsdom-global` to clean up the component for every test unit, Is there any effect for the testing result? 
```
import jsdom from 'jsdom-global';
import { render, cleanup, fireEvent } from '@testing-library/react';

jsdom();

describe('Testing', () => {
  before(() => {
    // @ts-ignore
    global.cleanup = jsdom();
  });
  after(() => {
    // @ts-ignore
    global.cleanup();
  });
  afterEach(cleanup);

// ... test unit
});
```

**Comment by kentcdodds** [comment]
The codesandbox is using jest. Could you please make a github repo with only the dependencies needed to reproduce this issue?

**Comment by whodoeshua** [comment]
https://github.com/whodoeshua/mocha-react-testing-library

**Comment by rvdkooy** [comment]
The jsdom-global package has a section for setting up mocha tests:
https://github.com/rstacruz/jsdom-global#mocha

Your test is working again if I change your package.json script according to the docs:
```
"test": "tsc --pretty && mocha --exit --trace-warnings -r jsdom-global/register -r source-map-support/register -c \"build/**/@(skip|test)-*.js\""
```

R

**Comment by whodoeshua** [comment]
It's work!

Or initalization jsdom environment before import `react-testing-library`; as below:

```
// work
import jsdom from 'jsdom-global';
jsdom(); // Same effect with import `jsdom-global/register `;
import { ... } from 'react-testing-library';

// not work
import jsdom from 'jsdom';
import { ... } from 'react-testing-library';
jsdom();
```

I think it cloud be a enhancement that make every one to use it easier? or create a tips to let other know there has a limiting condition in somewhere like `FAQ`? @kentcdodds 

Thanks for your great help! @kentcdodds @rvdkooy
