### ISSUE TITLE
Cannot avoid "Warning: You seem to have overlapping act() calls" in tests

### ISSUE THREAD

**Issue by nickform** [testing-library/react-testing-library#545]
- `react-testing-library` version: 9.3.2
- `react` version: 16.11.0
- `node` version: 12.8.0
- `npm` version: 6.13.0

### Relevant code or config:

[See reproduction below]

### What you did:

Upgraded from 8.0.1 to 9.3.2.

### What happened:

Several pre-existing tests began to emit the following warning:

`console.error node_modules/@testing-library/react/dist/act-compat.js:52`
`Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one.`

The tests in question ensure that the user is shown a cancel button during the lifetime of an async API call and prove that the cancel button safely cancels the API call and transitions the component into the correct next state, etc.

### Reproduction:

https://codesandbox.io/s/sweet-clarke-kq299?fontsize=14&hidenavigation=1&theme=dark

To see the warning messages, make sure to switch to the tests pane and then switch to the console pane at the bottom right.

### Problem description:

I have been unable to find a way of avoiding the warning whilst still covering the code I was trying to test. I asked for help on [StackOverflow](https://stackoverflow.com/questions/58918780/how-should-i-test-functionality-accessible-only-during-the-lifetime-of-an-async) and [Spectrum](https://spectrum.chat/testing-library/help-react/testing-transiently-accessible-functionality~90b580c7-cbcf-44f6-89dc-5e5afc237f64) but have received no answers to either unfortunately. I am aware that react hooks are quickly becoming the more popular way of writing components which display asynchronously-fetched content but 1) I have read several reassurances that there are no plans to withdraw support for classes from React and 2) it's not clear that adopting react hooks would solve the problem (I have not tried).

### Suggested solution:

Apologies - I've tried to spend the time I have available creating a good problem description and reproduction which I hope will be useful to someone who understands the internals of the react testing library.

**Comment by kentcdodds** [comment]
Hi @nickform!

Here's the way I would write this test:

https://codesandbox.io/s/agitated-babbage-w1bkz

I'm not entirely sure why yours isn't working to be honest. I don't have time to dig in and figure it out though. Sorry 😬

Good luck!

**Comment by nickform** [comment]
Thanks @kentcdodds for reviewing this at least and providing an alternative pattern to try. I will try it out on the more complicated tests that check the cancel button's click handler as well and update various posts I've made once I know the result.

**Comment by nickform** [comment]
Just wanted to circle back for any future visitors to this thread who run into the same problem after having applied @kentcdodds suggested approach. My conclusion: it works. I no longer have the warning messages but my tests do still fail if I deliberately try to break them. I have no evidence of flakiness in the tests which is what prompted me to use the overcomplicated testing approach I had earlier. Thanks again.
