### ISSUE TITLE
document.queryCommandSupported()  is not a function

### ISSUE THREAD

**Issue by rehan-sattar** [testing-library/react-testing-library#546]
- `react-testing-library` version: 9.3.2
- `react` version: 16.7.0
- `node` version: 12.11.0
- `npm` (or `yarn`) version: 6.11.3

### Relevant code or config:

```js
document.queryCommandSupported('copy')
```
### Problem description:
I'm  writing test cases for my feature and this line is just a part of that feature. Everything works perfectly except this line.  Every time I'm getting this error at this line, I'm not sure weather it's supported or not by the testing environment.

**Comment by eps1lon** [comment]
Issues is tracked in jsdom: https://github.com/jsdom/jsdom/issues/1742
