### ISSUE TITLE
Could we please have a detailed changelog file

### ISSUE THREAD

**Issue by emilysas** [testing-library/react-testing-library#549]
Changelog files are really valuable when updating packages as it makes it clear what the breaking changes are etc, could you please add details to yours beyond a link to the semver?

**Comment by kentcdodds** [comment]
Hi @emilysas,

The changelog file also links to [the releases page](https://github.com/testing-library/react-testing-library/releases) which is where the changelog is.

I agree! A changelog is important! I have the file there so people know where to find it.
