### ISSUE TITLE
Document/implement matchers with `getAll`

### ISSUE THREAD

**Issue by C0DK** [testing-library/react-testing-library#550]
### Describe the feature you'd like:

Examples using the `getAll` queries.

As all the matchers work on a singular element, not arrays, i don't really know how to use the `getAll` queries, and in my current case i'd really love to use something like:

```javascript
       expect(getAllByRole("figure")).some(tag =>
                expect(tag).toHaveTextContent(data.current_balance)
            )

```
But i'm not sure how, or even if it's possible, to do this.

**Comment by kentcdodds** [comment]
Could you present an actual use case and we can help you know how to use the `*All*` queries effectively for that use case.

Granted, I don't personally use `*All*` queries very often.

**Comment by alexkrolick** [comment]
The most common use case for "all" from what I've seen is counting or iterating over a list:

```js
const menuOptions = getAllByTestId(/menu-options-/)
expect(menuOptions).toHaveLength(3)
expect(menuOptions[0]).toHaveTextContent(/share/)
expect(menuOptions[1]).toHaveTextContent(/delete/)
expect(menuOptions[2]).toHaveTextContent(/archive/)
```

**Comment by gnapse** [comment]
Related: testing-library/jest-dom#174 (also reported by @C0DK).

**Comment by alexkrolick** [comment]
I could imagine adding asymmetric matchers so you could pass in an array of them to .arrayContaining or .toContain:

```js
expect(getAllByRole("figure"))
  .toContain(expect.elementWithClass("xyz"))

expect(getAllByLabelText("close"))
  .toEqual(expect.arrayContaining([
    expect.elementWithRole("button"),
    expect.elementWithClass("active"),
  ])
```

Not sure how to implement it, I am guessing the functions return an object with a custom .toEqual method

**Comment by C0DK** [comment]
> Related: [testing-library/jest-dom#174](https://github.com/testing-library/jest-dom/issues/174) (also reported by @C0DK).

Yep I didn't know whether it was a problem with you or them.. or both.. In their case, i found a lacking documentation, whereas with you i missed some matchers.. i guess.

Mainly i would expect it to have some functional matchers for the quite generic `forAll` and `forAny` logical questions. 

I could naturally do it with a for-loop


> ```js
> // add the assertion count if it is possible for iteration to skip a desired assertion
> expect.assertions(3)
> const figures = getAllByRole("figure")
> for (const figure of figures) {
>   expect(figure).toHaveTextContent(data.current_balance)
> }
> ```

as mentioned here. I did not think of that. I think i expected a functional interface, but this is naturally as strong, computationally. 

Right now i have a dashboard, and i want to validate that atleast one of the figures contains information about each data-point.

**Comment by szabototo89** [comment]
You can solve it by using the following code snippet: 
```js
expect(getAllByRole("figure")).toEqual(
  expect.arrayContaining(
    getByText(data.current_balance)
  )
);
```

**Comment by kentcdodds** [comment]
Hi friends,

I don't think we're going to do this. The workarounds are reasonable enough so we can't justify adding more API for this use case.

Good luck!

**Comment by igreulich** [comment]
Having just found this because I was looking for, like the OP, _examples_ of how to use the getAll queries in the documentation.

I understand the various methods here for using them are fine, or the expected; I also think having examples of them in the documentation would be a good thing.

I don't thing the OP wanted more API, just more API documentation. I do as well.

**Comment by MatanBobi** [comment]
Hi @igreulich, if you feel that there's a need for more examples regarding `getAllBy*`, you can feel free to create a PR, this will be really helpful :)
