### ISSUE TITLE
why not add a query way with classname/id?

### ISSUE THREAD

**Issue by MuYunyun** [testing-library/react-testing-library#555]
There are some query ways provided by `render` api from `@testing-library/react`

![image](https://user-images.githubusercontent.com/19354791/71230966-b9228c80-2326-11ea-9c0d-bf66a218aebc.png)

It seems there is no api called `queryByClassName`、`queryAllByClassName`, `queryById`, is there any reason why not add them? I think the `className` are also help for some situations lack of text、testId、roleId.

**Comment by alexkrolick** [comment]
Because your users can't see classnames

https://testing-library.com/docs/guiding-principles

**Comment by MuYunyun** [comment]
> Because your users can't see classnames
> 
> https://testing-library.com/docs/guiding-principles

By the way, if I want to use queryByTestId/queryByAllTestId, I need add `data-testId` in the element, and the user can't also see the `data-testId`, isn't it? And if so why not use `id` props in element.

**Comment by weyert** [comment]
The idea of test-id is that it's used as last resort and is this way on par with id/class

**Comment by alexkrolick** [comment]
> And if so why not use id/className props

- classnames change as part of the app code, test IDs are supposed to be more independent of the implementation
- using a special attribute is a reminder that the test is using the least semantic query

**Comment by MuYunyun** [comment]
yep, I understand the react-testing-library is based behaviour testing. 

When I test the component now the test way most used are queryAllByText/queryByText, and the second is queryByTextId. Sometimes It's 
inconvenient for me to add extra test-id to element using queryByTextId.(Maybe I ignore some effects of the other query function 😸) So I mention such a question so I may not add extra props to element.

**Comment by eps1lon** [comment]
>  is there any reason why not add them?

Could you include an example where the `id` or `className` would be more appropriate in your opinion?

**Comment by MuYunyun** [comment]
> > And if so why not use id/className props
> 
> * classnames change as part of the app code, test IDs are supposed to be more independent of the implementation
> * using a special attribute is a reminder that the test is using the least semantic query

Thanks, I get.
