### ISSUE TITLE
"screen" export is missing from @types/testing-library__react

### ISSUE THREAD

**Issue by NateRadebaugh** [testing-library/react-testing-library#557]
- `react-testing-library` version: `^9.3.2`
- `react` version: `^16.12.0`
- `node` version: `v10.15.2`
- `npm` (or `yarn`) version: `npm`: `6.4.1`, `yarn`: `1.21.1`

### Relevant code or config:

```js
import {
  screen
} from "@testing-library/react";
```

### What you did:

I'm trying to import `screen` in my `jest` test file (typescript) but hitting compile errors.

### What happened:

![image](https://user-images.githubusercontent.com/130445/71260063-916bfe00-22ff-11ea-97f9-1188f217b2f8.png)

### Reproduction:

Using [tsdx](https://github.com/jaredpalmer/tsdx):

```sh
npx tsdx create mylib
yarn add @testing-library/react
```

Create a `Example.test.tsx` file.

Add the following:
```js
import {
  screen
} from "@testing-library/react";
```

Run: `yarn tsdx test`

### Problem description:

I want to use the new `screen` functionality but am blocked.

### Suggested solution:

I think the `screen` type needs to be exported here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/testing-library__react/index.d.ts

**Comment by NateRadebaugh** [comment]
I resolved this issue locally by manually running "yarn upgrade" which updated the deps in `yarn.lock` to have the correct intermediate dependency versions.

**Comment by lmolema** [comment]
@NateRadebaugh `yarn upgrade` is breaking my app, do you know which package(s) needs to be updated to make this work?

**Comment by NateRadebaugh** [comment]
Not sure, it must have been related to the underlying deps that `@types/testing-library__react` needed... maybe `@types/testing-library__dom` or something similar.
