### ISSUE TITLE
Utility function for creating wrapper components easily 

### ISSUE THREAD

**Issue by szabototo89** [testing-library/react-testing-library#559]
### Describe the feature you'd like:

I'd like to add a simple utility function (`createWrapper`) to create wrapper components easily. See example below:

Instead of this:
```js
function Wrapper({ children }) {
  return <Router history={...}>
     <Provider store={...}>
       {children}
     </Provider>
  </Router>
}

const utils = render(<MyComponent />, { wrapper: Wrapper });
```
`createWrapper` function could replace the code above:
```js
const utils = render(<MyComponent />, { 
  wrapper: createWrapper(<Router history={...} />, <Provider store={...} />)
});
```

**Comment by a-c-sreedhar-reddy** [comment]
Hi kent. :-)

**Comment by codecog** [comment]
I think doing this is fine: https://www.native-testing-library.com/docs/setup#custom-render

Granted it's in `native-testing-library` docs. The concept is more or less the same. Write your custom render once, and then use it as you need to.

**Comment by kentcdodds** [comment]
Hi friends 👋

@codecog, we have the same kind of thing for React DOM as well: https://testing-library.com/docs/react-testing-library/setup#custom-render

That's what I'd recommend, and I don't see much of a reason to add more API to simplify something that I don't think is all that challenging (and actually I think would just convolute the code unnecessarily).

Thanks anyway!
