### ISSUE TITLE
Problem testing modal on button click

### ISSUE THREAD

**Issue by aatifbandey** [testing-library/react-testing-library#565]
I have a log-in button in my component and on that button click I need to write a test case to check if the modal box with data-testid=login is present in the document
**This is my code**

     const {getByTestId} = render(<NonLoggedIn /> );
     const container = document.body;
     fireEvent.click(getByTestId('btnHeaderLogin'));
     await wait(() => {
       const htmlElement = document.querySelector('[data-testid="loginform"]');
       expect(htmlElement).toBeInTheDocument();
     });
     `

Attached screenshot of the error.

<img width="663" alt="Screen Shot 2020-01-03 at 11 52 05 PM" src="https://user-images.githubusercontent.com/12999825/71741779-bdea5300-2e85-11ea-9755-754024a3cc85.png">

Here is the codesandbox link: https://codesandbox.io/s/wizardly-euler-xg7jh

**Comment by bandeyaatif** [comment]
Got the fixed by looking at some examples. 
Closing this

**Comment by aatifbandey** [comment]
Got fix by making use of `awaitElement` & `beforeAll()`

**Comment by lukqw** [comment]
Could you please post your fix?

**Comment by alfonsoperez** [comment]
```
it("test modal opens", async () => {
  screen.getByTestId("myButton").click();
  await waitFor(() => screen.getByTestId("someElemInMyModal"));
 // here I can do screen.getByTestId("someElemInMyModal") again
});
```

**Comment by MatanBobi** [comment]
@Adrian-Benavente the reason for that is that `waitForElement` has been deprecated, you should be using [`waitFor`](https://testing-library.com/docs/dom-testing-library/api-async/#waitfor).

**Comment by jthomas-rsi** [comment]
This was very helpful thank you all for your answers here I was able to get my modal testing suite working 

` it("ButtonDialog opens when title button clicked", async () => {
    render(
      <ButtonDialog
        data={{ id: "", Title: "Open", Desc: "This Dialog is open", List: "" }}
      />,
    );

    const openButton = screen.getByTestId("titleButton");

    fireEvent.click(openButton);

    await waitFor(() => {
      screen.getByTestId("dialogDescription");
    });

    const description = screen.getByTestId("dialogDescription");

    // eslint-disable-next-line testing-library/no-debugging-utils
    // screen.debug();

    expect(description).toBeTruthy();
    expect(description).toHaveTextContent("This Dialog is open");
  });`
