### ISSUE TITLE
Drop Node 8

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/react-testing-library#575]
Because [it's no longer LTS](https://nodejs.org/en/about/releases/).

**Comment by thomasgrz** [comment]
This would be resolved by updating [to >= Node 10](https://github.com/testing-library/react-testing-library/blob/d6fac0584cd06d39123301c8c2ed33ca5425a2f3/package.json#L8), correct? Happy to submit a PR for this as this is a project I use fairly frequently.

**Comment by eps1lon** [comment]
> I assume there may be some security settings on the repo to disallowed it?

You usually set the `origin` to the repo you own and `upstream` to the fork. See https://gist.github.com/Chaser324/ce0505fbed06b947d962 or https://help.github.com/en/github/getting-started-with-github/fork-a-repo.

**Comment by thomasgrz** [comment]
@eps1lon thank you! I believe I properly (?) submitted the PR thanks to your guidance 👍 .
