### ISSUE TITLE
fireEvent - mouseEnter/mouseLeave not working with addEventListener

### ISSUE THREAD

**Issue by greypants** [testing-library/react-testing-library#577]
- `react-testing-library` version: 9.4.0
- `react` version: 16.12.0
- `node` version: 10.16.0
- `npm` (or `yarn`) version: 1.21.1

### Relevant code or config:

```jsx
import React, { useEffect, useState, useRef } from "react";
import { render, fireEvent } from "@testing-library/react";

const HoverMe = () => {
  const ref = useRef();
  const [isMouseEntered, setIsMouseEntered] = useState(false);

  useEffect(() => {
    const setYes = () => setIsMouseEntered(true);
    const button = ref.current;
    // If you change the event to "mouseover"
    // the test passes, even if you don't update the test
    button.addEventListener("mouseenter", setYes);

    return () => {
      button.removeEventListener("mouseenter", setYes);
    };
  });

  return <button ref={ref}>{isMouseEntered ? "yes" : "no"}</button>;
};

describe("mouseenter/mouseleave bug", () => {
  test("mouseenter should update text to 'yes'", () => {
    const { getByText } = render(<HoverMe />);
    fireEvent.mouseEnter(getByText("no"));
    expect(getByText("yes")).toBeTruthy();
  });
});
```

### What you did:

I'm using a third party library that attaches `mouseenter` and `mouseleave` events to a DOM element accessed via a React `ref` via `HTMLElement.addEventListener`. Was testing this behavior.

### What happened:

Works fine in the browser, but when writing my tests, I noticed that `fireEvent.mouseEnter` and `fireEvent.mouseLeave` have no effect. What's weird is if I leave the test alone, but change the event in the component to `mouseover/mouseout`, it works. If I attach the events the react way, via `onMouseEnter` and `onMouseLeave`, it also works.

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-37yqv?fontsize=14&hidenavigation=1&theme=dark

### Problem description:

`fireEvent.mouseLeave` and `fireEvent.mouseOver` do not work when the events are added via `addEventListener`.

### Suggested solution:

It may have something to do with this: https://reactjs.org/docs/events.html#mouse-events

If this is a React limitation, or if there's a workaround, it would be great to add it to the FAQ.

**Comment by greypants** [comment]
Looking under the hood here, https://github.com/testing-library/dom-testing-library/blob/master/src/events.js#L356-L393, I didn't see anything that specifically looked problematic. I recreated the logic as best I could in the browser, and it seemed fine:

![mouseenter](https://user-images.githubusercontent.com/647549/73185212-a6e8fa80-40eb-11ea-94a1-bb296734d791.gif)

Is it a jsdom thing?

**Comment by greypants** [comment]
Upon further testing, I noticed by creating the event myself and passing it to `fireEvent`, DOES pass ✅ :

```js
const mouseenter = new MouseEvent("mouseenter", {
      bubbles: false,
      cancelable: false
    });

fireEvent(getByText("no"), mouseenter);

// Passes!
```

**Comment by greypants** [comment]
Ok, found the issue. These lines re-assign `mouseEnter/mouseLeave` to `mouseOver/mouseOut`:
https://github.com/testing-library/react-testing-library/blob/master/src/pure.js#L128-L132

> // React event system tracks native mouseOver/mouseOut events for
> // running onMouseEnter/onMouseLeave handlers
> // @link https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react-dom/src/events/EnterLeaveEventPlugin.js#L24-L31

Is this still true?

**Comment by kentcdodds** [comment]
Hi @greypants,

Thanks for the issue.

Yeah, sorry about that. I can't remember exactly the reasons for the non-standard event stuff in React, but that's what we needed to do to get things working with react event props.

I'm not sure what to do here, and I'm afraid I don't have the bandwidth right now to look into it 😬 Sorry.

Anyone else have ideas/want to dig?

**Comment by weyert** [comment]
Looks like an interesting problem. I can have a look at it over the weekend or next week.

**Comment by jessethomson** [comment]
So there are the four cases we want to work with the fireEvent utility.
1. mouseEnter/mouseLeave with native events
2. mouseOver/mouseOut with native events
3. mouseEnter/mouseLeave with react events
4. mouseOver/mouseOut with react events

Currently, number 3 does not work.

We want to make a change to fix 3, without breaking the others. Here's a test people we can use to ensure we have done that. So as long as the following tests pass, I'm assuming there shouldn't be any issues getting this change in.

(Like others, I unfortunately don't have time to look into this right now, but maybe in a couple months)

```
import React, { useState, useEffect, useRef } from 'react';
import { render, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom';

const NativeEnterLeave = () => {
    const btnRef = useRef();
    const [label, setLabel] = useState('outside');
    useEffect(() => {
        const btn = btnRef.current;
        function handleMouseEnter() {
            setLabel('inside');
        }
        function handleMouseLeave() {
            setLabel('outside');
        }
        btn.addEventListener('mouseenter', handleMouseEnter);
        btn.addEventListener('mouseleave', handleMouseLeave);
        return () => {
            btn.removeEventListener('mouseenter', handleMouseEnter);
            btn.removeEventListener('mouseleave', handleMouseLeave);
        };
    });
    return <button ref={btnRef}>{label}</button>;
};

const NativeOverOut = () => {
    const btnRef = useRef();
    const [label, setLabel] = useState('outside');
    useEffect(() => {
        const btn = btnRef.current;
        function handleMouseEnter() {
            setLabel('inside');
        }
        function handleMouseLeave() {
            setLabel('outside');
        }
        btn.addEventListener('mouseover', handleMouseEnter);
        btn.addEventListener('mouseout', handleMouseLeave);
        return () => {
            btn.removeEventListener('mouseover', handleMouseEnter);
            btn.removeEventListener('mouseout', handleMouseLeave);
        };
    });
    return <button ref={btnRef}>{label}</button>;
};

const ReactEnterLeave = () => {
    const [label, setLabel] = useState('outside');
    return (
        <button
            onMouseEnter={() => setLabel('inside')}
            onMouseLeave={() => setLabel('outside')}
        >
            {label}
        </button>
    );
};

const ReactOverOut = () => {
    const [label, setLabel] = useState('outside');
    return (
        <button
            onMouseOver={() => setLabel('inside')}
            onMouseOut={() => setLabel('outside')}
        >
            {label}
        </button>
    );
};

test('fires native mouseEnter/mouseLeave events', () => {
    const { getByRole } = render(<NativeEnterLeave />);
    const btn = getByRole('button');
    expect(btn).toHaveTextContent('outside');
    fireEvent.mouseEnter(btn);
    expect(btn).toHaveTextContent('inside');
    fireEvent.mouseLeave(btn);
    expect(btn).toHaveTextContent('outside');
});

test('fires native mouseOver/mouseOut events', () => {
    const { getByRole } = render(<NativeOverOut />);
    const btn = getByRole('button');
    expect(btn).toHaveTextContent('outside');
    fireEvent.mouseOver(btn);
    expect(btn).toHaveTextContent('inside');
    fireEvent.mouseOut(btn);
    expect(btn).toHaveTextContent('outside');
});

test('fires react mouseEnter/mouseLeave events', () => {
    const { getByRole } = render(<ReactEnterLeave />);
    const btn = getByRole('button');
    expect(btn).toHaveTextContent('outside');
    fireEvent.mouseEnter(btn);
    expect(btn).toHaveTextContent('inside');
    fireEvent.mouseLeave(btn);
    expect(btn).toHaveTextContent('outside');
});

test('fires react mouseOver/mouseOut events', () => {
    const { getByRole } = render(<ReactOverOut />);
    const btn = getByRole('button');
    expect(btn).toHaveTextContent('outside');
    fireEvent.mouseOver(btn);
    expect(btn).toHaveTextContent('inside');
    fireEvent.mouseOut(btn);
    expect(btn).toHaveTextContent('outside');
});
```

**Comment by the-teacher** [comment]
Not sure the case is relevant to the topic. But for people who look an information about **fireEvent.mouseEnter** by search phrase like `fireEvent.mouseEnter doesn't work`

In my case **fireEvent.mouseEnter** worked only if before I did **fireEvent.mouseOver**

```tsx
<Cell
  onMouseEnter={() => { console.log("FIRE! ".repeat(50))}}
  data-testid='test-item'
/>
```

```js
   const testItem = () => document.querySelector('[data-testid="test-item"]')

    render(<Table />)

    act(() => {
      fireEvent.mouseOver(testItem())
      fireEvent.mouseEnter(testItem())
    })
```

**Comment by MaxJaison** [comment]
@the-teacher had same issue, thank you!
