### ISSUE TITLE
Unable to test svg element

### ISSUE THREAD

**Issue by isabellachen** [testing-library/react-testing-library#579]
I am working on a project that uses react-testing-library. I am getting an error when trying to use the render() function on a component which uses react-simple-maps to generate and SVG map in this component. Is it possible to test SVG with this library?

```jsx
  it('should render an empty map', () => {
    const { container } = renderWithStores(
      Map,
      {
        dataCenterLocationsItems: [],
      },
      {},
    );
    const map = container.querySelector('.rsm-svg') as SVGElement;
    const circles = container.querySelectorAll('circle');
    expect(circles.length).toBe(0);
    expect(map).toBeDefined();
  });
```
The renderWithStores function is what uses react-testing-library
```
import React from 'react';
import { Provider } from 'mobx-react';
import { render } from 'react-testing-library';
import { HashRouter } from 'react-router-dom';

export function renderWithStores(Component, props, stores) {
  return render(
    <HashRouter>
      <Provider {...stores}>
        <Component {...props} />
      </Provider>
    </HashRouter>,
  );
}

```
The error
  ● The Map component › should render an empty map
```
    TypeError: svg.createSVGPoint is not a function

       5 | 
       6 | export function renderWithStores(Component, props, stores) {
    >  7 |   return render(
         |          ^
       8 |     <HashRouter>
       9 |       <Provider {...stores}>
      10 |         <Component {...props} />
```
- `react-testing-library` version: 6.0.2
- `react` version: 16.8.3
- `node` version: v10.15.0
- `npm` (or `yarn`) version: 6.4.1

**Comment by eps1lon** [comment]
Thanks for opening this issue and filling out the template.

This is an issue with your testing environment. You're probably using JSDOM (via jest) which does not implement `createSVGPoint`. See https://github.com/jsdom/jsdom/issues/300
