### ISSUE TITLE
`getByType` not working on memo components

### ISSUE THREAD

**Issue by karlmarxlopez** [testing-library/react-testing-library#582]
- `react-testing-library` version: `1.12.0`
- `react` version: `16.9.0`
- `node` version: `10.15.2`
- `npm` (or `yarn`) version: `1.6.0`

### Relevant code or config:

Problem is similar to [react-test-renderer findByType bug](https://github.com/facebook/react/issues/17301)

**Comment by eps1lon** [comment]
Thanks for opening this issue.

Could you fill out the template, please? I don't think we have any `*ByType` query. For issues with `react-test-renderer` you already identified the appropriate place to discuss this issue: https://github.com/facebook/react/issues/17301

**Comment by karlmarxlopez** [comment]
Sorry wrong repo. It was react-native-testing-library. 😆 Closing this.
