### ISSUE TITLE
useEffect and test ordering

### ISSUE THREAD

**Issue by davsucks** [testing-library/react-testing-library#583]
- `react-testing-library` version: 9.1.3
- `react` version: 16.9
- `node` version: 10.15.1
- `npm` (or `yarn`) version: 1.21.1
- `jest` version: 23.6.0

### Relevant code or config:

We're using react with react-redux (and hooks). Imports have been elided, but note that in the test code we have a custom wrapper for `render()` which includes all of our providers and also lets us inject state into the redux store, which is why we're passing state in.

Our test suite is using jest.

We have a simple component which listens for 'online' and 'offline' events and renders an icon for users to see when they're offline.

Our problem is with our test suite. We're having an issue with the second test below named `'should log the downtime'`, when we run the test in isolation it passes as expected, but when we run it with the other it appears that the first `useEffect()` in `<NetworkIndicator/>` is being executed _after_ the event is dispatched in the test to bring the component online.

```tsx
// NetworkIndicator.tsx:
const NetworkIndicator: React.FC = () => {
  const isOnline = useSelector(networkSelectors.getIsOnline)
  const [offlineTimestamp, setOfflineTimestamp] = useState<number | undefined>()
  const dispatch: Dispatch = useDispatch()
  const classes = NetworkIndicatorStyles()
  const handleNetworkChange = (isClientOnline: boolean) => {
    dispatch(networkActions.setNetworkStatus(isClientOnline))
  }
  useEffect(() => {
    window.addEventListener('online', () => handleNetworkChange(true))
    window.addEventListener('offline', () => handleNetworkChange(false))
    return () => {
      window.removeEventListener('online', () => handleNetworkChange(true))
      window.removeEventListener('offline', () => handleNetworkChange(false))
    }
  }, [])
  useEffect(() => {
    if (!isOnline) setOfflineTimestamp(Date.now())
    else if (isOnline && offlineTimestamp) {
      const payload: SendErrorMessagePayload = {
        message: 'Network connection recovered',
        context: { methodName: 'NetworkIndicator', offlineTimestamp: offlineTimestamp, onlineTimestamp: Date.now() }
      }
      dispatch(errorActions.sendErrorMessage(payload))
    }
  }, [isOnline])

  if (isOnline) return null
  return (
    <Typography className={classes.indicator} align="center" data-testid={NETWORK_OFFLINE_INDICATOR_TEST_ID}>
      <SignalCellularConnectedNoInternet0BarIcon className={classes.indicatorIcon} />
      Network connection issues detected...
    </Typography>
  )
}

// NetworkIndicator.test.tsx:
describe('<NetworkIndicator />', () => {
  beforeEach(() => jest.resetAllMocks())

  describe('when offline', () => {
    const state = new MockBuilder(RootState)
      .with('network', new MockBuilder(NetworkState).with('isOnline', false).build())
      .build()

    beforeEach(() => {
      jest.spyOn(authClient, 'logError').mockImplementation(jest.fn())
    })

    it('should display a banner', () => {
      const { findByTestId } = render(<NetworkIndicator />, state)
      expect(findByTestId(NETWORK_OFFLINE_INDICATOR_TEST_ID)).toBeTruthy()
    })

    it('should log the downtime', done => {
      const { getByTestId } = render(<NetworkIndicator />, state)

      waitForElementToBeRemoved(() => getByTestId(NETWORK_OFFLINE_INDICATOR_TEST_ID)).then(() => {
        expect(authClient.logError).toHaveBeenCalled()
        done()
      })

      window.dispatchEvent(new Event('online'))
    })
  })
})
```

### What you did:
When we run this test in isolation we see the order of events occurring as expected, the component is rendered, the `useEffect` hooks are called and we see handlers being set properly. Afterwards the 'online' event is dispatched, the indicator is removed and the `waitForElementToBeRemoved` callback is invoked, passing the test. 

While running this with other tests, we see the 'online' event in the test being dispatched _before_ the `useEffect` callbacks are fired, which means the event is dropped, the component is not removed and the test fails.

### What happened:
We do see an error in the problematic test when we run the whole suite:
```
console.error node_modules/@testing-library/react/dist/act-compat.js:50
    Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one.
```

### Reproduction:
If you need us to try to set up a test repo for reproduction let us know, right now we don't have the time but if it'll prove to be helpful we can devote some time to it.

### Problem description:
We can get around this by using a `setTimeout` in the test to have the tests wait until after the `useEffect` hook is called but that is flaky and feels wrong.

**Comment by eps1lon** [comment]
Thanks for opening this issue and filling out the template. 

Having the relevant code inside a codesandbox would help a lot. Especially with `async done => {}` it's hard to reason what's actually going on. It seems like you can either use an async test `async () => {}` or use the callback signature `done => {}`

**Comment by davsucks** [comment]
My apologies, we added the async while we were debugging and forgot to remove it. We aren't actually `await`ing anything in that test though so I removed it from the question. I'll look into adding a codesandbox, but I don't know if I'll be able to right now.

**Comment by kentcdodds** [comment]
Hi @davsucks,

As @eps1lon said, it's hard for us to help when there's no reproduction. In fact, it would be best to follow the instructions here first: https://kcd.im/rtl-help

The issues are for bug reports and feature requests, so I'm going to close this. Please do open a thread in our community if you are unable to resolve this. Good luck!

**Comment by SercanSercan** [comment]
This blog post may help to those who want to mock addEventListener in React.

https://storksnestblog.wordpress.com/2022/03/15/how-to-mock-addeventlistener-in-react-testing-library/
