### ISSUE TITLE
Simplify asynchronous component testing

### ISSUE THREAD

**Issue by reinismu** [testing-library/react-testing-library#584]
### Describe the feature you'd like:

As it is now you have to do a lot of boilerplate code to test asynchronous components.
Example from here https://reactjs.org/docs/testing-recipes.html#rendering

```
// hello.test.js

import React from "react";
import { render, unmountComponentAtNode } from "react-dom";
import { act } from "react-dom/test-utils";

import Hello from "./hello";

let container = null;
beforeEach(() => {
  // setup a DOM element as a render target
  container = document.createElement("div");
  document.body.appendChild(container);
});

afterEach(() => {
  // cleanup on exiting
  unmountComponentAtNode(container);
  container.remove();
  container = null;
});

it("renders with or without a name", () => {
  act(() => {
    render(<Hello />, container);
  });
  expect(container.textContent).toBe("Hey, stranger");

  act(() => {
    render(<Hello name="Jenny" />, container);
  });
  expect(container.textContent).toBe("Hello, Jenny!");

  act(() => {
    render(<Hello name="Margaret" />, container);
  });
  expect(container.textContent).toBe("Hello, Margaret!");
});
```

### Suggested implementation:

Why couldn't we make it like this?

```
// hello.test.js

import React from "react";
import { render } from "react-dom";
import { act } from "react-dom/test-utils";

import Hello from "./hello";

it("renders with or without a name", () => {
    const { getByText, asFragment } = act(() => {
        return render(<Hello />);
    });

    expect(getByText('Remove as admin')).toBeTruthy();
    expect(asFragment()).toMatchSnapshot();
});
```

### Describe alternatives you've considered:

I mean any other way that doesn't introduce such mutability would be nice as well.

### Teachability, Documentation, Adoption, Migration Strategy:

I haven't yet looked in to this. Maybe it is super hard to do.

**Comment by eps1lon** [comment]
You're probably in the wrong repo. Did you mean to open this on https://github.com/reactjs/reactjs.org?

Our API is already simpler than the suggested syntax: https://testing-library.com/docs/react-testing-library/example-intro

**Comment by reinismu** [comment]
Thanks! Got a bit confused there.

So in my case where component does async stuff on initialization I should do

```
// hello.test.js

import React from "react";
import { render, act } from '@testing-library/react';

import Hello from "./hello";

it("renders with or without a name", () => {
    const { container }  = render(<Hello />);
    // Wait for component to finish async calls
    await act(async () => {});

    expect(container).toMatchSnapshot();
});
```

**Comment by eps1lon** [comment]
@reinismu Seems good. For further question I would suggest stackoverflow our [our spectrum.chat](https://spectrum.chat/testing-library?tab=posts)

**Comment by alexkrolick** [comment]
Render is already wrapped in act(), so "async stuff" should work if it doesn't have a non-zero timeout

**Comment by kentcdodds** [comment]
And if your component *is* doing something async in `useEffect`, it's better to use [an async utility](https://testing-library.com/docs/dom-testing-library/api-async) rather than putting async `act` call around.
