### ISSUE TITLE
React input ref not applying calls onchange

### ISSUE THREAD

**Issue by OriginLive** [testing-library/react-testing-library#586]
- `@testing-library/react` ^9.4.0:
- `react` version: ^16.12.0
- `npm` (or `yarn`) version: 1.21.1

### Relevant code or config:

testing the component from
https://material-ui.com/components/text-fields/#integration-with-3rd-party-input-libraries

code:
https://github.com/mui-org/material-ui/blob/master/docs/src/pages/components/text-fields/FormattedInputs.tsx

### What you did:

```ts
    const phoneNumberInput = renderResult.baseElement.querySelectorAll('input')[0];
   //OR
     const otherWay = renderResult.getAllByRole('textbox')[0];

 await act(async () => {
       if(phoneNumberInput) {
         await userEvent.type(phoneNumberInput, '4151234567',);
       }
      //OR
       fireEvent.change(phoneNumberInput, {
         target: {
           value: '(415) 123 - 4567',
         }
       });
    });
```
### What happened:

```js
      <input
        aria-invalid="true"
        class="MuiInputBase-input MuiOutlinedInput-input Mui-disabled Mui-disabled"
        disabled=""
        id="mobile-number"
        type="tel"
        value=""
      />
```

value remains empty > ""

### Reproduction:

Create a project using CRA, load material ui and then create a test using the above code to test a telephone number input.

### Problem description:

It seems to be a problem relating to DOM manipulation, with injected refs/inputs onchange does not seem to trigger.

### Suggested solution:

the following solution seems to work: 
```ts
    await act(async () => {

      var data = {
        target: {
          value: '4151234567'
        }
      };
      ReactTestUtils.Simulate.change(phoneNumberInput, data as unknown as SyntheticEventData);

    });
```

**Comment by eps1lon** [comment]
Thanks for opening this issue.

Could you provide this as a complete codesandbox? The code you posted is not the one you linked. I couldn't find any issue with a basic `<input type="tel" />`.

**Comment by OriginLive** [comment]
https://codesandbox.io/s/elated-cloud-3znlo?fontsize=14&hidenavigation=1&theme=dark

Here's an approximation, i couldn't get your library to load in codesandbox, i'm also using redux to pass values, if you can complete the test it should throw an error.

**Comment by DanceParty** [comment]
@OriginLive I _think_ I was able to get your code working in this example

https://codesandbox.io/s/determined-fog-1mw9s

You were expecting a mock to be called that was never passed to the component. I deleted the mock expectation and replaced with checking the value of the input like your original post said. 👍

**Comment by eps1lon** [comment]
This looks like a better candidate for our [spectrum.chat](https://spectrum.chat/testing-library?tab=posts). It looks like everything is working as expected on our part.

**Comment by OriginLive** [comment]
Your example does not work for my case. I'm trying to write another example, but it'll be really hard to replicate it.
Regardless, when i do 
      console.log(prettyDOM(someInput));
on l40 in your file, it does not print out the value on the component, it seems like you have to target it's inner input? That might be a reason why i've had so much trouble.
