### ISSUE TITLE
fireEvent.change not always firing on sequential calls

### ISSUE THREAD

**Issue by mmmaaatttttt** [testing-library/react-testing-library#591]
Hi there,

I looked through closed issues but couldn't find this specific problem (#532 came the closest).

- `@testing-library/react` version: 9.4.0
- `react` version: 16.12.0
- `node` version: 10.14.1
- `npm` version: 6.8.0

### Relevant code or config:

I'm trying to write a test that requires me to change multiple inputs inside of a form. When writing code like 

```js
const text1Input = getByLabelText("Text1");
const text2Input = getByLabelText("Text2");

fireEvent.change(text1Input, { target: { value: "a" } });
fireEvent.change(text2Input, { target: { value: "b" } });
```

I discovered that the first event went through, but the second did not.

I thought maybe React's synthetic event and pooling had something to do with it, but persisting the event doesn't fix the problem. My tests fail with this `handleChange`:

```js
const handleBrokenChange = e => {
  e.persist();
  setBrokenForm(form => ({ ...form, [e.target.name]: [e.target.value] }));
};
```

But pass with this one:

```js
const handleWorkingChange = e => {
  setWorkingForm({ ...workingForm, [e.target.name]: e.target.value });
};
```

### What you did:

Trying to write a simple test for a component involving a form.

### What happened:

The test failed because only one `fireEvent.change` appears to have registered.

### Reproduction:

Here's a codesandbox with two forms that are functionally the same, with identical tests but with different `handleChange` functions:

https://codesandbox.io/s/react-testing-library-demo-xxcll

At the bottom of `App.js` I've also got a few other examples of passing / failing `handleChange` functions

### Problem description:

I don't know why the `handleChange` function with persisting the event would fail, and the behavior in the test is different from the behavior in the (working) app.

### Suggested solution:

I haven't done any digging yet - happy to do so, I just want to make sure there's not something obvious I'm overlooking here.

Thanks!

**Comment by kentcdodds** [comment]
Hi @mmmaaatttttt!

First off, the value was being set to an array 😅

![image](https://user-images.githubusercontent.com/1500684/75082559-75d4cd80-54d1-11ea-82ff-db48e0d6ba11.png)

So after fixing that... I'm actually thinking this is some sort of race-condition problem. I don't have time to explain it all right now, but you can fix this easily by changing things around a little bit (especially since persisting the event isn't recommended, this is what I'd suggest you do if you want to use the function update form):

```javascript
  const handleBrokenChange = e => {
    const {name, value} = e.target
    setBrokenForm(form => ({...form, [name]: value}))
  }
```

Get those values before so there's no time for React to update the input's `value` before you get a chance to reference it for your state update.

https://codesandbox.io/s/react-testing-library-demo-dynh8

Good luck!

**Comment by mmmaaatttttt** [comment]
Yeah, I got it working that way as well - I guess I'm just not sure why this works for the tests:

```js
const handleBrokenChange = e => {
  const {name, value} = e.target;
  setBrokenForm(form => ({...form, [name]: value}))
}
```

but this doesn't:

```js
const handleBrokenChange = e => {
  const tgt = e.target;
  setBrokenForm(form => ({...form, [tgt.name]: tgt.value}))
}
```

Maybe a referencing issue? Or the same race condition you're thinking of?

**Comment by mmmaaatttttt** [comment]
Yeah, I got it working that way as well - I guess I'm just not sure why this works for the tests:

```js
const handleBrokenChange = e => {
  const {name, value} = e.target;
  setBrokenForm(form => ({...form, [name]: value}));
}
```

but this doesn't:

```js
const handleBrokenChange = e => {
  const tgt = e.target;
  setBrokenForm(form => ({...form, [tgt.name]: tgt.value}));
}
```

Maybe a referencing issue? Or the same race condition you're thinking of?

**Comment by kentcdodds** [comment]
Yeah, the thing I think is happening is after the user changes the value, react comes in and changes it back to whatever the controlled value is. I'm not sure why it works in the UI but not the test. Feel free to dig in further if you want, but even without tests I would still recommend getting the values you need as I did.

**Comment by rparias** [comment]
I was having the same issue. Thanks @kentcdodds for your answer.
