### ISSUE TITLE
fireEvent.change not triggering render

### ISSUE THREAD

**Issue by mnsr** [testing-library/react-testing-library#594]
- `@testing-library/react` version: 9.4.1
- `react` version: 16.12
- `node` version: 12.16.1
- `npm` (or `yarn`) version: 6.14.1

### Relevant code or config:

```js

const SearchPanel = props => {
  const renderPanel = () => (
    <div className="search-panel" aria-label="search-panel">
      {props.myValue}
    </div>
  );

  if (props.isPanelOpen) console.log("panel is open");
  return props.isPanelOpen ? renderPanel() : null;
};

export default function App() {
  const [myValue, setMyValue] = useState("");
  const [isPanelOpen, setIsPanelOpen] = useState(false);

  const handleChange = e => {
    setMyValue(e.target.value);
    setIsPanelOpen(myValue.length > 1);
    console.log("on-change triggered");
  };

  // uncomment following, and tests work
  // useEffect(() => {
  //   setIsPanelOpen(myValue.length > 1);
  // }, [myValue.length]);

  return (
    <div className="App">
      <input
        type="text"
        onChange={handleChange}
        onKeyDown={handleChange}
        value={myValue}
        aria-label="my-input"
      />
      <SearchPanel isPanelOpen={isPanelOpen} myValue={myValue} />
    </div>
  );
}

test("search panel opens on change", async () => {
  const app = render(<App />);

  const myInput = app.queryByLabelText("my-input");
  expect(myInput).toBeInTheDocument();

  expect(app.queryByLabelText("search-panel")).not.toBeInTheDocument();

  // ------
  // Test fails because state change hasnt triggered from onChange event
  // even thoguh in browser it works fine
  // ------

  fireEvent.change(myInput, { target: { value: "hello" } });

  // uncomment following, and test passes due to
  // onKeyDown event on myInput
  // fireEvent.keyDown(myInput, { key: "w" });

  expect(myInput.value).toBe("hello");

  app.debug();

  const searchPanelDiv = await waitForElement(() =>
    app.getByLabelText("search-panel")
  );

  expect(searchPanelDiv).toBeInTheDocument();
});

```

### What you did:

In my main project, i came across this. If i don't use the useEffect and solely rely on the onChange event, i can't get the test to pass, despite it working in the browser. A work around is using keydown, which works for some reason and causes the test to pass.  I'm not sure exactly what the correct way is to handle tests like this (ie best practice). Reason i'm avoiding useEffect here is due to it causing unwanted effects due to reusing of the same component.

Also, i understand the fireEvent.change event is simulating a copy/paste effect in the textbox. But a second fireEvent.change doesnt seem to cause the div to appear

### Reproduction:

https://codesandbox.io/s/vigorous-cohen-ijnbg?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.test.js&previewwindow=tests&theme=dark

### Problem description:

user types something in textbox, it should render a div onChange. Works in browser, not in test.

**Comment by PaulACoroneos** [comment]
So your onChange updates state right? You are not guaranteed to get state to immediately update because state updates async. What if you await the change in the input value so the change has time to hydrate?

**Comment by mnsr** [comment]
> So your onChange updates state right? 

Yup. And i understand it updates async. 

> What if you await the change in the input value so the change has time to hydrate?

Makes sense. But for the test to pass, i still need to add another fireEvent.change which also makes sense as the change simulates a copy/paste rather than key presses that trigger onChange after each one.

The following makes the test work. 

``` js
  await wait(() => {
    expect(myInput.value).toBe("hello");
  });

  fireEvent.change(myInput, { target: { value: "hellop" } });

  const searchPanelDiv = await waitForElement(() =>
    app.getByLabelText("search-panel")
  );

```
https://codesandbox.io/s/nervous-agnesi-937n9?hidenavigation=1&module=%2Fsrc%2FApp.test.js&previewwindow=tests&theme=dark

Is this the best way to do it? Or is there a more optimal way?

**Comment by PaulACoroneos** [comment]
Yes waitForElement() is just a nice helper function that essentially will check for the dom to update with an instance of that element (I think default timeout is 5000ms). This is in fact how the official example tests something async. :)

https://testing-library.com/docs/react-testing-library/example-intro

I think waitForElement() may be newer. This also should be valid:

```
  await wait(() => {
    expect(app.getByLabelText("search-panel")).toBeInTheDocument();
  });
```

But the key is yes let testing library know to that the element may not be in the dom yet while async actions are occuring.
