### ISSUE TITLE
Automatic Cleanup Breaking Existing Tests

### ISSUE THREAD

**Issue by lukashambsch** [testing-library/react-testing-library#602]
### What you did:

I introduced react-testing-library into an existing codebase.

### What happened:

Some existing tests in unrelated files started failing. I eventually tracked it down to the automatic cleanup that occurs because of react-testing-library.

### Problem description:

The tests that were affected aren't using react-testing-library, so the source of the new errors were confusing.

### Suggested solution:

Only do the automatic cleanup for files that are using react-testing-library.

**Comment by kentcdodds** [comment]
Hi @lukashambsch, are you using jest? Are you running the tests serially or in parallel (the default)?

**Comment by lukashambsch** [comment]
I'm using jest and the tests are run in parallel (I think, I don't see any references to `runInBand`). I was able to fix my issue using the env variable that skips the cleanup, but it took a lot of digging to figure out the root cause since I wasn't expecting just importing react-testing-library to affect tests in other files.

**Comment by kentcdodds** [comment]
If this is happening then that's a bug. Could you make a minimal reproduction repository on GitHub and link it here?

**Comment by lukashambsch** [comment]
I think I tracked down the real issue. I created a helper function to render with redux & react-router. That file is * imported in another file, which is causing react-testing-library to be loaded anytime that other file is loaded.

It doesn't look like it's a `react-testing-library` issue. Sorry for jumping the gun and thanks for taking the time help me with this.
