### ISSUE TITLE
getByRole('textbox') cannot find <input /> html element in v9.5.0

### ISSUE THREAD

**Issue by laij84** [testing-library/react-testing-library#606]
- `@testing-library/react` version: 9.5.0
- `react` version: 16.12.0
- `node` version: 10.16.0
- `yarn` version: 1.17.3

### Relevant code or config:

```js
const inputProps = {
    name: 'test',
    label: 'Enter your name',
}

test('You should be able to type in the input and see the text', () => {
    const textToType = 'Hello, World!'
    const { getByRole } = render(<Input {...inputProps} />)
    userEvent.type(getByRole('textbox'), textToType)
    expect(getByRole('textbox')).toHaveAttribute('value', textToType)
})
```

### What you did:

After upgrading to 9.5.0, tests using `getByRole('textbox') are unable to locate the <input /> html element.

### What happened:
Unable to find an accessible element with the role "textbox"

    Here are the accessible roles:

      document:

      Name "":
      <body />

      --------------------------------------------------

    <body>
      <div>
        <div
          class="Inputstyles__Field-ml9srx-3 gUrUvl"
        >
          <div
            class="Inputstyles__InputWrapper-ml9srx-2 bKKQul"
          >
            <input
              class="Inputstyles__StyledInput-ml9srx-1 ezsCsI"
              id="ECJHn78Lr"
              name="test"
              value=""
            />
            <label
              class="Inputstyles__StyledLabel-ml9srx-0 VKxRB"
              for="ECJHn78Lr"
            >
              Enter your name
            </label>
          </div>
        </div>
      </div>
    </body>

**Comment by eps1lon** [comment]
[This is a known bug in `aria-query`](https://github.com/A11yance/aria-query/pull/42). You would need to explicitly set `type="text"`. This is probably a good idea anyway.

**Comment by jonasantonelli** [comment]
Try to use the config `configure({ defaultHidden: true })` in your test

**Comment by mkelley33** [comment]
The following isn't working for me even though I have a MUI generated input of type text with a name, id, and label with for attribute set:

```expect(screen.getByRole('textbox', { name: 'firstName' })).toBeInTheDocument();```

I'm using ```@testing-library/react": "^14.0.0```

Do you know why this would fail my unit test expectation?

**Comment by MatanBobi** [comment]
@mkelley33 based on your `name` property value, I assume that this is not the accessible name. The name for an the `textbox` role is calculated using name from author which is `aria-label` or `aria-labelledby`.

**Comment by mkelley33** [comment]
@MatanBobi I think the ```textbox``` role should be calculated also when an input (like mine) has a name, id, and label with matching for attribute, since this would make the ```aria-label``` and ```aria-labelledby``` redundant, useless, and ignored by assistive technology in this case.  Do you think that could be an improvement to the functionality of ```getByRole```?

**Comment by MatanBobi** [comment]
The `name` attribute is never used for accessibility reasons nor it is visible to the user so it is not taken as part of our selectors.
To calculate the accessible name (which is what you're trying to filter by), we're using the accessible name computation algorithm which is defined in the [ARIA spec](https://www.w3.org/TR/accname-1.2/) :)

**Comment by mkelley33** [comment]
@MatanBobi okay thanks for the answer. I should probably be using ```getByLabelText``` then in my tests, right?

**Comment by MatanBobi** [comment]
@mkelley33 `getByRole` tests for some stuff (including visibility and verifies correct roles) and `getByLabelText` tests some other stuff. It's your call. The point is, if you're using `getByRole('textbox', {name: 'yourLabelText'})` and you do have a label, it will also work :)
