### ISSUE TITLE
Warning about overlapping act() calls when using Promise.all / Axios.all

### ISSUE THREAD

**Issue by vallq** [testing-library/react-testing-library#615]
- `@testing-library/react` version:
- `react` version: 16.13.0
- `node` version: v13.5.0
- `npm` (or `yarn`) version: 6.14.1

### Relevant code or config:

```js
await Axios.all([
          axios.post("/publish", articleDetails),
          axios.post("/articles", articleDetails)
        ]);
```

### What you did:

Trying to make multiple axios calls (appended with baseURL) using Axios.all causes the following warning message:

### What happened:

> console.error node_modules/react-dom/cjs/react-dom-test-utils.development.js:87
>     Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one.

### Problem description:

Working on an external product for a client; would like to get rid of console error warnings

**Comment by eps1lon** [comment]
We need more information to debug this issue (component code, test code, `@testing-library/react` version etc). 

We don't have the bandwidth to deep-dive without complete information.

**Comment by AndreasPresthammer** [comment]
Seeing a similar issue using Promise.all.

See repro: https://codesandbox.io/s/focused-lehmann-438q7?file=/src/__tests__/index.js

Seem's to me like the findBy* api isn't intended to be run concurrently?

**Comment by kentcdodds** [comment]
Yeah, they're not intended to be run concurrently. If you *need* them to for some reason, then you can do this: https://codesandbox.io/s/happy-framework-hjzlx?file=/src/__tests__/index.js:458-608

```javascript
await waitFor(() => [
  screen.getByTestId('my-id-1'),
  screen.getByTestId('my-id-2'),
])
```

I'm not sure whether there's anything we need to or can do about this.
