### ISSUE TITLE
Dependancy on @testing-library/dom at ^7.0.2 causes failed installs on node less than 10.18

### ISSUE THREAD

**Issue by SamTolmay** [testing-library/react-testing-library#616]
- `@testing-library/react` version: 10.0.1
- `react` version:  16.13.0
- `node` version: 10.16.3
- `npm` (or `yarn`) version:  yarn v1.17.3

### Relevant code or config:
```
"@testing-library/dom@^7.0.2":
  version "7.0.2"
  resolved "https://registry.yarnpkg.com/@testing-library/dom/-/dom-7.0.2.tgz#9edc922dfe2644a3f0ff70f256d8c78a525b88c3"
  integrity sha512-5pqMlPaBC/5bvvFtuNTTcB4/Vg8NjZfs11LQQc08JhpMfx82W85nVw3re4D92A/C5O8zDkxPxyYPWNp8PtnQ/w==
  dependencies:
    "@babel/runtime" "^7.8.4"
    "@types/testing-library__dom" "^6.12.1"
    aria-query "^4.0.2"
    dom-accessibility-api "^0.3.0"
    pretty-format "^25.1.0"

"@testing-library/react@10.0.1":
  version "10.0.1"
  resolved "https://registry.yarnpkg.com/@testing-library/react/-/react-10.0.1.tgz#4f5e2a8836257c5bd3df640b21d7bea5a0d83ead"
  integrity sha512-sMHWud2dcymOzq2AhEniICSijEwKeTiBX+K0y36FYNY7wH2t0SIP1o732Bf5dDY0jYoMC2hj2UJSVpZC/rDsWg==
  dependencies:
    "@babel/runtime" "^7.8.7"
    "@testing-library/dom" "^7.0.2"
    "@types/testing-library__react" "^9.1.3"
```

### What happened:
Error message:
```
error @testing-library/dom@7.0.2: The engine "node" is incompatible with this module. Expected version ">=10.18". Got "10.16.3"
```

### Problem description:
Yarn install is failing on node versions less the 10.18. This was fixed in @testing-library/react in version 10.0.1, and in @testing-library/dom in version 7.0.3. However, @testing-library/react requires @testing-library/dom at version ^7.0.2. Thus if @testing-library/dom is pinned at v7.0.2 in yarn.lock, yarn install still fails for node less than version 10.18.

This is an issue since AWS CodeBuild still runs on node v10.16

### Suggested solution:
Require @testing-library/dom at version 7.0.3 or higher.

**Comment by ekatzenstein** [comment]
This issue is not resolved. The shadow libraries are an odd design and are causing conflicts with deployment.
