### ISSUE TITLE
Incorrect typings (may be)

### ISSUE THREAD

**Issue by artem-malko** [testing-library/react-testing-library#618]
- `@testing-library/react` version: 10.0.1
- `react` version: 16.13.1
- `node` version:  v12.14.0
- `npm` (or `yarn`) version: 6.13.4

### Problem description:

In source code of react-testing-library we can see, that cleanup is async function: https://github.com/testing-library/react-testing-library/blob/master/src/pure.js#L92

But it sync in typings: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/testing-library__react/index.d.ts#L50

So, where is the truth?

### Suggested solution:

Should I open pull request with fix in DefinitelyTyped?

**Comment by eps1lon** [comment]
Thanks for the report. Almost forgot this change.

Already got an open PR for /react typings in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43108. Should include this change in the end.

**Comment by artem-malko** [comment]
@eps1lon thx
