### ISSUE TITLE
focus() on active element triggers onBlur and onFocus

### ISSUE THREAD

**Issue by eiko** [testing-library/react-testing-library#627]
I'm not sure if this is a bug with react-testing-library itself, but I could not replicate it in the browser with a normal react component or in JSDOM directly.

In the browser, calling `focus()` on an element that's already active is a no-op, but in testing, calling `focus()` on an active element causes the `onBlur` and `onFocus` events to emit again.

- `@testing-library/react` version: 9.5.0
- `react` version: 16.13.0
- `node` version: 12.10.0
- `npm` (or `yarn`) version: 6.10.3

### Relevant code or config:

```js
import React from 'react';
import { render } from '@testing-library/react';

const handleFocus = (event) => {
  console.log('focused');
  event.target.focus();
}

test('it renders', () => {
  const { container } = render(<div tabIndex={-1} onFocus={handleFocus} />);
  container.firstChild.focus();
});
```

### What you did:

I wrote a test that uses `render` to render a DOM element that calls `focus()` in its own `onFocus()` event.

### What happened:

`onFocus` got called over and over until the stack size exceeded:

```

      focused
    console.log src/testcom/simple.test.js:5
      focused
    console.log src/testcom/simple.test.js:5
      focused
    console.log src/testcom/simple.test.js:5
      focused
    console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Uncaught [RangeError: Maximum call stack size exceeded]
```

**Comment by eps1lon** [comment]
You very likely have an older version of jsdom installed. That particular bug was fixed in jsdom 15 (.2 I believe). Try `yarn why jsdom` to find out which version you're using. I'd recommend using jest-environment-jsdom-sixteen.

**Comment by eiko** [comment]
You're right, using `jest-environment-jsdom-sixteen` worked for me. Thank you!
