### ISSUE TITLE
FireEvent Mouse Events do not trigger

### ISSUE THREAD

**Issue by crgoldstein** [testing-library/react-testing-library#631]
- `@testing-library/react` version: 9.5.0
- `react` version: 16.12.0
- `node` version: 12.12.22
- `npm`  version: 6.4.1

### Relevant code or config:
```
import '@testing-library/jest-dom' 
import React from 'react'
import { render , screen , fireEvent } from '@testing-library/react'
import  IpConfiguration from './IpConfiguration'

describe('Ip Configuration  basic props tests', () => {

    it('should be disabled & have Tooltip', async () => {
        const renderResult =   render(
            <IpConfiguration
                config={null}
                updateConfiguration={ipConfig => {
                }}
                id={123}
                isDefault={true}
            /> 
        )

        expect(screen.queryByText('Static IP')).not.toBeNull()

        const buttons = renderResult.getAllByRole('button')
        expect(buttons.length).toBe(2)

        const staticIP = renderResult.getByText('Static IP')
        expect(staticIP).toBeInTheDocument()

        expect(buttons[1]).toBeDisabled()
        
        // fireEvent.mouseOver(buttons[1]) -- Dose not work 
        // fireEvent.mouseEnter( buttons[1]) -- Dose not work 
        // fireEvent.focus( buttons[1]) -- Dose not work 
        fireEvent.click( buttons[1])
        expect(screen.queryByText('Static IP is not available.')).not.toBeNull()
        
     })   
   
})

```

### What you did:

I have a Component that calls a [Semantic UI Popup](https://react.semantic-ui.com/modules/popup/) on a hover event if the button is Disabled.

### What happened:

When I write a test to see if the pop up appears in the screen all of the the fireEvent.MouseEvents do not trigger the popUP. The fireEvent.click dose cause the test to Pass. When running it in my react App all mouseEvents trigger the pop up so I think this is a bug in the testing library

**Comment by kentcdodds** [comment]
Hi, could you provide a reproduction in https://kcd.im/rtl-help?

**Comment by rohmanhm** [comment]
@kentcdodds Looks like it's similar with https://github.com/testing-library/react-testing-library/issues/680

**Comment by samtsai** [comment]
@crgoldstein have you tried `screen.debug()` to see what's rendered? And have you tried `screen.findByText` in case there's a delay?

**Comment by eps1lon** [comment]
> expect(buttons[1]).toBeDisabled()

If a button is disabled it won't receive mouse(enter|out) events. Even clicking wouldn't be registered. Only dispatching click events works.
