### ISSUE TITLE
useSelector not working when testing for appearance of an element

### ISSUE THREAD

**Issue by matteoreda** [testing-library/react-testing-library#633]
### Problem description:

Hello. I'm developing a sample app using React and Redux Saga. I followed this guide to set up my test environment: https://testing-library.com/docs/example-react-redux.

I'm facing a problem with testing for the appearance of an element, based on a condition which changes after clicking on a button; the value of this condition is set by the useSelector hook.
I tried to follow this guide to perform such test:
https://testing-library.com/docs/guide-disappearance.

Unfortunately, even if the action is correctly dispatched when clicking on the button, it's like the useSelector callback get never applied.

- `@testing-library/react` version: 10.0.2
- `react` version: 16.13.1
- `node` version: 12.14.0
- `npm` (or `yarn`) version: 1.21.1

### Relevant code or config:

Here is my component

```js
import React from 'react'
import './button.scss'
import { useSelector, useDispatch } from 'react-redux';
import { REQUEST_API_DATA } from '../../actions/actions';
import { WARNING_COLOR } from '../../constants';


const Button = () => {

    const data = useSelector(state => state.data);
    const dispatch = useDispatch();

    const inc = () => {
        dispatch({
            type: REQUEST_API_DATA
        });
        
    }

    const User = () => {
        if (!data.results) return <p>No name</p>
        return data.results.map(item => <p key={item.name.first} data-testid="name" className="name" 
            style={{ color: WARNING_COLOR }}>{item.name.first}</p>);
    }


    return (
        <>
            <User data-testid="name"></User>
            <button data-testid="button" onClick={inc}>Load</button>
        </>
    );
}

export default Button;
```

Here is the main component
```js
import React from 'react';
import './App.css';
import { createStore, applyMiddleware, compose } from 'redux';
import { Provider } from 'react-redux';
import { combineReducers } from 'redux';
import createSagaMiddleware from 'redux-saga';
import Button from './components/button/button';
import rootReducer from './reducers/';
import rootSaga from './sagas/sagas'


const sagaMiddleware = createSagaMiddleware();
const store = createStore(
  combineReducers(
    rootReducer
  ),
  compose(
    applyMiddleware(sagaMiddleware),
    window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__(),
  )
);
sagaMiddleware.run(rootSaga);

function App() {
  return (
    <Provider store={store}>
      <div className="App">
        <Button></Button>
      </div>
    </Provider>
  );
}

export default App;
```

And here is the test
```js
import React from 'react';
import Button from '../button';
import { render, fireEvent, screen, cleanup } from './../../../utils/test-utils'
import '@testing-library/jest-dom/extend-expect';
import axiosMock from 'axios';

const mockedData = {
    data: {
        results: [
            {
                "gender": "male",
                "name": {
                    "title": "Mr",
                    "first": "Aymeric",
                    "last": "Dupont"
                }
            }]
    }
}
afterEach(cleanup);

describe('Button', () => {

    it('renders without crashing', () => {
        const div = document.createElement('div');
        render(<Button></Button>, div);
    })

    it('should render a Load button', () => {
        const { queryByTestId } = render(<Button></Button>);
        expect(queryByTestId('button')).toHaveTextContent('Load');
    })

    it('should render a random name after being clicked', async () => {
        
        axiosMock.get.mockResolvedValueOnce(mockedData);
        
        const { findByTestId, getByTestId } = render(<Button></Button>);

        fireEvent.click(getByTestId('button'));
        
        const name = await findByTestId('name');
        expect(name).toBeInTheDocument();
    })

})
```

This is the error I get

```js
    TestingLibraryElementError: Unable to find an element by: [data-testid="name"]

    <body>
      <div>
        <p>
          No name
        </p>
        <button
          data-testid="button"
        >
          Load
        </button>
      </div>
    </body>
```

**Comment by alexkrolick** [comment]
Can't really diagnose the issue with this without the full code, including the reducer, or a codesandbox reproduction

**Comment by alexkrolick** [comment]
`import axiosMock from 'axios';` this doesn't look right to me, you need a `jest.mock` call or something like that; this is just importing the default export of the regular `axios` library

**Comment by matteoreda** [comment]
I actually mocked it by creating an axios.js file inside src/__mocks__ folder. 
I think I will provide a code sandbox tomorrow.

**Comment by alexkrolick** [comment]
We can re-open if this is an issue with the library, but it doesn't sound like it is

**Comment by Ba-stian** [comment]
I have the same problem.
I trying all of queries in my code and I get an error. 
At first, I was thinking, that something wrong with my code, but then I wrote dummy component, and I still get an error.

Here's my component 

```
import React from 'react';

const FakeButton = () => (
      <div>
          <button data-testid="btn">Push</button>
      </div>
  );

export default FakeButton;
```

Here's test

```
import React from 'react';
import FakeButton from './FakeButton';
import {cleanup, render} from '@testing-library/react';


describe('FakeButton', () => {
   afterEach(cleanup);
   const {asFragment, getByTestId} = render(<FakeButton/>);
    it('should render button without crashing', () => {
        expect(asFragment()).toMatchSnapshot();
    });
    it('should find button inside component', () => {
        expect(getByTestId('btn').length).toEqual(1);
    });
});

```

And here's an error, that following me

```
 FAIL  src/components/reportButton/FakeButton.test.js
  ● FakeButton › should find button inside component

    TestingLibraryElementError: Unable to find an element by: [data-testid="btn"]

    <body />

      11 |     });
      12 |     it('should find button inside component', () => {
    > 13 |         expect(getByTestId('btn').length).toEqual(1);
         |                ^
      14 |     });
      15 | });

      at Object.getElementError (node_modules/@testing-library/dom/dist/config.js:30:19)
      at node_modules/@testing-library/dom/dist/query-helpers.js:76:38
      at getByTestId (node_modules/@testing-library/dom/dist/query-helpers.js:59:17)
      at Object.<anonymous> (src/components/reportButton/FakeButton.test.js:13:16)

```
Will happy any help.

**Comment by matteoreda** [comment]
@alexkrolick 

this is my custom render... I think it is something to do with the moment I call sagaMiddleware.run(rootSaga). Basically, the first time the middleware is working correctly and the test pass; from the second time on, I think it does not work as expected... and I guess this could be related to the auto cleanup (I read it on the docs). In fact, by disabling the auto cleanup, the tests pass.
Any suggestion?

`
// test-utils.js
import React from 'react'
import { render as rtlRender } from '@testing-library/react'
import { createStore, combineReducers, compose, applyMiddleware } from 'redux'
import { Provider } from 'react-redux';
import reducer from '../reducers';
import rootSaga from '../sagas/sagas';
import createSagaMiddleware from 'redux-saga';


const sagaMiddleware = createSagaMiddleware();

function render(
  ui,
  {
    initialState = {},
    store = createStore(
      combineReducers(reducer),
      compose(
        applyMiddleware(sagaMiddleware),
      ),
    ),
    ...renderOptions
  } = {}
) {
  function Wrapper({ children }) {
    sagaMiddleware.run(rootSaga);
    return <Provider store={store}>{children}</Provider>
  }
  return rtlRender(ui, { wrapper: Wrapper,  ...renderOptions })
}

// re-export everything
export * from '@testing-library/react'

// override render method
export { render }
`

**Comment by Silverium** [comment]
removing the "cleanup" also fixed it to my tests.
```js
afterEach(()=>{
  cleanup(); // removing this line the elements are found
...
```

**Comment by cs11wcq** [comment]
> @alexkrolick
> 
> this is my custom render... I think it is something to do with the moment I call sagaMiddleware.run(rootSaga). Basically, the first time the middleware is working correctly and the test pass; from the second time on, I think it does not work as expected... and I guess this could be related to the auto cleanup (I read it on the docs). In fact, by disabling the auto cleanup, the tests pass.
> Any suggestion?
> 
> ```js
> // test-utils.js
> import React from 'react'
> import { render as rtlRender } from '@testing-library/react'
> import { createStore, combineReducers, compose, applyMiddleware } from 'redux'
> import { Provider } from 'react-redux';
> import reducer from '../reducers';
> import rootSaga from '../sagas/sagas';
> import createSagaMiddleware from 'redux-saga';
> 
> 
> const sagaMiddleware = createSagaMiddleware();
> 
> function render(
>   ui,
>   {
>     initialState = {},
>     store = createStore(
>       combineReducers(reducer),
>       compose(
>         applyMiddleware(sagaMiddleware),
>       ),
>     ),
>     ...renderOptions
>   } = {}
> ) {
>   function Wrapper({ children }) {
>     sagaMiddleware.run(rootSaga);
>     return <Provider store={store}>{children}</Provider>
>   }
>   return rtlRender(ui, { wrapper: Wrapper,  ...renderOptions })
> }
> 
> // re-export everything
> export * from '@testing-library/react'
> 
> // override render method
> export { render }
> ```

Thank you for your analysis.  Same thing happening with me. The first time useSelector is working correctly but from the second time on, it does not work as expected, and the value is empty.

What is the line to disable automatic cleanup??

**Comment by MatanBobi** [comment]
@cs11wcq, you can set an environment variable named `RTL_SKIP_AUTO_CLEANUP` to `true` or import everything from `/pure` instead of the index file.
