### ISSUE TITLE
Name property does not exist in ByRoleOptions typing

### ISSUE THREAD

**Issue by eric-burel** [testing-library/react-testing-library#636]
- `@testing-library/react` version: 10.0.2

### Relevant code or config:

Name is documented here: https://testing-library.com/docs/dom-testing-library/api-queries#byrole

But absent from the "ByRole" typing.

### What you did:

```js
const checkbox2 = getByRole("checkbox", { name: "asset-2" });
```

### What happened:

Argument of type '{ name: string; }' is not assignable to parameter of type 'ByRoleOptions'.
  Object literal may only specify known properties, and 'name' does not exist in type 'ByRoleOptions'.ts(2345)

### Reproduction:

Use getByRole in a ts file like in the code provided above.

### Suggested solution:

Fix typings of the `ByRole` option

**Comment by eps1lon** [comment]
You need to manually update the typings for `@testing-library/dom` you have installed. [The latest typings are up-to-date](https://unpkg.com/@types/testing-library__dom@7.0.1/queries.d.ts).

The underlying issue is already part of #620

**Comment by eric-burel** [comment]
Hi, thanks but I don't get why, upgrading does not work:
```
yarn upgrade --latest @types/testing-library__react
```
This will still install the old `__dom` typings within `@types/testing-library-react`. I've tried to install the dom typings separately, I get the lastest version but no luck, the react typings will still load the older types.

Do you have a quickfix for this?

**Comment by eps1lon** [comment]
> yarn upgrade --latest @types/testing-library__react

You need to upgrade `@types/testing-library__dom` because Yarn will not upgrade dependencies of the package you are upgrading.

If that doesn't help remove the lockfile entry for `@types/testing-library__dom` and run `yarn install` again.

**Comment by eric-burel** [comment]
Thanks it works after manually removing reference to testing-library__dom v6 and rerunning the yarn upgrade command.
