### ISSUE TITLE
Change event not working when using a function in setState

### ISSUE THREAD

**Issue by giovannigiordano** [testing-library/react-testing-library#640]
- `@testing-library/react` version: 9.5.0
- `react` version: 16.9.0
- `node` version: 10.20.1
- `yarn` version: 1.22.4

### Relevant code or config:

```js
class App extends React.Component {
  state = {
    value: ""
  };
  handleChange = ({ target }) => {
    this.setState(state => {
      console.log(target.value) // Here the value is the previous one
      return {
        value: target.value
      };
    });
  };

  render() {
    return (
      <div className="App">
        <p>Value: {this.state.value}</p>
        <input
          type="text"
          value={this.state.value}
          onChange={this.handleChange}
        />
      </div>
    );
  }
}
```

### What you did:

I was trying to test a controlled input text

### What happened:

The expected value is not tot the fired event's value

### Reproduction:
Here the tests:
https://codesandbox.io/s/infallible-galileo-qfvur?file=/src/__tests__/on-change.js

And here the running app to make sure it is not a React bug
https://codesandbox.io/s/silly-mahavira-odq1y?file=/src/App.js

### Problem description:
I need the updater function in `setState` API

**Comment by eps1lon** [comment]
```js
onUpperChange = (event) => {
  const value = event.target.value
  this.setState(state => {
    console.log('inner scope value =>', value)
    return {
      upper: value.toUpperCase(),
    }
  })
}
```

fixes this. It's probably an issue with persisting events.

**Comment by kentcdodds** [comment]
Thanks @eps1lon 👍

**Comment by giovannigiordano** [comment]
@eps1lon thanks for the answer.
@kentcdodds it's ok to close it but maybe there is something wrong in the fireEvent API.
I am migrating to react-testing-library from enzyme and I have to rewrite some methods of the components to make the tests passing for this stuff.

**Comment by kentcdodds** [comment]
Three way you've written it is susceptible to this bug in the wild and it's possible that users with slower devices are experiencing problems because this is basically a race condition between Reacts event pool and state updates. So you really should change the code anyway.
