### ISSUE TITLE
SVGGElement's getBBox method works in browser, not in testing

### ISSUE THREAD

**Issue by DSom20** [testing-library/react-testing-library#651]
- `@testing-library/react` version: 9.5.0 (also 10.0.3 in codesandbox)
- `react` version: 16.13.1
- `node` version: 10.18.0
- `npm` (or `yarn`) version: 6.13.4

### Relevant code or config:

see codesandbox: https://codesandbox.io/s/react-testing-library-svggelement-bug-f4yc9?file=/src/Svg.js:0-1775

### What you did:

I was using a library that was calling the "getBBox" method on on a `<g>` element. Worked fine in the browser. No errors.

### What happened:

Despite the code working in the browser, my App's smoke test failed. Inside the library's script, the `<g>` element was stored in a variable called "fg". The testing error said, "fg.getBBox() is not a function".

### Reproduction:

I reproduced the error in a simple way in a codesandbox. A simple Svg React component renders an `<svg>` with a `<g>` element. Then a useEffect hook queries the `<g>` element and tries to call `getBBox()` on it. Rendering the component in the browser works successfully with no errors. Running a smoke test on the component raises the same error as before, saying "getBBox() is not a function".

see codesandbox: https://codesandbox.io/s/react-testing-library-svggelement-bug-f4yc9?file=/src/Svg.js:0-1775

### Problem description:

Calling `getBbox` on a queried `<g>` element works when running a script in the browser, but not when passing it through react-testing-library.

### Suggested solution:

I'm no expert and really don't know how to solve it. But I dug a little deeper into maybe why the bug is happening. 

Somehow react-testing-library isn't seeing the `<g>` element as an SVGGElement, but at best as an SVGElement (two parents up its prototype chain). Running the queried `<g>` element with "instance of SVGGElement" returns false in the codesandbox (and even throws an error of "SVGGElement is not defined" on my local machine). Running it with "instance of SVGGraphicsElement" returns false; with"instance of SVGElement" returns true on my local machine (false in the codesandbox). 

The problem is that `getBBox` is a method defined on the SVGGraphicsElement interface. SVGGElement inherits from SVGGraphicsElement which inherits from SVGElement. Since react-testing-library is seeing the `<g>` element as an SVGElement (at best), it hasn't inherited the `getBBox` method like it should. (Again, I'm no expert. Maybe I'm misunderstanding something here.)

**Comment by eps1lon** [comment]
This is an issue with the testing environment (here JSDOM) not the testing library. `getBBox` is not supported in JSDOM (https://github.com/jsdom/jsdom/issues/918). You need to run this particular test in a browser as you already realized.
