### ISSUE TITLE
onChange not triggered for child component of functional component using react hooks

### ISSUE THREAD

**Issue by dkaus1** [testing-library/react-testing-library#657]
- `@testing-library/react` version:
- `react` version: 16.12.0
- `node` version: 8.16.0
- `@testing-library/react` : 9.4.0
- `npm` (or `yarn`) version: 

### Relevant code or config:

```js
// Mycomp.js
import React, { useState } from 'react';
import InputField from './InputField.jsx'

const Comp = (props) => {
 const onChange = () => { 
 console.log("triggered");
}
 return (
   <InputField onChange={onChange} type='text' data-testid='email'/>
)
}
```

```js
// Mycomp.spec.js

import React from "react";
import Enzyme, { shallow, mount } from "enzyme";
import EnzymeAdapter from "enzyme-adapter-react-16";
import {Comp} from "./Mycomp";
import {render, fireEvent, screen} from '@testing-library/react'

const utils = render(<Comp />)
const input = utils.getByTestId('email')
fireEvent.change(input, { target: { value: 'test@test.com' } })
```

onChange method is not invoked as a part of code coverage for above code and if i replace the InputField with normal html input element then onChange method is covered as part of code coverage.

Please suggest what is missed here to fix this issue

**Comment by kentcdodds** [comment]
We really can't help much without seeing the `InputField` component itself.

Something you might try is using `@testing-library/user-event` to `type` rather than `fireEvent.change`. That typically works regardless of the implementation.

**Comment by dkaus1** [comment]
Thanks @kentcdodds  . I can explore user-event but here is below is Inputfield component. This component just return simple input text and take onchange prop.
InputField is simple react class component which has onchange 

class InputField extends React.Component {
onChange(e) {
		e = e || window.event;
                  const value = e.target.value || null;
	         this.props.onChange(this.props.fieldKey, value);
		}
render () {
 return (<input type='text' onchange={this.onChange} test-dataid={this.props.data-testid} />)
} 	

}

**Comment by kentcdodds** [comment]
Can you reproduce this issue in https://kcd.im/rtl-help?

**Comment by dkaus1** [comment]
Sure, I can do it. Meanwhile can you please tell how to trigger onChange event for above code using user-event package as I can't see option at https://github.com/testing-library/user-event

**Comment by dkaus1** [comment]
function InputField(props) {
  function onChange(){
    props.onChange();
  }
  return ( <input type='text' onChange={onChange} />)
}

function Counter() {
  const [count, setCount] = React.useState(0)
  function onChangeField() {
    console.log('m invoked');
  }
  return (
    <div>
      <div>{count}</div>
      <InputField onChange={onChangeField} />
      <button onClick={() => setCount(count + 1)}>click me</button>
    </div>
  )
}

**Comment by dkaus1** [comment]
> Can you reproduce this issue in https://kcd.im/rtl-help?

I have updated the code to mimic the same use case. But can't see the output console "m invoked"  .

**Comment by dkaus1** [comment]
> /*
> Hi! Need help with React Testing Library? The best way to get it is by forking
> this codesandbox, making a reproduction of your issue (or showing what you're
> trying to do) and posting a link to it on our spectrum chat:
> 
> https://spectrum.chat/testing-library/help-react
> 
> Click the "Tests" tab in codesandbox to get your tests running
> */
> 
> /*
> If you need to use APIs that do not work in codesandbox (like jest.mock for
> example), then please download this and make a github repository instead. Then
> post a link to your github repo.
> 
> P.S. This is Kent here. If you got here as a response to a tweet or email you
> sent me, I want to apologize for not responding more directly to you and just
> answering your question. I get many requests for help like yours every
> day and I don't have the bandwidth to respond to them all. Sorry :-/
> */
> 
> // here's an example
> import React from "react";
> import "@testing-library/jest-dom/extend-expect";
> import userEvent from "@testing-library/user-event";
> import { render, screen } from "@testing-library/react";
> 
> function InputField(props) {
>   function onChange() {
>     props.onChange();
>   }
>   return <input type="text" onChange={onChange} data-testid="email" />;
> }
> 
> function Counter() {
>   const [count, setCount] = React.useState(0);
>   function onChangeField() {
>     console.log("m invoked");
>   }
>   return (
>     <div>
>       <div>{count}</div>
>       <InputField onChange={onChangeField} />
>       <button onClick={() => setCount(count + 1)}>click me</button>
>     </div>
>   );
> }
> 
> test("renders counter", async () => {
>   render(<Counter />);
>   const count = screen.getByText("0");
>   const button = screen.getByText(/click me/i);
>   userEvent.click(button);
> 
>   const text = screen.getByTestId("email");
>   console.log(text);
>   expect(count).toHaveTextContent("1");
> });
> 

> We really can't help much without seeing the `InputField` component itself.
> 
> Something you might try is using `@testing-library/user-event` to `type` rather than `fireEvent.change`. That typically works regardless of the implementation.

I tried user-event type method , still no success. it does not invoke the method defined in parent functional component. Please suggest

**Comment by dkaus1** [comment]
> We really can't help much without seeing the `InputField` component itself.
> 
> Something you might try is using `@testing-library/user-event` to `type` rather than `fireEvent.change`. That typically works regardless of the implementation.

I tried user-event type method , still no success. it does not invoke the method defined in parent functional component. Please suggest

**Comment by dkaus1** [comment]
@kentcdodds : Thanks for all your comments. I have fixed the issue now based on your feedback.
