### ISSUE TITLE
Rerender doesn't trigger after fireEvents with file input

### ISSUE THREAD

**Issue by vadimshvetsov** [testing-library/react-testing-library#664]
- `@testing-library/react` version: ^9.5.0
- Testing Framework and version: jest@24.9.0
  
- DOM Environment: jest-dom@^4.2.4
  

### Relevant code or config:

```js
test("shows error from rules", async () => {
    const { result } = renderHook(() => useForm());

    const { getByTestId, getByText, rerender } = render(
      <FormContext {...result.current}>
        <form onSubmit={result.current.handleSubmit(() => {})}>
          <YetAnotherFileInput
            name="yai"
            rules={{ required: { value: true, message: "Is required" } }}
          />
          <input type="submit" data-testid="submit" />
        </form>
      </FormContext>
    );

    await act(async () => {
      fireEvent.click(getByTestId("submit"));
    });

    // Works only with manual rerender
    // rerender(
    //   <FormContext {...result.current}>
    //     <form onSubmit={result.current.handleSubmit(() => {})}>
    //       <YetAnotherFileInput
    //         name="yai"
    //         rules={{ required: { value: true, message: "Is required" } }}
    //       />
    //       <input type="submit" data-testid="submit" />
    //     </form>
    //   </FormContext>
    // );

    const errorTextEl = getByText(/is required/i);

    expect(errorTextEl).toBeTruthy();
  });
```

### What you did:

First case: I've rendered useForm hook, uploaded file with size more than allowed. 
Second case: I've rendered useForm hook, submit form without uploading required field.

### What happened:

If I upload file manually - everything works as expected.
But in test cases after `fireEvent` rerender doesn't fired.

### Reproduction:

[Codesandbox reproduction](https://codesandbox.io/s/condescending-resonance-j4cm9?from-embed=&file=/src/App.test.js:793-2582)

### Problem description:

There are 2 failing tests in reproduction codesandbox. Rerender did not trigger without manual rerender

### Suggested solution:

At first I thought there was an issue with `react-hook-form` and did post a [question](https://spectrum.chat/react-hook-form/help/seterror-doesnt-rerender-in-test-env~357605fa-29e8-488a-920b-4b436ba833a9).
Rerender fires after every [setError](https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L690) but not in test env.

Have no idea :/

**Comment by kentcdodds** [comment]
Hi @vadimshvetsov,

Combining react hooks testing Library with react testing Library like this is definitely not recommended.

You should instead simply render the function component that uses the hook (or make a test one that uses the hook).

**Comment by vadimshvetsov** [comment]
@kentcdodds thanks, this very helpful. I've rewrote test with it in mind and it passes now. Is there a way to assert values inside the hook with this kind of tests?

```ts
const FormWrapper = ({ children }: { children: React.ReactNode }) => {
  const methods = useForm()
  const onSubmit = methods.handleSubmit(() => {})
  return (
    <FormContext {...methods}>
      <form onSubmit={onSubmit}>
        {children}
        <input type="submit" data-testid="submit" />
      </form>
    </FormContext>
  )
})

test('shows validation error', async () => {
  const { container, getByText, getByTestId } = render(
    <FormWrapper>
      <AvatarField
        name="avatar"
        rules={{ required: { value: true, message: 'Is required' } }}
      />
    </FormWrapper>,
  )

  const submitButton = getByTestId('submit')

  await act(async () => {
    fireEvent.click(submitButton as HTMLButtonElement)
  })
  
  expect(getByText(/is required/i)).toBeInTheDocument()
  expect(container).toMatchSnapshot()
})
```

**Comment by kentcdodds** [comment]
You could test the hook separately or expose those values to what you render in your custom test component. Maybe this could be of help: https://kentcdodds.com/blog/how-to-test-custom-react-hooks

Also, take a look at https://kentcdodds.com/blog/common-mistakes-with-react-testing-library (you don't ned to wrap fireEvent with `act`).

**Comment by vadimshvetsov** [comment]
@kentcdodds Thanks, I will look.

Without `await act` it doesn't pass unfortunately

```ts
const FormWrapper = ({ children }: { children: React.ReactNode }) => {
  const methods = useForm()
  const onSubmit = methods.handleSubmit(() => {})
  return (
    <FormContext {...methods}>
      <form onSubmit={onSubmit}>
        {children}
        <input type="submit" data-testid="submit" />
      </form>
    </FormContext>
  )
})

test('shows validation error', () => {
  const { container, getByText, getByTestId } = render(
    <FormWrapper>
      <AvatarField
        name="avatar"
        rules={{ required: { value: true, message: 'Is required' } }}
      />
    </FormWrapper>,
  )

  const submitButton = getByTestId('submit')

  fireEvent.click(submitButton as HTMLButtonElement)
  
  expect(getByText(/is required/i)).toBeInTheDocument() // Can't find
  expect(container).toMatchSnapshot()
})
```

**Comment by kentcdodds** [comment]
Do this instead:

```javascript
expect(await findByText(/is required/i)).toBeInTheDocument() // Can find
```
