### ISSUE TITLE
Cleanup not happening when using configure from @testing-library/react

### ISSUE THREAD

**Issue by krajasekhar** [testing-library/react-testing-library#666]
- `@testing-library/react` version:`"10.0.4"`
- Testing Framework and version:`"jest": "26.0.1"`
  
- DOM Environment:`"@testing-library/jest-dom": "5.7.0"`
  

### What you did:
Using with jest with a setup file having just `import { configure } from "@testing-library/react";` with simple component

testing a component by using `getByTestId`

### What happened:
In the second test, getting the error `Found multiple elements by: [data-testid="myinputtest"]`
but when I un-comment import statement from the config file, it is passing.

![image](https://user-images.githubusercontent.com/5477450/81523619-fcc87200-936b-11ea-95e6-37655b7ab53d.png)

### Reproduction:
Codesandbox url: https://codesandbox.io/s/rtl-test-c8hj6
It is not failing in codesandbox but can reproduce by exporting as zip and trying in local
1. Download this repo.
2. Do 'npm i'
3. Do 'npm run start'

### Problem description:

Cleanup is not happening, can't select by using data-testid

**Comment by kentcdodds** [comment]
Hi @krajasekhar,

Here's the fix (in the jest config of package.json):

```json
"setupFiles": [
  "react-app-polyfill/jsdom"
],
"setupFilesAfterEnv": [
  "<rootDir>/config/jest/testingLibraryConfig.js"
],
```

Move the config to the `setupFilesAfterEnv` config because we require the jest environment to be setup to get the auto-cleanup functionality working.

Good luck!
