### ISSUE TITLE
Async tests with `waitFor` stay in loop and not finish the tests (freeze the execution).

### ISSUE THREAD

**Issue by EduhCosta** [testing-library/react-testing-library#674]
- `@testing-library/react` version: ^10.0.4
- Testing Framework and version: Jest@^26.0.0
  
- DOM Environment: @testing-library/jest-dom": "^4.0.0
  

### Relevant code or config:

This works.
```js
it('Should change localStorage when select was changed',  async () => {
    const model = createSelectModel();
    await wait();
    model.changeData('Data 1');
    model.changeData('Data 2');
    expect(localStorage.getItem('lotacao')).toEqual('2');
});
```

This freeze tests.
```js
it('Should change localStorage when select was changed',  async () => {
    const model = createSelectModel();
    await waitFor(() => {
      model.changeData('Data 1');
      model.changeData('Data 2');
      expect(localStorage.getItem('lotacao')).toEqual('2');
    });
});
```

### What you did:

I'm executing a test of an asynchronous select, ever if this select changes he executes a promise, to get new data.

### What happened:

When I updated the tests to use `waitFor`, all of them with two or more async callers freeze the execution.  

### Problem description:

In my job, all of the developers with using the new version, are doing a "parallel" solution to this problem.
Some using the `sixteen solution`, others using the `waitFor(() => waitFor())` and today we don`t have a common solution to all repositories.

### Suggested solution:

I'm debugging the error, and see the waitFor script inner the node_modules, and see this code.

```js
// Line 37 of wait-for.js
return new Promise((resolve, reject) => {
...
```

If I mapped correctly the error, to resolve this you can use the `Promise.all`, but I don't know if this is a correct mode because I don't know better about the MutationObserver API.

Someone can help me?

**Comment by kentcdodds** [comment]
Hi @EduhCosta,

Try this:

```javascript
it('Should change localStorage when select was changed',  async () => {
    const model = createSelectModel();
    model.changeData('Data 1');
    model.changeData('Data 2');
    await waitFor(() => {
      expect(localStorage.getItem('lotacao')).toEqual('2');
    });
});
```

You should avoid performing side-effects in `waitFor` callbacks. And `waitFor(() => waitFor())` should actually throw an error. That's definitely not supported.

Something that may be helpful to you is this: https://kentcdodds.com/blog/common-mistakes-with-react-testing-library

Good luck!
