### ISSUE TITLE
Add ability to use custom queries with screen

### ISSUE THREAD

**Issue by ml054** [testing-library/react-testing-library#675]
### Describe the feature you'd like:

Right now we can't use custom queries with screen object. It would be nice if we can register custom queries on screen object. 

### Suggested implementation:

Follow the logic currently implemented in render result - we can pass queries. 

### Describe alternatives you've considered:
```
export function rtlRender(ui: React.ReactElement, options?: Omit<RenderOptions, "queries">) {
    const allQueries = { ...queries, ...byNameQueries, ...byClassNameQueries };
    const container = render(ui, { wrapper: AllProviders, queries: allQueries,  ...options });
    
    const getQueriesForElementFunc = element => getQueriesForElement(element, { ...queries, ...byNameQueries, ...byClassNameQueries });
    const screen = getQueriesForElementFunc(document.body);
    
    return {
        ...container,
        screen: screen as Screen<typeof allQueries>,
        fillInput,
        fireClick,
        selectEvent,
        getQueriesForElement: getQueriesForElementFunc,
        fillInputs: (object: object) => fillInputs(object, container.getByName),
        waitForElementToBeRemoved
    };
}
```

**Please keep in mind that we have here  byNameQueries and byClassNameQueries which is ANTI-PATTERN**

**Comment by danieljcafonso** [comment]
Hey @ml054 I've asked this question in the past in https://github.com/testing-library/dom-testing-library/issues/516. The solution presented of pretending the queries worked for me!
