### ISSUE TITLE
Misleading deprecation warning when using waitForElement

### ISSUE THREAD

**Issue by pelotom** [testing-library/react-testing-library#677]
The current deprecation warning is misleading:

```
`waitForElement` has been deprecated. Use a `find*` query (preferred:
https://testing-library.com/docs/dom-testing-library/api-queries#findby) or
use `waitFor` instead (it's the same API, so you can find/replace):
https://testing-library.com/docs/dom-testing-library/api-async#waitfor
```

Specifically, the suggestion to "use `waitFor` instead (it's the same API, so you can find/replace)". I tried doing a find/replace and ran into a bunch of errors, because they are not equivalent: `waitForElement`'s promise will not resolve until you return something truthy.

**Comment by kentcdodds** [comment]
True. Thanks for the issue. Would you like to help by fixing that?

**Comment by pelotom** [comment]
Sure.
