### ISSUE TITLE
Unexpected behavior on input[type=number] with incomplete floating number

### ISSUE THREAD

**Issue by eunjae-lee** [testing-library/react-testing-library#678]
- `@testing-library/react` version: 10.0.4
- Testing Framework and version: jest@26.0.1
- DOM Environment: @testing-library/jest-dom@5.8.0

### Relevant code or config:

```jsx
<div>
  <label htmlFor="num">Num</label>
  <input id="num" type="number" />
</div>
```

### What you did:

```js
  render(<MyComp />)
  const value = '10.'
  const input = screen.getByLabelText(/num/i)
  fireEvent.change(input, {target: {value}})
  expect(input.value).toEqual(value)
```

### What happened:

```
Expected value to equal:
  "10."
Received:
  ""
```

### Reproduction:

https://codesandbox.io/s/dom-testing-library-template-65o0j?file=/src/__tests__/index.test.js:206-385

### Problem description:

When we have an `input` with `type=number`, what value do we expect to have after we set `10.` which isn't a valid float number?

https://codesandbox.io/s/kind-rgb-mlwsy?file=/src/index.js

If you run a code like this
```js
document.getElementById("app").innerHTML = `
<input type="number" />
`;

const input = document.querySelector("input");
input.value = "10.";

console.log("value: ", JSON.stringify(input.value));
```

![image](https://user-images.githubusercontent.com/499898/83020451-c6a41700-a028-11ea-9ffa-f43952bcab8d.png)

The result is like the above. What I see in the input is `10.` so I was expecting to receive `10.`, but in this console log, it's just `10`, and the result returned from testing-library was an empty string.

Although I wanted to have `10.`, according to this mini example, testing-library should've returned `10`. What do you think?

### Suggested solution:

As I'm not 100% sure what should be the correct output, I'm just opening this issue for a discussion.

**Comment by eps1lon** [comment]
This is unrelated to `@testing-library/react`. You would never see change events with an invalid input value. If you type "1" - "0" - "." - "1" you  would only see 3 change events for the values `1`, `10` and `10.1` but never a change event for the third input.

`input[type="number"]` is very strict when it comes to its input values. Maybe you find better advise on StackOverflow or our [spectrum.chat](https://spectrum.chat/testing-library?tab=posts)

**Comment by eunjae-lee** [comment]
@eps1lon Thanks for the reply. So I guess it's the strict behavior coming from `input[type="number"]`, not from `testing-library`.
