### ISSUE TITLE
AfterEach Cleanup not working

### ISSUE THREAD

**Issue by samuk190** [testing-library/react-testing-library#681]
When I setup my   "setupFilesAfterEnv": [
      "@testing-library/jest-dom/extend-expect",
      "react-testing-library/cleanup-after-each"
    ],

I get this error.

 Module react-testing-library/cleanup-after-each in the setupFilesAfterEnv option was not found.
         <rootDir> is: E:\RocketSeat\Projetos\ReactJS\modulo12

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

without that "cleanup-after-each"

my techlist test doesnt work.

```
` import { render, fireEvent,cleanup } from '@testing-library/react';
import React from 'react';
import TechList from '~/components/TechList';
// procura por texto dentro do elemento, ex button

describe('Techlist component', () => {
 
  beforeEach(() => {
    localStorage.clear();
  })
it('Should be able to add new tech', () => {

    const { getByText, getByTestId,getByLabelText } = render(<TechList />);

    // <input onChange={e => e.target.value} />
    //passar o elemneto do input
    //pega o valor htmlfor da label e do input id
    fireEvent.change(getByLabelText('Tech'), { target: {value: 'Node.js'} });
      
    fireEvent.submit(getByTestId('tech-form'));

      // fireEvent.click(getByText('Adicionar'));

      // debug();
       expect(getByTestId('tech-list')).toContainElement(getByText('Node.js'));
       expect(getByLabelText('Tech')).toHaveValue('');
       

});


it('Should store techs in storage', () => {
  let { getByText, getByTestId,getByLabelText } = render(<TechList />);
//precisa redefinir var
    // <input onChange={e => e.target.value} />
    //passar o elemneto do input
    //pega o valor htmlfor da label e do input id
    fireEvent.change(getByLabelText('Tech'), { target: {value: 'Node.js'} });
      
    fireEvent.submit(getByTestId('tech-form'));
    cleanup();

  //limpa a dom inteira para dar um reload e ver se a lista ta la
  ({ getByText, getByTestId,getByLabelText } = render(<TechList />));
  expect(getByTestId('tech-list')).toContainElement(getByText('Node.js'));
});
});
```
`
ERROR:  
  ● Techlist component › Should store techs in storage

    TestingLibraryElementError: Found multiple elements by: [data-testid="tech-list"]
    (If this is intentional, then use the `*AllBy*` variant of the query (like `queryAllByText`, `getAllByText`, or `findAllByText`)).

@testing-library/dom@^7.2.2"

"@testing-library/jest-dom@^5.8.0":

"@testing-library/react@^10.0.4":

"@testing-library/user-event@^7.1.2":

**Comment by samuk190** [comment]
Erased node modules and it solved itself

**Comment by bigfoot31** [comment]
Different libraries of testing-library seem to have version conflict issues.

The current combination of versions that work for me are
```json
"@testing-library/dom": "^7.10.1",
"@testing-library/jest-dom": "^5.9.0",
"@testing-library/react": "^10.2.1",
"@testing-library/user-event": "^11.4.0",
"jsdom": "^16.2.2",
```

**Comment by vanduc1102** [comment]
I found this page because i followed an old article, using an old version of `@testing-library`
I solved the issue by removing `jest.config.*` file, then run `npx jest --init`, it will generate a new `jest.config.*` file with the current installed jest.

**Comment by himanshu-1034** [comment]
@vanduc1102 's solution worked for me. I am unblocked. thanks
