### ISSUE TITLE
Not able to get popover component on mouse enter

### ISSUE THREAD

**Issue by drjosephliu** [testing-library/react-testing-library#682]
- `@testing-library/react` version: 0.0.2
- Testing Framework and version: React 16.13.1
   24.9.0
- DOM Environment: jest-dom 5.8.0
  

### Relevant code or config:

```
<Popover
    popoverClassName="market-selector-popover"
    content={marketMenu}
    interactionKind={PopoverInteractionKind.HOVER}
>
    <AnchorButton
        onMouseEnter={() => console.log("FIRE!")}
        data-testid="market-selector-btn"
        className="market-selector-btn"
        rightIcon="chevron-down"
        text="Button"
    />
</Popover>
    
it("Selects Spot tab and displays it", () => {
   const { getByTestId, getByText } = renderWithProviders(<MarketSelector />);
    
   fireEvent.mouseOver(getByTestId("market-selector-btn")); // FIRE!
   expect(getByText("Spot")).toBeInTheDocument();           // FAIL
});
```
Test failure msg:

```
TestingLibraryElementError: Unable to find an element with the text: Spot. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.
```

### What you did: 

Try to get `Popover` component that gets rendered when mouse hovers over a button using `fireEvent.mouseOver`

### What happened: 

Terminal shows the `Popover` is being triggered because console outputs `FIRE! FIRE!...`. However, test fails because it's unable to find a component in the `Popover` component (in this case I try to grab using `getByText("Spot")`). 

Note: when I change `Popover` to appear on button click and update test to `fireEvent.click`, then I'm able to `getByText("Spot")`

**Comment by weyert** [comment]
What if you try `await findByText("spot")`? Maybe it takes a bit of time before the component becomes available in the DOM so you might be checking too early

**Comment by drjosephliu** [comment]
Thanks for providing that link; I learned a ton of things that I was doing wrong!

So I changed my test case to:

  ```
  it("Selects Spot tab and displays it", async () => {
    renderWithMockRedux(<MarketSelector />);

    fireEvent.mouseOver(screen.getByTestId("market-selector-btn"));
    await waitFor(() => expect(screen.getByText("Spot")).toBeInTheDocument());
  });
```
And it's giving me `TypeError: MutationObserver is not a constructor`.

The weird thing is, I recreated a simpler example with the exact same dependencies and it's passing the test: https://codesandbox.io/s/adoring-tdd-hfikp?file=/src/App.js

I can't really figure out where this TypeError is coming from. Any ideas?


I believe this is how it should be written, though I may be wrong.

**Comment by drjosephliu** [comment]
Found the problem. Turns out CRA is using an old version of jsdom, which can be resolved by updating it: `yarn add -D jest-environment-jsdom-sixteen` and updating `package.json`. Please refer to the top comment in this post (https://stackoverflow.com/questions/61036156/react-typescript-testing-typeerror-mutationobserver-is-not-a-constructor).

**Comment by weyert** [comment]
Glad to hear you got it working, awesome!
