### ISSUE TITLE
screen.debug()  TypeScript support

### ISSUE THREAD

**Issue by JacobMGEvans** [testing-library/react-testing-library#684]
This may be a Feature or a Bug, unsure which category, either way, I can look into this with more input. 

### Describe the feature you'd like:

In TypeScript if you attempt to run `screen.debug()` it gives an expected argument error. Generally, this would be ideal type guard, however, the functionality expected which we get in plain JS is a full printout of the `render()`

### Suggested implementation:
Either there can be an optional on the first argument or something else that could allow for the 0 arguments to be passed in.

**Comment by JacobMGEvans** [comment]
More information, I am using an outdated version of RTL at work and this may be part of the issue. I will take a look at the source code later to see if I can find any fixes already in place and test in codesandbox

**Comment by kentcdodds** [comment]
Hi @JacobMGEvans! Hope you're doing awesome.

If you're using an outdated version of RTL, it's likely you're getting an outdated version of the types which does mark the element as required: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1f57d3641f9e128dba6ed35df6a88184290a3fc6/types/testing-library__dom/screen.d.ts#L11

More recent versions of DOM Testing Library have the type definitions within the package itself and they are correct: https://github.com/testing-library/dom-testing-library/blob/master/types/screen.d.ts#L11

I'm not sure what to do at this point. I think we'll just leave things as they are considering `screen.debug()` is something you only use during development (shouldn't be committed) and hopefully you'll be able to upgrade soon.
