### ISSUE TITLE
Rendering an element in beforeAll doesn't work with multiple tests

### ISSUE THREAD

**Issue by aiwatko** [testing-library/react-testing-library#686]
- `@testing-library/react` version: `9.5.0`
- Testing Framework and version: `jest@24.9.0`
- DOM Environment: `jsdom@14.1.0`

### Relevant code or config:

```js
    let myForm;
    beforeAll(async () => {
      myForm = render(
          <MyForm />
      );
      const submitButton = myForm.queryByTestId("submit-button");
     // wait function is needed for internal form (formik state to change)
      await wait(async () => {
        user.click(submitButton);
      });
    });

    // works fine if assertions are within the same test block
    it("expects errors to be in the DOM", () => {
      const error1 = myForm.queryByTestId(`error1`);
      expect(error1).toBeInTheDocument();

      const error2 = myForm.queryByTestId(`error2`);
      expect(error2).toBeInTheDocument();
    });
        
    // only first test works if assertions are split in 2 different tests
    it("expects error1 to be in the dom", () => {
      const error1 = myForm.queryByTestId(`error1`);
      expect(error1).toBeInTheDocument();
    });

    it("expects error2 to be in the dom", () => {
      const error2 = myForm.queryByTestId(`error1`);
      expect(error2).toBeInTheDocument();
    });
```

### What you did:

In order to optimise my form testing performance, I wanted to check all required fields' error with only one user interaction (submit click on empty form).
I wanted to achieve this with one `beforeAll` block that submits the form and captures the state of `myForm` and different `it` block for testing every field of the form.

### What happened:
It seems that with this approach only the first `it` block gets the correct state of my submitted empty form. The test `expects error2 to be in the dom` fails if I split my assertions in two different `it` blocks.

**Comment by iamalisajid** [comment]
Why you closed this ?

**Comment by brendan-donegan** [comment]
@aiwatko The version of render which you import in your test automatically runs cleanup after each spec. This conforms with best practice that each test should be self contained, but if you want to take the approach you are trying then you need to import render from `'@testing-library/react/pure'`

**Comment by Hakeemmidan** [comment]
After reading @brendan-donegan's comment that cleanup happens after each spec, I switched it to `beforeEach`, and it worked! = )

I assume that also follows best practices since it will do a render for each spec, and thus make them more self-contained.

**Comment by rayanfer32** [comment]
This took me a whole day to figure out, thanks to @brendan-donegan for this piece of info , which was nowhere to be seen in the official docs. This cleanup has to be highlighted in the docs, as it is a **hidden implicit procedure**  and as a developer will expect pure js to work as intended.

**Comment by MatanBobi** [comment]
@rayanfer32 Thanks for the feedback :)
We did try to highlight this procedure and already documented this in the [setup page](https://testing-library.com/docs/react-testing-library/setup/#skipping-auto-cleanup). 
Do you believe this isn't enough? If so, we'd be more than happy to accept a PR that explains this better :)

**Comment by rayanfer32** [comment]
I feel cleanup must not be performed implicitly as developers want to reuse the component once rendered.

**Comment by MatanBobi** [comment]
@rayanfer32 We do supply a way to bail out of auto cleanup for these specific use cases, but most of the developers working with the library are used to this behavior as it's documented already and IMO it's a good pattern to cleanup on our end rather than relying on the developers to cleanup after every test they run.
