### ISSUE TITLE
@types/testing-library__react"' has no exported member 'waitFor'

### ISSUE THREAD

**Issue by matassp** [testing-library/react-testing-library#688]
Sorry, for duplicating issue #610 , but it looks like it was closed unresolved.

```
    "@testing-library/react": "10.0.5",
    "@testing-library/jest-dom": "5.9.0",
    "react": "16.13.1",
```

Relevant code or config:
`import {  waitFor } from '@testing-library/react';`

What happened:
I get a typescript error:

`@types/testing-library__react"' has no exported member 'waitFor'.ts(2305)`

**Comment by samtsai** [comment]
@matassp what version of `@testing-library/dom` is in your `yarn.lock` or `package-lock.json`?

**Comment by pranjaljately** [comment]
The quickest way I found to fix this was to:
1. Delete node_modules and your .lock file (yarn or package-lock)
2. Install the dependencies again (npm install or yarn install)

**Comment by kentcdodds** [comment]
I'm definitely willing to accept a pull request to bring type definitions within this repo [like we did with DOM Testing Library](https://github.com/testing-library/dom-testing-library/pull/530). That would help us avoid issues like this in the future.

**Comment by matassp** [comment]
thank you!
