### ISSUE TITLE
Run cleanup() when test runner supports teardown()

### ISSUE THREAD

**Issue by screendriver** [testing-library/react-testing-library#689]
I guess my comment in my pull request https://github.com/testing-library/react-testing-library/pull/676 was overlooked but I don't know how to fix my pull request:

- linting fails because teardown is not defined. Is this somewhere deep in eslint-config-kentcdodds?
- I had problems to write a test for that because you are using Jest which does not have teardown()

**Comment by eps1lon** [comment]
Sorry for letting the PR get stale. Let's keep the discussion in the PR though.
