### ISSUE TITLE
afterEach(cleanup) not being called automatically when using styled-components ThemeProvider

### ISSUE THREAD

**Issue by rishitank** [testing-library/react-testing-library#708]
### Problem description
Hi, currently when using a `ThemeProvider` it results in a new element rendered to the DOM in each test, resulting in the error `TestingLibraryElementError: Found multiple elements by: [data-testid....`

- `@testing-library/react` version: v10.2.1
- Testing Framework and version: jest v26.0.1
- DOM Environment: jest-environment-jsdom-sixteen v1.0.3

### What you did:

```
import React from 'react';
import { render } from '@testing-library/react';
import { ThemeProvider } from 'styled-components';
import { colours, layout } from '@themes';
const theme = {
  colours,
  layout
};

const renderComponent = ({ ...props } = {}) => render(
  <ThemeProvider theme={theme}>
    <div data-testid="content" {...props} />
  </ThemeProvider>
);

describe('my test', () => {
  it('should render correctly', () => {
    const { container } = renderComponent();

    expect(container).toMatchSnapshot();
  });

  it('should contain the content', () => {
    const { getByTestId } = renderComponent();
    expect(getByTestId('content')).not.toBeNull();
  });
});
```

### What happened:

TestingLibraryElementError: Found multiple elements by: [data-testid="content"]

**Comment by eps1lon** [comment]
I can't reproduce this in a codesandbox: https://codesandbox.io/s/great-cherry-tix62?file=/src/index.test.js

This is either a problem with your setup or with `@themes` (what is this?). We need to complete repro to check if this an issue with `@testing-library/react`.

**Comment by rishitank** [comment]
@eps1lon I've changed the code in codesandbox to be close to my current implementation, however the snapshot test is unable to update, so I'm wondering if that were to pass would the issue occur or not...

**Comment by rishitank** [comment]
@eps1lon I've found the culprit, I was using a test helper that was loaded into jest via `setupFiles` and in that helper `render` was being used. If I used something like enzyme instead, the problem went away, so I'm guessing it is related to using the `render` function at the wrong time...

**Comment by eps1lon** [comment]
If you use `render` outside of the test runs you need to cleanup manually. We can only cleanup in `afterEach`

**Comment by roginfarrer** [comment]
I'm encountering the same issue, but only recently. I have a repo that has been using the [custom render](https://testing-library.com/docs/react-testing-library/setup#custom-render) as documented, without manually invoking `cleanup` and it works fine. When creating a new repo with the same pattern, I'm finding the same errors around not having any cleanup called.

If this error is expected, can we/should we update the custom render page in the docs to say that using that pattern will require manual cleanup?

**Comment by MatanBobi** [comment]
> I'm encountering the same issue, but only recently. I have a repo that has been using the [custom render](https://testing-library.com/docs/react-testing-library/setup#custom-render) as documented, without manually invoking `cleanup` and it works fine. When creating a new repo with the same pattern, I'm finding the same errors around not having any cleanup called.
> 
> If this error is expected, can we/should we update the custom render page in the docs to say that using that pattern will require manual cleanup?

Having a custom render while it's called within the `test` is fine and won't cause the problem discussed here.. This problem only occurs if you call the render function outside your `test`.
Is that what you did @roginfarrer ? And that worked before and now it's not?

**Comment by roginfarrer** [comment]
Yeah, below is some pseudo code of what we're doing:

```js
// src/testUtils.js

import React from 'react';
import {render} from '@testing-library/react';
import {ThemeProvider} from 'styled-components';

const Providers = ({children}) => (
  <ThemeProvider theme={...}>{children}</ThemeProvider>
);

const themedRender = (ui, options) =>
  render(ui, {wrapper: Providers, ...options});

export * from '@testing-library/react';
export {themedRender as render};
```

```js
// src/Table/__tests__/Table.test.js

import React from 'react';
import Table from '../Table';
import {render} from '../../testUtils';

describe('Table', () => {
  it('test name', () => {
    const {...} = render(<Table />);
    expect(...).toBe(...)
  });

  it('test name', () => {
    const {...} = render(<Table />);
    expect(...).toBe(...)
  });

  it('test name', () => {
    const {...} = render(<Table />);
    expect(...).toBe(...)
  });
});
```

By the last test, when I run `debug()`, there's 3 instances of the component being rendered. I assumed that this should work since even though the render function is being referenced outside the test, it's not being called outside of the test.

Adding `cleanup` manually on `afterEach` fixes the problem.

**Comment by roginfarrer** [comment]
Ah, it turns out that the same issue can be caused by a separate symptom: set-up file order

I have a set-up file that sets the default testId attribute: `configure({testIdAttribute: '...'})`,  and I imported that set-up file into the jest config. Making the following change fixed the tests not cleaning up:

```diff
// jest.config.js

module.exports = {
-  setupFiles: ['./jest.setup.js'],
-  setupFilesAfterEnv: ['@testing-library/jest-dom/extend-expect'],
+  setupFilesAfterEnv: ['@testing-library/jest-dom/extend-expect', './jest.setup.js'],
}
```

Same solution to this issue https://github.com/testing-library/react-testing-library/issues/666
