### ISSUE TITLE
addEventListener inside setTimeout doesn't work

### ISSUE THREAD

**Issue by kozzztya** [testing-library/react-testing-library#719]
- `@testing-library/react` version: 10.3.0
- Testing Framework and version: jest 26.0.1
  
- DOM Environment: "@testing-library/jest-dom": "^5.10.1"
  

### Relevant code or config:

```js
const React = require('react')
const { render, fireEvent } = require('@testing-library/react')

function Comp() {

  React.useEffect(() => {
    setTimeout(() => {
      document.addEventListener('mouseleave', () => console.log('triggered in timeout'));
      console.log('timer worked');
    }, 0);

    document.addEventListener('mouseleave', () => console.log('triggered not in timeout'));

    document.addEventListener('mouseleave', () => console.log('triggered not in timeout again'));
  }, [])
  return null
}

test('runs', (done) => {
  render(React.createElement(Comp))
 
  fireEvent.mouseLeave(document);

  setTimeout(done, 2000)
})
```

### What you did:

I tested 'mouseleave' event. Listener creates in setTimeout after some time. And everything is working with manual testing.

### What happened:

Listener inside of setTimeout didn't trigger. But everything is working for addEventListener outside of setTimeout.

### Reproduction:

Run this repl:
https://repl.it/repls/WildFabulousFibonacci#index.test.js

"console.log('triggered in timeout'))" will not work. But other logs will work.

### Problem description:

Event listener doesn't work inside of setTimeout in tests. Outside of setTimeout it triggers. With manual testing after npm start of such code no problem.

**Comment by eps1lon** [comment]
Could you convert this to a codesandbox.io so that we're able to investigate what happens in a real browser?

It's odd that mouseleave is triggered on the document anyway. [`mouseleave` shouldn't bubble](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseleave_event).

**Comment by eps1lon** [comment]
Nevermind. You need to let the timers run before you fire the event. You can see in the log that the timer is executed after the event is dispatched which means any listener added in the timer won't trigger.

**Comment by marcosvega91** [comment]
`setTimeout` is run on the next event loop so you need to wait the event to be attached before fire it.

[here](https://repl.it/repls/SwiftRequiredTruespace) I have used `useFakeTimers` as an example
