### ISSUE TITLE
Complex example from README.md file is not passing with jest + jsdom

### ISSUE THREAD

**Issue by spamshaker** [testing-library/react-testing-library#725]
- `@testing-library/react` version: 10.4.3
- Testing Framework and version: Jest: 26.1.0
  
- DOM Environment: jest-environment-jsdom, jsdom:16.2.2
  

### Relevant code or config:
https://github.com/testing-library/react-testing-library/blob/master/README.md#complex-example

### What you did:
1. forked to https://github.com/spamshaker/dom-testing-library-template
1. added two files base on example [README.md#complex-example](https://github.com/testing-library/react-testing-library/blob/master/README.md#complex-example)
here (https://github.com/spamshaker/dom-testing-library-template/pull/1/commits/1ee1ff0155f5f24987ae8ca85ab431084210b71f) 
2. Got couple of errors which are fixed step by step in the pull request https://github.com/spamshaker/dom-testing-library-template/pull/1

### What happened:

Cannot run mentioned example with basic configuration + code contains some bugs which fails tests

### Reproduction:
clone exact commit https://github.com/spamshaker/dom-testing-library-template/pull/1/commits/1ee1ff0155f5f24987ae8ca85ab431084210b71f
`npm i`
`npm run test`

### Problem description:

This complex example is not passing in jest jsdom due to couple of issues 

### Suggested solution:
replace [README.md#complex-example](https://github.com/testing-library/react-testing-library/blob/master/README.md#complex-example) code by files from PR
https://github.com/spamshaker/dom-testing-library-template/pull/1/files
or include reference to repo that resolves those issues and allows to run and pass unit tests

**Comment by nickmccurdy** [comment]
I don't think the Babel config is needed, CRA's defaults for Jest should be fine. I'm also not sure issues there are with dom-testing-library-template vs react-testing-library. Could you please open separate PRs in both repos to address some of these repos (assuming there are issues with both) so we can have a more focused review?

**Comment by lidoravitan** [comment]
Can I help with it?

**Comment by lidoravitan** [comment]
I played with it a bit and it looks fine. 
Locally RCA works great except from few errors which fixed by #806.

about the Code Sandbox, I guess this happens because the complex example uses `msw/node` so it won't work there.
https://codesandbox.io/s/dom-testing-library-template-forked-2se34?file=/src/__tests__/login.test.js
```[MSW] Failed to execute `setupServer` in the environment that is not NodeJS (i.e. a browser). Consider using `setupWorker` instead.```
for more details, as the error points to, take a look on [mswjs/msw Browser ](https://github.com/mswjs/msw#browser)section

**Comment by MatanBobi** [comment]
@nickmccurdy IMO we can close this one, the complex example in README was updated by @lidoravitan and the codesandbox with `msw` won't work since it needs NodeJS environment to run.. wdyt?

**Comment by nickmccurdy** [comment]
It seems like most issues here have either been solved or given suggested fixes. I'll close this but if @spamshaker still has issues feel free to reply.
