### ISSUE TITLE
Trying to use prettyDOM, TypeError: container is not a function but works anyways

### ISSUE THREAD

**Issue by imyjimmy** [testing-library/react-testing-library#741]
Reading the docs for [debug](https://testing-library.com/docs/react-testing-library/api#debug), I thought it was pretty cool to be able to do the following:

```
const { debug } = render(<HelloWorld />)
debug()
```

So I tried it out in my own tests using `const { container }`, and then `container()`, but got the following fail test and error:

`TypeError: container is not a function` 

However, the console went ahead and printed the output of container anyways. What can I do to suppress TypeError?

**Comment by marcosvega91** [comment]
Hi @imyjimmy thanks for opening the issue :).

Container returned from render function is a DOM element and not a function. You can call `querySelector`, `getElementsByTagName` or every other function that you can call on node. 

Container is by default a `div` that will wrap your code

**Comment by imyjimmy** [comment]
🤦‍♂️ of course.
