### ISSUE TITLE
Right click doesn't trigger onMenuContext

### ISSUE THREAD

**Issue by michaelsharpe** [testing-library/react-testing-library#742]
- `@testing-library/react` version: 10.4.5
- Testing Framework and version: booted from latest create react app.
- DOM Environment: @testinbg-library/jest-dom ^4.2.4

I am not sure if this is a bug, or if I am doing something wrong, but here it is...

### Relevant code or config:

```js

describe('click test', () => {
  it.only('should call the click handler', () => {
    const onClick = jest.fn().mockName('updateTalent');

    const {queryByTestId} = render(
      <div onContextMenu={onClick} data-testid="button"></div>,
    );

    fireEvent.click(queryByTestId('button'), {button: 2});
    expect(onClick).toHaveBeenCalled();
  });
})
```

### What you did:

I was trying to set up a test on my react component to ensure that a function prop was called when the right mouse button is clicked (ie onContextMenu).

### What happened:

Handler is not called.

### Reproduction:

I ran the above test snippet in a fresh CRA instance to ensure it wasn't anything else.  For some reason it seems that the onContextMenu is not picking up the event being generated by the testing library.

### Problem description:

It would be good to test event handling on right mouse clicks in my components.

### Suggested solution:

I'll dig in and see what I can find when I have time.

**Comment by MatanBobi** [comment]
Hi @michaelsharpe,
to trigger a right click you should actually either try `fireEvent.contextMenu(queryByTestId('button'))` or use the `user-event` package which ["tries to simulate the real events that would happen in the browser as the user interacts with it"](https://github.com/testing-library/user-event#the-solution).
Since `click` with the right button doesn't really trigger a `contextmenu` event, it wouldn't work as you expect it to.

**Comment by ut2k** [comment]
`fireEvent.contextMenu(queryByTestId('button'))` doesn't trigger a right click for me any suggestions?

**Comment by MatanBobi** [comment]
> `fireEvent.contextMenu(queryByTestId('button'))` doesn't trigger a right click for me any suggestions?

Can you share your code please? That way we'll be able to help :)

**Comment by ut2k** [comment]
Hi, the righ click event works, the problem was somewhere else. Sorry about that and thank you for your prompt response.

**Comment by ad1992** [comment]
@MatanBobi I am using `fireEvent.contextMenu` to trigger the context menu, it works fine when context menu is rendered on body when its rendered on a container its not working. Any idea why this could happen ?

**Comment by MatanBobi** [comment]
> @MatanBobi I am using `fireEvent.contextMenu` to trigger the context menu, it works fine when context menu is rendered on body when its rendered on a container its not working. Any idea why this could happen ?

What do you mean @ad1992 ? Can you share a code example of this one?

**Comment by ad1992** [comment]
@MatanBobi in this file https://github.com/excalidraw/excalidraw/blob/b2822f353882d0d479c809da4212862091ab9665/src/components/ContextMenu.tsx#L51
if i change it to `document.querySelector('.excalidraw').appendChild(div)` the specs start breaking

**Comment by MatanBobi** [comment]
> @MatanBobi in this file https://github.com/excalidraw/excalidraw/blob/b2822f353882d0d479c809da4212862091ab9665/src/components/ContextMenu.tsx#L51
> if i change it to `document.querySelector('.excalidraw').appendChild(div)` the specs start breaking coz the menu is not getting rendered for example this [spec](https://github.com/excalidraw/excalidraw/blob/b2822f353882d0d479c809da4212862091ab9665/src/tests/regressionTests.test.tsx#L710) even if I change the selector from `GlobalState.canvas` to `document.querySelector('.excalidraw')`.
> I am not sure if I am missing something here.
> Let me know if you need any more information on this.

Sorry it took me time to respond.
I'm not 100% sure without debugging this one, but it might be related to the fact that you're creating a DOM element without React in the way and therefor the `act` that should make sure what we see in the test equals to what the user sees doesn't wrap this side effect.
Any chance to get a reproduction? You can use http://kcd.im/rtl-help
