### ISSUE TITLE
Problem with getByRole on listitem

### ISSUE THREAD

**Issue by rehman-00001** [testing-library/react-testing-library#752]
Could someone please help me with this issue?
https://stackoverflow.com/questions/63033144/unable-to-use-getbyrole-on-listitem-with-a-specific-name-rtl

I'm not sure what I am missing here. getByRole on listitem isn't working as expected :(

Codesandbox link:
https://codesandbox.io/s/wandering-browser-mrf78?file=/src/App.test.js

**Comment by eps1lon** [comment]
Answered on StackOverflow: https://stackoverflow.com/a/63080940/3406963

**Comment by rehman-00001** [comment]
Thanks a lot for the quick response. :pray:
