### ISSUE TITLE
TypeError: _react2.fireEvent.submit(...) is not a function

### ISSUE THREAD

**Issue by IgorCruzz** [testing-library/react-testing-library#753]
"jest": "^26.1.0",
"babel-jest": "^26.1.0",
"@testing-library/react": "^10.4.7",
"@testing-library/jest-dom": "^5.11.1",
"jest-extended": "^0.11.5",

im trynna test my code, but it gives an error "TypeError: _react2.fireEvent.submit(...) is not a function", I dont know how to fix it, This error appears when i put the **"({ getByText, getByTestId, getByLabelText } = render(<TechList />)) "**, in the second test.

I need to test if the text "Node.js" stay in the component even when i rerender it., I put the cleanup() to clean the component. but it is depecrated, so i dont  know what can i do

How can i do, to render the same component twice times in one test, whitout the "cleanup()"?

My test code below:

```
 import '@testing-library/jest-dom/extend-expect'
import React from 'react' 
import { render, fireEvent } from '@testing-library/react'

import TechList from '../components/Techlist'

 describe('TechList component', () => {
 
   it('should be able to add new Tech', () => {  
      const { getByText, getByTestId, getByLabelText } = render(<TechList />)

      fireEvent.change(getByLabelText('Tech'), { target: { value: 'Node.js' }})
      fireEvent.submit(getByTestId('tech-form')) 
    
      expect(getByTestId('tech-list')).toContainElement(getByText('Node.js'))
      expect(getByLabelText('Tech')).toHaveValue('')
   })
 
   it('should store techs in storage', () => {
     let { getByText, getByTestId, getByLabelText} = render(<TechList />)

     fireEvent.change(getByLabelText('Tech'), { target: { value: 'Node.js' }})
     fireEvent.submit(getByTestId('tech-form')) 


   //cleanup() -> I put this, but doesnt work, cause it  is depecrated

    ({ getByText, getByTestId, getByLabelText } = render(<TechList />))  // When I call this, gives the error TypeError: _react2.fireEvent.submit(...) is not a function

     expect(getByTestId('tech-list')).not.toContainElement(getByText('Node.js'))
   })
 
 })
```
and the Component:

```
    import React, { useState } from 'react'; 

function Component() {
  const [techs, setTechs] = useState([])
  const [newTech, setNewTech] = useState('')
  
  function handleAddTech() {
    setTechs([...techs, 'Node.js'])
    setNewTech('')
  }

  return (
    <form data-testid="tech-form" onSubmit={handleAddTech} >      
     
      <ul data-testid="tech-list">
      {techs.map(tech => <li key={tech}>{tech}</li>)}
      </ul>
      <label htmlFor="tech">Tech</label>
      <input id="tech" type="text" value={newTech} onChange={e => setNewTech(e.target.value)}/>

      <button  type="submit" onClick={handleAddTech}>Adicionar</button>
    </form>
  )
}

export default Component;
```

Jest.config.js:
```
module.exports = { 
  bail: 1, 
  clearMocks: true,
  collectCoverage: true,
  collectCoverageFrom: ['components/*.js'], 
  coverageDirectory: "__tests__/coverage", 
 coverageReporters: [  
   "text",
   "lcov",   
 ], 
  setupFilesAfterEnv: [
    "@testing-library/jest-dom/extend-expect"
  ],
  testEnvironment: "jsdom", 
  testMatch: [
    "**/__tests__/*.spec.js",    
  ], 
  transform: {
    ".(js|jsx|ts|tsx)": "babel-jest"
  }
}
```
setupTest.js:

`import '@testing-library/jest-dom/extend-expect'`

**Comment by marcosvega91** [comment]
Hi @IgorCruzz thanks for opening the issue :) 

 @testing-library/react requires @testing-library/dom for working.

**Comment by kentcdodds** [comment]
Hi @IgorCruzz,

This issue is due to automatic semicolon insertion issues (which you would be warned about if you used [this rule](https://eslint.org/docs/rules/no-unexpected-multiline) in ESLint).

This code:

```javascript
fireEvent.submit(getByTestId('tech-form')) 
({ getByText, getByTestId, getByLabelText } = render(<TechList />))
```

Could be rewritten like so:

```js
fireEvent.submit(getByTestId('tech-form'))({ getByText, getByTestId, getByLabelText } = render(<TechList />))
```

See the problem? You're invoking the returned result of your call to `fireEvent.submit`.

What you should probably do is use `screen` rather than destructuring the return value of `render` and then you don't need to worry about this at all. [Learn more](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library).

Good luck!

**Comment by IgorCruzz** [comment]
Thanks, I put the **screen**  and it works

**Comment by nickmccurdy** [comment]
Alternatively, you could call `rerender(<TechList />)` without destructuring.
