### ISSUE TITLE
preventDefault does not result in defaultPrevented being set true

### ISSUE THREAD

**Issue by BurgersMcSlopshot** [testing-library/react-testing-library#754]
- `@testing-library/react` 10.4.7:
- Testing Framework and version: Jest 26.0.7
- DOM Environment: jsdom 15.2.1
- Node: 14.4.0

### Relevant code or config:

```js
it('should prevent default on a click event', () => {
    const onClick = event => event.preventDefault();
    const { container } = render(<a onClick={onClick}></a>);
    const anchor = container.firstElementChild;
    const event = createEvent.click(anchor);
    fireEvent.click(anchor, event);
    expect(event.defaultPrevented).toBeTruthy();
}
```

### What you did:

I was updating a test to ensure that a click event handler would invoke prevent default

### What happened:

preventDefault was invoked on the event but the property defaultPrevented was not set to true nor is there
any indication via the event that preventDefault was invoked

### Reproduction:

1. Run the test 'should prevent default on a click event'
expected result: test passes
actual result: test fails on the defaultPrevented assertion

### Problem description:

From what I can tell, checking whether or not defaultPrevented is true is the way to establish whether or not an event's preventDefault was triggered.

### Suggested solution:

I haven't been able to track down test event firing all the way through yet, so I have no suggestion.

**Comment by BurgersMcSlopshot** [comment]
Note: switching `fireEvent.click(anchor, event);` to `anchor.dispatch(event)` seems to produce the expected results.  I do not know if this behavior is intended though it is a bit surprising.

**Comment by kentcdodds** [comment]
The second argument to `fireEvent.click` isn't an event, it's just properties you want applied to the event, so I'm unsurprised that this doesn't quite work. What you probably should do instead is:

```javascript
const anchor = container.firstElementChild;
const event = createEvent.click(anchor);
fireEvent(anchor, event);
expect(event.defaultPrevented).toBeTruthy();
```

Hope this helps! Thanks :) 

If you'd like to add something about this to [the docs](https://testing-library.com/docs/dom-testing-library/api-events#fireevent) that would be welcome :)
