### ISSUE TITLE
Mocked dataTransfer items are overwritten by rtl

### ISSUE THREAD

**Issue by Snizhana** [testing-library/react-testing-library#756]
- `@testing-library/react` version: `10.2.1`
- Testing Framework and version: jasmine version `3.5.0`
- Test runner: karma version `4.0.1`
- DOM Environment: chrome version `83`

### Relevant code or config:

```js
const dragNdropZone = component.getByTestId('drag-n-drop-zone');
const fileName = 'testFileName';

const fileItem = {
  name: fileName,
  size: 100,
  type: 'file',
};

const fileEntry = {
  name: fileName,
  fullPath: `folder_one/folder_two/${fileName}`,
  file: (resolve) => resolve(fileItem),
};

const itemOne = {
  webkitGetAsEntry: () => fileEntry,
};

const dataTransfer = new DataTransfer();

Object.defineProperty(dataTransfer, 'items', {
  value: [itemOne],
});

fireEvent.drop(dragNdropZone, { dataTransfer });

```

### What you did:
I am trying to test drag-and-drop functionality.

### What happened:
rtl overrides items in `dataTransfer` object assigning an empty array to it

### Reproduction:
If we check an event object passed to the `onDrop` handler of  `dragNdropZone` we'll see that `e.dataTransfer.files` is an empty array even though we assigned an array with one item.

### Problem description:

I am not able to mock items as a prop of `dataTransfer` object and test drag-and-drop functionality properly. **NOTE:** mocking worked correctly in rtl version `9.2.0`

**Comment by kentcdodds** [comment]
That solution looks good to me. But let's make sure to handle the case where DataTransfer is not supported by the environment as well.

Would you be interested in contributing this fix?

**Comment by Snizhana** [comment]
@kentcdodds I am sorry, it seems I need to submit the issue to dom-testing-library

**Comment by Snizhana** [comment]
@kentcdodds I am sorry, it seems I need to submit the issue to dom-testing-library
