### ISSUE TITLE
Incorrect userEvent import in the cheat sheet

### ISSUE THREAD

**Issue by sapegin** [testing-library/react-testing-library#759]
### Problem description:

The `userEvent` is incorrectly imported in the [cheat sheet PDF](https://github.com/testing-library/react-testing-library/raw/master/other/cheat-sheet.pdf).

### Suggested solution:

It should be a default import instead of a named one:

```diff
- import { userEvent } from '@testing-library/user-event';
+ import userEvent from '@testing-library/user-event';
```

Unfortunately, can’t send a pull request because I don’t have Affinity Publisher.

**Comment by kentcdodds** [comment]
Ah, whoops! Thanks for letting us know. cc @weyert could you get that fixed please?

**Comment by weyert** [comment]
Whoops totally missed this message. I will update it :)
