### ISSUE TITLE
Implementing a method to access components by name

### ISSUE THREAD

**Issue by m98** [testing-library/react-testing-library#762]
**Note:** I know I'm supposed to post this issue on dom-testing-library, but it's not related to common queries, and it's just related to React. So, here might be a better place for it.

### What's the problem?
Imagine there is a  `Comment` component, and we have another component named`CommentList`

In the case of having pagination, how can we check the correct number of `Comment` is showing in the `CommentList`? How to check `Comment`s sort and order?

the comment does not have an identical text (they are user-generated), and we can't access to them by `getAllByText`, and in the `CommentList` component, we might have a specific `role` repeated in different places, so it's not easy to count `Comment` components or access each of them.

### What's the solution?
We need something special for that. What if we could have `getByComponentName` and `getAllByComponentName`?  in this case, we could simply do something like:
```
render(<CommentList/>)
expect(screen.getByComponentName('Comment')).toHaveLength(10);
```

### Is it not against RTL's philosophy?
I believe it's not against the React-Testing-Library's philosophy "similarly to how users would find things", users might not know what a component is, but they know different between "comment" and "comment list", or "search" and "product item"

If you're agreeing to me, I would be very happy to work on it

**Comment by m98** [comment]
I have to move this to dom-testing-library

**Comment by afontcu** [comment]
Hi! 👋 

> the comment does not have an identical text (they are user-generated), and we can't access to them by getAllByText

You could rely on `data-testid` and `getAllByTestId` and assert the length of the resulting array.

> …and in the CommentList component, we might have a specific role repeated in different places, so it's not easy to count Comment components or access each of them.

A combination of `within` and `getByRole` would help you narrow down the search. Again, `data-testid` might do the trick, too.


> I believe it's not against the React-Testing-Library's philosophy "similarly to how users would find things", users might not know what a component is, but they know different between "comment" and "comment list", or "search" and "product item"

I do believe this is against Testing Lib principles. The difference between a comment and a comment list might be their structure, their roles, whatever. The fact that this issue "is not related to common queries, and it's just related to React" is a warning sign that we would be relying on implementation details – one as big as component names!

Hope it helps!

**Comment by kentcdodds** [comment]
Thanks for taking the time to open the issue and discussion @m98. And thank you @afontcu for your thoughtful response.

I agree with @afontcu here (and I expect all the other maintainers will as well) so I'm going to close this one. Thanks anyway!
