### ISSUE TITLE
Can't find input on submitting an uncontrolled form

### ISSUE THREAD

**Issue by renerbaffa** [testing-library/react-testing-library#763]
- `@testing-library/react` version: 10.4.8
- Testing Framework and version: "react-scripts": "3.0.1"
- DOM Environment: "react-scripts": "3.0.1"

### What you did:

Given a form with uncontrolled input, when submitting, it is not possible to find the input element by using `event.target`.

### What happened:

When submitting the form, the function you provide as handler takes the event as argument. In the browser it is possible to access inputs of the form by doing `event.target.inputName`. In jest, `inputName` is not defined.

### Reproduction:

https://codesandbox.io/s/bold-germain-h0mfd

**Comment by renerbaffa** [comment]
I also tried out using the `user-event` library but did not work as well:

**Comment by kentcdodds** [comment]
It should be: `element.target.elements.inputName`:

https://codesandbox.io/s/wonderful-hofstadter-fxbbu?file=/src/Form.js:106-205

```
console.log(event.target.elements.testing)
console.log(event.target.elements.testing.value)
```

That works :) Cheers!

**Comment by renerbaffa** [comment]
Nice ...
Thanks a lot!
:)
