### ISSUE TITLE
Type Definition on `screen` is potentially incorrect with VSCode complaining

### ISSUE THREAD

**Issue by arggrande** [testing-library/react-testing-library#765]
- `TypeScript` + `Create-React-App Template`
- `@testing-library/react` version: 9.5.0
- Testing Framework and version: `jest` 24.9.1
- DOM Environment: `react-dom` is 16.13.1

What happened:

TypeScript doesnt like invoking `screen.debug()` with no parameters. It still *runs*, but VSCode syntax highlighting (because of TypeScript) gives a red squiggly.

Looking at the Type Definition:
```javascript
// screen.d.ts
export type Screen<Q extends Queries = typeof queries> = BoundFunctions<Q> & {
    /**
     * Convenience function for `pretty-dom` which also allows an array
     * of elements
     */
    debug: (
        element: Element | HTMLDocument | Array<Element | HTMLDocument>,
        maxLength?: number,
        options?: OptionsReceived,
    ) => void;
};
```

Suggested solution:

I suspect `element` may need to be changed to nullable (with `?` in the definition of the parameter), as the rest of these are currently nullable. Though its possible I dont understand *why* the `element` param wasnt nullable in the first place.

Happy to help fix it if I can get some guidance on how, whether thats a code fix here, or a fix on the typings themselves.

**Comment by MatanBobi** [comment]
Hi @arggrande, thanks for opening this issue!
Following Kent's comment [here](https://github.com/testing-library/react-testing-library/issues/684#issuecomment-637183391)
you can see [here](https://github.com/testing-library/dom-testing-library/blob/master/types/screen.d.ts#L11) that `element` is actually nullable.. Maybe you're using an older version of RTL?

**Comment by arggrande** [comment]
Oh my god you're exactly right >_<

I didnt realise my version was so out of date -_- Interestingly this is what came with the create-react-app template for typescript. 

Thanks, I'll close this <3

**Comment by nickmccurdy** [comment]
FYI the react-scripts 4 alpha has more up to date dependencies
