### ISSUE TITLE
Can I use the testing library logo (octopus) for personal use?

### ISSUE THREAD

**Issue by AlastairM-E** [testing-library/react-testing-library#773]
Hi, 

I would like to use the testing library logo (octopus) on my personal website.

It would be used to show that I use the react testing library utility, as a skill. 

Can I have permission to use the logo?

**Comment by nickmccurdy** [comment]
I believe this is the Octopus emoji from JoyPixels (formerly EmojiOne) 5: https://www.joypixels.com/emoji/v5

Here's the license information, some use is free and some is paid depending what you're doing: https://www.joypixels.com/licenses

**Comment by AlastairM-E** [comment]
Thanks
