### ISSUE TITLE
render options: ability to pass props to wrapper

### ISSUE THREAD

**Issue by kelly-tock** [testing-library/react-testing-library#780]
### Describe the feature you'd like:
In creating a custom render for tests, it is often desirable to modify some of the providers in the wrapper to meet various scenarios, such as switching locale, etc. I was able to accomplish this via what now maybe seems to be the older recommendation from the docs:

```jsx
export const customRender = (ui: React.ReactElement, options?: CustomRenderOptions) => {
  return {
    ...render(<TestProviders {...options?.TestProviderProps}>{ui}</TestProviders>),
  };
};
```

where we allow some props to be passed into the TestProviders component that has redux, etc. 

### Suggested implementation:
I'd like to be able to just do that in the render options, so something like:

```jsx
const customRender = (ui, options) =>
  render(ui, { wrapper: AllTheProviders, wrapperProps: options.wrapperProps, ...options })
```
or something like that. 

### Describe alternatives you've considered:
see implementation above.

**Comment by alexkrolick** [comment]
I could see this pattern replacing the "custom render" idea in many cases:

```jsx
import { render, screen } from '@testing-library/react'
import AppContext from '../'

render(<Foo />, {
  wrapper: AppContext,
  wrapperProps: { intl: { lang: 'en-US' } },
})
```

I like it because you can rely more on the examples from the docs instead of remapping imports to an internal file with the custom render function.

**Comment by kentcdodds** [comment]
I think this has come up in the past. Either way, I would prefer to not add this extra API when there's a simpler alternative:

```javascript
const customRender = (ui, options) =>
  render(ui, { wrapper: props => <AllTheProviders {...props} {...options.wrapperProps} />, ...options })
```

**Comment by alexkrolick** [comment]
Does that implement rerender and unmount correctly? I feel like there is a simple way but it doesn't cover everything fully, so you can't really use it if you're setting up the lib for a team and expecting it to work just like the docs say.

**Comment by kentcdodds** [comment]
How does it not support rerender?

**Comment by kelly-tock** [comment]
maybe my example is incorrect, but here's a rerender that's not working with this approach:

```jsx
test('will re-render with different children value', async () => {
  const { container, getByTestId, rerender, debug } = customRender(
    <Button data-testid="rerender">First</Button>
  );
  expect(getByTestId('rerender').textContent).toBe('First');
  rerender(<Button data-testid="rerender">Second</Button>);
  expect(getByTestId('rerender').textContent).toBe('Second');
});
```

```jsx
export const customRender = (ui: React.ReactElement, options?: CustomRenderOptions) => {
  return render(ui, {
    wrapper: (props: any) => (
      <TestProviders {...props} {...options?.TestProviderProps}>
        {ui}
      </TestProviders>
    ),
    ...options?.testingLibraryOptions,
  });
};
```

**Comment by kentcdodds** [comment]
Thanks @kelly-tock, I think there's a bug in that `customRender`:

```javascript
export const customRender = (ui: React.ReactElement, options?: CustomRenderOptions) => {
  return render(ui, {
    wrapper: (props: any) => <TestProviders {...props} {...options?.TestProviderProps} />,
    ...options?.testingLibraryOptions,
  });
};
```

The `props` that `wrapper` gets contains the `children` which you'll want forwarded. Pretty sure this will work fine.

**Comment by kelly-tock** [comment]
doh, I didn't fully convert it from before. let me test this, I see what you mean now.

**Comment by kelly-tock** [comment]
confirmed, that works.

**Comment by kentcdodds** [comment]
Wahoo :) I love it when we realize new APIs aren't needed 😄 Thanks @kelly-tock.

**Comment by soullivaneuh** [comment]
It would be great to have @kentcdodds documented somewhere. :-)

**Comment by lbragile** [comment]
I use the `useReducer` hook and here is how I got my `customRender` to work:

```javascript
import React, { ComponentType, ReactElement, useReducer } from "react";
import { render, RenderResult } from "@testing-library/react";
import { AppContext } from "../../src/context/AppContext";
import { IAction, IState } from "../../src/typings/AppTypes";
import { AppReducer } from "../../src/reducers/AppReducer";

interface IReducerMocks {
  stateMock?: IState;
  dispatchMock?: React.Dispatch<IAction>;
}

interface IComponentWrapperProps {
  children: ReactElement;
}

export function customRender(ui: ReactElement, mocks?: IReducerMocks): RenderResult {
  const ComponentWrapper = ({ children }: IComponentWrapperProps): ReactElement => {
    const [state, dispatch] = useReducer(AppReducer, mocks?.stateMock ?? global.initialState);
    return (
      <AppContext.Provider value={{ state, dispatch: mocks?.dispatchMock ?? dispatch }}>{children}</AppContext.Provider>
    );
  };

  return render(ui, { wrapper: ComponentWrapper as ComponentType });
}
```

What I find handy about the above is that in my tests I have a few options
1. `customRender(<Component/>)`  if I want the `dispatch` to update `state` based on initial global values.
2. `customRender(<Component prop1="..." prop2="..."/>)` to do same as 1. just with component level props
3.  `customRender(<Component prop1="..." prop2="..."/>, { stateMock: ... })` to use a different initial state in the `useReducer`
4.  `customRender(<Component prop1="..." prop2="..."/>, { dispatchMock: mockFn })` to assert on `mockFn` and make sure it was called with correct values.
5.  `customRender(<Component prop1="..." prop2="..."/>, { stateMock: ..., dispatchMock: mockFn })` - combine 3. & 4.
6. `render(<Component/>)` if I don't want custom render. 

The only issue I am facing is this, let's say I don't want to render the entire App during integration testing and can simply verify the global state from my `useReducer`. What would be the best approach to extracting the (current) state from the `useReducer` of the `customRender`?

**Comment by brunojs02** [comment]
> I think this has come up in the past. Either way, I would prefer to not add this extra API when there's a simpler alternative:
> 
> ```js
> const customRender = (ui, options) =>
>   render(ui, { wrapper: props => <AllTheProviders {...props} {...options.wrapperProps} />, ...options })
> ```

It's doesn't work in my case, bc i need to update wrapper props and run rerender to execute useEffect in child component, ex https://codesandbox.io/s/rtl-playground-forked-m1x4qr?file=/src/Form.test.js
Has anyone knows how i can achive this?
