### ISSUE TITLE
[createEvent] Reference of click event has missing field values

### ISSUE THREAD

**Issue by MarcoLeko** [testing-library/react-testing-library#781]
- `@testing-library/react` version: ^10.2.1
- Testing Framework and version: jest: ^26.4.0
- DOM Environment: jsdom by jest

#### Example comp
```js
export default function App() {
  function onClick(e) {
    foo({e, bar: 'foo'}); // <== event object is passed as argument
  }
  return (
    <button onClick={onClick}>
    Click me
    </button>
  );
}
```

#### Test case
```js
jest.mock('path/of/foo', () => ({
    foo: jest.fn(),
}));

describe('ExampleComp', () => {
    it('should call foo on click', async () => {
        const { queryByText } = render(
                <App />
        );

        const event = createEvent.click(queryByText('Click me'));
        fireEvent(queryByText('Click me'), click);

        await waitFor(() => {
            expect(foo).toHaveBeenCalledWith({
                e: event, // <== missmatch of received obj.
                bar: 'foo'
            });
        });
});
```

### What happened:

I have a missmatch of the expected with the received even though I pass in the event obj. as argument:
```js
- Expected
 + Received


Object {
        "foo": "bar",
    -   "e": MouseEvent {
    -     "isTrusted": false,
    +   "e": Class {
    +     "_dispatchInstances": null,
    +     "_dispatchListeners": null,
    +     "_targetInst": null,
    +     "altKey": null,
    +     "bubbles": null,
    +     "button": null,
    +     "buttons": null,
    +     "cancelable": null,
    +     "clientX": null,
    +     "clientY": null,
    +     "ctrlKey": null,
    +     "currentTarget": [Function currentTarget],
    +     "defaultPrevented": null,
    +     "detail": null,
    +     "dispatchConfig": null,
    +     "eventPhase": null,
    +     "getModifierState": [Function getEventModifierState],
    +     "isDefaultPrevented": [Function functionThatReturnsFalse],
    +     "isPropagationStopped": [Function functionThatReturnsFalse],
    +     "isTrusted": null,
    +     "metaKey": null,
    +     "movementX": [Function movementX],
    +     "movementY": [Function movementY],
    +     "nativeEvent": null,
    +     "pageX": null,
    +     "pageY": null,
    +     "relatedTarget": [Function relatedTarget],
    +     "screenX": null,
    +     "screenY": null,
    +     "shiftKey": null,
    +     "target": null,
    +     "timeStamp": [Function timeStamp],
    +     "type": null,
    +     "view": null,
        },

```

### Problem description:

So I what Im basically trying to do, is to simulate a click event in my jest test and expect a specific mock method to have been called with specific arguments. One of the arguments is the click event handler object. Now when creating the click event in my test-case with ````createEvent.click(...)```` the reference of this event does not seem to match with the received ones of the actual call, which seems to be a bug to me, according to this description: https://testing-library.com/docs/dom-testing-library/api-events#createeventeventname

**Comment by eps1lon** [comment]
This is expected behavior in React 16 due to [event pooling](https://reactjs.org/docs/events.html#event-pooling). You can call `event.persist()` before passing it along to be able to re-use it later. Note that [event pooling is planned to change in React 17](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#no-event-pooling) where `event.persist()` will be the default.

**Comment by MarcoLeko** [comment]
@eps1lon But when adding ````e.persist()```` in the handler function, the test expectation still fails, due to the mismatch of received and expectet! You can also reproduce this!

**Comment by eps1lon** [comment]
That's why excessive snapshot tests are a problem. You'll also see internal properties from React and properties that you needn't care about (e.g. functions). Those not matching is somewhat expected.  

If you got a repro with `e.persist` and a useful snapshot please let me know.
