### ISSUE TITLE
display wrong version of node and npm

### ISSUE THREAD

**Issue by ChinmayDeyUI** [testing-library/react-testing-library#787]
My current version of the node is 11.15.0 and the npm version is 6.7.0. still, it getting the error at the time of npm install

npm ERR! Linux 4.15.0-112-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save-dev" "@testing-library/react"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG
.....
![image](https://user-images.githubusercontent.com/55885649/93121843-22cb9d80-f6e3-11ea-8067-d1cec937526f.png)

**Comment by afontcu** [comment]
Hi! Looks like your using `sudo npm`. Does it work without `sudo`? If not, is it possible that you have several versions of node installed in your machine?

You can check that out by running `sudo node -v`.

**Comment by MatanBobi** [comment]
Hi @ChinmayDeyUI, looks like there's nothing left for us here so I'm closing this one. If there is, please feel free to comment here and I'll open it again.
