### ISSUE TITLE
RTL 11 fails on codesandbox

### ISSUE THREAD

**Issue by mattdarveniza** [testing-library/react-testing-library#791]
- `@testing-library/react` version: 11.0.4
- Testing Framework and version: Jest via codesandbox
  
- DOM Environment: n/a
  

### Relevant code or config:

Link to sandbox: https://codesandbox.io/s/github/kentcdodds/react-testing-library-examples/tree/master/?file=/src/__tests__/async.js

### What you did:

Tried to see the tests in codesandbox

### What happened:

Tests failed at import of `import {render} from '@testing-library'` with the following

```
Identifier 'test' has already been declared

SyntaxError: Identifier 'test' has already been declared
    at eval (<anonymous>)
    at z (https://codesandbox.io/static/js/sandbox.bb0970cac.js:1:97621)
    at X.evaluate (https://codesandbox.io/static/js/sandbox.bb0970cac.js:1:109776)
    at ye.evaluateTranspiledModule 
[ ... more unhelpful uglified garbage stack ]
```

### Reproduction:

See the linked [sandbox](https://codesandbox.io/s/github/kentcdodds/react-testing-library-examples/tree/master/?file=/src/__tests__/async.js), go to the tests panel, observe error

### Problem description:

So I happened across this trying to write my own sandbox, but it's interesting that it also fails in the existing set of offical examples in codesandbox.

### Suggested solution:

I'm not sure there's really anything you can do about this, as it's probably something weird on code sandbox's end around import scoping or something, but I thought you may be interested to know regardless in case you know someone over there you can ping.

Interestingly RTL v10.4.9 doesn't have this issue. I suppose you could refrain from internally using `test` as a variable anywhere near the module scope and that would potentially fix it? Admittedly you shouldn't have to but hey.

Sorry if this has already been brought up, I searched through the issues and couldn't find anything around this though.

**Comment by eps1lon** [comment]
Thanks for the report. We already forwarded it to codesandbox: https://github.com/codesandbox/codesandbox-client/issues/4887
