### ISSUE TITLE
creating an event of space Key

### ISSUE THREAD

**Issue by Morteza-Jenabzadeh** [testing-library/react-testing-library#792]
- `@testing-library/react` version: 9.3.2
- Testing Framework and version: jest default CRA
  
- DOM Environment: jsdom default CRA
  

### Relevant code or config:

```js
import React from "react";

const Button = (props) => {
  const { children, disabled, ...rest } = props;

  return (
    <button
      disabled={disabled}
      autoFocus={rest.autoFocus}
      onClick={rest.onClick}
      type={rest.type}
      onFocus={rest.onFocus}
    >
      {children}
    </button>
  );
};
export default Button;
```

### What you did:
I have tried to write a test suite that onClick event  of a button fired by pressing the space key 
it works in real world  (chrome browser)

here is my test suite:
```js
  it("focus and enter should fire handle click", () => {
    const handleFocus = jest.fn();
    const handleClick = jest.fn();
    const ui = (
      <Button type="button" onFocus={handleFocus} onClick={handleClick}>
        {TEXT1}
      </Button>
    );
    const { container } = render(ui);
    const button = container.querySelector("button");

    fireEvent.focus(button);
    expect(handleFocus).toHaveBeenCalled();
    fireEvent.keyDown(screen.getByRole("button"), {
      key: "Space",
      code: "Space",
    });
    expect(handleClick).toHaveBeenCalled();
  });
```

### What happened:
but the onClick callBack never called!
```
 expect(jest.fn()).toHaveBeenCalled()
    Expected number of calls: >= 1
    Received number of calls:    0
      80 |       code: "Space",
      81 |     });
    > 82 |     expect(handleClick).toHaveBeenCalled();
         |                         ^
      83 |   });
      84 | });
      85 | 
```

### Reproduction:

please check this repo the code is the minimum to run the test
https://github.com/Morteza-Jenabzadeh/react-test-library.git

**Comment by eps1lon** [comment]
Thanks for the report. I can see how this can be confusing.

`fireEvent` really only fires events. Any default behavior of these events is not responsibility of `fireEvent`. 

What you're looking for is [`type()` from `user-event`](https://github.com/testing-library/user-event#typeelement-text-options).

PS: The correct key for space is `" "` not `"Space"`.

PPS (even though irrelevant when using user-event): Click is only triggered for buttons on `keyup` not `keydown`.

**Comment by Morteza-Jenabzadeh** [comment]
Thanks, Sebastian for your clarification.
As I saw the Doc and test again `keyUp` is not supported in `userEvent`:
`TypeError: _userEvent.default.keyUp is not a function`

and tried this as Doc suggested :
```js
    userEvent.type(screen.getByRole("button"), "{space}");
```
but got the same result.

**Comment by eps1lon** [comment]
> but got the same result.

I'd suggest [opening an issue in `user-event`](https://github.com/testing-library/user-event/issues/new). Seemed like they supported this use case.
