### ISSUE TITLE
react-ace text content is not rendered into html markup

### ISSUE THREAD

**Issue by zaharzagrava** [testing-library/react-testing-library#793]
- `@testing-library/react` version: 9.5.0
- Testing Framework and version: jest: 24.9.0
- DOM Environment:
 jsdom 14.1.0 (the default with jest)
Chrome 85.0.4183.121

### Problem description:

My react-ace editor does not have a text inside **ace_text-layer** as it should. I have addressed this issue [here ](https://github.com/securingsincity/react-ace/issues/923#issuecomment-703218313) as well

### Relevant code or config:

Component.tsx:

```tsx
    import React, { ReactElement } from 'react';
    import AceEditor from 'react-ace';
    import 'ace-builds/src-noconflict/mode-yaml';
    import 'ace-builds/src-noconflict/theme-github';
    import { ComponentType} from '../../types/types';

    export interface Props {
      component: ComponentType;
    }

    function Component(): ReactElement {
      return (
        <>
          <AceEditor
            mode="yaml"
            theme="github"
            maxLines={Infinity}
            tabSize={2}
            showGutter={false}
            highlightActiveLine={false}
            defaultValue={'This is a source text'}
            width={'100%'}
            name="UNIQUE_ID_OF_DIV"
            editorProps={{ $blockScrolling: true }}
          />
        </>
      );
    }

    export default Component;
```

Component.test.tsx:

```tsx
    import React from 'react';
    import { render } from '@testing-library/react';
    import '@testing-library/jest-dom/extend-expect';

    import { Default as DefaultStory } from './Component.stories';
    import { Props } from './Component';

    it('renders the button in the primary state', async () => {
      const { findByText } = render(
        <DefaultStory {...(DefaultStory.args as Props)} />
      );

      let beta = await findByText('This is a source text');

      // different expects
    });
```

### What you did:

I executed the two files above and it resulted html with error: **Unable to find an element with the text: This is a source text. This could be because the text is broken**. And indeed there is no "This is a source text" string inside the html generated below:

    <body>
      <div>
        <div
          class=" ace_editor ace_hidpi ace-github"
          id="UNIQUE_ID_OF_DIV"
          style="width: 100%; height: 500px; font-size: 12px;"
        >
          <textarea
            autocapitalize="off"
            autocorrect="off"
            class="ace_text-input"
            spellcheck="false"
            style="opacity: 0; font-size: 1px;"
            wrap="off"
          />
          <div
            aria-hidden="true"
            class="ace_gutter"
            style="display: none;"
          >
            <div
              class="ace_layer ace_gutter-layer ace_folding-enabled"
              style="height: 1000000px;"
            />
          </div>
          <div
            class="ace_scroller"
            style="line-height: 0px;"
          >
            <div
              class="ace_content"
            >
              <div
                class="ace_layer ace_print-margin-layer"
              >
                <div
                  class="ace_print-margin"
                  style="left: 4px; visibility: visible;"
                />
              </div>
              <div
                class="ace_layer ace_marker-layer"
              />
              <div
                class="ace_layer ace_text-layer"
                style="height: 1000000px; margin: 0px 4px;"
              />
              <div
                class="ace_layer ace_marker-layer"
              />
              <div
                class="ace_layer ace_cursor-layer ace_hidden-cursors"
              >
                <div
                  class="ace_cursor"
                />
              </div>
            </div>
          </div>
          <div
            class="ace_scrollbar ace_scrollbar-v"
            style="display: none; width: 20px;"
          >
            <div
              class="ace_scrollbar-inner"
              style="width: 20px;"
            >
               
            </div>
          </div>
          <div
            class="ace_scrollbar ace_scrollbar-h"
            style="display: none; height: 20px;"
          >
            <div
              class="ace_scrollbar-inner"
              style="height: 20px;"
            >
               
            </div>
          </div>
          <div
            style="height: auto; width: auto; top: 0px; left: 0px; visibility: hidden; position: absolute; wh
          >
            <div
              style="height: auto; width: auto; top: 0px; left: 0px; visibility: hidden; position: absolute; 
            />
            <div
              style="height: auto; width: auto; top: 0px; left: 0px; visibility: hidden; position: absolute; 
            >
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX            </div>
          </div>
        </div>
      </div>
    </body>

Finally, when I open this same Component in my [codesandbox](https://codesandbox.io/s/react-ace-default-example-1jbbd), the resulted html looks different. There is a "This is a source text" text inside **ace_text-layer**:

![image](https://user-images.githubusercontent.com/31539383/95010119-846e9000-062f-11eb-975c-9e3489297a2a.png)

**Comment by eps1lon** [comment]
> Finally, when I open this same Component in my storybook, the resulted html looks different. 

Your storybook is probably doing something that you're not simulating in your test (loading data, setting a timeout etc). 

For us to be able to help you should break down your component so that it includes only source necessary for the this issue to reproduce. That means that all component related code needs to be available and not e.g. hidden inside node_modules. The best way to do this is by using [codesandbox](https://react.new/).

**Comment by zaharzagrava** [comment]
Here is a [codesandbox](https://codesandbox.io/s/react-ace-default-example-1jbbd). The result is the same.

**Comment by eps1lon** [comment]
> Here is a [codesandbox](https://codesandbox.io/s/react-ace-default-example-1jbbd). The result is the same.

Please inline and reduce as much as possible from `react-ace`. Not everybody know this library and it'll take much longer for us to understand their implementation.

**Comment by zaharzagrava** [comment]
> > Here is a [codesandbox](https://codesandbox.io/s/react-ace-default-example-1jbbd). The result is the same.
> 
> Please inline and reduce as much as possible from `react-ace`. Not everybody know this library and it'll take much longer for us to understand their implementation.

Done. Reduced as much code as I could. First 2 imports for importing **mode** of the editor (that regulates autocomplete and other features) and **theme** (how it looks visually). **defaultValue** sets the starting value in the editor and **name** is needed for unique id.

**Comment by eps1lon** [comment]
This issue is not actionable for us since it involves third-party code. Feel free to ping me once every bit of component related code is directly accessible from the repro and as minimal as possible.

It's likely that the library in question does some custom scheduling (setTime, requestAnimationFrame) or renders elements to containers that are inaccessible.
