### ISSUE TITLE
I have a component in which an api is called on load, which populate a state. How to mock this scenario. How to populate state in such cases?

### ISSUE THREAD

**Issue by siddharthmittal202Mck** [testing-library/react-testing-library#795]
```js
useEffect(() => {
	(async () => {
		try {
			setLoader(true);
			const userMckDocs = await getUserMckDocuments(
				parseInt(userDetails.fmno, 10)
			);
			console.log("userMckDocs", userMckDocs);
			setMckDocs(userMckDocs);// want to populate this via react testing library, else my component will not render.
			setVisibleDocuments(userMckDocs.slice(0, 5));
			setLoader(false);
		} catch (e) {
			setDocError({
				errorMessage: "There was an error in fetching data",
			});
			setLoader(false);
		}
	})();
}, []);
```

**Comment by nickmccurdy** [comment]
If you need to mock the API I'd recommend [msw](https://mswjs.io/)

**Comment by siddharthmittal202Mck** [comment]
I have mocked the API, don't know how it will set the api response in the state variable.

**Comment by nickmccurdy** [comment]
React Testing Library can't access or mock state directly. It uses React DOM to render the components, so the state should work the same way as it would normally, but with the API calls mocked.

**Comment by siddharthmittal202Mck** [comment]
Thanks for the prompt responses. It will be awesome if we can access or mock state directly, just a thought.

**Comment by nickmccurdy** [comment]
Testing library is intentionally designed to prevent state access, which can lead to brittle tests relying on implementation details. Instead, it's better to focus on user behavior.

- [Why should I use the React Testing Library?](https://testing-library.com/docs/react-testing-library/migrate-from-enzyme#why-should-i-use-the-react-testing-library)
- [FAQ: What about enzyme is "bloated with complexity and features" and "encourage poor testing practices"?](https://testing-library.com/docs/react-testing-library/faq)
