### ISSUE TITLE
ReactDOM is misspelled as ReactDom in UMD files

### ISSUE THREAD

**Issue by hornta** [testing-library/react-testing-library#797]
https://github.com/kentcdodds/kcd-scripts/issues/162

I noticed that the generated UMD files has incorrect spelling of ReactDOM. The "DOM" part is misspelled as "Dom". 

Steps:
* npm i @testing-library/react -SED
* Search for ReactDom in ./node_modules/@testing-library

![Screenshot 2020-10-12 at 17 39 49](https://user-images.githubusercontent.com/4553604/95765735-8f21c880-0cb2-11eb-8489-58b63cadb400.png)

How did I find this? Our company are using a legacy build system and we rely on globals everywhere and we are on way to migrate from Enzyme to this lib.

**Comment by kentcdodds** [comment]
Hi @hornta,

I'm guessing you're on an old version because this has been fixed in more recent versions. Which version are you running?

Here's the UMD output for the latest version:

```javascript
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('react'), require('react-dom'), require('react-dom/test-utils')) :
  typeof define === 'function' && define.amd ? define(['exports', 'react', 'react-dom', 'react-dom/test-utils'], factory) :
  (global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global.TestingLibraryReact = {}, global.React, global.ReactDOM, global.ReactTestUtils));
}(this, (function (exports, React, ReactDOM, testUtils) { 'use strict';
```

https://unpkg.com/@testing-library/react@11.0.4/dist/@testing-library/react.umd.js

**Comment by hornta** [comment]
I had 9.5.0 installed 🤦‍♂️🤦‍♂️🤦‍♂️
