### ISSUE TITLE
tests are unstable

### ISSUE THREAD

**Issue by paxarpp** [testing-library/react-testing-library#798]
Hello!
some tests are unstable, what could be the reason?

when run JEST in all tests mode
some test finished with text "Timeout - Async callback was not invoked within the 15000ms timeout specified by jest.setTimeout."

at the same time, for all long tests, the interval has been increased to 10000-150000,
all such tests with asynchronous actions

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by paxarpp** [comment]
ok,
there is no way to download for playback, you can close,
Sorry for disturbing.
