### ISSUE TITLE
CI/CD pipelines with node version 10.13.0 is failing

### ISSUE THREAD

**Issue by 6axter82** [testing-library/react-testing-library#804]
- `@testing-library/react` version: 11.1.0
- Testing Framework and version: React, node version 10.13.0, jest version 24
  
- DOM Environment:
  

### Relevant code or config:

```js
error @jest/types@26.6.0: The engine "node" is incompatible with this module. Expected version ">= 10.14.2". Got "10.13.0"
```

### What you did:
 Just installed the latest yarn add @testing-library/react -D

### What happened:
 git add . && git commit -m "try it out on CI/CD pipeline"

### Problem description: 
Getting the following error: 
error @jest/types@26.6.0: The engine "node" is incompatible with this module. Expected version ">= 10.14.2". Got "10.13.0"

**Comment by alexkrolick** [comment]
That error is coming from jest, not us
https://unpkg.com/@jest/types@26.6.0/package.json
