### ISSUE TITLE
connect ECONNREFUSED 0.0.0.0:25888

### ISSUE THREAD

**Issue by Goldabj** [testing-library/react-testing-library#805]
### About 

- `@testing-library/react` version: ```"@testing-library/jest-dom": "^5.9.0",
                                                             "@testing-library/react": "^10.0.4",```
- Testing Framework and version: ```"jest": "^24.9.0",```
- DOM Environment: ```"jest-environment-jsdom-sixteen": "^1.0.3",``` `node 12`
  

Test File: 

```
import '@testing-library/jest-dom/extend-expect';
import { render, screen, cleanup, fireEvent, waitFor, queryByAttribute } from '@testing-library/react';
import React from 'react';
import { Provider } from 'react-redux';
import { SELECT_CONTAINERS_PLACEHOLDER } from '../../../../src/common/constants';
import configureMockStore from 'redux-mock-store';
import SelectContainers from '../../../../src/components/RescueDetails/SelectContainers';
import * as TestHelper from '../../test-helpers';

describe('Testing SelectContainers', (): void => {
  afterEach(cleanup);

  it('Should load all texts correctly', async () => {
    const state = TestHelper.getDefaultAppState();
    state.rescue!.recommendation.rescueInformation.containersToTransfer = [
      {
        containerId: 'container1',
        totalPackageCount: 30,
        transferAll: true,
        packagesToTransfer: []
      }
    ];

    const mockStore = configureMockStore();
    const store = mockStore(state);

    const dom = render(
      <Provider store={store}>
        <SelectContainers />
      </Provider>
    );

    //Mock scrollIntoView: Works fine on other elements but fails on this element for some reason, so mocking it
    window.HTMLElement.prototype.scrollIntoView = jest.fn();

    expect(screen.getByText('Full bags')).toBeInTheDocument();
    const getByAriaPlaceholder = queryByAttribute.bind(null, 'aria-placeholder');
    const select = getByAriaPlaceholder(dom.container, SELECT_CONTAINERS_PLACEHOLDER);
    expect(select).toHaveAttribute('aria-expanded', 'false');
    fireEvent.mouseDown(select);
    await waitFor(() => screen.getByRole('listbox'));
    expect(select).toHaveAttribute('aria-expanded', 'true');
  });
});


```
### Issue

When running tests (`jest --coverage --env=jest-environment-jsdom-sixteen`) I receive `connect ECONNREFUSED 0.0.0.0:25888`. 

This occurs 90% of the time, but sometimes it passes. It also happens randomly to different tests. The one shown is just the latest test file that failed when I ran the test. 

Is this an issue anyone else has noticed, or knows a fix for? It started happening about 2 weeks ago randomly, and I have yet to figure out a fix yet.

**Comment by eps1lon** [comment]
Sorry to hear you're having trouble. This doesn't sound like an issue with `@testing-library/react` itself but rather with your mocks (or lack of network request mocking). 

I recommend you check out our [community discord](https://testing-library.com/discord) and see if someone is able to help you there.
