### ISSUE TITLE
Tests interfere with each other in a specific case - console.warn

### ISSUE THREAD

**Issue by kneczaj** [testing-library/react-testing-library#815]
- `@testing-library/react` version: 11.1.0
- Testing Framework and version: jest 24.9.0 (on my local machine, no idea about the provided sandbox)
- DOM Environment:
jsdom, see: https://codesandbox.io/s/wizardly-proskuriakova-mdgml?file=/src/bug.spec.js

### Relevant code or config:

See https://codesandbox.io/s/wizardly-proskuriakova-mdgml?file=/src/bug.spec.js
Click `Tests` tab to see the tests results

### What you did:
I want to catch warning about react uncontrolled to controlled input change. I spy on `console.error` to check if it has been called.

### What happened:
The test fails in the example as expected. However if I enable the other test ("dummy test") with `fireEvent.change` on the input which is run before "does not throw uncontrolled input warning", the warning seems to show up, but the test unexpectedly passes. The order of the tests matters here.

### Reproduction:

1. See the code sandbox: https://codesandbox.io/s/wizardly-proskuriakova-mdgml?file=/src/bug.spec.js
2. Run tests, see that "does not throw uncontrolled input warning" test fails.
3. In line 22 replace `xit` with `it` to enable "dummy test"
4. See that "does not throw uncontrolled input warning" test passes

### Problem description:
Test "does not throw uncontrolled input warning" should never pass disregarding what is written in another test.

### Suggested solution:
No idea

**Comment by MatanBobi** [comment]
Hi @kneczaj, thanks for opening this! :)
I'm trying to reproduce it in the codesandbox you've attached but the test always fails for me.. Am I missing something?
![image](https://user-images.githubusercontent.com/12711091/97979533-04774980-1dd8-11eb-9dfe-68b77e5a6e76.png)

**Comment by eps1lon** [comment]
> The test fails in the example as expected. However if I enable the other test ("dummy test") with fireEvent.change on the input which is run before "does not throw uncontrolled input warning", the warning seems to show up, but the test unexpectedly passes. The order of the tests matters here.

React deduplicates warnings at its module level. So if it issues a warning in the first test, the second test doesn't see it. If the first test doesn't issue the warning, the second test doesn't see it.

Note that testing React warnings is brittle since it's not considered part of the public API and might change at any time. 

If you still want to test the warnings [reset the modules](https://jestjs.io/docs/en/jest-object.html#jestresetmodules) before each test and re-require **everything**

**Comment by kneczaj** [comment]
@eps1lon so you mean that after uncommenting "dummy test" the warning comes from the "dummy test" and then it is ignored (deduplicated) in "does not throw uncontrolled input warning"?

**Comment by eps1lon** [comment]
> @eps1lon so you mean that after uncommenting "dummy test" the warning comes from the "dummy test" and then it is ignored (deduplicated) in "does not throw uncontrolled input warning"?

That's what I suspect.
