### ISSUE TITLE
intellisense for @testing-library/react is not working on Ubuntu

### ISSUE THREAD

**Issue by Umer-Hayyat** [testing-library/react-testing-library#817]
Intellisense stopped working with CRA, VSCode and Ubuntu

---
All of sudden, intellisense which was working fine stopped working on VSCode installed on Ubunto 20. Tried several solutions including installing types locally and globally, adding typeAcquisition for jest in jsconfig.js but none of the solution worked for me.

**Comment by nickmccurdy** [comment]
Are you sure it works for other libraries? This seems like it's likely an issue with VSCode rather than the library.

**Comment by Umer-Hayyat** [comment]
> Are you sure it works for other libraries? This seems like it's likely an issue with VSCode rather than the library.

yes I am sure, I have tested several times before posting the issue to here. I also created another test project and added testing library there and the intellisense is working perfectly fine there however, with my project it stopped working and every solution over the internet seems not to be working with that. 
If the problem is with VS than why its working in test project?

**Comment by nickmccurdy** [comment]
There's probably some different configuration in that project. Can you post either the whole product or a minimal reproductive of the issue with any sensitive code removed?

**Comment by ddehart** [comment]
I just ran into the same issue with Webstorm after upgrading from 11.1.1 to 11.2.2. Webstorm would no longer recognize `fireEvent`, `screen`, or `within`, although it did recognize `render` using this import statement:

`import { fireEvent, render, screen, within } from '@testing-library/react';`

11.1.1:
![11 1 1](https://user-images.githubusercontent.com/901215/99927781-a5409100-2d14-11eb-81ab-5705f088bd1b.png)

11.2.2 (the yellow-ish squiggly lines are a warning that it can't find the reference):
![11 2 2](https://user-images.githubusercontent.com/901215/99927792-b25d8000-2d14-11eb-83c7-e7b49d3a532b.png)

**Comment by nickmccurdy** [comment]
Please double check if this is still broken when downgrading to 11.1.1. If not I'd recommend bisecting these releases to figure out which release caused the problem.

I have an [automated bisect tool](https://nickmccurdy.com/bisect/) you could use by entering this configuration:
```
11.2.2
11.2.1
11.2.0
11.1.2
11.1.1
```

Also, check if your TypeScript build still has these issues, or if it's just WebStorm.

**Comment by marcosvega91** [comment]
There is also this package developed by @smeijer https://github.com/smeijer/where-broke it could help

**Comment by ufo22940268** [comment]
In my case, by installing @testing-library/dom can fix this problem.

**Comment by eps1lon** [comment]
Closing this as unactionable. If you can share a minimal, reproducible example we can re-open. I suggest you delete all node_modules and install again but beyond that we would need to investigate your complete setup which is inappropriate for this issue tracker.

**Comment by fpsantos86** [comment]
> In my case, by installing @testing-library/dom can fix this problem.

For me too. Thanks.
