### ISSUE TITLE
render unexpectedly returns <body> <div /> </body>

### ISSUE THREAD

**Issue by NoMaillard** [testing-library/react-testing-library#818]
- `@testing-library/react` version: `^11.1.1`
- Testing Framework and version: `    "jest": "^26.6.3",`
  
- DOM Environment: `jsdom`
  

other relevant packages:
```
    "react-scripts": "4.0.0",
    "typescript": "4.0.5",
    "ts-jest": "^26.4.3",
```

### Relevant code or config:

```tsx

    const { getByText } = render(
      <AppContext.Provider value={{ state, dispatch }}>
        <Router history={history}>
          <Header />
        </Router>
      </AppContext.Provider>,
    );
    const linkElement = getByText(/john doe/i);
    expect(linkElement).toBeInTheDocument();
```

### What you did:

i ran the tests

### What happened:

```
TestingLibraryElementError: Unable to find an element with the text: /john doe/i. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

<body>
  <div />
</body>
```

**Comment by kentcdodds** [comment]
Hi @NoMaillard,

My guess is the router is not matching the route to your component so it's not rendering anything. Either way, this doesn't appear to be a Testing Library issue. Find channels for help here: https://testing-library.com/help

Good luck!

**Comment by joonk025** [comment]
Same here. no solution?

**Comment by dimzerdevas** [comment]
same here.

**Comment by MatanBobi** [comment]
@dimzerdevas - Since this isn't an issue with testing-library, we recommend seeking for help in our discord channel or in stackoverflow.

**Comment by Lyokoo** [comment]
I'm having the same issue too.

**Comment by joonk025** [comment]
> I'm having the same issue too.

Hey y'all, so I realized it indeed was not the problem with RTL. In my case, there was a authorization later in my components that were not being passed. Therefore, the jsdom was not able to display any of the component hence the <body></div></body>.

**Comment by Lyokoo** [comment]
emm.. I'm trying to update my react version from 16.13 to 18.2 and It works...

**Comment by georgesunnyt** [comment]
I had the same issue. I had my tests wrapped in an act. I removed the act and used findby instead, which solved my issue
code snippet before:
` it('checks if team page renders correctly', async () => {
   await act(async () => {
    renderWithProviders(<Team />, { msalTester `});`
    });
  }, 5000);
});`
code snippet after:
` it('checks if team page renders correctly', async () => {
    renderWithProviders(<Team />, { msalTester });
    screen.debug(undefined, Infinity);
    await screen.findByText('Manage Your Team');
  }, 5000);
});
`
Hope this helps someone :-)

**Comment by MehinHuseynova** [comment]
When the test file name and the rendered component inside the test don’t match, the same issue occurs.
Renaming test file name fixed this issue for me.

**Comment by camball** [comment]
As others have said here—look into your own codebase for issues; RTL isn't causing the flakiness. In my case, I got this `<body><div /></body>` issue only around half the time. Turns out, I was missing a mock for a critical API endpoint that lived in a React context provider. As soon as I added the correct API mock, tests passed every time with no flakiness.
