### ISSUE TITLE
Unable to test antd 3.x Datepicker

### ISSUE THREAD

**Issue by Abhikumar98** [testing-library/react-testing-library#824]
- `@testing-library/react` version: 11.1.0
- Testing Framework and version: Jest
- DOM Environment: @testing-library/jest-dom 5.11.5

### Relevant code or config:

```
    const datePicker = getByTestId("date-picker");
    fireEvent.click(datePicker);
    console.log(datePicker);
    fireEvent.change(datePicker, { target: { value: "29 Oct, 2020" } });
    expect(datePicker.value).toBe("29 Oct, 2020");
```

### What you did:

I trying to
- Click on the Datepicker component
- Change its value
- expecting the changed date in the value

### What happened:

![Screenshot 2020-11-12 at 12 23 51 PM](https://user-images.githubusercontent.com/35174288/98905733-f0bb9980-24e1-11eb-9a23-6141225a3371.png)

### Reproduction:

https://codesandbox.io/s/datepicker-test-forked-c1jjp?file=/src/index.test.js

### Problem description:

The value of the date picker component wasn't changed

**Comment by nickmccurdy** [comment]
This seems to be a bug with antd 3 (see [original issue solution](https://github.com/ant-design/ant-design/issues/27568#issuecomment-722266528)). antd 4 has already fixed this using the same React Testing Library code, and if `<input type="date" />` is used instead it still works (though you'd have to use a different format) [[example](https://codesandbox.io/s/datepicker-test-forked-icrux?file=/src/index.test.js)]. I don't think we should support a workaround for a bug in another library that's already been patched unless there's evidence that React Testing Library is doing something incorrectly, which I'm not seeing so far.

Here are some alternative options:
1. Patch antd 3 to fix this bug yourself, as it's not going to be implemented upstream
2. Migrate to antd 4
3. Use yarn 2 resolutions to install both versions of antd and only use DatePicker from 4
4. Reimplement your own DatePicker based on antd 4's implementation
5. Use a standard input (like my [example](https://codesandbox.io/s/datepicker-test-forked-icrux?file=/src/index.test.js))

**Comment by Abhikumar98** [comment]
Got it.  
Thanks @nickmccurdy

**Comment by MatanBobi** [comment]
>
> ```
> fireEvent.click(screen.getByTestId(`date-picker`));
> fireEvent.click(getByHtmlAttribute('title', 'July 8, 2021'));
> ```

Hi @lennertVanSever! Thanks for sharing your solution. We do have [`getByTitle`](https://testing-library.com/docs/queries/bytitle) specifically to query the title attribute, have you tried it? :)

**Comment by DercilioFontes** [comment]
@lennertVanSever, thanks for that. 

Important to remember to use a dynamic date because the DatePicker shows the current month/year. So, the tests can start to fail each new month looking for a static date that is now there anymore.
