### ISSUE TITLE
Convert class components to functional components

### ISSUE THREAD

**Issue by fadelkaadan** [testing-library/react-testing-library#832]
### Describe the feature you'd like:

I would like the class components in the src/_tests_ to be replaced with functional components.

### Suggested implementation:

Convert the class components to functional components with hooks.

**Comment by kentcdodds** [comment]
Hey @fadelkaadan!

Thanks for the offer! We do have some hooks and some classes. I think the mix is necessary though because it helps us ensure that we support both.

Thanks anyway!
