### ISSUE TITLE
Unable to find role

### ISSUE THREAD

**Issue by ngoble-phdata** [testing-library/react-testing-library#835]
- `@testing-library/react` version: 11.2.0
- Testing Framework and version: Jest (CRA) 26.6.0
- DOM Environment: jsdom

### Problem description:

`Unable to find role="execute-button000"`

![image](https://user-images.githubusercontent.com/68344170/99700538-ec9af900-2a58-11eb-9954-62917362bf28.png)

It says it can't find that role, but as you can see in the debug print, it clearly exists in the DOM.  This also fails for `screen.findByRole`

![image](https://user-images.githubusercontent.com/68344170/99701169-b611ae00-2a59-11eb-85d1-35d684929659.png)

This seems to be happening to any component I add a custom role to, and was working in previous versions.

**Comment by brendan-donegan** [comment]
ByRole actually looks up by accessible role, which is not something that can be defined freely. See https://www.w3.org/TR/html-aria/#allowed-aria-roles-states-and-properties for different kinds of role. In your case getByRole('button') should work. You may also want to specify the accessible name which would be the buttons text if it has any, or the aria-label if it does not.

**Comment by ngoble-phdata** [comment]
Okay so that much have changed between versions.  Is that called out somewhere... on like a change log or migration doc?

**Comment by brendan-donegan** [comment]
To be honest I deleted the comment because I just read that you said it was working before, so the library maintainers would need to comment as to why it was changed.

**Comment by ngoble-phdata** [comment]
Yeah I understand now from your previous comment that it's not a valid accessibility role.  I'm having a hard time targeting this because it's a button with an SVG as the content, so I can't use text within the button to target it.

**Comment by brendan-donegan** [comment]
But your button *should* have an aria-label for screen readers so why not
just add one, like 'Execute' for example? Then you could do
`getByRole('button', { name: 'Execute' });`

**Comment by kentcdodds** [comment]
@brendan-donegan is correct. Applying an invalid role is very bad for accessibility. Don't do it. Use a label instead. If for some reason that doesn't work, use a `data-testid`. Never apply an invalid `role`.

Thanks!

**Comment by ngoble-phdata** [comment]
There should still be documentation that calls out this breaking change in the library.  This worked in previous versions.

**Comment by ngoble-phdata** [comment]
Also, testIds aren't working for me.

Browser DOM:
![image](https://user-images.githubusercontent.com/68344170/99704866-94ff8c00-2a5e-11eb-9cc8-73254c7837fa.png)


jsdom
![image](https://user-images.githubusercontent.com/68344170/99704900-a052b780-2a5e-11eb-903c-02ddebc3a2f6.png)

**Comment by kentcdodds** [comment]
> There should still be documentation that calls out this breaking change in the library. This worked in previous versions.

Technically all bug fixes are breaking changes for people who relied on the bug. The fact it worked previously is a bug.

I'm not sure why the test ID isn't getting applied in jsdom. That will be a jsdom issue though I'm afraid. Any reason the aria-label idea isn't going to work for you? Consider that a blind user won't know what this is if it has no label.

**Comment by ngoble-phdata** [comment]
Turns out the reason it wasn't getting added was unrelated to this library.  I had to set the jsdom window size in order to have the desktop variant shown.  Thank you for your time, and updates on accessibility functionality.
