### ISSUE TITLE
Why is waitForElementToBeRemoved related to warning 'Can't perform a React state update...' ?

### ISSUE THREAD

**Issue by pokuwagata** [testing-library/react-testing-library#844]
- `@testing-library/react` version: 9.5.0
- Testing Framework and version: jest 24.9.0 
  
- DOM Environment: jest-dom 5.11.5

### Relevant code or config:

test.js
```js

describe("<Test />", () => {
  afterEach(() => {
    cleanup();
  });

  it("test1", async () => {
    render(<App />);

    await act(async () => {
      const button = screen.getByText("button");
      fireEvent.click(button);
    });
    /* await expect(
      waitForElementToBeRemoved(() => screen.queryByText("loading"))
    ).resolves.not.toThrow(); */
  });

  it("test2", async () => {
    render(<App />);

    await act(async () => {
      const button = screen.getByText("button");
      fireEvent.click(button);
    });

    expect(screen.queryByText("loading")).not.toBeNull();

    await expect(
      waitForElementToBeRemoved(() => screen.queryByText("loading"))
    ).resolves.not.toThrow();
  });
});

```

App.jsx
```jsx
export const App = () => {
  const [loading, setLoading] = useState(false);
  const onClick = () => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
    }, 3000);
  };

  return (
    <>{loading ? <p>loading</p> : <button onClick={onClick}>button</button>}</>
  );
};

```

### What you did:

I ran test (`describe("<Test />"`)

### What happened:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in App (at test.js:19)
```

### Reproduction:
https://codesandbox.io/s/react-testing-library-demo-forked-bt69w?file=/src/__tests__/test.js:179-900

### Problem description:

`waitForElementToBeRemoved` in `test1` case is necessary for turning off this warning. But Why?

**Comment by brendan-donegan** [comment]
When the spec finishes, cleanup (i.e. unmounting) will be performed automatically. If you initiated something that would trigger updates to state (your click event) and the spec exits before these are run then you will get this warning. The only way to ensure the state has finished updating is to waitForElementToBeRemoved. I think for the sake of this being a good test you want to do that anyway.

Btw I don't think you're using it correctly either, there's no need to expect it not to throw, you can just do:

```
await waitForElementToBeRemoved(() => screen.queryByText("loading"));
```

**Comment by pokuwagata** [comment]
thanks for your answer.  I understand why the warning appears.
I think cleanup timer is also good idea.  This way will work well without `waitForElementToBeRemoved` in test1.

```jsx
export const App = () => {
  const [loading, setLoading] = useState(false);
  const onClick = () => {
    setLoading(true);
  };
  useEffect(() => {
    let id;
    if (loading) {
      id = setTimeout(() => {
        setLoading(false);
      }, 3000);
    }
    return () => {
      clearTimeout(id);
    };
  }, [loading]);

  return (
    <>{loading ? <p>loading</p> : <button onClick={onClick}>button</button>}</>
  );
};
```

**Comment by eps1lon** [comment]
Looks like the issue in the original issue description is resolved i.e. everything is green in https://codesandbox.io/s/react-testing-library-demo-forked-bt69w?file=/src/App.jsx.

If an issue persists please [mention](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax#mentioning-people-and-teams) me and update the original issue description with the unexpected failure.

**Comment by SampathKumar27896** [comment]
> thanks for your answer. I understand why the warning appears. I think cleanup timer is also good idea. This way will work well without `waitForElementToBeRemoved` in test1.
> 
> ```js
> export const App = () => {
>   const [loading, setLoading] = useState(false);
>   const onClick = () => {
>     setLoading(true);
>   };
>   useEffect(() => {
>     let id;
>     if (loading) {
>       id = setTimeout(() => {
>         setLoading(false);
>       }, 3000);
>     }
>     return () => {
>       clearTimeout(id);
>     };
>   }, [loading]);
> 
>   return (
>     <>{loading ? <p>loading</p> : <button onClick={onClick}>button</button>}</>
>   );
> };
> ```

After searching for no of days, finally I found we have to clear the timeout. This worked for me. Thanks!
