### ISSUE TITLE
getByLabelText finds label of hidden/aria-hidden parent div

### ISSUE THREAD

**Issue by lassekl92** [testing-library/react-testing-library#845]
- `@testing-library/react` version:9.2.0
- Testing Framework and version:
  
- DOM Environment:
  

### Relevant code or config:

```js
describe("App", () => {
  it("should find input by label", () => {
    render(<div>
      <label id="label-firstname" htmlFor="input-firstname">
        Firstname
      </label>
      <input id="input-firstname" type="text" />
    </div>);
    screen.getByLabelText(/firstname/i);
  });

  it("should not find input by label", () => {
    render(
      <div hidden>
        <label id="label-firstname" htmlFor="input-firstname">
        Firstname
      </label>
      <input id="input-firstname" type="text" />
      </div>
    );
    const firstname = screen.queryByLabelText(/firstname/i);
    expect(firstname).toBe(null);
  });
});
```

### What you did:
Ran the test.

### What happened:
![image](https://user-images.githubusercontent.com/61147590/101169356-13eaec00-363d-11eb-8075-51d8c89ac02f.png)

### Reproduction:
https://codesandbox.io/s/lively-glade-r8dqb?file=/src/App.test.tsx

### Problem description:
I Have 3 equal forms for 3 different people, and you can switch between which one is visible. Therefore it will be several labels with equal name.

I thought, if I set aria-hidden or the hidden attribute too true for the parent div the screen.getByLabelText will only find the form that is visible. But NO. The getByLabelText finds all three. 

I don't want to use getAllByLabelText. In my opinion it will not be as clean.

### Suggested solution:
Labels that are children of an element which has the aria-hidden attribute will not get found with screen.getByLabelText

**Comment by evenodd** [comment]
I ran into this issue today as well. I was trying to test some content gets hidden using `queryByText`. I was under the assumption these queries only return visible elements but I suppose thats not true. 
@lassekl92 for your use case I think you can just use the `byRole` queries like so...
```
 screen.queryByRole('textbox', { name: /firstname/i });
```
byRole uses the accessibility tree so hidden elements wont be returned. I would do this for myself but the content I was testing doesn't have an aria role.

**Comment by Benedicttt** [comment]
I have two labels formats: 
```
<div><label for="kuu">Kuukausi</label></div>
<div><label for="vuosi">Vuosi</label></div>
 


       screen.queryByRole('label', { name: /Vuosi/i })
```

return Received has type:  Null
