### ISSUE TITLE
Rerender doesn't step into useEffect

### ISSUE THREAD

**Issue by fasaas** [testing-library/react-testing-library#847]
- `@testing-library/react` version: 11.2.2
- Testing Framework and version: jest@26.6.3
  
- DOM Environment: @testing-library/dom@7.28.1 @testing-library/jest-dom@5.11.6
  

### Relevant code or config:

```js
import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { act, render, waitFor } from "@testing-library/react";

const TriggerComponent = ({ isDisabled }) => {
    const [disabled, setDisabled] = useState(isDisabled);

    useEffect(() => {
        console.log("USE EFFECT")
        setDisabled(isDisabled)
    }, [isDisabled])

    const onTrigger = async () => {
        setDisabled(true);
        try {
            await axios.get('https://jsonplaceholder.typicode.com/todos/1')
        } catch (e) {
            console.error(e);
            setDisabled(false);
        }
    }

    return (
        <button disabled={disabled} title="Trigger" onClick={onTrigger}>Trigger</button>
    )
}

describe("Trigger component", () => {
    it("Should enable trigger button when rerendering tells it to do so", async () => {
        const { queryByText, rerender } = render(<TriggerComponent isDisabled={false} />)
        expect(queryByText("Trigger")).toBeEnabled();

        act(() => queryByText("Trigger").click())
        await waitFor(() => expect(queryByText("Trigger")).toBeDisabled())

        rerender(<TriggerComponent isDisabled={false} />)

        await waitFor(() => expect(queryByText("Trigger")).toBeEnabled())
    })
})
```

### What you did:

I was writing a simple component `TriggerComponent` that would be re-rendered every 1 minute given it's parent would execute a method every X amount of seconds via a `setInterval`. I am drilling the props correctly, in fact, the actual code updates correctly.

### What happened:

The test I had in mind would be the following: given the parent component re-renders the `TriggerComponent` every so often by the interval, I wanted to cover against the case that when the interval completes, if I get a prop indicating the `TriggerComponent` should be triggerable, I would expect the button to be enabled. However, I am unable to see the button reenabled.

![image](https://user-images.githubusercontent.com/4102787/101374536-91696300-38ae-11eb-9b77-dcb32c1bcf3c.png)

### Reproduction:

Go to https://codesandbox.io/s/react-testing-library-demo-forked-m70zr and see for yourself

### Problem description:

I don't know why after re-rendering, the `useEffect` doesn't get executed when this code in production works.

**Comment by eps1lon** [comment]
Sorry to hear you're having trouble.

> rerender(<TriggerComponent isDisabled={false} />)

This does not re-run the effect since it's dependency didn't change. 

> const [disabled, setDisabled] = useState(isDisabled);

Does only set `disabled` to the value from the prop on mount. Subsequent re-renders will not change the state. The argument for `useState` is only used for the initial state.

**Comment by fasaas** [comment]
@eps1lon  Thanks for the answer, however, that's not the point I'm actually coming for with this issue.
If you actually run the sandbox example, you'll see the isDisabled is actually changed, so the `useEffect` should have been triggered.

**Comment by eps1lon** [comment]
>  so the useEffect should have been triggered because I ask to re-render with isDisabled={false} when the state for disabled is true, so there should be a change in the useEffect dependencies

The dependency of the effect is just the _prop_ `isDisabled` which is `false` on the initial render and the re-render. So the dependency of the effect doesn't change and it's therefore not run.

**Comment by fasaas** [comment]
Ok, now I get it, thanks for explaining. However, how could I force a useeffect update if the production code actually re-enables the button with that same code?
