### ISSUE TITLE
Add handling of async side effects to render function

### ISSUE THREAD

**Issue by andyrichardson** [testing-library/react-testing-library#850]
### Describe the feature you'd like:

Add support for wrapping async render events in `act`.

By default, async side effects dispatched at mount aren't wrapped in act. It would be nice if RTL could handle this.

### Suggested implementation:

Before:

```tsx
it('some test', async () => {
  const myThing = render(<SomeComponent />);
  await act(async () => {}); // <- wait for async action on mount
});
```

After:

```tsx
  const myThing = await render(<SomeComponent />);  // <- wait for async action on mount
```

### Describe alternatives you've considered:

Could provide an option to more strongly differentiate between sync and async renders (not preferred)

```tsx
  const myThing = await render(<SomeComponent />, { async: true });
```

### Teachability, Documentation, Adoption, Migration Strategy:

Created a [PR Here](https://github.com/testing-library/react-testing-library/pull/851)

**Comment by eps1lon** [comment]
Thanks for the report.

I'm not following what you mean by "async renders"? We're currently not supporting concurrent mode if that's what you're asking for. A codesandbox would help understand what you're trying to test.

**Comment by andyrichardson** [comment]
Hey @eps1lon, I'm referring to components that dispatch side effects on mount, following an asynchronous action.

Here's an example:

```tsx
const MyComponent = () => {
  const [data, setData] = useState();

  useEffect(() => {
    fetch('/some-data')
      .then(d => d.json())
      .then(setData);
  }, [])

  return <h1>{data}</h1>
}
```

Testing this component synchronously would result in `act` warnings and potentially memory leaks

```tsx
it('shows data', () => {
  const wrapper = render(<MyComponent />);
  expect(wrapper).toMatchSnapshot();
});
```

Either of these would prevent the aforementioned issue (depending on what the test criteria is)
```tsx
it('shows data', async () => { // <- Test is async
  const wrapper = render(<MyComponent />);
  expect(wrapper).toMatchSnapshot();
  await act(async () => {}); // Wait for async mount actions to settle
});

it('shows data', async () => { // <- Test is async
  const wrapper = render(<MyComponent />);
  await act(async () => {}); // Wait for async mount actions to settle
  expect(wrapper).toMatchSnapshot();
});
```

With the proposed change, this would look like this (depending on what the test criteria is)

```tsx
it('shows data', async () => { // <- Test is async
  const wrapper = await render(<MyComponent />); // Wait for async mount actions to settle
  expect(wrapper).toMatchSnapshot();
});

// OR

it('shows data', async () => { // <- Test is async
  const wrapper = render(<MyComponent />);
  expect(wrapper).toMatchSnapshot();
  await wrapper;  // Wait for async mount actions to settle
});
```

**Comment by eps1lon** [comment]
> Testing this component synchronously would result in act warnings and potentially memory leaks

React has built-in warnings for this particular type of leak.

I suggest you add those cases as tests to your PR since I'm fairly certain your proposal does not fix them. In your PR you're only waiting for a single microtask i.e. you would only act on promises that resolve on the next tick. However, almost all scenarios for promises in effects take longer than that.

**Comment by andyrichardson** [comment]
Sure thing, I'll throw in some tests at some point demonstrate usage :+1:

Just to clarify, I'm not saying this is a solution for all async use cases, but there are many examples of components which dispatch async actions immediately on mount - this is a proposed solution for those cases.

**Comment by eps1lon** [comment]
> this is a proposed solution for those cases.

I suspect that it's even worse to have to explain in which category a certain async task falls than saying: async tasks are not awaited. 

From what I can tell https://github.com/testing-library/react-testing-library/pull/851 could implemented in userland as well. So if this a common pattern in your codebase then you could wrap our `render` with your custom implementation that awaits microtasks and use that instead.

**Comment by andyrichardson** [comment]
Sounds good, I'll close this as it sounds like first-party support isn't desired

**Comment by kelly-tock** [comment]
just came across this, I have a similar question. @andyrichardson did you end up wrapping render and doing this?  if so, how did you end up doing that?  

I have a handful of context providers that many components need. ATM, one is IDB, which we're mocking, and after it is set up we call save on a value to it. this is all in a hook that is in a context. would love to wait for this to settle before the snapshot/any other tests.
