### ISSUE TITLE
Firing click should fire mouseDown and mouseUp too

### ISSUE THREAD

**Issue by SunriseM** [testing-library/react-testing-library#852]
- `@testing-library/react-testing-library` version: 11.2.2
- `node` version: 12.18.2
- `npm` (or `yarn`) version: npm 6.14.5

### Relevant code or config:

```js
fireEvent.click(screen.getByTestId('modal-overlay'))
```

I was expecting `.click` to fire the events `onMouseDown` and `onMouseUp` as the `click` event is fired after those but it's not the case.

It looks important to me because sometimes the component's logic depends on the fact that `onMouseDown/onMouseUp` are fired before `click`

I'm open to making this change if you are ok with it.

**Comment by balavishnuvj** [comment]
@SunriseM, have you tried using https://github.com/testing-library/user-event ?

**Comment by SunriseM** [comment]
> @SunriseM, have you tried using https://github.com/testing-library/user-event ?

I found it after creating this issue, but i still think it would be a nice addition to this lib as its really simple and something you would expect (at least for me). 

I understand though if the idea is to have this implementation without side effects and that one with the "real" behavior.

**Comment by brendan-donegan** [comment]
Definitely don't make this change, it could break a lot of peoples tests.
fireEvent is intended for issuing raw browser events, not for mimicking
user actions.

**Comment by eps1lon** [comment]
> @SunriseM, have you tried using testing-library/user-event ?

We recommend you use this library for your particular problem.

The fireEvent from `@testing-library/react` and `/dom` are supposed to fire low-level events. We only make exceptions for `/react` if we need to fire multiple events to trigger the corresponding Synthetic event (e.g. focus/blur and mouseEnter/Leave).
