### ISSUE TITLE
Input on `focus` or on `hover`, does not display content in conditional rendering 

### ISSUE THREAD

**Issue by georgekrax** [testing-library/react-testing-library#854]
- `@testing-library/react` version: **"11.1.2"**
- Testing Framework and version: **React.js: "17.0.1"** 
  
- DOM Environment:  **Jest.js: "26.6.3"** 
  

### Relevant code or config:

```ts
test("onFocus", async () => {
    render(<Input.Number />);
    const input = screen.getByTestId("input-number");

    // fireEvent.focus(input);
    userEvent.hover(screen.getByTestId("input-number-container"));
    await waitFor(() => {
      expect(screen.getByTestId("input-number-btn-container")).toBeInTheDocument();
    });
    expect(input.getAttribute("value")).toBe("");
    expect(input.getAttribute("aria-valuenow")).toBe("");
    expect(input.getAttribute("data-isbtnshown")).toBeTruthy;
  });
```

### What I did:
I tried to wrap the `fireEvent.focus(input)` into the `act()` function. but nothing really changed. Also, I tried to use the `input.focus()` input's element method, but nothing happened again.

### What happened:
I am using conditional rendering on my component, depending on whether the input is on hover or focused, but in the `screen` element it does not seem to appear. In the browser, it works great!

### Reproduction:
It does not display an error, only except form the fact that it cannot find my buttons, which are meant to be displayed on hover or focus.

### Problem description:
Hello everyone. I am trying to test my number input component, which should display two control buttons, if the user hovers or the input is focused. So, I have conditional rendering involved and of course the use of the `useState()` hook. However, when I try to either `focus()` or `hover()` (neither with `fireEvent.mouseOver()` nor `userEvent.hover()`) nothing changes in the test `screen`. The buttons are not displayed but the state however changes. Below, you can find the relative technical info. Any idea? 

***Note:*** When I add a second conditional to the component, to show something else it works, and displays both elements. Also, I use the `framer-motion` library, and have the `motion.div` being wrapped by `AnimatePresence`. However, when I remove the animation third-party components and functions, nothing different happens.

### Suggested solution:
I have no idea, after trying it for the whole day and not finding something helpful to solve it.

**Comment by eps1lon** [comment]
Thanks for the report.

Please include a reproduction and try to remove as much code as possible. The reproduction should not include any 3rd party code that we're not able to inspect.

**Comment by georgekrax** [comment]
@eps1lon  The issue is now resolved, but I forgot to close the issue. I am sorry for this, and thank you for your help
