### ISSUE TITLE
Errors using RTL with Ionic Modal

### ISSUE THREAD

**Issue by acegautam** [testing-library/react-testing-library#855]
- `@testing-library/react` version: ^9.4.0
- Testing Framework and version: Jest (latest)
  
- DOM Environment: JSDom (with Jest)
  

### Relevant code or config:

```js
import React from 'react';
import { render, screen, waitForElement, wait } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import Home from '../pages/Home';
import {
  mockIonicReact,
  ionFireEvent as fireEvent,
} from '@ionic/react-test-utils';

mockIonicReact();

// const { baseElement, findByText } = render(<Home />);
let renderObj: any;
describe('Home Page Load', () => {
  beforeEach(() => {
    renderObj = render(<Home />);
    // mockIonicReact();
  });


  test('should popup department modal', async () => {
    fireEvent.click(screen.getByTestId('btn'));
    expect(await screen.findByTestId('modalTitle')).toHaveTextContent(
      'Department'
    );
  });
});
```

### What you did:

I am building a hybrid app using Ionic React and using RTL for unit test. All of my tests work fine, except when it comes to clicking a button that open an **IonModal**. I have pasted my test code above.

### What happened:

It fails with a bunch of errors as shown below:
```
(node:79801) UnhandledPromiseRejectionWarning: TypeError: Caught error after test environment was torn down

Cannot read property 'body' of null
(node:79801) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:79801) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 FAIL  src/tests/Home.test.tsx
  ● Home Page Load › should popup department modal

    TypeError: Cannot read property 'present' of undefined

      at Overlay.present (node_modules/@ionic/react/src/components/createOverlayComponent.tsx:105:26)
```

### Problem description:

Because of the above error, I am blocked and am not able to proceed further with the subsequent actions and test. Would really appreciate if you could help me out.

### Suggested solution:
 I researched a lot, looked at some similar situations mentioned in stackoverflow, discord, tried a bunch of solutions desperately (e.g. using renderInDocument, passing container body as prop, wait, waitForElement etc.) but none worked. I am completely stumped at the moment, would be really grateful if you could help solve this for me. Thanks.

**Comment by Fernito69** [comment]
Hi @acegautam, could you find a solution for this? I'm running into exactly the same issue.

**Comment by m98** [comment]
When in need to wait for any period of time you can use [waitFor](https://testing-library.com/docs/dom-testing-library/api-async/#waitfor)

You can change your `expect` to this:
```
    await waitFor(()=>expect(screen.findByTestId('modalTitle')).toHaveTextContent(
        'Department'
    ));
```

**Comment by m98** [comment]
Close since it does not seem to be an issue
