### ISSUE TITLE
Return type of unmount function

### ISSUE THREAD

**Issue by sanchit121** [testing-library/react-testing-library#856]
- `@testing-library/react` version: 11.2.2
- Testing Framework and version: Jest 26.6.3
- DOM Environment: jsdom

### Relevant code or config:

```js
export type RenderResult<Q extends Queries = typeof queries> = {
  container: Element
  baseElement: Element
  debug: (
    baseElement?:
      | Element
      | DocumentFragment
      | Array<Element | DocumentFragment>,
    maxLength?: number,
    options?: prettyFormat.OptionsReceived,
  ) => void
  rerender: (ui: React.ReactElement) => void
  unmount: () => boolean
  asFragment: () => DocumentFragment
} & {[P in keyof Q]: BoundFunction<Q[P]>}
```

### What you did:

Trying to use unmount()

### Problem description:

wrapper.unmount() returns undefined, whereas the type shows it returns boolean
...\node_modules\@testing-library\react\types\index.d.ts

### Suggested solution:

We can update the type definition file.

**Comment by sanchit121** [comment]
Here is pull request https://github.com/testing-library/react-testing-library/pull/857

**Comment by eps1lon** [comment]
Closed in https://github.com/testing-library/react-testing-library/pull/857
