### ISSUE TITLE
Documentation unclear with screen vs render

### ISSUE THREAD

**Issue by jonniedarko** [testing-library/react-testing-library#863]
-   "@testing-library/react": "^11.2.3",
-   "@testing-library/jest-dom": "^5.11.9",

I am finding the documentation confusing, throughout the doc it mention using `screen` e.g. `screen.getByTestId` or `screen.getByText` but when I try to use this these function do not exist. Render results has these functions but not finding elements I can find in browser console (another issue not trying to address here) 

I am unclear why docs say to use the screen methods but I am not able to. Is there some config I am missing?

**Comment by alexkrolick** [comment]
> but when I try to use this these function do not exist

Can you show an example of how you are trying to use them?

**Comment by jonniedarko** [comment]
this seemed to be a jest setup issue because when I have :
```
import * as testing from '@testing-library/react';
const { screen } = testing;
``` 
it seemed to work fine 🤷  

thanks for responding, I'll close this since it is clearly something funky with my local env
