### ISSUE TITLE
Cleanup not working as I would expect

### ISSUE THREAD

**Issue by vandercloak** [testing-library/react-testing-library#864]
- `@testing-library/react` version: 11.2.3
- Testing Framework and version: Jest 26 via react-scripts 4.0.1
- DOM Environment: react-dom 17

### Relevant code or config:

```js
// App.tsx
export default function App({ showMessage }) {
  useEffect(() => {
    if (showMessage) message.success("Foo Bar");
  }, [showMessage]);

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
    </div>
  );
}

// App.test.tsx
test("control", () => {
  expect("react is awesome").toBeTruthy();
});

test("works great", async () => {
  const screen = render(<App showMessage />);
  await waitFor(() => screen.getByText("Foo Bar"));
});

// 👇 Does not fail  🤯
test("should fail", async () => {
  const screen = render(<App showMessage={false} />);
  await waitFor(() => screen.getByText("Foo Bar"));
});
```

### What you did:

Wrote two tests where a message should be showing in one and not in the other.

### What happened:

The message showed up in both tests. 

### Reproduction:

https://codesandbox.io/s/strange-elion-8yv5r?file=/src/App.tsx:127-407

### Problem description:

As I understand, the cleanup up functionality should clean up the message in the first test and not show up in the second test. This does not appear to be happening as I would expect. 

I read through https://github.com/testing-library/react-testing-library/issues/368 but didn't find a resolution to my problem.

**Comment by vandercloak** [comment]
I can get the tests to pass by adding a callback to my useEffect to clean up the message like so:
```js
useEffect(() => {
    if (showMessage) message.success("Foo Bar");
    return message.destroy();
  }, [showMessage]);
``` 

But my desired behavior is not for he message to be destroyed on unmount but carry over to other pages/screens of my app. Could just be thinking about this wrong, but just confused why cleanup wouldn't give me a fresh dom state.

**Comment by alexkrolick** [comment]
What does `message.success()` do? Is that some kind of global side-effect?

**Comment by vandercloak** [comment]
@alexkrolick It's ant-designs notification which uses rc-notification under the hood. It has a managed list on notices that inserted into a div that has a fixed position and a high z-index.

**Comment by MatanBobi** [comment]
> 
> Could just be thinking about this wrong, but just confused why cleanup wouldn't give me a fresh dom state.

What we do in the [cleanup](https://github.com/testing-library/react-testing-library/blob/deafd51bc20209612674dbdaba920750c1d6352e/src/pure.js#L108
) is call `ReactDOM.unmountComponentAtNode` for each container we rendered before. This basically starts an unmount flow in React and if the `parentNode` of the current component is the `body` element then we also detach it from the DOM. My guess is that since we don't render the `rc-notification`, it happens as a side effect, it's not a part of the `cleanup` flow since it's not inside the `mountedContainers` DOM.

**Comment by tomasfrancisco** [comment]
I had the same problem with components that would trigger a change on the DOM through a `setTimeout`.
I added `unmount` after the assertion `expect(...).toBe(...)` and it solved the duplicates in the DOM in between tests.

**Comment by eps1lon** [comment]
Closing since this issue is unactionable for `@testing-library/react`. 

I would recommend you file this against `antd` to find out how their library methods can be isolated inbetween tests.

If this is in fact an issue with `@testing-library/react` please open a new issue that doesn't contain 3rd party code besides `react` and `react-dom` i.e. no `antd`.

**Comment by sauldeleon** [comment]
Hi @vandercloak I do not pretend to reopen the issue, but I faced the same problem and maybe my solution works for you.

this is just a test for our notification system based on antd too, and indeed the dom between each test in the same test suite was with the previous tests.

this is our final solution to 2 tests that renders the same notification and wait until its automatic close

P.S `renderLayout` is a simple method that renders a button to trigger the modal and the notification mount component.

```ts
  it('renders info notification correctly', async () => {
    const { getByTestId } = renderLayout({ message: 'Test', description: 'description test', type: 'info' })
    const button = getByTestId('notification-button')
    await act(async () => {
      fireEvent.click(button)
    })
    expect(getByTestId('icon-info')).toBeDefined()
  })

  it('notification is removed when pass 1 seconds', async () => {
    const { getByTestId, queryByTestId } = renderLayout({
      message: 'Test',
      description: 'description test',
      type: 'info',
    })

    const button = getByTestId('notification-button')
    await act(async () => {
      fireEvent.click(button)
    })
    await waitFor(() => expect(queryByTestId('icon-info')).toBeNull())
  })
```
