### ISSUE TITLE
Async "findBy" query not working as expected

### ISSUE THREAD

**Issue by manedurphy** [testing-library/react-testing-library#866]
Hello. I am currently encountering an issue with the `screen.findByText` query. I have included a link to show this issue at the bottom. I am simply inputting text into the input text field, and on submit, appending that text to the DOM. I am trying to "await" the query, but the error shows it is not finding this text.

Is there as step I am missing/concept I am not understanding? Or is this a bug?
Thank you.

Sandbox: https://codesandbox.io/s/new-resonance-ngze3?file=/package.json

**Comment by eps1lon** [comment]
Thanks for the report.

The value you want to set has to be set with `target: { value }`:

```diff
-  fireEvent.change(input, { target: "User" });
+  fireEvent.change(input, { target: { value: "User" } });
```

**Comment by manedurphy** [comment]
@eps1lon thank you for your response, that did the trick
