### ISSUE TITLE
onSubmit does not receive nativeEvent.submitter

### ISSUE THREAD

**Issue by TimvdEijnden** [testing-library/react-testing-library#870]
- `@testing-library/react` version: 11.2.3
- Testing Framework and version: Jest 
  
- DOM Environment: Firefox 85 & Chrome 88
  

### Relevant code or config:

```html
      <form onSubmit={handleOnSubmit}>
        <p>
          <input type="firstname" value="Michael" readOnly />
        </p>
        <p>
          <input type="lastname" value="Scott" readOnly />
        </p>
        <button type="submit" value="next" name="action">
          Next
        </button>
        <button type="submit" value="save" name="action">
          Save
        </button>
      </form>
```

```js
  function handleOnSubmit(event) {
    event.preventDefault();
    console.log(event.nativeEvent.submitter); <--------------------- does not exit
  }
```

### What you did:

```js
  fireEvent.click(getByRole("button", { name: "Next" }));
```

### What happened:

The submit event is received by handleOnSubmit, the event.nativeEvent does not have the submitter property.

### Reproduction:

https://codesandbox.io/s/missing-submitter-lj4pq?file=/src/App.test.js

### Problem description:

When testing this situation manually in the browser the submitter values is set to the HTML element clicked to submit the form. When dealing with multiple submit buttons you should be able to distinguish the button pressed to submit the form. 

### Suggested solution:

Allow to provide properties to be added to the nativeEvent which end up in the `handleOnSubmit`

**Comment by davidakerr** [comment]
I have also just encountered this issue. I have multiple submit buttons outside the scope of the form and this is the only way I can identify which of those buttons is pressed.

**Comment by davidakerr** [comment]
I thought I'd come back and post the hack I made to get this working <3

`          <button
            onClick={(e) => {
              const customEvent = new Event('submit');
              // @ts-ignore
              customEvent.name = 'Next';
              //@ts-ignore
              document.forms[`${currentStepData.id}__form`].dispatchEvent(
                customEvent
              );
            }}
          >
            Next
          </button>`
          
          ` <form
            id={`${currentStepObject.id}__form`}
            data-testid={`${currentStepObject.id}__form`}
            onSubmit={(event) => {
              handleSubmit(event);
              // not sure how to type this hack :p
              // @ts-ignore
              const pressedButton = event.nativeEvent.name;
              if (pressedButton === 'Next') {
                currentStepObject?.nextStep &&
                  dispatch(setCurrentStep(currentStepObject.nextStep));
              }
              if (pressedButton === 'Previous') {
                currentStepObject?.previousStep &&
                  dispatch(setCurrentStep(currentStepObject.previousStep));
              }
            }}
          >

          </form>`

**Comment by ChasinHues** [comment]
> When dealing with multiple submit buttons you should be able to distinguish the button pressed to submit the form.
This is the situation I have encountered as well.

**Comment by eps1lon** [comment]
Thanks for the report.

This issue only occurs when using JSDOM as your testing environment instead of a real browser. Closing in favor of https://github.com/jsdom/jsdom/issues/3117 since this should be fixed directly in JSDOM.

Please upvote and subscribe to the JSDOM issue if you're interested in fixing the issue.
