### ISSUE TITLE
Error in useEffect clean up function not causing test to fail

### ISSUE THREAD

**Issue by jniemin** [testing-library/react-testing-library#874]
- `@testing-library/react` version: 11.2.5
- Testing Framework and version: 
New application created by create-react-app with dependencies
```
"@testing-library/jest-dom": "^5.11.4",
"@testing-library/react": "^11.1.0",
"@testing-library/user-event": "^12.1.10",
"react": "^17.0.1",
"react-dom": "^17.0.1",
```
  
- DOM Environment:
Jest version 26.6.3
JSDOM 16.4.0
  

### Relevant code or config:

```js
import React from 'react';
import { render } from '@testing-library/react';

function SimpleComponent() {
  React.useEffect(() => {
    return function cleanUp() {
      throw new Error('Clean up throws error');
    };
  }, []);
  return (<div>HelloWorld</div>);
}

describe('Simple test case', function() {
  it('This test case should not pass', () => {
    expect(() => {
      const { unmount } = render(<SimpleComponent />);
      unmount();
    }).not.toThrow();
  });
});

```

### What you did:
Simple test case above

### What happened:
When react useEffect cleanup function throws error, test passes when it should not.

### Reproduction:
1. Create new react app (I did this with create-react-app). 
1. Add above test case to app
1. Run tests

### Problem description:
This test case should fail as there was error thrown in useEffect clean up, but it does not. It will log the error but test case passes.

### Suggested solution:
Test should fail if cleanup function throws any errors.

**Comment by giseleml** [comment]
Maybe you should reproduce your code on something like CodePen or CodeSandbox and add to your issue because when I'm testing locally the test does not pass. :confused:

**Comment by jniemin** [comment]
@giseleml I added new sample to CodeSandbox https://codesandbox.io/s/intelligent-oskar-puduj?file=/src/example.spec.js. Let me know if you need any more help on debugging this

**Comment by eps1lon** [comment]
@jniemin Thanks for the repro. This behavior changed in React 17. I've opened https://github.com/facebook/react/issues/20946 on the React repo to get clarification since I don't think that we can do anything about it in `@testing-library/*`

**Comment by eps1lon** [comment]
The behavior you're looking for is currently behind a feature flag and not accessible to open-source builds of React. I encourage you to subscribe to https://github.com/facebook/react/issues/20946 to be notified about updates.

We can't do anything about in `testing-library/react`.
