### ISSUE TITLE
Receiving warning - "Warning: You seem to have overlapping act()" when test executed in describe block

### ISSUE THREAD

**Issue by abhi747** [testing-library/react-testing-library#880]
- `@testing-library/react` version: 11.1.2
- Testing Framework and version: 26.0.8
   No
- DOM Environment:
  

### Relevant code or config:

```js
it('submit allocations', async (done) => {
      cleanup();
      http.post = jest.fn().mockResolvedValueOnce({ status: 200 });
      render(<Configure isOnlineMode={true} />);
      await waitFor(() => {
        expect(http.post).toHaveBeenCalled();
        done();
      });
    });

    it('log error when queue submission fails', async (done) => {
      cleanup();
      http.post = jest.fn().mockRejectedValue({ status: 404 });
      const consoleSpy = jest.spyOn(console, 'error');
      render(<Configure isOnlineMode={true} />);
      await waitFor(() => {
        expect(consoleSpy).toHaveBeenCalledWith({ status: 404 }));
        done();
      });
    });
```

### What you did:

I have the above two tests in one `describe `block. In the `useEffect ` of `Configure` component, there is a promise called. On the successful resolution of the promise, the` http.post` method is called which is an API call. In the catch block of the `http.post`, there is `console.error` statement with the error that is caught as a parameter.

The useEffect is like below. Refactored it here for simplicity and brevity.

```
  useEffect(() => {
    if (flag) { // flag is a boolean state variable
      values().then((data: any[]) => { // values() return a promise
        data.length &&
          http // HTTP network call
            .post("url", data)
            .then((res) => console.log(res))
            .catch((err) => console.error(err));
      });
    }
  }, [flag]);
```

### What happened:

When executed the above two tests individual, they are getting passed. But when I execute the `describe` containing the above two tests, the later one fails with the below output.

![image](https://user-images.githubusercontent.com/39051251/109831887-db6fa400-7c65-11eb-9c5b-9eef2c834050.png)

What is wrong happening here? How come the tests are getting passed when executed individually but the latter fails when executed in the `describe` block with the first one?

**Comment by MatanBobi** [comment]
Hi @abhi747, thanks for taking the time to open this.
Can you please attach your `useEffect`'s/component's code? We probably won't be able to try and understand what's happening here without it..

**Comment by abhi747** [comment]
@MatanBobi , I have added the useEffect block from the code in the original question. Have refactored it there for simplicity and brevity.

**Comment by MatanBobi** [comment]
@abhi747 Tried recreating it and looks like it's working with now warnings:
https://codesandbox.io/s/xenodochial-mendeleev-cc7r6?file=/src/index.test.js

I'm trying to think what in your specific logic causes the test not to end at time.
When is the `flag` changing? Also the `values` returns a promise but it's not mocked, is that some async operation that may take time and doesn't end at time?

**Comment by abhi747** [comment]
@MatanBobi , thank you very much for recreating and looking into this!

It was my bad. You are right, not mocking the `values()` which returns a promise was actually taking time to complete and causing the issue. I mocked it now and the issue vanished.

**Comment by MatanBobi** [comment]
Sure, glad I was able to help @abhi747 :)
So I'm closing this one. If you need anything further, feel free to comment :)
