### ISSUE TITLE
Seeing @testing-library/dom on the production bundle 

### ISSUE THREAD

**Issue by davidpaley** [testing-library/react-testing-library#884]
- `@testing-library/react` 9.5.0:
- Testing Framework and version:`Jest`: "25.5.4",
- DOM Environment:
"@testing-library/jest-dom": "5.11.6"

### Relevant code or config:

```js
"devDependencies": {
    "@babel/runtime-corejs2": "^7.9.2",
    "@cityfurniture/connector": "^2.2.32",
    "@next/bundle-analyzer": "^9.4.4",
    "@testing-library/jest-dom": "^5.11.6",
    "@testing-library/react": "^9.5.0",
    "@types/cleave.js": "^1.3.3",
    "@types/enzyme": "^3.1.14",
    "@types/enzyme-adapter-react-16": "^1.0.3",
    "@types/googlemaps": "^3.40.3",
    "@types/jest": "^23.3.14",
    "@types/next": "^7.0.0",
    "@types/next-redux-wrapper": "^2.0.0",
    "@types/node": "^10.17.28",
    "@types/react": "^16.8.13",
    "@types/react-redux": "^6.0.14",
    "@types/react-select": "^3.0.0",
    "@types/react-sticky": "^6.0.2",
    "@types/react-test-renderer": "^16.0.3",
    "@types/redux-mock-store": "^1.0.0",
    "@types/redux-saga": "^0.10.5",
    "@types/styled-jsx": "^2.2.5",
    "@types/yup": "^0.29.5",
    "@typescript-eslint/eslint-plugin": "^2.16.0",
    "@typescript-eslint/parser": "^2.16.0",
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-sass": "^1.0.1",
    "awesome-typescript-loader": "^5.2.1",
    "babel-jest": "^24.8.0",
    "babel-loader": "^8.0.2",
    "babel-plugin-transform-define": "^1.3.1",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.5",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-config-react": "^1.1.7",
    "eslint-plugin-import": "^2.20.0",
    "eslint-plugin-jest": "^22.21.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.17.0",
    "husky": "^4.3.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^25.5.4",
    "jest-dom": "^3.1.3",
    "jest-environment-enzyme": "^7.1.2",
    "jest-enzyme": "^7.1.2",
    "jest-junit": "^11.1.0",
    "mockdate": "^3.0.2",
    "mutationobserver-shim": "^0.3.7",
    "next-purgecss": "^4.0.0",
    "nextjs-export-path-map": "^0.1.2",
    "node-sass": "^4.14.1",
    "prettier": "1.19.1",
    "react-test-renderer": "^16.13.1",
    "redux-devtools-extension": "^2.13.8",
    "redux-logger": "^3.0.6",
    "redux-mock-store": "^1.5.3",
    "redux-saga-test-plan": "^4.0.1",
    "typescript": "^3.9.7",
    "webpack-bundle-analyzer": "^3.3.2"
  },
```
### What you did:
Test performance of my client's site https://www.cityfurniture.com/browse/dining-room 

### What happened:

I am using version 5.11.6 of `testing-library/jest-dom` and Lighthouse is showing me that `@testing-library/dom` is on the production bundle.
![image](https://user-images.githubusercontent.com/4527780/111467215-f11fa780-8702-11eb-917a-61f8bb69414f.png)

![image](https://user-images.githubusercontent.com/4527780/111507193-2808b400-8729-11eb-8ec5-0ddf70b00dd1.png)

### Reproduction:
Go to https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.cityfurniture.com%2Fbrowse%2Fdining-room and check the unused Javascript section.

### Problem description:
I need to make my bundle smaller.

### Suggested solution:
Make sure we don't include this in the production bundle

**Comment by eps1lon** [comment]
Thanks for the report.

Unfortunately, this is almost impossible to debug without knowing that code that resulted in that bundle and how that bundle is build (+config).

Though it looks like you're just including `pretty-format` not `@testing-library/dom`. It just happens to be the version of `pretty-format` that is used by `@testing-library/dom`. Are you maybe importing `prettyDOM` from `@testing-library/dom` somewhere?

What happens if you just install the production dependencies (`npm install --production`) and build your site?

**Comment by davidpaley** [comment]
Hi, thanks for the answer. No, I am not importing prettyDOM. When I built the project after executing npm install --production I got the same results.

I can see the chunk that have that with the bundle analyzer
![image](https://user-images.githubusercontent.com/4527780/111562512-1cdb7580-8775-11eb-846e-b7fd5efb703a.png)

I am not sure if this is a problem related with the configuration of next js.

**Comment by eps1lon** [comment]
I'm unable to identify the issue without a full reproduction in this case.

**Comment by nickmccurdy** [comment]
You might want to use a dependency inspector like madge. webpack bundle analyzer only shows the paths and sizes of modules (not the dependency chains that cause modules to be bundled) as far as I'm aware.

**Comment by davidpaley** [comment]
Hi, I discovered the reason for the issue. It was related to how we were managing some component imports on the server, using `require` instead of dynamic imports.

Thanks @eps1lon and @nickmccurdy for the help :)

**Comment by luiznasciment0** [comment]
@davidpaley can you elaborate a bit more about how you solved it? I'm having the exactly same problem

**Comment by davidpaley** [comment]
> @davidpaley can you elaborate a bit more about how you solved it? I'm having the exactly same problem

I was using Next js, and one of the components was importing many components with `require` statement. That seems to make some problem with the next js built and it generates a big chunk with a lot of unnecessaries dependencies.

**Comment by gtempesta-pixartprinting** [comment]
I can confirm that using `require` for some assets in a completely different project was the cause for having `@testing-library` in the bundle. 

I think that what was happening was that `require` forced **webpack** to bundle all the files in my src folder. Close to `App.tsx` I also had `App.test.tsx` which was importing `@testing-library`, hence the strange behaviour.

Did anyone else have some similar experience? Is this behaviour documented?
