### ISSUE TITLE
Mocha support

### ISSUE THREAD

**Issue by minu1994** [testing-library/react-testing-library#885]
I'd like to know if I can configure React Testing Library with Mocha. 
I can't find any documentation about it.
Thanks

**Comment by eps1lon** [comment]
Do you have a specific question? This should work by default.

**Comment by minu1994** [comment]
I'm starting from a Create React App project and I'd like to switch from jest to mocha for performance reason. I installed mocha inside my devDependencies and then I didn't understand how connect React Testing Library with it

**Comment by eps1lon** [comment]
Just like you would with jest. I suggest you ask around on [our discord](https://discord.gg/testing-library) since we use github for bugs and feature requests. We're using react-testing-library in Material-UI and there isn't anything special to jest vs mocha.
