### ISSUE TITLE
Documentation mismatch: fireEvent wrapped in act()

### ISSUE THREAD

**Issue by jancama2** [testing-library/react-testing-library#887]
[Cheatsheet | Testing Library](https://testing-library.com/docs/react-testing-library/cheatsheet/#events) says "React Testing Library wraps render and fireEvent in a call to `act`". I've checked the implementation and there is no sigh of `act` being used. Is it my poor understanding of the code or is the sentence in the docs misleading?

**Comment by alexkrolick** [comment]
https://github.com/testing-library/dom-testing-library/blob/master/src/config.ts#L23
https://github.com/testing-library/react-testing-library/blob/master/src/pure.js#L19

It's implemented via config

**Comment by jancama2** [comment]
> https://github.com/testing-library/dom-testing-library/blob/master/src/config.ts#L23
> https://github.com/testing-library/react-testing-library/blob/master/src/pure.js#L19
> 
> It's implemented via config

Oh, I see, missed that, thanks for the explanation!
