### ISSUE TITLE
Should I use the document to query classes and ids?

### ISSUE THREAD

**Issue by ArmantoArisRoutsis** [testing-library/react-testing-library#904]
Hello. I am a new developer and I don't know if this is the right place to ask this question. 

I have been using the react-testing-library for about a month now and I really enjoy working with it. I am currenlty trying to test the DOM behavior (things such as classNames and ids) and from what I read the recomended way to do that with react testing library is by using test-ids. However I am trying to avoid that and want to work with only already written code. I have been using the document object to query classNames and ids ( document.getElementById, document.getElementsByClassNames ) and it has been working amazing. I even saw some people here posting about using that alternative since there are not plans on adding any new queries such as getByClass or getById. Just looking for some feedback.

**Comment by eps1lon** [comment]
Support requests filed as GitHub issues often go unanswered. We want you to find the answer you're looking for, so we suggest the following alternatives:



Talk to other React developers
We have a dedicated discord with lots of people that may have had similar issues. Check out https://discord.gg/testing-library and hopefully somebody can help you.
