### ISSUE TITLE
@testing-library/dom as peerDependency

### ISSUE THREAD

**Issue by romain-trotard** [testing-library/react-testing-library#906]
Hello guys :)

In a project I work for, I had recently a problem with my dependencies. 
We use:
- @testing-library/react: 11.2.6
- @testing-library/user-event: 13.1.5
- @testing-library/dom: 7.13.0

Because the version I used for `@testing-library/dom` was not compatible with the version used by `@testing-library/react`, I had two versions of `@testing-library/dom` which were pulled.
So when I used `@testing-library/user-event`, my event calls were not wrap with act because it was not the same instance which were wrapped by `act`. 
So I had warnings from React telling me to wrap in `act` (although I know that `fireEvent` wrap with `act`). It takes me sometimes to understand that it was not the same instance of  `@testing-library/dom`  which were used.

 
### Describe the feature you'd like:

I ask myself why `@testing-library/dom` is in peerDependency in `@testing-library/user-event` (what I think is a good thing) but not in `@testing-library/react`. 
Does someone know the choice to have `@testing-library/dom` as a dependency in `@testing-library/react` ?

### Suggested implementation:

Put  `@testing-library/dom` as a peerDependency.

### Teachability, Documentation, Adoption, Migration Strategy:

This will require a breaking version and a migration guide.

What do you think of it guys ? (Maybe I didn't understand why it was necessary to have `@testing-library/dom` as dependency)
Thank you in advance

**Comment by MatanBobi** [comment]
Hi @romain-trotard! Thanks for taking the time to open this.
I can explain the rational behind this as far as I can understand it.
Unlike `user-event` which is a companion library and doesn't really stand on it's own, the other libraries we have are standalone and only rely on `testing-library/dom` which is the core module.
As a user, you'd probably install `user-event` along with `testing-library/react` and not only `user-event`.
On the other hand, a user can install `testing-library/react` only.
I believe that's the reason why there's a difference between the two.
Another thing we do in the libraries is we `export` everything from `testing-library/dom` so one wouldn't really need to import anything from `testing-library/dom` directly.

Given all I wrote above, I'm not sure if we really should state it as a `peerDependency` as these libraries are different, but I'll keep this one open to hear more opinions :)

Thanks again for posting this!

**Comment by hendis85** [comment]
👍👌

**Comment by romain-trotard** [comment]
Thank you @MatanBobi for your response. Let's wait for another opinion :)

**Comment by rosczja** [comment]
I have a similar problem, but with types and TypeScript.

I have `testing-library/dom` 8.11.1 and `testing-library/react` 12.1.2 installed. I want to use the `current` option of the `ByRole` queries, but that is not included in the `testing-library/dom` version installed with `testing-library/react`. In the documentation this option is of course mentioned. I find this very confusing.

So please consider either switching to peer dependency or to release a new version of `testing-library/react` if a new major/minor version of `testing-library/dom` has been released.

**Comment by romain-trotard** [comment]
Hello @rosczja.
Actually, if there is a new minor version of `testing-library/dom` and the semver is compatible with the version pulled by `testing-library/react` you can upgrade it on your own by:
- removing the entry corresponding to `@testing-library/dom` in your `yarn.lock` (or package-lock.json)
- launching `yarn` (or `npm i`)
(I do like this not to upgrade any other libraries)
You will get the latest compatible version of `@testing-library/dom`. 
I guess for major version, `@testing-library/react` already does the change in their `package.json`, followed by a new version.

The `current` option seems to have been added in `8.2.0` make sure to have only one version of `@testing-library/dom` at version `8.11.1` and it will work :) (you can check the versions pulled by your project with `yarn why @testing-library/dom).
And if you want to deduplicate all your dependency automatically there is this library https://github.com/atlassian/yarn-deduplicate

Hoping that could help you :)

**Comment by rosczja** [comment]
Hello @romain-trotard ,

thanks for the link to yarn-deduplicate. That helped in my case. Nice.

**Comment by romain-trotard** [comment]
I close the issue ;)
