### ISSUE TITLE
Could not find a declaration file for module "@testing-library/react"

### ISSUE THREAD

**Issue by coler-j** [testing-library/react-testing-library#907]
- `@testing-library/react` version: `9.4.0`
- "@types/testing-library__react": "10.2.0",
- Testing Framework and version:
  -  "jest": `26.6.3`
  - "babel-jest": `26.6.3`
  - "ts-jest": `26.5.5`
- DOM Environment:
  -  "@testing-library/jest-dom": "5.11.10"

### Relevant code or config:

(In any test file)

`import { render, fireEvent, screen, act, waitForElementToBeRemoved } from '@testing-library/react';`

![image](https://user-images.githubusercontent.com/7839615/116909156-cbe2ec00-ac11-11eb-8097-d9f9a38b83af.png)

### What you did:

Try to import `@testing-library/react`

### What happened:

The types do not also get imported.

### Problem description:

Are special steps required to install/configure types?

**Comment by eps1lon** [comment]
We're not supporting v10 and lower. Please upgrade to `@testing-library/react^11.0.0`.

**Comment by MatanBobi** [comment]
Also, the types have moved to this repo so no need for `@types/testing-library__react": "10.2.0"`.
