### ISSUE TITLE
Invalid offsetParent when rendering

### ISSUE THREAD

**Issue by megawebmaster** [testing-library/react-testing-library#915]
- `@testing-library/react` version: v11.1.2
- Testing Framework and version: 25.3.0 (built-in Jest version from `@testing-library/react`)
- DOM Environment: console
- `react`: 17.0.1
- Node: 16.2.0

### Relevant code or config:

Here's a piece of a test code that will fail (and shouldn't):

```js
test('properly renders elements within the document', () => {
  const { getByTestId } = render(<div data-testid="element" />)
  expect(getByTestId('element').offsetParent).not.toBe(null)
})
```

### What you did:

I'm writing a test for `react-responsive-modal` library that checks if elements within the modal are properly focusing if we trap the focus within the modal (for accessibility). The library checks whether there are any visible elements and focuses the first, visible one. According to MDN [HTMLElement.offsetParent](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent) can be used to determine (in most cases) that element is hidden (for the rest we can check heavier calculated styles).

### What happened:

Tests fail due to theoretically invisible elements - unable to focus them.

### Reproduction:

Just run `yarn test` on this code: https://github.com/megawebmaster/react-responsive-modal/tree/master/react-responsive-modal

### Problem description:

Unfortunately the library does not set `offsetParent` property properly causing the library to fail the test as it is unable to find any visible elements on the page causing focus to stay on the `body` of the page. The code works as expected in a real browser, but does not pass in console tests.

### Suggested solution:

I have no solution as it is hard for me to find how `@testing-library/react` renders the page and why `offsetParent` is not set as expected.

**Comment by eps1lon** [comment]
Thanks for the report.

This is a known limitation of the test environment you're using (`jsdom`). For layout assertions you should run your tests in an actual browser.

Closing since this isn't actional for testing-library packages.
