### ISSUE TITLE
fireEvent.change not triggering event on element when value is an empty string

### ISSUE THREAD

**Issue by crtl** [testing-library/react-testing-library#924]
- `@testing-library/react` version: 11.1.0
- Testing Framework and version: 
React: 17.0.2
@testing-library/user-event: 12.1.10

### Reproduction:

```tsx
import {fireEvent, render} from "@testing-library/react";

it("should call onChange", () => {

    const onChange = jest.fn();

    const wrapper = render(<div>
        <label htmlFor="my-input">Input</label>
        <input type="text" id="my-input" name="myInput" onChange={onChange}/>
    </div>);

    const input = wrapper.getByLabelText("Input");

    expect(input).toBeInTheDocument();

    fireEvent.change(input, {target: {value: ""}});

    // Test fails
    expect(onChange).toHaveBeenCalledTimes(1);
});
```

### Problem description:

Using `fireEvent.change` on an input will not trigger the change event when the provided value is an empty string.

### Suggested solution:

Events should be fired to enable testing for empty inputs and related logic.

**Comment by eps1lon** [comment]
Thanks for the feedback!

> Events should be fired to enable testing for empty inputs and related logic.

An `onChange` event is only fired if the value actually changes. So if you initialize the input with no value, setting the empty string does not change the value.

Does this clear things up?

**Comment by crtl** [comment]
@eps1lon Yes, thank you.
