### ISSUE TITLE
Playwright support

### ISSUE THREAD

**Issue by marcuslindfeldt** [testing-library/react-testing-library#935]
### Describe the feature you'd like:

Unsure if this is the correct place for this feature request but I could not find any any existing issues regarding [Playwright](https://playwright.dev/) support and the discord invite link in the docs is invalid.

Just like testing-library has specialised libraries for Cypress and Puppeteer etc.. it would be great with official support for the new [Playwright](https://playwright.dev/) library as well.

**Comment by eps1lon** [comment]
You probably want to try out https://github.com/hoverinc/playwright-testing-library
