### ISSUE TITLE
asFragment does not works properly with `td`, `tr` or `tbody`

### ISSUE THREAD

**Issue by artola** [testing-library/react-testing-library#940]
- `@testing-library/react` version: 11.2.7
- Testing Framework and version: jest 26.6.3
  
- DOM Environment: jsdom 16.4.0
  

### Relevant code or config:

```js
        const tbody = document.createElement('tbody');

        const {asFragment} = render(
          <tr>
            <td>foo</td>
          </tr>,
          {container: document.body.appendChild(tbody)},
        );

        // EXPECTED
        expect(asFragment()).toMatchInlineSnapshot(`
          <DocumentFragment>
            <tr>
              <td>foo</td>
            </tr>
          </DocumentFragment>
        `);

       // RECEIVED
        expect(asFragment()).toMatchInlineSnapshot(`
          <DocumentFragment>
            foo
          </DocumentFragment>
        `);
```

### What you did:

Using `asFragment` when the "root" element is `td`, `tr` or `tbody` seems to not work properly, as with any other element, just `table` works.

### What happened:

For example, this construction (with this passed `container` or with the default one) will work as expected:

```js
       const div = document.createElement('div');

        const {asFragment} = render(
          <table>
            <tbody>
              <tr>
                <td>foo</td>
              </tr>
            </tbody>
          </table>,
          {container: document.body.appendChild(div)},
        );
```

but every single element wrapping "foo" is not properly working when used outside of this composition. No errors are printed.

**Comment by MatanBobi** [comment]
Hi @artola, thanks for opening this one.
The reason for that is that rendering `tbody`, `tr` or `td` without a `table` isn't a valid HTML.
To create a Fragment we use [`createContextualFragment`](https://developer.mozilla.org/en-US/docs/Web/API/Range/createContextualFragment) and since that's not a valid HTML, that API doesn't return the elements.
I don't think we should support this IMO since that's not a valid HTML.

**Comment by nickmccurdy** [comment]
This test is pretty much passing for me, it's only failing because of the whitespace alignment:
```
 FAIL  src/index.test.js
  ✕ renders fragment (30ms)

  ● renders fragment

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `renders fragment 1`

    - Snapshot
    + Received

      <DocumentFragment>
        <tr>
    -     <td>foo</td>
    +     <td>
    +       foo
    +     </td>
        </tr>
      </DocumentFragment>

      26 |   )
      27 |
    > 28 |   expect(asFragment()).toMatchInlineSnapshot(`
         |                        ^
      29 |     <DocumentFragment>
      30 |       <tr>
      31 |         <td>foo</td>
```

**Comment by artola** [comment]
@nickmccurdy Could you please share the source code of your test?  I do not figure out how to create the "container".

This fragment for the whole table works:

```
        const {asFragment} = render(
          <table>
            <tbody>
              <tr>
                <td>foo</td>
              </tr>
            </tbody>
          </table>,
        );
```

How to use the "container" to make it work for a `td`?:

```
render(<td>foo</td>, {container:   ???  })
```

**Comment by MatanBobi** [comment]
Well, since your container is only the `tr`, it's still not a valid HTML. That's my guess at least, I'd be happy if @nickmccurdy will share the code that worked for him :)
