### ISSUE TITLE
Module '"@testing-library/react"' has no exported member 'fireEvent'

### ISSUE THREAD

**Issue by xiaoqi7777** [testing-library/react-testing-library#943]
"@testing-library/react": "^11.2.7",
"@types/jest": "^26.0.24",

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox, a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by eps1lon** [comment]
Closing since no response was giving in over a month.
