### ISSUE TITLE
Audio and sound handling

### ISSUE THREAD

**Issue by balboFK** [testing-library/react-testing-library#947]
Hello everybody!

- @testing-library/react version: `"@testing-library/react": "^12.0.0"`
- Testing Framework and version: `"jest": "^27.0.6"`
- DOM Environment: `"@testing-library/jest-dom": "^5.14.1"`

### Problem description:
At our project today, we have a component that reads certains barcodes, and when the barcode is invalid, said component plays an "error" sound, and when the barcode is valid, it plays an "ok" sound.
We play sounds because the user reads the barcodes with a wifi-reader from far away from the actual machine and a error message or visual notification would not help with any feedback for him if the reading was successful.

### What you did:
```
test('Should play warning sound on incorrect label', async () => {
    makeSut()
    const labelInput = await waitFor(() => screen.getByTestId('label-read'))
    fireEvent.input(labelInput, { target: { value: '01234567' } })
    fireEvent.keyDown(labelInput , { key: 'Enter', keyCode: 13 })
  })
```

### What happened:
Now i'm getting this console error when a test runs trough this component:

```
console.error
    Error: Not implemented: HTMLMediaElement.prototype.play
        at module.exports (C:...\node_modules\jsdom\lib\jsdom\browser\not-implemented.js:9:17)
        at HTMLAudioElementImpl.play (C:...\node_modules\jsdom\lib\jsdom\living\nodes\HTMLMediaElement-impl.js:118:5)
        at HTMLAudioElement.play (C:...\node_modules\jsdom\lib\jsdom\living\generated\HTMLMediaElement.js:145:60)
        at C:...\src\presentation\modules\stock\warehouse-transfer\warehouse-transfer.tsx:85:18
        at Generator.next (<anonymous>)
        at C:...\src\presentation\modules\stock\warehouse-transfer\warehouse-transfer.tsx:27:71
        at new Promise (<anonymous>)
        at Object.<anonymous>.__awaiter (C:...\src\presentation\modules\stock\warehouse-transfer\warehouse-transfer.tsx:23:12)
        at handleTransfer (C:...\src\presentation\modules\stock\warehouse-transfer\warehouse-transfer.tsx:78:52)

      84 |       })
    > 85 |       errorSound.play()
         |                  ^
      86 |       return
      87 |     }
```

### Suggested solution:
Is there an actual way of testing if a sound has been played?
Should i just ignore this error or is there something else that i can do to get rid of it?

**Comment by MatanBobi** [comment]
Hi @balboFK! Thanks for taking the time to open this one.
Unfortunately, jsdom doesn't support `HTMLMediaElement` at the moment, you can have a look [here](https://github.com/jsdom/jsdom/issues/2155#issuecomment-366703395).
I'd suggest you to mock it the same as they suggest there.
I'm closing this one as this isn't an issue with testing-library, if you feel it is or you have any comments, please feel free to reach out here :)

Thanks!

**Comment by balboFK** [comment]
Thank you @MatanBobi! 
For now, what i done is to also show a visual notification on the machine, and on my test, i assert on the notification being shown or not, as the sound is also playing on the same effect, it should be a "valid" test.
I'll check out the mocking on jsdom as you suggested aswell.
Thanks again!
