### ISSUE TITLE
Ability to configure global `baseElement` for all renders 

### ISSUE THREAD

**Issue by Friss** [testing-library/react-testing-library#949]
### Describe the feature you'd like:

Today you can pass your own `container` option to the `render` function but that means if you need to pass that every time you call render instead of setting a global setting (ideally via `configure`) 

This would be helpful for when you have other things on the test page (in my case `Jasmine` test results) So then other functions like the DOM logger wouldn't include unrelated HTML content. Same with the other available role logger. 

### Suggested implementation:

Add a new `baseElement` or `baseContainer` option to config. That would default to the current default of `document.body` 

This would then be referenced in the `render` function [here](https://github.com/testing-library/react-testing-library/blob/main/src/pure.js#L43) then the rest of the testing should work correctly as it is based around this `baseElement` 

### Describe alternatives you've considered:

I have been able to partially solve this with a custom `getElementError` function that filters down to just the test dom node. 

```js
// Prevents failed get() and find() from printing the entire Jasmine runner document.body DOM
configure({
  getElementError: (message, container) => {
    const testDiv = container.querySelector(
      'body>div:not(.jasmine_html-reporter)'
    );
    const debug = prettyDOM(testDiv);
    const error = new Error(`${message}\n\n${debug}`);
    error.name = 'TestingLibraryElementError';
    error.stack = null;
    return error;
  },
});
```

But I still get a list of HTML elements that are just jasmine and unrelated to my test. 
![Screen Shot 2021-08-03 at 5 18 37 PM](https://user-images.githubusercontent.com/4588318/128087700-ffbb172d-be13-490e-8076-ad940f745999.png)

### Teachability, Documentation, Adoption, Migration Strategy:

This should be pretty straightforward to document for users much like the `getElementError` documentation that exists currently.

**Comment by afontcu** [comment]
Hi! Do you think setting up a [custom render](https://testing-library.com/docs/react-testing-library/setup#custom-render) would be enough for your use case? You can customize your render with any additional config you might want for the whole test suite.

👋

**Comment by Friss** [comment]
We did try the customer render function but I'm not really a fan of having to always import from a custom file which adds the redirection for what you are actually using instead of directly from testing-library. 

We are also solving for 100's of packages that would need this logic so sharing a simple initial configuration is much easier than a custom renderer implementation and teaching everyone to import from this special package instead of `@testing-library/react` etc.
