### ISSUE TITLE
Calling render more than once inside a single test closure causes multiple instances in base element

### ISSUE THREAD

**Issue by JayAndCatchFire** [testing-library/react-testing-library#950]
- `@testing-library/react` version: 9.2.0
- Testing Framework and version: Jest 25.1.0
  
- DOM Environment: 
  

### Relevant code or config:

```js
const ui = (props = { handleSubmit: jest.fn() }) =>
  render(<Input {...props} />);

describe("<Input>", () => {
  it("can be rendered once in a test", () => {
    let { queryByTestId } = ui();

    expect(queryByTestId("input-component")).toBeInTheDocument();
  });

  it("can be rendered twice in a test", () => {
    let { queryByTestId } = ui();

    expect(queryByTestId("input-component")).toBeInTheDocument();

    ({ queryByTestId } = ui());

    expect(queryByTestId("input-component")).toBeInTheDocument();
  });
});
```

### What you did:
I was trying to render my component multiple times without using `rerender` because that wasn't necessary for my use case.

### What happened:
The component appears to be rendered in the container or base element multiple times.  In my actual code environment, I can render my component twice without issue.  As soon as I try to render it a third time inside the same jest test closure, two instances are rendered within the base element.  I know this because I get the `Found multiple elements` error, and I confirmed this using the `debug` method.

When creating a minimum viable example, I found that I can get it to occur while only attempting two renders.  I'm not sure why my actual code only triggers on three.

### Reproduction:
https://github.com/JayAndCatchFire/react-testing-library-multiple-renders

### Problem description:
I would assume that `render` is idempotent, but it appears as if it is not.  I'm writing test cases where multiple idempotent renders would make sense to fully test a particular case.  I can get around this by breaking out the renders into multiple test closures, but it would be nice if I didn't have to do that.

**Comment by eps1lon** [comment]
That's why we specifically have a `rerender` method. `render` is not idempotent.

**Comment by DanielRios549** [comment]
In my case, I have a component that returns a different node element according to its props (either a `button` or an `anchor`), so I use two `describes` in the test file and I need to render the component twice, but in the second time, the method `toBeInTheDocument()` returns false, even that `toHaveTextContent()` returns true

**Comment by MatanBobi** [comment]
@DanielRios549, would you mind sharing a minimal reproduction so we'll be able to help? Are you using `render` or `rerender`?

**Comment by charlieforward9** [comment]
@eps1lon I extend the `render` method with a wrapper to preload our redux store. However when I call the `rerender` method, it does not reset the store. Do you have an approach for resetting the store as well as the component?

**Comment by MatanBobi** [comment]
@charlieforward9 can you please share a reproduction so we'll be able to assist?

**Comment by charlieforward9** [comment]
CC:// @sainaruufl
