### ISSUE TITLE
Mocked function being called, but not being called?

### ISSUE THREAD

**Issue by rnnyrk** [testing-library/react-testing-library#951]
- `@testing-library/react` version: 12.0.0
- `@testing-library/jest-dom` version: 5.14.1
- Testing Framework and version: Jest 27.0.6
- DOM Environment: jsdom

### Problem description:
I would like to test the implementation of a function being called. My basic component being tested is, in particular the `onSkipTask` function:

```js
...

export const TasksList: React.FC<TasksListProps> = ({ tasks }) => {
  const [modalOpen, openModal, closeModal, modalTaskId] = useModal();
  const { mutate: createUserTask } = useCreateUserTask();
  const { data: userTasks } = useQueryUserTasks({ category });
  const { data: user } = useQueryUser();

  const onSkipTask = () => {
    if (!modalTaskId || !user?.userId) return null;

    // This console.log is being called, which (I think) means the function is called also
    console.log('createUserTask', {
      userId: user.userId,
      taskId: modalTaskId,
      category,
      status: 'SKIPPED',
    });

    createUserTask({
      userId: user.userId,
      taskId: modalTaskId,
      category,
      status: 'SKIPPED',
    });
    closeModal();
  };

  return (
    <>
      {modalOpen && modalTaskId && (
        <ConfirmModal
          closeModal={closeModal}
          onConfirm={onSkipTask}
          confirmText="Yes, skip"
          text="I'm sure I want to skip this task"
        />
      )}
      <TasksListContainer>
        {tasks.map((task) => (
          <TaskItem
            key={task.taskId}
            {... { task, status, variant, openModal }}
          />
        ))}  
      </TasksListContainer>
    </>
  );
};
```

So as you can see above there are a few hooks, which I've mocked in my test as well as a console.log so I'm able to see in my test if the function is called with the correct data (spoiler; it is).

So this brings me to the test itself. I've added some comments to clarify what's happening.

```js
jest.mock('queries/tasks');
const mockUseCreateUserTask = mockedTasks.useCreateUserTask as jest.Mock;
const mockUseQueryTasks = mockedTasks.useQueryTasks as jest.Mock;
const mockUseQueryUserTasks = mockedTasks.useQueryUserTasks as jest.Mock;

beforeEach(() => {
  mockUseCreateUserTask.mockImplementation(() => ({
    mutate: jest.fn(() => console.log('mock')),
  }));

  mockUseQueryTasks.mockImplementation(() => ({
    status: 'success',
    data: allTasks,
  }));

  mockUseQueryUserTasks.mockImplementation(() => ({
    status: 'success',
    data: userTasks,
  }));
});

afterEach(() => {
  cleanup();
  jest.resetAllMocks();
});

test('<Category /> skip a task', async () => {
  const { debug, findAllByTestId, findByTestId, queryByTestId } = render(<Category />, { wrapper: TestWrapper });
  const { mutate: createUserTask } = mockUseCreateUserTask();

  const skipBtn = await findAllByTestId('skipButton');
  expect(skipBtn).toBeTruthy();
  expect(queryByTestId('modalConfirm')).toBeFalsy();

  fireEvent.click(skipBtn[0]);

  const modalConfirmBtn = await findByTestId('modalConfirm');
  expect(modalConfirmBtn).toBeTruthy();
  expect(createUserTask).not.toHaveBeenCalled();

  // DOM tree of Modal is visible debug()

  fireEvent.click(modalConfirmBtn);
  expect(queryByTestId('modalConfirm')).toBeFalsy();

  // Modal is removed from the DOM
  // since closeModal() is the function right after createUserTask()
  expect(createUserTask).toHaveBeenCalled(); 
  // The test keeps faling there and returns 0 calls

  debug();
});
```

As you can see I'm doing quite some mocking the make sure all the data is covered. I'm also mocking the `useCreateUserTask()` and the `mutate` (which comes from `react-query` btw) function (which should be called) from the return. 

As you can see I've also tried to let the mocked mutate return a console.log, and even that one is being called. Although the `expect(createUserTask).toHaveBeenCalled();` keeps returning 0 calls and I can't seem to figure out why this keeps happening. I would love any help or recommendations, thanks in advance!

Also a screenshot to show the results of the test:
<img width="1144" alt="Screenshot 2021-08-13 at 11 33 23" src="https://user-images.githubusercontent.com/4519142/129337322-f54eb6ef-a8ba-45ba-adc9-e753a9800ba1.png">

**Comment by iamdevelopergirl** [comment]
Hi @rnnyrk ,
I see that the createUserTask is a mock function.. 
So createUserTask.mock.calls should return the number of times the mock is called. In your case, should be 1.

**Comment by rnnyrk** [comment]
Hi @iamdevelopergirl. I thought I made the issue clear, since what you suggest is exactly what I expect, but what isn't happening. As I'd try to clarify is that the number of times `createUserTask` is called is 0. Instead of 0 I would expect it to be called once, but that for some reason is not happening..

**Comment by iamdevelopergirl** [comment]
Hi @rnnyrk , If I understand your problem correctly, you are trying expect(createUserTask).toHaveBeenCalled() and have not tried, expect(createUserTask.mock.calls).toBe(1),

**Comment by alexkrolick** [comment]
The problem is the hook creates a new `mutate` function, so you have 2 different references - one where you call the hook in the component, and another in the test body.

**Comment by rnnyrk** [comment]
@alexkrolick Thanks for replying. I do not really understand the problem. Can you point me in the right direction?

When I do not destruct the function and use `const createUserTask = useCreateUserTask();` with `createUserTask.mutate` the same thing happens. How can I let both test and component use the same mutate function?

**Comment by vishalthakur3666** [comment]
@alexkrolick I am facing the same problem. "initializeSdkMock" is called but not counted.
`console.log
      initializeSdkMock called
  Expected number of calls: >= 1
    Received number of calls:    0

    expect(initializeSdkMock).toHaveBeenCalled();  
`
`jest.mock('@app/hooks/useLiveperson/useLiveperson');
const initializeSdkMock = jest.fn();
(initializeSdkMock as jest.Mock).mockImplementation(() => {
  console.log('initializeSdkMock called');
});
const startConversationWithEngagementMock = jest.fn();
(useLiveperson as jest.Mock).mockImplementation(() => {
  return {
    initializeSdk: initializeSdkMock,
    startConversationWithEngagement: startConversationWithEngagementMock,
  };
});`

**Comment by jigmeloday** [comment]
> Hi @rnnyrk , If I understand your problem correctly, you are trying expect(createUserTask).toHaveBeenCalled() and have not tried, expect(createUserTask.mock.calls).toBe(1). If so, please try that.
> 
> Since I saw the console to just have expect(createUserTask).toHaveBeenCalled(), I thought the one I am proposing is not done. Please correct me if my understanding is wrong.

from my understanding, it does not make sense to turn `toHaveBeenCalled() to toBe(1)` cause `toBe(1)` means you are expecting that element to be 1 not the number of calls but `toHaveBeenCalled()` means number of call that happened 

thank you i might be wrong, please correct me if so :) happy to learn
