### ISSUE TITLE
Types: shouldn't ByLabelText return type be HTMLInputElement?

### ISSUE THREAD

**Issue by Fabious** [testing-library/react-testing-library#952]
Hello!

I was working with react-testing-library in a Typescript project and i noticed that the return type for ByLabelText is `HTMLElement`

So when you try to access the `value` property, which exists on `HTMLInputElement`, you get this TS warning `Property 'value' does not exist on type 'HTMLElement'`

Shouldn't the return type always be `HTMLInputElement`?

I found examples illustrating that in the doc : https://testing-library.com/docs/example-input-event/

**Comment by eps1lon** [comment]
> Shouldn't the return type always be HTMLInputElement?

We can't know at compile time what element will be returned. Could also be `HTMLSelectElement` or `HTMLTextAreaElement` or any labelable element.

Does this clear things up?

**Comment by Fabious** [comment]
Ah i was sure i was missing something, and you cleared that for me

And using a union Type like `HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement`, not a good idea?

**Comment by eps1lon** [comment]
> Edit: i guess we can't type properly 'any labelable element' as you said

Yep 👍🏻

**Comment by indiesquidge** [comment]
@eps1lon how do we feel about allowing an optional generic (default `HTMLElement`) to be passed in for what to expect the element return type to be on these types of queries? E.g.

```
getByLabelText<HTMLInputElement>('Email address').value
```
