### ISSUE TITLE
Bug: Render Function Wrapper Typescript Issue

### ISSUE THREAD

**Issue by akashshyamdev** [testing-library/react-testing-library#965]
- `@testing-library/react` version: ^11.1.0
- Testing Framework and version(JEST): ^26.6.0 
- Dom ENV: JS dom(default, no specific config)

### Relevant code or config:

```js
import { render as rtlRender, RenderOptions, screen } from '@testing-library/react';
import { createMemoryHistory } from 'history';
import React, { Component, ReactElement } from 'react';
import { Router } from 'react-router-dom';
import App from './App';

type DefaultOptions = Omit<RenderOptions, 'queries'> & { route: string };

const render = (ui: ReactElement, options?: DefaultOptions) => {
  const history = createMemoryHistory({ initialEntries: [options?.route || '/'] });

  const Wrapper = ({ children }: { children: ReactElement }) => {
    return <Router history={history}>{children}</Router>;
  };

  return rtlRender(ui, { wrapper: Wrapper, ...options });
};

test('renders to screen', () => {
  render(<App />);

  expect(screen.getByTestId('router')).toBeInTheDocument();
});
```

### What happened:
This is a typescript error. check the screenshot below for the error:
![Screenshot 2021-09-24 at 12 35 12](https://user-images.githubusercontent.com/56759828/134632580-88971a2e-cdc0-41de-ac42-1366b37454b1.png)

### Problem description:

I believe the problem is coming from here:
![Screenshot 2021-09-24 at 12 36 41](https://user-images.githubusercontent.com/56759828/134632749-37bc8852-db72-4668-b306-7b3dc309c724.png)

### Suggested solution:
I believe that this can be solved easily by a simple change. I've changed the wrapper type from `React.ComponentType` to `JSX.Element`. Is this a bug or is this being done intentionally?

![Screenshot 2021-09-24 at 12 37 32](https://user-images.githubusercontent.com/56759828/134632830-a138faf0-c193-4f8e-aca0-ee81f1bf4c0a.png)

**Comment by kentcdodds** [comment]
I literally just ran into this myself. The proper fix should probably be: `wrapper?: (props: {children: React.ReactNode}) => JSX.Element`. I'll make a PR.

**Comment by akashshyamdev** [comment]
Thanks @kentcdodds 👍

**Comment by akashshyamdev** [comment]
Thanks @kentcdodds 👍 . btw, I'm coming from your course so I guess you should update that too...

**Comment by kentcdodds** [comment]
Awesome! I'm afraid that I don't maintain this project anymore much so I can't really recommend something to you for this project. But [Hactoberfest](https://hacktoberfest.digitalocean.com/) is coming soon. Maybe you'll find something there :)

**Comment by eps1lon** [comment]
@all-contributors add @akashshyamdev for bug

**Comment by akashshyamdev** [comment]
Thanks @eps1lon. btw, Are there any pending beginner friendly issues/tasks which I could work on?
