### ISSUE TITLE
Tests are FAILING after bumping @testing-library/react from 10.4.8 to 10.4.9 or newer

### ISSUE THREAD

**Issue by karlosos** [testing-library/react-testing-library#978]
After upgrading the `@testing-library/react` from 10.4.8 to 10.4.9 (and other newer versions) my tests are no longer passing.

```
expect(jest.fn()).toHaveBeenCalledTimes(expected)
project     Expected number of calls: 4
project     Received number of calls: 3
```

I've found out that `@testing-library/react@10.4.9` bumped `@testing-library/dom` from 7.17.1 to 7.22.3. However, manually installing 7.22.3 while using `@testing-library/react@10.4.8` didn't change the output of the tests (they are still working correctly). Only directly bumping `@testing-library/react` fails my tests.

What to check next? I have no ideas why tests are suddently not working after upgrading testing package.

**Comment by MatanBobi** [comment]
Hi @karlosos, thanks for the feedback.
Unfortunately, this issue doesn't contain anything we can do to further investigate.
Also, `@testing-library/react` is currently in version 12 so upgrading it will probably be best (I read that you tried newer version too).

If you can please create a repro example in codesandbox or github so we'll be able to investigate this one it will be helpful
Thanks.
