### ISSUE TITLE
Act's warning when the component is rendered in beforeEach

### ISSUE THREAD

**Issue by Chaisenbois** [testing-library/react-testing-library#990]
- `@testing-library/react` version: 12.1.2
- Testing Framework and version: jest@25.5.4
- DOM Environment: jsdom@18.0.1

### Relevant code or config:

Part of the component which cause the issue
````ts
useEffect(() => {
    async function fetch() {
        const userData = await api.getUserData();
        setUser(userData);
    }
    fetch();
}, []);
````

The test:
```ts
beforeEach(() => {
    data = {
        lastName: 'Houl',
        email: 'pierre@hotmail.fr',
        firstName: 'Pierre',
        tel: '0647524585',
    };
    history = createMemoryHistory({ initialEntries: [routes.compte] });
    mockApi.getUserData.mockResolvedValue(data);
    mockApi.updateUser.mockImplementation((args) => Promise.resolve(args));
    fixture = renderWithStore(
        <Router history={history}>
            <ComptePage />
        </Router>,
    );
})
  
it('should get user info displayed', async () => {
    const { queryByText } = fixture;
    await waitFor(() => {
        expect(queryByText(data.lastName!)).toBeInTheDocument();
        expect(queryByText(data.firstName!)).toBeInTheDocument();
        expect(queryByText(data.email!)).toBeInTheDocument();
        expect(queryByText(data.tel!)).toBeInTheDocument();
    });
})

```

### What you did:
I do the rendering of the component in beforeEach, so that I don't duplicate it in all of my tests.

### What happened:
I have got this known error:
````bash
 An update to ComptePage inside a test was not wrapped in act(...).
````

### Reproduction:
1. Make some state change(s) in useEffect with asynchronous task
2.  Rendering the component in a __beforeEach__

### Problem description:
Currently if you do some asynchronous task(s) in useEffect and then call __setState__ . And if in your test you render the component in a __beforeEach__, then the act warning shows up.

### Suggested solution:
The only solution is to render the component in the test itself, but you can't do itt in a __beforeEach__ without getting the act's warning.

**Comment by eps1lon** [comment]
> Currently if you do some asynchronous task(s) in useEffect and then call setState . And if in your test you render the component in a beforeEach, then the act warning shows up.

This is expected behavior. Every update must be wrapped in `act`. But if you have some asynchronous task then your test is responsible for awaiting those. We can't know when exactly when asynchronous tasks will resolve.

I suggest using our `waitFor` to await certain data. If you need more help I suggest [our discord](https://testing-library.com/discord).

**Comment by Chaisenbois** [comment]
It's what I did, and it work well if I render the component in the test like this:
````ts

it('should get user info displayed', async () => {
    fixture = renderWithStore(
        <Router history={history}>
            <ComptePage />
        </Router>,
    );
    const { queryByText } = fixture;
    await waitFor(() => {
        expect(queryByText(data.lastName!)).toBeInTheDocument();
        expect(queryByText(data.firstName!)).toBeInTheDocument();
        expect(queryByText(data.email!)).toBeInTheDocument();
        expect(queryByText(data.tel!)).toBeInTheDocument();
    });
})
````
But if I move out the render method in the beforeEach, then the act's warning appears like that:
```ts
beforeEach(() =>  {
    fixture = renderWithStore(
        <Router history={history}>
            <ComptePage />
        </Router>,
    );
})
  
it('should get user info displayed', async () => {
    const { queryByText } = fixture;
    await waitFor(() => {
        expect(queryByText(data.lastName!)).toBeInTheDocument();
        expect(queryByText(data.firstName!)).toBeInTheDocument();
        expect(queryByText(data.email!)).toBeInTheDocument();
        expect(queryByText(data.tel!)).toBeInTheDocument();
    });
})
```

**Comment by eps1lon** [comment]
Because the initial render is already scheduling an async update. But That isn't triggered if all happens inside a `test`. You only encounter it if you move `render` into `beforeEach`
